### ISSUE TITLE
Unable to remove existing homepage from site

### ISSUE THREAD

**Issue by dfood** [Puzzlepart/prosjektportalen365#100]
After downloading and unzipping the 1.0.0 release using 7-zip and running the installer, I noticed that I got this error:

    Get-PnPListItem : Object reference not set to an instance of an object.
    At C:\Users\Gjermund\Downloads\prosjektportalen365-1.0.0.21385b8\Install.ps1:228 char:5
    +     Get-PnPListItem -List "OmrÃ¥desider" -Connection $SiteConnection  ...
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPListItem], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Lists.GetListItem

And after it finished, the original homepage was still set, without any of the relevant webparts for Prosjektportalen.

I edited the Install.ps1 file to replace Ã¥ with å, as I assumed this was an encoding error that happened somewhere. I still got the error:

    Get-PnPListItem : Object reference not set to an instance of an object.
    At C:\Users\Gjermund\Downloads\prosjektportalen365-1.0.0.21385b8\Install.ps1:228 char:5
    +     Get-PnPListItem -List "Områdesider" -Connection $SiteConnection | ...
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPListItem], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Lists.GetListItem

This was all running Install.ps1 on non-existant sites, by the way. Finally, I edited line 228 of Install.ps1 to this:

`Get-PnPListItem -List "Områdesider" -Connection $SiteConnection | Where-Object { $_["FileLeafRef"] -eq "Home.aspx" } | ForEach-Object { Remove-PnPListItem -Identity $_ -List Områdesider -Force -Connection $SiteConnection }`

As the old code was looking for a site page called "Home" but in my site it was called "Hjemmeside" and after some local testing I couldn't seem to find the site page using the existing code. Not sure if this is a good enough fix, but I wanted to notify you of both the encoding issue I experienced (which may just be on my side), as well as not being able to find the homepage.

After the changes I made it seems to work okay.

**Comment by olemp** [comment]
Thanks a lot @disturbedfood. We'll look into it.

I found this encoding error too, and I thought I updated the package for release 1.0.0, but I guess not.

Need to find a better way to remove the exisiting homepage. We don't want to use Replace="TRUE" for the homepage in our template, becuase we don't want to replace the homepage on upgrades, because there might have been some modifications to the homepage.

**Comment by okms** [comment]
I suggest trying to use url in lieu of list name, e.g. 

Get-PnPListItem -List SitePages 

Since Get-PnPListItem will try to get by url in case no list by the supplied title is found, this should work regardless of locale.

**Comment by olemp** [comment]
Will change to the following:

```powershell
Get-PnPListItem -List SitePages -Connection $SiteConnection | Where-Object { ($_["Title"] -eq "Home") -or ($_["Title"] -eq "Hjemmeside") } | ForEach-Object { Remove-PnPListItem -Identity $_ -List Områdesider -Force -Connection $SiteConnection }
```

Alternative is to delete homepage by url.

**Comment by olemp** [comment]
I think this is a better approach:

```powershell
 Remove-PnPFile -ServerRelativeUrl "$($Uri.LocalPath)/SitePages/Home.aspx" -Force -Connection $SiteConnection
```

**Comment by olemp** [comment]
Published a new release containing the fix from this issue: https://github.com/Puzzlepart/prosjektportalen365/releases/tag/v1.0.1
