### ISSUE TITLE
Melding om "Prosjektet er allerede satt opp", selvom prosjektet ser riktig ut

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1000]
### Beskriv feilen

Det dukker opp melding om "Prosjektet er allerede satt opp". Dette skjer på et prosjekt som ser riktig ut og har innhold. Kan det hende det har noe med webhook steget å gjøre selvom det ikke er definert i malen?

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til [test prosjekt](https://puzzlepart.sharepoint.com/sites/ppDev_v18b/SitePages/ProjectHome.aspx)

### Forventet oppførsel

Dersom et prosjekt blir satt opp riktig så skal ikke dialogen dukke opp.

### Skjermbilder

![image](https://user-images.githubusercontent.com/28678468/220290721-d3f81a63-62f9-4bf8-a9c8-8d52ed85df68.png)

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by Remi749** [comment]
Har fått til å framprovosere feilen.

1. Opprett prosjekt med Byggmal

Når opprettelsen er så og si ferdig dukker følgende melding opp:
![image](https://user-images.githubusercontent.com/28678468/220338467-57e3af7b-df4b-4772-8dfe-26f78f938dc2.png)

Lukker brukeren eller refresher siden så dukker meldingen som vist i OP

**Comment by olemp** [comment]
> Har fått til å framprovosere feilen.
> 
> 1. Opprett prosjekt med Byggmal
> 
> Når opprettelsen er så og si ferdig dukker følgende melding opp: ![image](https://user-images.githubusercontent.com/28678468/220338467-57e3af7b-df4b-4772-8dfe-26f78f938dc2.png)
> 
> Lukker brukeren eller refresher siden så dukker meldingen som vist i OP

Ser ut som det er noe galt med standardinnholdet for bygg. Da feiler setupen, og custom action `ProjectSetup` forblir på siten.

**Comment by Remi749** [comment]
> 

Det kan også hende at dev miljøet vårt har blitt "fucket" og at det ikke vil gjelde andre upgrades, det kan vi egentlig teste. @Petterandre, du testet vel akkurat en upgrade et annet sted? Har du mulighet til å verifisere at byggmal med innhold fungerer som normalt og at du ikke får feilmeldingen over?

**Comment by Remi749** [comment]
Det er vårt dev miljø som er synderen i dette issuet. Lukker saken og fikser dev mijø.
