### ISSUE TITLE
Tom planner genereres selv når planneroppgaver er valgt

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1002]
### Beskriv feilen

For å unngå plannerfeil genereres det en tom planner ved opprettelse av prosjekt.
Dette er ikke nødvendig dersom en planner er valgt.

Dette er ikke en breaking bug, da valgte planner blir valgt for prosjektet, men det er unødvendig med to plannere per prosjekt, hvor planner har blitt valgt.

![image](https://user-images.githubusercontent.com/10527497/220328434-38c2b11d-9aeb-4ee1-95e2-c6badfd13078.png)

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Opprett prosjekt med planner plan valgt
 2. Gå til Oppgaver
 3. Rediger siden
 4. Se feil under "Velg eksisterende plan"

### Forventet oppførsel

Det er forventet at det kun skal være en plan da en plan er valgt.

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by okms** [comment]
Related issue where this bug came from (ref plannerfeil): https://github.com/Puzzlepart/prosjektportalen365/issues/752
