### ISSUE TITLE
Valgt(e) elementer skal legge seg øverst ved søk

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1004]
### Beskriv feilen

Valgt(e) prosjekttilegg/standardinnhold skal legge seg øverst ved søk. Dette gjelder også andre steder som Administrasjon (Program/Overordnet).

**Trinn for å gjenskape:**

 1. Opprett nytt prosjekt
 2. I dialog, velg prosjekttilegg/standardinnhold 
 3. Søk...
 4. Se at valgte elementer ikke legger seg øverst

### Forventet oppførsel

Valgt(e) prosjekttilegg/standardinnhold legger seg øverst ved søk

### Skjermbilder

![image](https://user-images.githubusercontent.com/28678468/220340403-e2f39f45-5764-4062-a2f1-9b7d3983ff8c.png)
![image](https://user-images.githubusercontent.com/28678468/220350263-2ddf8cc6-b3f7-4ebe-84b9-273ba759f71a.png)

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by olemp** [comment]
Tenker vi venter til 1.8.1/1.9.0 med denne @Remi749, hva tenker du? Siden det er low-pri.

**Comment by Remi749** [comment]
> Tenker vi venter til 1.8.1/1.9.0 med denne @Remi749, hva tenker du? Siden det er low-pri.

Hvis det er tid innen fredagen for å fikse det (så lenge det som har høyere pri er fikset), så kan du godt ta det. Hvis ikke så blir det nok etter 1.8.0 ja

**Comment by olemp** [comment]
> Dette gjelder også andre steder som Administrasjon (Program/Overordnet)

Har du en fullstending oversikt over hvor dette skjer?

`Hvis det er tid innen fredagen for å fikse det (så lenge det som har høyere pri er fikset), så kan du godt ta det. Hvis ikke så blir det nok etter 1.8.0 ja. Dette gjelder alt med lav prioritet tag`
Vi får se hva vi får tid til.

**Comment by olemp** [comment]
Denne er ikke bare-bare. Vil vi at valgte elementer skal flyttes til toppen med en gang de velges, eller skal det bare legges på toppen når man søker på nytt? Gir det egentlig en bedre opplevelse? Jeg er litt usikker selv. @Remi749 @tarjeieo

**Comment by olemp** [comment]
Pusher denne til 1.9.0. Vi avventer eventuelle tilbakemeldinger fra brukere.

**Comment by Remi749** [comment]
> Pusher denne til 1.9.0. Vi avventer eventuelle tilbakemeldinger fra brukere.

Til info så skal dette utføres, men først etter 1.8.0

**Comment by olemp** [comment]
> > Pusher denne til 1.9.0. Vi avventer eventuelle tilbakemeldinger fra brukere.
> 
> Til info så skal dette utføres, men først etter 1.8.0

Snakket med @tarjeieo og denne bør diskuteres og avklares før den utføres. Vi bør også dra inn @pzljanb.

**Comment by pzljanb** [comment]
@pzljanb er veldig klar på at denne må gjøres. Vi kan gjerne diskuter hvordan, men brukeropplevelsen slik den er nå er ikke akseptabel

**Comment by tarjeieo** [comment]
Oppsummering av diskusjon: Vi løfter valgte prosjekter/områder ut i en egen visningsliste så det er uambiguøst hvilke områder som er valgt. Må da også ha deselect av områder.
