### ISSUE TITLE
'Risikooversikt' should be named 'Usikkerhetsoversikt' (split into two separate lists?)

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#101]
Split in separate lists?

![image](https://user-images.githubusercontent.com/7606007/64339625-ba80b100-cfe4-11e9-8263-c132a3c4bebb.png)

Not all fields and views makes sense for `Mulighet`.

**Comment by olemp** [comment]
![image](https://user-images.githubusercontent.com/7606007/64339736-f61b7b00-cfe4-11e9-9ea8-a0e0aa09a409.png)

**Comment by olemp** [comment]
Thoughts @okms @tarjeieo?

**Comment by tarjeieo** [comment]
Keep as is for now
