### ISSUE TITLE
'FNs bærekraftsmål' felt kommer ikke med i eksisterende prosjekter

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1012]
### Beskriv feilen

'FNs bærekraftsmål' feltet og tilhørende 'tekst' felt kommer ikke med i eksisterende prosjekter. Dette er noe vi må få inn i UpgradeAllSitesToLatest.

### Forventet oppførsel

Feltene skal med i eksisterende prosjekter

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by Remi749** [comment]
> @Remi749 Dette kommer med når man synkroniserer prosjektegenskaper (skal i hvert fall det). Jeg tenker at denne ikke er så mye brukt at den bør inn i UpgradeAllSitesToLatest-scriptet. Tanker @tarjeieo?

Dersom synkroniseringen gjør at feltet kommer med er nok det godt nok. Men gjerne verifiser.

**Comment by tarjeieo** [comment]
> @Remi749 Dette kommer med når man synkroniserer prosjektegenskaper (skal i hvert fall det). Jeg tenker at denne ikke er så mye brukt at den bør inn i UpgradeAllSitesToLatest-scriptet. Tanker @tarjeieo?

Jeg er enig.

**Comment by olemp** [comment]
> > @Remi749 Dette kommer med når man synkroniserer prosjektegenskaper (skal i hvert fall det). Jeg tenker at denne ikke er så mye brukt at den bør inn i UpgradeAllSitesToLatest-scriptet. Tanker @tarjeieo?
> 
> Dersom synkroniseringen gjør at feltet kommer med er nok det godt nok. Men gjerne verifiser.

Verifisert med det eldste prosjektet vi har i vår testportal.

1. Endret egenskaper.
2. Synkronisering starter.
3. Går til redigering av egenskaper igjen, og finner feltet.

![image](https://user-images.githubusercontent.com/7606007/220913370-1a63901c-0ea3-4719-9599-a928c42a49de.png)

**Comment by tarjeieo** [comment]
Det er jo kjempebra! 
![HappyHappyDanceGIF](https://user-images.githubusercontent.com/1837390/220915203-aca39388-3381-4cf4-88cc-7de37895bc84.gif)

**Comment by Remi749** [comment]
Avklart med Jan, dette burde holde. Lukker dermed saken.
