### ISSUE TITLE
Prosjektnavigasjon: Gevinstarbeid burde ikke lenke til "Hjem"

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1013]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Dårlig brukeropplevelse at trykk på "Gevinstarbeid" leder deg til Hjem siden. Dette er en veldig unaturlig brukeropplevelse.

### Beskriv løsningen du ønsker

Det er ønskelig at siden "Gevinstoversikt" vises når man trykker på Gevinstarbeid

**Comment by olemp** [comment]
Fiks i https://github.com/Puzzlepart/prosjektportalen365/pull/1022. Koblet til milepæl 1.9, men kan taes med i 1.8 om dere ønsker @Remi749 @pzljanb @tarjeieo <3
