### ISSUE TITLE
Navigasjonsmenyen i prosjekt: Program/ Underordnet innhold

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1014]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Det er en dårlig brukeropplevelse at menypunktet Programinnhold" og "Underordnet innhold" fører deg til Hjem siden

### Beskriv løsningen du ønsker

Menypunktet bør i stedet by default vise siden "Oversikt"

**Comment by Remi749** [comment]
@pzljanb , det bør vel kanskje gjøres for "Gevinstarbeid" gruppen i venstremeny, denne kan peke til Gevinstoversikt?

**Comment by olemp** [comment]
Fiks i https://github.com/Puzzlepart/prosjektportalen365/pull/1022. Koblet til milepæl 1.9, men kan taes med i 1.8 om dere ønsker @Remi749 @pzljanb @tarjeieo <3
