### ISSUE TITLE
Regruppering på aggregert oversikt (Program/Overordet) feiler

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1021]
### Beskriv feilen

Regruppering på aggregert oversikt (Program/Overordet) feiler. Testet på clean install og oppgradert.

Testprosjekt: https://puzzlepart.sharepoint.com/sites/Lykkepillen124c/SitePages/OverordnetLeveranser.aspx

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til en aggregert oversikt på program/overordnet område
 2. Klikk på Prosjekt kolonnen og velg grupper
 3. Se at gruppering fungerer
 4. Gjør det samme igjen for å fjerne gruppering
 5. Deretter prøv å grupper på nytt. Se nå at gruppering er merket selvom den ikke er gruppert.

### Forventet oppførsel

Regruppering etter gruppering/avgruppering på aggregert oversikt (Program/Overordet) skal fungere...

### Skjermbilder

![image](https://user-images.githubusercontent.com/28678468/220889087-eb165893-4bd7-4915-8a37-e206f887f4bb.png)

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by olemp** [comment]
@Remi749 Fiks for issue #988 utført i PR #1011 løste kun problemet for `PortfolioAggregation` webdelen. Med PR #1023 er samme fiks gjort for webdelen `ProgramAggregation` som brukes av program og overordnede prosjekter.
