### ISSUE TITLE
Feil ved publisering av statusrapport grunnet vedleggsnavn?

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1033]
### Beskriv feilen

Feil ved publisering av statusrapport grunnet vedleggsnavn?

Prosjekt som feiler: https://puzzlepart.sharepoint.com/sites/PublicDok2/SitePages/Prosjektstatus.aspx

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til prosjektet over og publiser en statusrapport
 2. Se at vedlegg ikke blir opprettet

### Forventet oppførsel

Vedlegg bør opprettes uansett. Det bør være en fallback dersom vedleggsnavn blir for langt eller genereringen av navnet feiler på grunn av at prosjektet har ugyldige tegn.

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

### Relevant logg

```shell
POST: https://puzzlepart.sharepoint.com/sites/pp365/_api/web/lists/getByTitle('Prosjektstatus')/items(231)/AttachmentFiles/add(FileName='Ny-statusrapport-for-%22Ro,-orden-og-sikkerhet%22---en-studie-av-fengselsbetjenters-sikkerhetsarbeid_2023-02-24-10-42.png') 500

Message: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-2130575245, Microsoft.SharePoint.SPException","message":{"lang":"nb-NO","value":"Fil- eller mappenavnet inneholder tegn som ikke er tillatt. Bruk et annet navn."}}} Data: {"response":{},"status":500,"statusText":"","isHttpRequestError":true}
```

**Comment by olemp** [comment]
Ser ut som det er hermetegn som er problemet. Fungerer med følgende prosjektnavn:

![image](https://user-images.githubusercontent.com/7606007/221167338-d45e244d-457c-4633-96e9-ff3b1135c115.png)
