### ISSUE TITLE
Inkludere symbol for å indikere personlige visninger for Porteføljeoversikt

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1045]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Er ikke mulig å se hvilke spørringer som er av privat karakter når man ser listen med visninger på Porteføljeoversikten.

### Beskriv løsningen du ønsker

Symbol (gjerne en person ala 🤵) vises på linjen sammen med visningsnavnet

**Comment by olemp** [comment]
@pzljanb @tarjeieo Dette gjelder vel i all hovedsak Porteføljeoversikt? Hvis ikke - hvilke andre webdeler tenkte du på?

![image](https://user-images.githubusercontent.com/7606007/228240716-7b53e626-1787-4a3b-b81a-5a5a2de41347.png)

**Comment by tarjeieo** [comment]
Jepp, må vel være kun der?

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/pull/1063 og blir med i 1.8.1

**Comment by olemp** [comment]
Let's revert the change in PR #1065 and move this to 1.8.2.
