### ISSUE TITLE
Feilmelding "Microsoft.SharePoint.Client.InvalidClientQueryException" ved publisering av statusrapport

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1049]
### Beskriv feilen

Feilmelding "Microsoft.SharePoint.Client.InvalidClientQueryException" ved publisering av statusrapport.

### Versjon

1.7.2

### Relevant logg

```json
{"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"nb-NO","value":"The maximum number of bytes allowed to be read from the stream has been exceeded. After the last read operation, a total of 1049600 bytes has been read from the stream; however a maximum of 1048576 bytes is allowed."}}}
```

**Comment by olemp** [comment]
Ser ut som feilen skjer med persisteringen av data i feltet `GtSectionDataJson`.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/7606007/226328776-7f58a8e3-96a0-438c-9f56-38300d11da7e.png">

Over en megabyte med data blir for meget for et note-felt.

**Comment by tarjeieo** [comment]
Se også ASSIST-4920

**Comment by okms** [comment]
Mulige tekniske løsninger som har vært diskutert er
- Eget bibliotek med json data, benytte dette i istedenfor GtSectionDataJson
  - Fordel: fleksibel løsning, ingen størrelsesbegrensning 
  - Ulempe: flere kall, avhengigheter. Slette statusrapport mer komplisert 
- Bruke attachments på listeelement
  - Fordel: hver statusrapport er selvstendig listeelement
  - Ulempe: Håndtering av vedlegg kan være kompliserende

**Comment by tarjeieo** [comment]
Ulempe nr 2 på attachment: Vi bruker allerede attachment for snapshop-filene, så da må vi håndtere begge type filer.

**Comment by olemp** [comment]
Vi bør være sikre på at vi trenger å mellomlagre før vi gjør dette. Kan vi ikke endre spørringen til å filtere på modified eller created?

**Comment by olemp** [comment]
> Vi har diskutert denne her @pzljanb og vi har ikke landet helt og trenger at du bestemmer. Vi må lagre dataene et annet sted enn i et listefelt, og da har vi to alternativer:
> 
> 1. Filvedlegg på statuselementet. Data lagres i json-fil som vedlegg på statuselementet. Fordel: Ganske enkelt å få til, samme som vi gjør med snapshots, lite migrering, enkel datamodell der hver status har sitt vedlegg. Ulempe: Kan virke forvirrende med vedlegg på statuselementet som ikke er lesbart for folk flest. Sårbart for sletting (dersom noen deaktiverer vedlegg er rapportene borte).
> 2. Eget bibliotek. Data lagres i json-filer i et eget sentralt bibliotek med referanse til statusrapport. Bør også da flytte over png-snapshots til dette biblioteket. Fordel: Data lagres tryggere, med søppelbøtte-mulighet og evt. egen rettighetsstyring.  Referanse til prosjektstatus lages enkelt gjennom kolonne-verdier. Ulempe: Større implementasjon. Større migreringsjobb. Data skilt fra statusrapport ved f.eks. sletting eller flytting av rapporter.
> 
> Teknisk avdeling er splittet.
> 
> ![WhyAreYouDividedOnThisCristineRaquelRotenbergGIF](https://user-images.githubusercontent.com/1837390/235682525-fd86631a-30c9-45b6-bec4-5dbf09d32756.gif)

![GIF](https://media.tenor.com/wImEppzbG2YAAAAM/truly-we-are-a-divided-nation-seth-meyers.gif)

**Comment by olemp** [comment]
> @olemp , lukker vi denne da vi har midlertidig fiks og oppretter nytt issue som inneholder det vi egentlig ønsker?

Ja, jeg synes det.

**Comment by olemp** [comment]
> @olemp , lukker vi denne da vi har midlertidig fiks og oppretter nytt issue som inneholder det vi egentlig ønsker?

Let's do it

**Comment by olemp** [comment]
> @olemp , lukker vi denne da vi har midlertidig fiks og oppretter nytt issue som inneholder det vi egentlig ønsker?

#1104 @tarjeieo @Remi749
