### ISSUE TITLE
Angi standard 'vis som flis/liste' egenskap på Prosjektutlisting-webdel er borte

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1053]
### Beskriv feilen

Angi standard vis som flis/liste egenskap på Prosjektutlisting-webdel er borte (se bilde under). Dersom man satt "Vis som fliser" til "Av" ble webdelens standardvisning listevisning.

### Forventet oppførsel

Det må være mulig å velge om man ønsker at Prosjektutlisting-webdel skal standard vises som flis eller listevisning.

### Skjermbilder

1.7.2:
![image](https://user-images.githubusercontent.com/28678468/226925860-b54e6d45-071a-4a2f-8265-502493dd64c4.png)

1.8.0
![image](https://user-images.githubusercontent.com/28678468/226926147-57811a53-9d52-4f73-95e3-2b06d764b059.png)

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by olemp** [comment]
@Remi749 Egenskapen ble fjernet i [denne commiten](https://github.com/Puzzlepart/prosjektportalen365/commit/a6cef84dbb25c67c57fc212fad87061268c56063#diff-a7fd0332404f815f8b9231100f6ebd9c1a97b47f1e5ee6060aed7bfb3becae80) da det ble endret fra `showAsTiles` til `renderAs`.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/7606007/228474437-cb533044-f3be-477f-9d67-5dd532bf1b56.png">
