### ISSUE TITLE
SharePoint full kontroll rettigheter er ikke nok for å få opp prosjektadministratortilganger

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1054]
### Beskriv feilen

Når en person får full kontroll tilganger på et prosjektområde (i SharePoint) så får ikke vedkommende opp prosjektadministrasjonsmuligheter. Dette gjør at under prosjektinformasjon på forsiden ligger kun standardknappen "Vis alle prosjektegenskaper".

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Legg til en bruker med full kontroll på et prosjekt uten andre tilganger
 2. Se at vedkommende ikke får opp Prosjektportalen-spesifikke verktøy, f.eks. under Prosjektinformasjon

### Forventet oppførsel

Jeg mener at SharePoint-rollen Full kontroll bør gi fulle rettigheter til området, og at default rollen "SP Områdeadministrator" også bør inkludere de som har full kontroll på området.

### Skjermbilder

SharePoint-eier med full kontroll:
![image](https://user-images.githubusercontent.com/1837390/227155099-85b61f2a-3194-4051-a38c-b3ec4edf367c.png)

Microsoft 365 gruppeeier eller områdesamlingadministrator:
![image](https://user-images.githubusercontent.com/1837390/227155168-77084621-d79e-4dfc-b194-8e85f7ffde86.png)

### Versjon

1.8.0

**Comment by Remi749** [comment]
@tarjeieo , løst i PR: #1055
