### ISSUE TITLE
Sorteringsrekkefølge på Planner oppgaver

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1056]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Et problem vedrørende planner oppgaver som defineres på porteføljenivå er at man ikke kan definere er rekkefølge eller legge til elementer som skal inn et bestemt sted i dagens "ID" rekkefølge.

Det er også et problem under provisjonering at elementer som har høyest ID kommer øverst i planner.

### Beskriv løsningen du ønsker

Legge til "Rekkefølge" (GtSortOrder) som en kolonne i listen "Planneroppgaver". Denne settes opp med "10, 20, 30..." verdier.

Endring som må gjøres på måten vi provisjonerer planneroppgavene: Øverste element basert på rekkefølge skal legge seg øverst i Planneren på prosjektet. Ettersom Siste element idag legger seg øverst, må vi bare "swappe" provisjoneringsrekkefølge, slik at den begynner med det siste elementet og avslutter med det første.

**Comment by olemp** [comment]
@Remi749 Duplikat av #1046?

**Comment by tarjeieo** [comment]
Håndterer dette også rekkefølgen på buckets? Har en kunde nå som trenger å styre rekkefølgen på oppgavene, men også bøttene de ligger i. Tenkt på det @Remi749 ?

**Comment by Remi749** [comment]
> Håndterer dette også rekkefølgen på buckets? Har en kunde nå som trenger å styre rekkefølgen på oppgavene, men også bøttene de ligger i. Tenkt på det @Remi749 ?

Rekkefølgen på buckets er tilsvarende rekkefølgen som er angitt på elementene. Så den setter rekkefølge slik det er satt opp i listen, men man angir inget eget tall for bucketen.

**Comment by tarjeieo** [comment]
Okay, så dersom oppgave 1 har kategori "Forprosjekt" så kommer "Forprosjekt" bøtta først i oversikten?

**Comment by olemp** [comment]
> Okay, så dersom oppgave 1 har kategori "Forprosjekt" så kommer "Forprosjekt" bøtta først i oversikten?

Det hørtes riktig ut!

**Comment by tarjeieo** [comment]
Supert!
