### ISSUE TITLE
Alfabetisk filtrering på filter-verdier

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1059]
### Beskriv feilen

I ressursallokeringen kan man filtrere på ressurs. Alle ressursene vises i tilsynelatende tilfeldig rekkefølge

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til ressursallokeringen
 2. Velg filter-ruten
 3. Se rekkefølgen på ressursene

### Forventet oppførsel

Rekkefølgen bør være alfabetisk

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.0

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/pull/1060 og blir med i 1.8.1
