### ISSUE TITLE
Last opp installasjonslogg-filen på installasjonselementet

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1066]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Av og til kan det være usikkerhet knyttet til hva som har skjedd under installasjon/oppgradering

### Beskriv løsningen du ønsker

For å bedre kunne tracka installasjoner og hva som evt kan ha oppstått under installasjonen, foreslås det å laste opp installasjonsfilen til elementet i Lists/Installasjonslogg som et vedlegg.

**Comment by olemp** [comment]
Added as part of #1047

![image](https://user-images.githubusercontent.com/7606007/228833263-79b65a1b-fc43-4a44-b8dc-3208ea57b813.png)

If we want to include it in 1.8.2 - let's cherry pick it to the `releases/1.8` branch.
