### ISSUE TITLE
Maloppsett  og Tidslinjekonfigurasjon  bør gjemmes fra områdeinnhold

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1072]
Maloppsett  og Tidslinjekonfigurasjon bør gjemmes fra områdeinnhold da disse finnes under Konfigurasjon-siden, og ikke trenger å være søkbare.

![image](https://user-images.githubusercontent.com/7606007/228844658-10f53216-952b-4c53-a26c-5b0094ef0c0a.png)

**Comment by Remi749** [comment]
Hva med å få inn Prosjekter, Prosjektstatus og Tidslinjeinnhold listene på konfigurasjonssiden, under "Avansert" delen.

**Comment by olemp** [comment]
> > > Hva med å få inn Prosjekter, Prosjektstatus og Tidslinjeinnhold listene på konfigurasjonssiden, under "Avansert" delen.
> > 
> > 
> > Enig, vi kan gjøre det som en del av dette issuet, _men_ egentlig skal man vel ikke inn i Prosjekterlisten? (Man må kanskje det per nå for å slette prosjekter)
> 
> Ja, inntil videre ihvertfall kan den inn under "Avansert" til vi får noe admin webdel.

Enig. Noen innspill til disse ledetekstene?

![image](https://user-images.githubusercontent.com/7606007/228854800-3c2937a1-6fd7-4ef4-bfa5-cbee713e7ac1.png)

**Comment by olemp** [comment]
Løst i #1074

**Comment by tarjeieo** [comment]
Jeg er helt uenig, de skal ikke skjules fra områdeinnhold. Både fordi kunder jobber med de listene fra områdeinnhold, bl.a. fordi de bruker de som utgangspunkt for kopi av nye lister (for egne maler etc.).

De skal _ikke_ skjules. Denne diskusjonen har vi hatt før.

**Comment by olemp** [comment]
> Jeg er helt uenig, de skal ikke skjules fra områdeinnhold. Både fordi kunder jobber med de listene fra områdeinnhold, bl.a. fordi de bruker de som utgangspunkt for kopi av nye lister (for egne maler etc.).
> 
> De skal _ikke_ skjules. Denne diskusjonen har vi hatt før.

https://github.com/Puzzlepart/prosjektportalen365/pull/1075

**Comment by olemp** [comment]
Etter en lang telefonsamtale med @tarjeieo, foreslår vi at **Maloppsett** og **Tidslinjekonfigurasjon** gjemmes fra områdeinnhold. Det rydder i hvert fall litt opp.
