### ISSUE TITLE
Project site configuration failed if other language pack is enabled

### ISSUE THREAD

**Issue by JimmyHang** [Puzzlepart/prosjektportalen365#108]
The project site configuration prosess may fail if the site have other language pack enabled other than Norwegian. If the user creating the site have other display language configured in their O365 profile, SharePoint will then enable all language packs with the NO as base. this will cause the configuration to fail, 

Maybe we can add and extra site script to make sure all language packs have been disabled in the site before configuration starts.

Thanks for the great work.. ;)

Cheers

**Comment by olemp** [comment]
Was the site created with the correct language (1044 - Norwegian)? The setup should give you an error if the site was not created in norwegian. 

Was it the profile language alone that caused this?

**Comment by JimmyHang** [comment]
The site was created using Norwegian as base language, the profile language causing the issue is English.

**Comment by olemp** [comment]
Not sure why the profile language is causing this.

Creating a project with any other languaget than Norwegian (1044), should yield this error:

**Comment by JimmyHang** [comment]
Yes, i got this one when I tried with English base language and it's fine, ;) the above error is caused while running.

**Comment by olemp** [comment]
See if `v1.0.6` helps: https://github.com/Puzzlepart/prosjektportalen365/releases/tag/v1.0.6.
