### ISSUE TITLE
Uthenting av prosjektinformasjon feiler

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1080]
### Beskriv feilen

Bruker får ikke hentet ut prosjektinformasjon når brukeren IKKE har tilgang på hub'n

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Legg til en bruker i prosjektet som IKKE er medlem på hub'n
 2. Logg på som brukeren du la til i steg 1
 3. Gå til prosjektet
 4. Se at prosjektinformasjonen melder feilen "Det skjedde en feil under uthenting av prosjektinformasjon"

### Forventet oppførsel

Prosjektinformasjonen burde blitt lastet fra prosjektets egen informasjonsliste, når tilgang til hub'n mangler

### Skjermbilder

![image](https://user-images.githubusercontent.com/58074707/229590985-8176281e-b455-48ef-8ba0-12a55f7f4cb8.png)

### Ytterligere informasjon

testet på v1.8.1

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

Annet (spesifiser over)

**Comment by pzljanb** [comment]
Den siste delen av setningen krever at data faktisk hentes fra lokal liste dersom sentral tilgang "mangler"

**Comment by olemp** [comment]
Hva med å gi brukeren minimal tilgang på hubben @pzljanb?

**Comment by pzljanb** [comment]
> Hva med å gi brukeren minimal tilgang på hubben @pzljanb?

Hvordan tenker du at det skal kunne gjøres med automatikk da @olemp ?
