### ISSUE TITLE
PreInstallUpgrade.ps1 feiler på renaming av innholdstyper og svelger feilen

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1094]
### Beskriv feilen

Ved oppgradering til 1.8.1 for en installasjon som allerede har bygg/anlegg så feiler PreInstallUpgrade.ps1 i operasjonen som skal rename Content Types. Feilen blir deretter svelget (tom catch-blokk) i overordnet skript. Dermed kommer PreInstallUpgrade.ps1 aldri fram til å legge inn FN's bærekraftsmål termsettet.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Oppgrader en site med gammel bygg anlegg

### Forventet oppførsel

Feilen må håndteres og løses (har ikke sett på hva som feiler ennå), og vi bør heller ikke svelge feilen i overordna skript.

### Versjon

1.8.0

**Comment by olemp** [comment]
The error must be here somewhere, @tarjeieo?

![image](https://user-images.githubusercontent.com/7606007/234559550-342edda3-d4bb-4ffb-8b8a-4c687580d717.png)

**Comment by tarjeieo** [comment]
Ja, jeg tipper den feiler på en av Context.ExecuteQuery... Ser ikke hva annet som skulle feila her

**Comment by olemp** [comment]
> Ja, jeg tipper den feiler på en av Context.ExecuteQuery... Ser ikke hva annet som skulle feila her

Bør være mulig å bruke `Set-PnPContentType`?
