### ISSUE TITLE
Setup: App Catalog 

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen365#110]
If a App Catalog is not created before the installation of Prosjektportalen 365, Office 365 takes a while to provision this. If that is the case, you have to specify the TenantAppCatalogUrl. To see if the App Catalog is ready, you have to go into the SharePoint Admin Center, and under Classic features click Apps and then App Catalog. If no App Catalog is present then, you have to wait (or use the TenantAppCatalogUrl).

This should be descibed in the Installation, and also, the TenantAppCatalogUrl is missing from the documentation.

Finally, I got an error when the language of the App Catalog was Norwegian (1044) and not English (1033)

**Comment by olemp** [comment]
@pzlespen What error did you get when the language of the App Catalog was Norwegian (1044) and not English (1033)?

**Comment by olemp** [comment]
Documentation updated.
