### ISSUE TITLE
Various error messages during installation

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#111]
Tried to install Project Portal365 on sites / Project Portal365

**Attempts 1-3:**
with the installation line: `.\install.ps1 -Url https://tenantname.sharepoint.com/sites/prosjektportalen365 -UseWebLogin`

received the following error message: `[ERROR] Failed to apply PnP templates to [https://tenantname.sharepoint.com/sites/prosjektportalen365]: Value does not fall within the expected range.`

during one of these installations appeared:
![image](https://user-images.githubusercontent.com/28678468/65147378-4c91ac00-da1e-11e9-9891-9c557639b5ad.png)

![image](https://user-images.githubusercontent.com/28678468/65147399-5c10f500-da1e-11e9-88aa-60b034fa2600.png)

**Attempt 4:**

Did just like above, but with another error message

received the following error message: `[ERROR] Failed to apply PnP templates to [https://tenantname.sharepoint.com/sites/prosjektportalen365]: Ob
jekt-IDen site:33cf8e53-e9d6-4344-b7d5-8321f09579c7:web:171d8795-42b7-4e8e-9883-acf3ef3d34ef er ugyldig.`

**Attempts 5:**
with the installation line: `.\install.ps1 -Url https://tenantname.sharepoint.com/sites/pp365 -UseWebLogin -TenantAppCatalogUrl https: // tenantname.sharepoint.com / sites / UBFappkatalog /`

During this, a number of warnings appeared (see image below), but here the installation went through as it should, and was completed after 20 minutes
![image](https://user-images.githubusercontent.com/28678468/65148040-ad6db400-da1f-11e9-9436-f984be6c4097.png)

seems like something is wrong if you do not specify an app catalog, even if it's being used and everything looks OK during installation without specifying.

Version 1.0.4

-Remi

**Comment by olemp** [comment]
I will look at the errors. The warnings are from PnP and cannot be surpressed. Don't worry about them.

**Comment by olemp** [comment]
If you don't specify `TenantAppCatalogUrl`, `Get-PnPTenantAppCatalogUrl` will be used to retrieve it.

Can you check what `Get-PnPTenantAppCatalogUrl` yield in the environment @Remi749? You need to be connected to the admin site.

**Comment by Remi749** [comment]
Update:
Tried to install again with the installation line from attempt 5, got this error message now:
![image](https://user-images.githubusercontent.com/28678468/65149606-b6ac5000-da22-11e9-98ce-9ae3d0de1d4f.png)

`[ERROR] Failed to apply PnP templates to [https://undervisningsbygg.sharepoint.com/sites/prosjektportalen365]: Objekt-IDen site:33cf8e53-e9d6-4344-b7d5-8321f09579c7:web:171d8795-42b7-4e8e-9883-acf3ef3d34ef er ugyldig.`

**Comment by olemp** [comment]
@Remi749 Looks like you get site:33cf8e53-e9d6-4344-b7d5-8321f09579c7:web:171d8795-42b7-4e8e-9883-acf3ef3d34ef instead of the actual URL. Never seen this before. Very weird.

Can you do the following in your PowerShell window?

```powershell
[System.Uri]$Uri = "https://tenantname.sharepoint.com/sites/prosjektportalen365"
``

Then check $Uri.LocalPath

**Comment by olemp** [comment]
Of course change tenantname to whatever tenant.

**Comment by Remi749** [comment]
Get-PnPTenantAppCatalogUrl yields me: `https://tenantname.sharepoint.com/sites/UBFappkatalog` which is the correct url for the app catalog and is seen being used during installation when catalog is not specified.

$Uri.LocalPath gives me: `/sites/prosjektportalen365`

**Comment by olemp** [comment]
This might look like something relevant @Remi749. Have a look: https://github.com/SharePoint/PnP-Sites-Core/issues/2025

**Comment by olemp** [comment]
Did you create the site prosjektportalen365 yourself, or just the installer?

**Comment by Remi749** [comment]
The installer creates the site.

**Comment by olemp** [comment]
What version of SharePointPnPPowerShellOnline are you using @Remi749?

```powershell
(Get-Module SharePointPnPPowerShellOnline).Version`
```

**Comment by Remi749** [comment]
```
Major  Minor  Build  Revision
-----  -----  -----  --------
3      9      1905   3
```

**Comment by olemp** [comment]
Would be interesting to see what happend if you deleted the site completely, recreated it, and installed again. It takes sometime before the URL are available again after a delete though.

**Comment by Remi749** [comment]
Every time I've tried to install it again, I've removed the site, and then deleted it from deleted sites list using SharePoint Online Management Shell command: `Remove-SPODeletedSite -Identity`

I tried to wait a while now after deleting it and a brand new error occured, similar to the previous one.

`[ERROR] Failed to apply PnP templates to [https://tenantname.sharepoint.com/sites/prosjektportalen365]: Ugyldig feltnavn. {bfbf2ffe-4960-4752-aab4-7cf20c3a757b} https://tenantname.sharepoint.com/sites/prosjektportalen365`

**Comment by olemp** [comment]
So the issue must be related to the deletion and restoring of the site.

Try a fresh site. New URL.

**Comment by olemp** [comment]
So this is not related to the installer, rather SPO/SharePointPnPPowerShellOnline. Not nuch we can do.

**Comment by Remi749** [comment]
Follow up question as the installation was able to complete trying with the name: "prosjekportalen-365" instead of "prosjektportalen365" which had failed multiple times before.

When deleting a site, I delete it from the Active Sites list, and then remove it with SharePoint Online Management Shell command: `Remove-SPODeletedSite -Identity urlofsite`.

If someone fails an installation, how can one fix this apart from trying with a new name?

**Comment by oleeinm** [comment]
Can't figure this one out:

_PS C:\Users\me\Downloads\prosjektportalen365-1.2.0.0273cd4> .\Install.ps1 -Url "https://oursite.sharepoint.com/sites/prosjekt" -UseWebLogin_

[INFO] Installing [Prosjektportalen 365] [1.2.0]
[INFO] Loaded [SharePointPnPPowerShellOnline] v.3.16.1912.0 from bundle

Get-PnPProperty : Den eksterne serveren returnerte feilen (403) Forbudt.
At C:\Users\olemar\Downloads\prosjektportalen365-1.2.0.0273cd4\Install.ps1:96 char:16
+ ... rrentUser = Get-PnPProperty -Property CurrentUser -ClientObject (Get- ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPProperty], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Base.EnsureProperty
