### ISSUE TITLE
Vis all statusinformasjon

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1112]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

For øyeblikket er det kun mulig å se felter og verdier for statusrapporten ved å redigere, dette er en tungvinn måte å vise informasjon på og hindrer folk som ikke har tilgang til å faktisk se informasjonen, det er et behov for å vise fram informasjonen lettere og holde det "consistent" med måten prosjektinformasjon også framstilles.

### Beskriv løsningen du ønsker

Legge til en knapp "Vis all statusinformasjon" på Prosjektstatus siden
- Knappen viser Prosjektinformasjonspanel med kun status felter fra rapport
- Legge til to typer som skiller hva panelet skal vise (Prosjektinformasjon,Statusinformasjon)
- Som standard legger vi i bunnen av Prosjektinformasjon/Statusinformasjon en "collapsed" variant av det motsatte for å enkelt få fram ytterligere informasjon
  - Eksempel: Prosjektinformasjon panel viser vanlige felter som tidligere, under feltene er det en "collapsed" seksjon for statusinformasjon.

**Comment by olemp** [comment]
@Remi749 Denne skjønner jeg ikke helt.

Hva er problemet med gjeldende løsning?

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/c1ff80ee-cc80-4243-a0f0-10eab3fb8aa4)

Vil man se mer informasjon enn dette kan man vel bare navigere til prosjektstatussiden? Synes ikke vi skal unødig overkomplisere prosjektinformasjonswebdelen, men mulig det er noe jeg misforstår her selvfølgelig.

Kan du legge inn noen skjermbilder for å forklare hva denne går ut på?

**Comment by olemp** [comment]
@Remi749 Savner litt overordnet om behovet, ikke bare løsning.

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/e50d69ae-c307-43bc-9eb4-4dd635076cf8)

**Comment by Remi749** [comment]
> @Remi749 Savner litt overordnet om behovet, ikke bare løsning.
> 
> ![image](https://user-images.githubusercontent.com/7606007/237097737-e50d69ae-c307-43bc-9eb4-4dd635076cf8.png)

Har oppdatert issue

**Comment by tarjeieo** [comment]
Jeg fjerna denne fra milestones, foreslår vi tar den om kunde ønsker og har betalingsvilje. Synes den har begrenset forretningsverdi

**Comment by olemp** [comment]
> Jeg fjerna denne fra milestones, foreslår vi tar den om kunde ønsker og har betalingsvilje. Synes den har begrenset forretningsverdi

Enig i det siste.

> det er et behov for å vise fram informasjonen lettere og holde det "consistent" med måten prosjektinformasjon også framstilles.

Ser ikke helt hvorfor det skal holdes "consistent" med prosjektinformasjon? Jeg mener måten prosjektstatus presenteres nå er den riktige måten for denne type "data".
