### ISSUE TITLE
Logisk rekkefølge for "Fase" kolonne på porteføljeoversikter

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1114]
### Beskriv løsningen du ønsker

I dagens løsning er det kun mulig å sortere alfabetisk.

| Dagens løsning | Forslag |
| -- | -- |
| ![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/7adeb9ae-a4c4-4976-a38b-f7cf2f472097) | ![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/0d7d1915-6730-4f0b-9460-2ed44c7493f4) |

For spesielt "Fase" kolonnen ønskes det mulighet for å velge Logisk rekkefølge, i dette tilfellet vil rekkefølgen i termsettet bli brukt eller en egen kolonne for å sette egendefinert rekkefølge.

**Comment by olemp** [comment]
Beste er om dette kan konfigureres ett sted så vi slipper å hardkode noe ala:

(pseudokode)
```pseudo
if(field == 'GtProjectPhase) arr.push(LOGISK_REKKEFØLGE_SORT)
```

**Comment by tarjeieo** [comment]
Jeg tenker en kolonne i Prosjektkolonner som er "Egendefinert sorteringsrekkefølge" (Note-felt) der man kan legge inn e.g. "Konsept; Planlegge, Gjennomføre, Avslutte, Realisere" også plukker vi opp den rekkefølgen alle steder der vi tilbyr sortering på feltet (altså porteføljeoversikt, programoversikt, ulike innholdsoversikter på portefølje og program).

**Comment by olemp** [comment]
Works like a charm 🔥 

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/cc4cf316-5342-4e99-b80c-c87e1d576182)
