### ISSUE TITLE
Feil forkortelse for eventuelt

### ISSUE THREAD

**Issue by bottekott** [Puzzlepart/prosjektportalen365#1116]
### Beskriv feilen

Flere steder brukes "evt." og "evt" som forkortelse for eventuelt.

**Evt.** er kort for **etter vår tidsregning**.

Riktig forkortelse er **ev.**. Ref. språkrådet:
https://www.sprakradet.no/svardatabase/sporsmal-og-svar/hvordan-forkortes-eventuelt/

### Versjon

1.8.0

**Comment by tarjeieo** [comment]
Takk for innspill @bottekott - vi tar den med i vNext+1.
