### ISSUE TITLE
Synkronisering feiler dersom prosjektet mangler i den sentrale prosjektlista

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1121]
### Beskriv feilen

Dersom prosjektelementet mangler i den sentrale lista klarer ikke prosjektet å synce prosjektegenskaper. En feil oppstår på forsida.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et prosjekt
 2. Slett prosjektets element i den sentrale prosjektlista
 3. Observer at sync av props ikke fungerer

### Forventet oppførsel

Syncen bør ta hånd om dette tilfellet, og gjenskape elementet sentralt dersom det mangler

### Skjermbilder

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/5f1a1f1b-d63f-4f5b-9e63-1713181ce3de)
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/651c880e-0723-4f96-8ddd-5d20e9de18ee)

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.0

**Comment by Remi749** [comment]
@tarjeieo , til info: dette var tidligere en "wont fix". ref: https://github.com/Puzzlepart/prosjektportalen365/issues/715
