### ISSUE TITLE
Søk i aggregerte oversikter søker ikke på prosjektnavn

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1123]
### Beskriv feilen

Søk i de ulike aggregerte oversiktene søker ikke på prosjektnavn. Det kunne vært nyttig for rask gjenfinning - selv om man ofte kan filtrere på prosjekt.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til f.eks. Usikkerhetsoversikt
 2. Søk etter et prosjektnavn
 3. Observer at det ikke er resultater

### Forventet oppførsel

Søk bør også ta med prosjektnavn om det ikke blir alt for komplisert å få til

### Skjermbilder

Før søk:
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/ccaac023-c469-4063-bf89-4a3e5d69bc99)

Søk på Innlandet:
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/255281f4-589a-494d-80df-4d7c7313202e)

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.0

**Comment by olemp** [comment]
Er det noe vi bør sette som opt-in (f.eks. innstilling på datakilden) eller tror du dette er noe vi trygt kan sette som standard? Det vil ikke være caser hvor det vil være "irriterende" å få treff i prosjektnavn?

**Comment by tarjeieo** [comment]
> Er det noe vi bør sette som opt-in (f.eks. innstilling på datakilden) eller tror du dette er noe vi trygt kan sette som standard? Det vil ikke være caser hvor det vil være "irriterende" å få treff i prosjektnavn?

Jeg tror dette trygt kan være standard egentlig... Har en følelse av at veeeldig få har forhold til WP Props uansett
