### ISSUE TITLE
Tooltip til status på prosjektforsida ser rart ut ved korte valg/beskrivelser

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1133]
### Beskriv feilen

Mouseover har blitt litt trykka sammen når man ikke har valg en status med "lang string" eller har skrevet en lang kommentar.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til prosjektstatus til et prosjekt
 2. Lag ny status med f.eks. status fremdrift=På plan og en kort kommentar
 3. Gå til forsida
 4. Se feil

### Forventet oppførsel

Dialogen bør se OK ut uansett

### Skjermbilder

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/0ad62673-6add-4742-b6a4-f41165bef720)

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.0

**Comment by Remi749** [comment]
Dette blir gjort som en del av #1132

**Comment by olemp** [comment]
> Dette blir gjort som en del av #1132, men kan fint gjøres før 1.9

Da tar vi det som en del av #1132
