### ISSUE TITLE
"Hent maldokumenter" improvements

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#115]
"Hent maldokumenter" works nice, bug could do with some improvements:
* The button should always be visible. If no documents are available to select, a nice error message should show.
* The functionality should not filter by phase, but rather add a column in the selector for phase. Alternatively group by phase column?
* The library should be pre-populated as part of the install, with the same as "standarddokumenter" in PP2
* Remove the "Teams Wiki Data" from the list of libraries you can copy to

**Comment by olemp** [comment]
Included in https://github.com/Puzzlepart/prosjektportalen365/pull/122
