### ISSUE TITLE
Not possible to scroll horizontally on project portfolio page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#116]

**Comment by olemp** [comment]
GIF please 🔨

**Comment by tarjeieo** [comment]
![image](https://user-images.githubusercontent.com/1837390/66123615-c1e6aa80-e5e2-11e9-8fdf-09474818261a.png)

Scrollbar not visible

**Comment by olemp** [comment]
Fixed.
