### ISSUE TITLE
Bedre nettlesertitler for custom sider i PP365

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1160]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Vanskelig å se hvilket prosjekt man har oppe når man bruker fanene i nettleseren.

### Beskriv løsningen du ønsker

Ta med Prosjektnavn i nettleserfanen. For eksempel "Nytt arkivsystem 2023 - Prosjektstatus"

### Ytterligere informasjon

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/d59710f8-c1b1-45cd-b165-fdcfad73a188)

**Comment by Remi749** [comment]
Dette er noe vi må få med, dette inngår under Universell Utforming. Vi tar dette som en del av
#1132

**Comment by olemp** [comment]
@Remi749 @tarjeieo Tenker dere da gjøre noe ala `document.title = 'xyz'` med en SPFx extension?

**Comment by tarjeieo** [comment]
> @Remi749 @tarjeieo Tenker dere da gjøre noe ala `document.title = 'xyz'` med en SPFx extension?

Ja, jeg ser ikke at det noen annen måte. Liker det ikke... Vi trenger ikke prioritere denne med det første av den grunn.

**Comment by tarjeieo** [comment]
Dette bør fikses, men ansvaret må ligge hos Microsoft eller som en egen extension som vi kan ha på siden av PP365. Lukker derfor denne per nå.
