### ISSUE TITLE
Resource allocation minor bugs

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#117]
* Should show percentage % next to numbers
* Resource allocation items are not clickable - dialogue missing

![image](https://user-images.githubusercontent.com/1837390/66123755-0d995400-e5e3-11e9-8b21-d0b1cff35ed5.png)

**Comment by olemp** [comment]
Bug fixed in https://github.com/Puzzlepart/prosjektportalen365/pull/123.

Dialog was never implemented. Add a spec to a new issue if we want this.
