### ISSUE TITLE
Malbibliotek-sti skal kunne konfigureres i maloppsett-lista

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1179]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Per i dag så er det vanskelig å styre stien til malbiblioteket. Stien ligger i sitescriptet https://github.com/Puzzlepart/prosjektportalen365/blob/6508a48fe2263184f185649f487dc8bd12593eeb/SiteScripts/src/002200%20-%20TemplateSelectorCommandSet.txt, så i teorien kan man lage flere sitescript og sitedesign. Dette er likevel ganske teknisk og noe man må passe godt på ved oppgraderingen.

### Beskriv løsningen du ønsker

Vi kunne hatt et felt i Maloppsett som vi kaller "Malbibliotek-sti" (evt. templateLibrary som det heter i scriptet) som har defaultverdi  "Malbibliotek". Da kunne det vært mulig å endre stien til biblioteket for ulike områdemaler.

**Comment by olemp** [comment]
Da kan vi beholde `templateLibrary` fra site scriptet som default verdi, og legge inn ett felt i malkonfigurasjonslisten for å overskrive dette? Eventuelt tar vi også bort egenskapen `templateLibrary`. Ulempen da er om man skriver inn en tom verdi for en mal.

**Comment by olemp** [comment]
> > > > > Ønsket i issuet er at det konfigureres i malkonfigurasjonslisten, men dette er vanskelig da det er vanskelig å få tak i malverdiene for ett prosjekt.
> > > > > Foreslår derfor at det konfigureres i Parameters gjennom egenskapen TemplateDocumentLibrary.
> > > > 
> > > > 
> > > > Jeg skjønte ikke helt... trodde også vi hadde fasa ut Parameters-seksjonen? Alle de andre verdiene der kommer vel fra Maloppsett-lista?
> > > > Dessuten er det 109 filer endra - kan vi ta formateringsendringer i en egen PR? Vanskelig å se hva som er endra! :-D
> > > 
> > > 
> > > Vet det er spesifisert i issuet:
> > > ![image](https://user-images.githubusercontent.com/7606007/247493418-7b3e7bff-56a2-47fc-9928-3c4538cbc067.png)
> > > Vi har ikke fasa ut parameters i malene nei? Dette brukes vel flere steder, man overskrives av malkonfigurasjonen. Det er ikke lett å få tilgang til feltverdiene for malkonfigurasjonen som er brukt når man står i et prosjekt.
> > 
> > 
> > Nei, skjønner at vi ikke får tak i den "on-the-fly", jeg tenkte nok i de baner å heller sette opp extensionen fra wizarden med dette som input-parameter (i prinsippet er det vel en custom action som inneholder properties?).
> 
> Aha, sånn ja. Det blir nok lettere enn å bruke Malkonfigurasjonslisten.

Det

> > > > Ønsket i issuet er at det konfigureres i malkonfigurasjonslisten, men dette er vanskelig da det er vanskelig å få tak i malverdiene for ett prosjekt.
> > > > Foreslår derfor at det konfigureres i Parameters gjennom egenskapen TemplateDocumentLibrary.
> > > 
> > > 
> > > Jeg skjønte ikke helt... trodde også vi hadde fasa ut Parameters-seksjonen? Alle de andre verdiene der kommer vel fra Maloppsett-lista?
> > > Dessuten er det 109 filer endra - kan vi ta formateringsendringer i en egen PR? Vanskelig å se hva som er endra! :-D
> > 
> > 
> > Vet det er spesifisert i issuet:
> > ![image](https://user-images.githubusercontent.com/7606007/247493418-7b3e7bff-56a2-47fc-9928-3c4538cbc067.png)
> > Vi har ikke fasa ut parameters i malene nei? Dette brukes vel flere steder, man overskrives av malkonfigurasjonen. Det er ikke lett å få tilgang til feltverdiene for malkonfigurasjonen som er brukt når man står i et prosjekt.
> 
> Nei, skjønner at vi ikke får tak i den "on-the-fly", jeg tenkte nok i de baner å heller sette opp extensionen fra wizarden med dette som input-parameter (i prinsippet er det vel en custom action som inneholder properties?).

Blir dog litt problematisk med oppdatering av site design + site scriptet tror jeg. Vet ikke om vi støtter fjerning av site script fra et site design per nå.

**Comment by olemp** [comment]
Noe som dette @tarjeieo? I en ny seksjon "Avansert".

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/cdd1d5a5-0a09-4ad6-98bf-2ce23ec9557b)

**Comment by olemp** [comment]
> Jeg tenkte vel i utgangspunktet at det ikke var behov for å tilgjengeliggjøre dette for brukere - bedre å ha et felt i Maloppsett der admins kan konfigurere.
> 
> I teorien kunne man jo støttet at "Hent dokumentmal" haddde mulighet til å velge kildebibliotek ut ifra et utvalg "godkjente" malbiblioteker - men det får vi ta en annen gang.

Aha, var ikke så lett å skjønne at det var slik du ville ha det (eller så har jeg bare tenkt feil). Da kjører vi ett felt i Maloppsett der admins kan konfigurere.

**Comment by tarjeieo** [comment]
> 



> > Jeg tenkte vel i utgangspunktet at det ikke var behov for å tilgjengeliggjøre dette for brukere - bedre å ha et felt i Maloppsett der admins kan konfigurere.
> > I teorien kunne man jo støttet at "Hent dokumentmal" haddde mulighet til å velge kildebibliotek ut ifra et utvalg "godkjente" malbiblioteker - men det får vi ta en annen gang.
> 
> Aha, var ikke så lett å skjønne at det var slik du ville ha det (eller så har jeg bare tenkt feil). Da kjører vi ett felt i Maloppsett der admins kan konfigurere.

Okay, men jeg skrev faktisk i issuet:

> Vi kunne hatt et felt i Maloppsett som vi kaller "Malbibliotek-sti" (evt. templateLibrary som det heter i scriptet) som har defaultverdi "Malbibliotek".

Beklager om jeg formulerte meg upresist! ;)

**Comment by olemp** [comment]
> > 
> 
> > > Jeg tenkte vel i utgangspunktet at det ikke var behov for å tilgjengeliggjøre dette for brukere - bedre å ha et felt i Maloppsett der admins kan konfigurere.
> > > I teorien kunne man jo støttet at "Hent dokumentmal" haddde mulighet til å velge kildebibliotek ut ifra et utvalg "godkjente" malbiblioteker - men det får vi ta en annen gang.
> > 
> > 
> > Aha, var ikke så lett å skjønne at det var slik du ville ha det (eller så har jeg bare tenkt feil). Da kjører vi ett felt i Maloppsett der admins kan konfigurere.
> 
> Okay, men jeg skrev faktisk i issuet:
> 
> > Vi kunne hatt et felt i Maloppsett som vi kaller "Malbibliotek-sti" (evt. templateLibrary som det heter i scriptet) som har defaultverdi "Malbibliotek".
> 
> Beklager om jeg formulerte meg upresist! ;)

Tar det på min kappe <3
