### ISSUE TITLE
Version history link from project frontpage doesnt work - goes to 404 page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#118]
Link is wrong, goes to e.g. "https://tenant.sharepoint.com/sites/&Source=https%3A%2F%2Ftenant.sharepoint.com%2Fsites%2FEiendomsskattikommunen"

**Comment by olemp** [comment]
Included in https://github.com/Puzzlepart/prosjektportalen365/pull/122
