### ISSUE TITLE
Bug ved Excel eksport av datofelter uten verdi

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1180]
### Beskriv feilen

Når man Excel eksporterer i porteføljeoversikten med elementer uten datoverdi, får man følgende feilmelding
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/10527497/92ee5343-9ec7-4064-a0ab-8e56a153e7c9)

Dette gjelder alle type datofelter, og er reprodusert i flere tenants.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til porteføljeoversikt
 2. Finn en visning med datofelt, og med tilfeller av tomme datofelt
 3. Eksporter til Excel
 4. Se feil

### Forventet oppførsel

Det er forventet at det skal være tomme felt, og ikke noe annet hvor elementet ikke har satt en dato

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by Remi749** [comment]
@Shared var ikke importert i pakkene med latest and greatest, kjører en quickfix på dette for Portefølje, Program og Prosjekt pakkene.

**Comment by olemp** [comment]
> @shared var ikke importert i pakkene med latest and greatest, kjører en quickfix på dette for Portefølje, Program og Prosjekt pakkene.

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/68e93347-b37b-4819-b597-012aa49baa3c)
