### ISSUE TITLE
Project status: Make it possible to work with draft and published versions of project status reports

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#119]
Project managers might use several days to correctly update project status. It's an idea to introduce a flag that separates draft and final versions of the project status. Only draft versions can be edited (unless you hack in the behind the scenes lists). In the dropdown, we can show a label for "Kladd" or "Publisert".

**Comment by olemp** [comment]
Fix will be included in next release. CHANGELOG updated.
