### ISSUE TITLE
Discussion: When browsing old project status reports, we need to handle list data better

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#121]
When browsing old reports, the lists are always "current". We need to handle this better, either by
* snapshoting the lists in some way or form 
* hiding them when browsing old report

We must avoid giving the impression that lists have historical snapshots.

**Comment by olemp** [comment]
Options:

1. JSON snapshot of the list content.
2. Hiding the lists when browsing old reportwhen browsing an older report

**Comment by olemp** [comment]
Options

1. Hide the list data it the report is a old report
2. Get items that was modified or created before the report was published

cc @pzljanb @tarjeieo

**Comment by olemp** [comment]
> olemp moved this from Future release to Backlog in Roadmap and release planning

Will move to future release when we decide what to do.

**Comment by pzljanb** [comment]
Handling of unpublished reports should also be improved.

Proposal:
Disable the button 'Ny statusrapport' When there is an unpublished report in place.

Goal;
To only have Published reports (plus one unpublished/ current report)

**Comment by olemp** [comment]
> Handling of unpublished reports should also be improved.
> 
> Proposal:
> Disable the button 'Ny statusrapport' When there is an unpublished report in place.
> 
> Goal;
> To only have Published reports (plus one unpublished/ current report)

That's not related to this. Moved to https://github.com/Puzzlepart/prosjektportalen365/issues/295.

**Comment by tarjeieo** [comment]
The snapshotting feature introduces in 1.2.4 through #337 mitigates this. To close this issue I think we should remove the list views when browsing old reports to avoid confusion

**Comment by olemp** [comment]
> The snapshotting feature introduces in 1.2.4 through #337 mitigates this. To close this issue I think we should remove the list views when browsing old reports to avoid confusion

https://github.com/Puzzlepart/prosjektportalen365/issues/374
