### ISSUE TITLE
Visuell oppgradering av prosjektutlistingswebdel - Flis visning

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1216]
### Beskriv løsningen du ønsker

Vi ønsker å oppgradere utseendet til prosjektkortene.

### Endringer som har vært tidligere ønsket

1. Vis prosjektstatus (GtProjectLifecycleStatus) på kortet.
2. Fjern startdatoen.
3. Legg til etikett for Tjenesteområde (GtProjectServiceArea).
4. Legg til etikett for Prosjekttype (GtProjectType).
5. Gi mulighet for tilpasning av farger på fasenavnet på en eller annen måte.

### Ytterligere informasjon:

Det vil også gjøres en jobb med genererte bilder, disse vil ikke lengre bli generert som før, men vil nå bli opprettet ved hjelp av ren CSS. Denne endringen vil redusere lastetiden og forbedre ytelsen til kortene betydelig. Videre vil fargepaletten for kortene nå bli generert fra bildet, og vi vil bruke gradienter på den genererte overskriften på kortene. Dette vil gi en mer dynamisk og visuelt tiltalende effekt som bidrar til å fremheve prosjektenes unike identiteter.

Denne oppgraderingen skal også ta høyre for universell utforming.

### Forventet resultat

Etter at disse endringene er implementert, bør PP365-prosjektkortene se mer attraktive ut og gi bedre informasjon om prosjektene. Fjerning av startdatoen vil redusere unødvendig informasjon, og det å vise prosjektstatus, tjenesteområde og prosjekttype vil gi bedre oversikt over prosjektets fremgang og egenskaper.

**Comment by olemp** [comment]
Deilige greier! 🌴

**Comment by olemp** [comment]
Lager en PR på endringene i property pane som diskutert på Teams.

**Comment by olemp** [comment]
@Remi749 

Denne må endres på:

<img width="875" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/06910ee3-34df-48c9-8bbe-16bbb6f7b1a9">

Setter man `useDynamicColors` til `false`, kræsjer webdelen (viser ingenting og kaster feil). Hooks can ikke brukes _conditionally_.

<img width="965" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/face4aa6-7e3c-4e2b-ab4c-2432778dd88c">

https://legacy.reactjs.org/docs/error-decoder.html/?invariant=300

**Comment by Remi749** [comment]
> @Remi749
> 
> Denne må endres på:
> 
> <img alt="image" width="875" src="https://user-images.githubusercontent.com/7606007/261327620-06910ee3-34df-48c9-8bbe-16bbb6f7b1a9.png">
> Setter man `useDynamicColors` til `false`, kræsjer webdelen (viser ingenting og kaster feil). Hooks can ikke brukes _conditionally_.
> 
> <img alt="image" width="965" src="https://user-images.githubusercontent.com/7606007/261327982-face4aa6-7e3c-4e2b-ab4c-2432778dd88c.png">
> https://legacy.reactjs.org/docs/error-decoder.html/?invariant=300

Fikset her #1236
