### ISSUE TITLE
Håndter flere enn 500 prosjekter på forsiden

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1217]
### Beskriv feilen

På forsiden viser vi prosjekter under "Tilgang til", "Mine prosjekter", "Alle prosjekter" osv.

Der har vi ikke tatt høyde for at det kan være flere enn 500 prosjekter. Selv om man aldri vil se alle 500-prosjektene når man bruker denne siden, fører begrensningen til at noen prosjekter vil falle ut av visningen, og ikke vil dukke opp via f.eks. søk.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til en PP porteføljeforside med flere enn 500 prosjekter
 2. Noen prosjekter vil ikke være søkbare på forsida

### Forventet oppførsel

Vi må benytte oss av batching slik vi har gjort på de andre oversiktsidene, slik at vi støtter å vise alle prosjekter

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.0

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/pull/1221
