### ISSUE TITLE
Oppdater PnP.PowerShell til 2.12.0

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1226]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Skulle vi oppdatert til versjon 2.5.0 av PnP PowerShell for å holde oss up 2 date? https://github.com/pnp/powershell/releases/tag/v2.5.0

### Beskriv løsningen du ønsker

Oppdater til 2.5.0. Bør ikke føre til de store endringene, men vi må muligens bytte ut noen kommandoer i skriptene våre. Ser f.eks. følgende endringer:

https://github.com/pnp/powershell/releases/tag/v2.5.0

**Comment by tarjeieo** [comment]
Utfordringen med dette er at PnP 2.* krever PowerShell 7, og det er nok ikke alle kunder som er klare for denne overgangen ennå. Vi avventer til 2024.

**Comment by olemp** [comment]
> Utfordringen med dette er at PnP 2.* krever PowerShell 7, og det er nok ikke alle kunder som er klare for denne overgangen ennå. Vi avventer til 2024.

Nå er det 2024!

**Comment by Remi749** [comment]
2.10 kom akkurat ut

**Comment by tarjeieo** [comment]
Dette er en endring fra PnP/Microsoft som tvinger oss til å oppdatere vår installasjonspakke: https://pnp.github.io/blog/post/changes-pnp-management-shell-registration/

**Comment by tarjeieo** [comment]
Har laget en PR nå for å oppdatere til 2.12.0 som er siste versjon (september 2024).
