### ISSUE TITLE
Redigering av prosjektegenskaper i Panel

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1227]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Ved å lage en egen webdel/komponent for redigering av prosjektegenskaper som bruker et Panel, har vi bedre kontroll på hele flyten.

### Beskriv løsningen du ønsker

Egen SPFx-webdel/komponent for rediger av prosjektegenskaper.

**Comment by tarjeieo** [comment]
Vi må håndtere taksonomi-felter slik at det går an å "browse" valgmulighetene

**Comment by tarjeieo** [comment]
Ser ut som "nye syncen" ikke fungerer helt ennå:
Testprosjekt: https://puzzlepart.sharepoint.com/sites/Inkluderendearbeidsplass/

Lokalt:
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/d41b9e3d-720c-4af5-8c1f-be263a03693d)

Sentralt:
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/2d2fefa5-6346-40b0-b752-5831048b8beb)

Prøvde å synce på nytt, da kom det seg:
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/d8297764-37a6-4bb9-bde9-b56a2895d461)

Klarer å gjenskape dette flere ganger - første gang syncer den bare 3-4 felter. Ser ingen feilmelding i console. Neste gang syncer den tilsynelatende alle feltene.

**Comment by olemp** [comment]
> Ser ut som "nye syncen" ikke fungerer helt ennå: Testprosjekt: https://puzzlepart.sharepoint.com/sites/Inkluderendearbeidsplass/
> 
> Lokalt: ![image](https://user-images.githubusercontent.com/1837390/260647174-d41b9e3d-720c-4af5-8c1f-be263a03693d.png)
> 
> Sentralt: ![image](https://user-images.githubusercontent.com/1837390/260647218-2d2fefa5-6346-40b0-b752-5831048b8beb.png)
> 
> Prøvde å synce på nytt, da kom det seg: ![image](https://user-images.githubusercontent.com/1837390/260647572-d8297764-37a6-4bb9-bde9-b56a2895d461.png)
> 
> Klarer å gjenskape dette flere ganger - første gang syncer den bare 3-4 felter. Ser ingen feilmelding i console. Neste gang syncer den tilsynelatende alle feltene.

#1232 👍

**Comment by olemp** [comment]
> Vi må håndtere taksonomi-felter slik at det går an å "browse" valgmulighetene

#1233 🎉
