### ISSUE TITLE
Prosjektkontor i prosjektadministrasjonsroller fører til feil på rettighetssjekk

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1237]
### Beskriv feilen

Det går på prosjektadminroller. Dersom man har valgt "Prosjektkontor" så vil ikke sjekken checkProjectAdminPermissions fungere for brukere uten tilgang på området. Ser ut til å fungere for "vanlige" eiere, men har ikke testet alle scenarioer.

Problemstillingen jeg tester er en feil rapportert fra en virksomhet der ekstern bruker ikke får gjort endringer på prosjektegenskaper eller prosjektstatus. De hadde valgt "Prosjektkontor" under Prosjektadministratorroller i prosjektet. Men denne verdien er knyttet til SharePoint-gruppen "Prosjektkontor" som ikke finnes, vi har ikke provisjonert den. Derfor feiler den på følgende linje med at gruppen ikke finnes, og kaster feil som avbryter sjekken: https://github.com/Puzzlepart/prosjektportalen365/blob/3d8fd79aa536cbb347adde2f388926200d8eecbd/SharePointFramework/@Shared/src/data/SPDataAdapterBase/index.ts#L168.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et prosjekt
 2. Rediger egenskaper, velg "Prosjektkontor" og "Prosjektstøtte" i Prosjektadministrasjonsroller
 3. Inviter en ekstern bruker (mulig andre scenarioer også kan gjenskape feilen)
 4. Legg til ekstern bruker som Prosjektstøtte i prosjektegenskaper
 5. Logg inn som ekstern bruker, observer at vedkommende ikke får rettigheter til prosjektegenskaper og prosjektstatus
 6. Observer feil i logg (NB: 10 minutters caching etter at feilen kommer, jeg måtte cleare application i browser for å gjenskape flere ganger)

### Forventet oppførsel

Vi bør fikse dette, og jeg er litt fristet til å fjerne hele "Prosjektkontor"-valget. Det peker jo på en gruppe på sitenivå som vi ikke oppretter, og det vil altså aldri fungere. Eventuelt kunne vi endra til at den gikk på porteføljenivå, og så oppretta gruppa på huben. Det er kanskje det enkleste, for da slipper vi å endre feltvalgene i alle eksisterende prosjekter?

### Ytterligere informasjon

Testa i 1.8.3, vi bør nok også ha denne i 1.9

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.x (siste stabile)

**Comment by olemp** [comment]
Den går vel i `catch` om den feiler, @tarjeieo? Eller har vi lagt inn try-catch i senere tid?

<img width="784" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/06295736-4603-41f9-a839-de150f5f49c5">

**Comment by tarjeieo** [comment]
Jeg ser det... Er i 1.8.3 også.. Men da er jeg usikker på hva som er grunnen til at det fungerer når jeg fjerner Prosjektkontor fra Prosjektadminstøtte. 🤔

**Comment by olemp** [comment]
> Jeg ser det... Er i 1.8.3 også.. Men da er jeg usikker på hva som er grunnen til at det fungerer når jeg fjerner Prosjektkontor fra Prosjektadminstøtte. 🤔

Fulgte akkurat samme oppskrift med min eksterne gmail-konto og [
Granåsen idrettspark](https://puzzlepart.sharepoint.com/sites/Gransenidrettspark/). Det fungerer helt fint. Feilen ligger ett annet sted tror jeg?

**Comment by olemp** [comment]
> > Jeg ser det... Er i 1.8.3 også.. Men da er jeg usikker på hva som er grunnen til at det fungerer når jeg fjerner Prosjektkontor fra Prosjektadminstøtte. 🤔
> 
> Fulgte akkurat samme oppskrift med min eksterne gmail-konto og [Granåsen idrettspark](https://puzzlepart.sharepoint.com/sites/Gransenidrettspark/). Det fungerer helt fint. Feilen ligger ett annet sted tror jeg?

Har du noe mer info her?

**Comment by olemp** [comment]
> Vi fant forsåvidt "en annen feil" som kan ha vært årsaken. Jeg er likevel ikke helt fornøyd med "Prosjektkontor" i dag som peker på en lokal gruppe som ikke blir oppretta. Det valget gir ikke mening som det er nå. Men det er forsåvidt en annen issue. Men lukker denne.

Tror valget er der fordi noen kunder bruker Prosjektkontor, og "provisjonerer" ut denne gruppen. Tanker om dette @pzljanb?
