### ISSUE TITLE
Noen gjestebrukere får ikke opp prosjektadministrasjonsmuligheter

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1245]
### Beskriv feilen

Noen gjestebrukere har ikke fått synkronisert e-posten fra AAD til SPO Brukerprofiltjenesten. Måten vi henter ut currentuser på nå fører til at e-post og loginname er blank for disse brukerne.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Inviter inn en gjestebruker i et prosjekt.
 2. Legg til gjestebrukeren under prosjektstøtte og legg til prosjektstøtte under Prosjektadministrasjonsroller
 3. Logg inn med gjestebrukeren i prosjektet (i annen browser/profil)
 4. Via PowerShell, sett at e-posten til gjestebrukeren er blank i SPO Brukerprofilen, e.g. `Set-PnPUserProfileProperty -Account "i:0#.f|membership|tarjeieo_puzzlepart.com#ext#@oslokommune.onmicrosoft.com" -PropertyName WorkEmail -Value ""`
 5. Med gjestebrukeren logga inn, observer at vedkommende ikke får opp mulighetene til å redigere prosjektinformasjon etc. (kan ta noe tid)

### Forventet oppførsel

Gjestebrukere som også ligger i prosjektstøtte skal få opp mulighetene som er angitt i rollen prosjektstøtte

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.x (siste stabile)

**Comment by olemp** [comment]
Løst i #1246. Vi prøver få ut 1.8.4 ila dagen, eller i morgen.
