### ISSUE TITLE
Visningspanelet for prosjekter viser feil informasjon på porteføljeoversikten

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1247]
### Beskriv feilen

I porteføleoversikten, når man trykker på info-knappen, så vises et infopanel med info om prosjektet. Neste gang man trykker på info-knappen for et annet prosjekt, vises fortsatt data fra første prosjekt.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til porteføljeoversikten
 2. Klikk på (i) for et prosjekt
 3. Klikk på (i) for et annet prosjekt
 4. Se at dataen vises for det første prosjektet (bortsett fra tittel)

### Forventet oppførsel

(i) skal vise info for prosjektet som velges

### Skjermbilder

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/bede2dd6-a924-451b-a69c-ddcbfb723e63)

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.x (siste stabile)

**Comment by olemp** [comment]
Ser nå ut som det fungerer [her](https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Portef%C3%B8ljeoversikt.aspx#viewId=1) @tarjeieo. Vi lukker ikke saken før det også er fikset i 1.9, og 1.8.4 release er lagt ut tilgjengelig for publikum.

**Comment by olemp** [comment]
[v1.8.4](https://github.com/Puzzlepart/prosjektportalen365/releases/tag/v1.8.4) er lagt ut, og releases/1.9 er oppdatert med fiks (#1251).
