### ISSUE TITLE
Feature req: Full contact integration from portfolio overview

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#125]
![image](https://user-images.githubusercontent.com/1837390/66388178-dd2c2e00-e9c5-11e9-9a9a-d83083dd05aa.png)

When hovering people fields, it would be nice to get a sweet O365 contact card if this is possible
![image](https://user-images.githubusercontent.com/1837390/66388123-c4bc1380-e9c5-11e9-987d-a31802a60b70.png)

**Comment by olemp** [comment]
Will need to wait for the persona card to be available. We can't create this custom.
