### ISSUE TITLE
Dokumentmal knapp forsvinner midlertidig

### ISSUE THREAD

**Issue by kiwihansen** [Puzzlepart/prosjektportalen365#1258]
### Beskriv feilen

Med nyere versjoner av Firefox og Chromium baserte nettlesere virker det som Hent Dokumentmal knappen blir borte når du åpner et dokumentområde i PP365. 
Knappen dukker opp igjen om man refresher området eller går til en ny mappe.
Gjenskapt feil i flere tenants med forskjellige browsere (FF116.03, Chrome 115.0.5790.171).

### Hvordan reprodusere feilen

1. Gå til et prosjekt.
2. Gå til dokumenter, sjekk om knappen er på verktøylinjen
3. Refresh området eller gå til en undermappe, så skal knappen være tilbake.

### Forventet oppførsel

Knappen skal være på verktøylinjen når man åpner dokumentområdet.

### Skjermbilder

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/69144808/51aa8e8a-cf17-45cf-8e44-0e1b2738e384)

### Hvilke nettleser(e) oppleves feilen på?

Chrome, Firefox

### Versjon

1.8.x (siste stabile)

**Comment by tarjeieo** [comment]
Vi klarer ikke gjenskape, lukker derfor og åpner om det rapporteres igjen
