### ISSUE TITLE
ClientSideComponents fra portfolio-extensions er tenant-wide

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1266]
### Beskriv feilen

Clientsidekomponentene fra portfolio-extensions pakka er tenant-wide. Dette medfører at koden for IdeaRegistration, IdeaProcessing og IdeaProjectData kjører tenant-wide.

Dette er litt unødvendig i grunn.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Installer PP365
 2. Opprett et kommunikasjonsområde
 3. Åpne console og Sources
 4. Søk etter e.g. "IdeaRegistrationCommand"
 5. Sett gjerne breakpoint i fila, observer at den laster

### Forventet oppførsel

Løsningene bør ikke deployes globalt. For denne konkrete pakka så kan vi droppe skipFeatureDeployment, og heller legge til appen på porteføljeområdet der den skal brukes som en del av installasjon/template.

Uansett er det så niche å bruke denne funksjonaliteten per nå, at jeg vil heller at vi må legge den inn manuelt enn at vi deployer globalt.

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.x (siste stabile)

**Comment by tarjeieo** [comment]
Hadde egentlig tenkte å installere den alltid på porteføljeområdet... Det sagt så kanskje vi bare skal la folk legge den til manuelt. Den er jo overdue for en oppgradering - og det har jo skjedd litt både her og der rundt dette temaet!

**Comment by olemp** [comment]
@Remi749 @tarjeieo Hva er status her? Jeg er litt usikker på hvordan det hele henger sammen. Skal det være custom actions på lister på både porteføljeområdet og prosjektnivå? For porteføljenivå er det jo rett frem å legge inn custom actions i [Porteføljemalen](https://github.com/Puzzlepart/prosjektportalen365/tree/releases/1.9/Templates/Portfolio). For prosjekter blir det nok å oppdatere site designet eller legge det i prosjektmalen (men usikker på om klientside provisjoneringen støtter dette per nå).

**Comment by tarjeieo** [comment]
Trenger vel egentlig bare på porteføljeområdet? Så om vi scoper til porteføljen så tror jeg vi er good for nå

**Comment by Remi749** [comment]
I PortfolioExtensions har vi Idébehandling opplegget og Footer. Footer må vises på Portefølje og Prosjekt, Idébehandling er eksklusiv Porteføljenivå

**Comment by Remi749** [comment]
> ... For porteføljenivå er det jo rett frem å legge inn custom actions i [Porteføljemalen](https://github.com/Puzzlepart/prosjektportalen365/tree/releases/1.9/Templates/Portfolio). ...

Dersom dette er det som må gjøres er dette allerede utført. Dette ble gjort her: 8aae36285b5ea432f2377aaa2f99408fd6937119
