### ISSUE TITLE
Liste over bugs (1.9)

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1267]
# 🐛 Bugs oppdaget så langt i 1.9

Her er en liste over kjente feil i versjon 1.9. Listen vil oppdateres etter hvert som flere problemer identifiseres. Disse trenger ikke egne oppføringer i **changelog** og heller ikke et eget issue da 1.9 fortsatt ikke er lansert.

### 1. PortfolioExtensions

- [x] (1.1) ListExtension knapper for Idéregistrering og Idébehandling dukker ikke opp lengre. 8aae36285b5ea432f2377aaa2f99408fd6937119
- [ ] (1.2) Idémodul skal ikke være globally deployed, dette kan forårsake feil inne på prosjekters lister, [se issue](https://github.com/Puzzlepart/prosjektportalen365/issues/1266)
- [ ] #1304
- [ ] #1305
- [ ] #1306

### 2. PortfolioWebParts

- [x] (2.1) Prosjektinformasjonspanelet på prosjektutsliting webdel kan kun åpnes én gang. For å åpne et annet panel må siden oppdateres https://github.com/Puzzlepart/prosjektportalen365/commit/cbd7a7119f785daa61b7b5d3bfcfb5080fd93c25
- [x] (2.2) Redigering av kolonner via egendefinert skjema på aggregerte oversikter fungerer ikke ved lagring. https://github.com/Puzzlepart/prosjektportalen365/commit/4b6ee6c140eb5b367cfbae1e1a97f9b21333e5e8
- [x] ~(2.3) Listevisning (juster kolonner etter skjermbredde) for Porteføljeoversikt og aggregerte oversikter gjør at den første kolonnen er "megabred", bedre hadde vært om "Legg til kolonne" kolonnen hadde vært den som tok opp mest plass slik at de andre faktisk baserer seg på breddene som er lagt inn~ _Foreslår å evt pushe til 1.9.1_
- [x] (2.4) Eksporter til Excel på Porteføljeoversikt fungerer ikke https://github.com/Puzzlepart/prosjektportalen365/commit/99d2b38aed0edd55dfe7e30e473e34fa45fc31e2
- [x] (2.5) Eksporter til Excel på Aggregerte oversikter tar ikke høyde for valgte elementer slik som Porteføljeoversikt gjør https://github.com/Puzzlepart/prosjektportalen365/commit/99d2b38aed0edd55dfe7e30e473e34fa45fc31e2
- [x] (2.6) Dismiss av tekst skrevet i søkefelt på alle sider tømmer ikke og "refetcher" innhold, innholdet i søkefeltet fjernes men liste tilknyttet oppdateres ikke https://github.com/Puzzlepart/prosjektportalen365/commit/5dda1fcc03445194efeab334d6f2d1f2ba3a7dd5
- [x] (2.7) Dersom man bytter visninger på Porteføljeoversikt for raskt så starter den en slags loop hvor den switcher mellom visninger i hytt og gevær, refresh fikser issuet. https://github.com/Puzzlepart/prosjektportalen365/commit/a2061acfe21d52f70fe478252548e70dff690b6c
- [x] (2.8) Prosjektinformasjonspanelet på på aggregerte oversikter klarer ikke hente informasjon om prosjektet, mulig issue med context da dette fungerer fint på Porteføljeoversikthttps://github.com/Puzzlepart/prosjektportalen365/commit/3e9fba5398de054cbe9e8e217d58e06bb7251c23
- [x] (2.9) Valuta blir ikke riktig sortert i Porteføljeoversikt (**se skjermbilde 01**) _Pusher til [1.9.1](https://github.com/Puzzlepart/prosjektportalen365/milestone/32)_
- [x] (2.10) Redigering av kolonnerekkefølge via egendefinert skjema på aggregerte oversikter fungerer ikke ved lagring.  https://github.com/Puzzlepart/prosjektportalen365/commit/e0eb41cdf49256f629f7b24eae0ff3225163f04f
- [x] (2.11) Porteføljeoversikt/aggregerte oversikter: Kolonnemeny henger igjen etter trykk, man må trykke utenfor menyen etterpå for at den skal forsvinne. Bør forsvinne ved trykk.
- [x] (2.12) Prosjekt kolonne lenke leder til element (likt som Tittel kolonnen), skal lede til prosjekt. https://github.com/Puzzlepart/prosjektportalen365/commit/b21a76562b3c7d747307ffc779d0004a68ebc20f
- [x] #1302
- [x] (2.14) Porteføljeoversikt: Legg til kolonne feiler med feilen "An unexpected ‘StartObject’ node was found when reading from the JSON reader. A ‘StartArray’ node was expected.", kolonne blir opprettet i Prosjektkolonner, men legges ikke inn i visningen.
- [x] (2.15) Aggregerte oversikter: Legg til kolonne fungerer, men kolonne blir ikke lagt til i visningen eller synlig i "Vis/skjul panelet”, selvom den har riktig kategori…

### 3. ProjectWebParts

- [x] (3.1) Fasevelger: Sjekkpunkter dukker ikke opp i fasevelger dialog selvom det finnes sjekkpunkter og koblet til riktig fase (trolig dukket opp etter 1219) https://github.com/Puzzlepart/prosjektportalen365/commit/07c6da4a6ea3ed6c8eeb31c8b5dd9249611a51b3
- [x] (3.2) Prosjektinformasjon: 'Overordnet prosjekt' dialog er ikke mulig å dismisse ved klikk på 'Avbryt' knapp eller klikk utenfor dialog. https://github.com/Puzzlepart/prosjektportalen365/commit/77a5e6a002aea42eeb20fa092725b98e966fcf98
- [x] #1303
- [x] (3.4) Prosjektstatus: Siden laster ikke, feil: "Cannot read properties of undefined (reading 'replace')"
- [x] (3.5) Prosjektstatus: Problem ved innlastning av Prosjektinformasjon i "SummarySection", laster evig.
- [x] (3.6) Prosjektinformasjon redigeringspanel: Clearing av personfelt fungerer ikke, den lagrer endringen men synker ikke til hub.
- [x] (3.7) Prosjektinformasjon redigeringspanel: Visuell bug med DatePicker (mangler FluentProvider?)
- [x] (3.8) Prosjektstatus: Seksjon for prosjektegenskaper fungerer ikke (se Økonomi seksjon), samt manglende økonomi relaterte fleter i redigeringspanel. Regner med det er gjort noe med hvilke felter som henter inn for prosjektstatus komponenten som gjør at det ikke vises i panel eller på seksjonen.
- [x] #1300
- [x] (3.10) Prosjektstatus: Ved publisering av rapport blir ikke "Åpne øyeblikksbilde" aktiv", fremstår som disabled inntil man refresher
- [x] (3.11) Fasevelger: Kommentarer og status blir ikke vist i oppsummering, hvis man refresher og velger fasen igjen så får man opp kommentarer og status i oppsummeringsdialogen. Den må kanskje gjøre hente data på nytt når man har gått gjennom siste punkt.
- [x] #1301
- [x] (3.13) Prosjekttidslinje: Manglende bounds i nye Popover gjør at popover kommer utenfor rct-scroll, må fikses slik at bounds blir riktig for popover.
- [x] (3.14) Prosjektstatus: Opprettelse av ny statusrapport for nyopprettet prosjekt er ikke mulig pga disabled button
- [ ] #1307

### 4. ProgramWebParts

- [x] (4.1) Administrasjon: Ikke mulig å legge til underområder i program. Ved refresh forsvinner de man la til.
- [x] (4.2) Aggregerte oversikter (Oversikt, Gevinster, Leveranser, Usikkerheter, Kommunikasjonsplaner), laster ikke inn, ser ut til å ha noe med locale å gjøre fra shared?
- [x] (4.3) Aggregert tidslinje laster ikke inn elementer fra prosjektene

---

#### Skjermbilder

| 01 | 3.15 |
| --- | --- |
| ![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/548684fc-868f-4bd5-a5b4-94cf73158550) | <img width="563" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/c10b4b15-8e1d-465a-b944-f3698f828dc8"> |

---

### Versjon

1.9.0

**Comment by olemp** [comment]
@Remi749 

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/923047b8-8524-47a7-b8c1-f39216fab0b8)

Søkeboksen er i preview (`@fluentui/react-search-preview`), og onClear fungerer ikke ordentlig enda tydeligvis. **onClear** gjør ingenting. Litt risky å bruke preview-komponenter, men om vi får det til å fungerer er den jo fin og deilig.

**Comment by olemp** [comment]
> Redigering av kolonner via egendefinert skjema på aggregerte oversikter fungerer ikke ved lagring. Det samme gjelder endring av rekkefølgen av kolonner.

Hva er det som ikke fungerer @Remi749?

**Comment by Remi749** [comment]
> > Redigering av kolonner via egendefinert skjema på aggregerte oversikter fungerer ikke ved lagring. Det samme gjelder endring av rekkefølgen av kolonner.
> 
> Hva er det som ikke fungerer @Remi749?

Gå for eksempel til 'Vis eller skjul kolonner' i Gevinstoversikt, prøv å endre rekkefølge. Feilmelding som dukker opp i console er som følger: 
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/6eac252f-96b9-4242-bef2-1340359b2d56)

Ellers prøv å endre Tittel på en kolonne, endringen ser ut til å fungere, men etter refresh er endringen borte. 
Eksempel på hva jeg gjorde for å gjenskape: Endret navnet til "Siste måling" kolonne på Gevinstoversikt og nytt navn vises. Gjør så en refresh og endringen er borte.

**Comment by olemp** [comment]
@Remi749 For å løse 2.3, må vi nok innføre maxWidth for kolonnene. Jeg tenker at det ikke er verdt det. Vil ikke kalle det en bug sånn egentlig.

**Comment by olemp** [comment]
> @Remi749 For å løse 2.3, må vi nok innføre maxWidth for kolonnene. Jeg tenker at det ikke er verdt det. Vil ikke kalle det en bug sånn egentlig.

Hva tenker du, @Remi749?

(Skal ta en titt på 3.4 i morgen om jeg får tid.)

**Comment by Remi749** [comment]
> > @Remi749 For å løse 2.3, må vi nok innføre maxWidth for kolonnene. Jeg tenker at det ikke er verdt det. Vil ikke kalle det en bug sånn egentlig.
> 
> Hva tenker du, @Remi749?
> 
> (Skal ta en titt på 3.4 i morgen om jeg får tid.)

Hadde vært deilig å fått det ordentlig til ved å innføre maxWidth, da kunne vi hatt "juster kolonner etter skjermbredde" som default oppsett da dette er penere og mer responsivt. Hvis ikke blir den nok sjelden brukt pga "megabred" kolonne "buggen"

**Comment by olemp** [comment]
Ref 2.13. Kul feature! Fikk gjenskapt feilen. Men en annen ting - bør ikke denne konfigurasjonen være i kolonnelisten istedenfor hardkodet? 

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/97ecca7f-b5f5-4dda-84ac-7233eff3faaa)

Alternativt bruke Tag-ikonet på alle:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/0841083e-3b88-4c07-b0a3-1ee3904c2e6a)

@Remi749

**Comment by Remi749** [comment]
> Ref 2.13. Kul feature! Fikk gjenskapt feilen. Men en annen ting - bør ikke denne konfigurasjonen være i kolonnelisten istedenfor hardkodet?
> 
> img1
> 
> Alternativt bruke Tag-ikonet på alle:
> 
> img2
> 
> @Remi749

Vurdere å legge det inn i kolonnelisten, men vi tilbyr få termfelter som vises i oversikten, dermed ble det hardkodet med fallback dersom kunde tar i bruk noe. Dersom vi legger inn maxWidth kunne vi også lagt inn ikon kolonne.

**Comment by olemp** [comment]
@Remi749 

> (2.11) Porteføljeoversikt/aggregerte oversikter: Kolonnemeny henger igjen etter trykk, man må trykke utenfor menyen etterpå for at den skal forsvinne. Bør forsvinne ved trykk.

@Remi749 Dette er pga selection på listen. Har ikke funnet noen måte å unngå dette på.

**Comment by olemp** [comment]
Skal se på 4.1 @Remi749

**Comment by olemp** [comment]
3.6 løst i https://github.com/Puzzlepart/prosjektportalen365/commit/354551bf4d701f872d8b19100efe035741fe2d10

**Comment by olemp** [comment]
Angående 3.7 @Remi749. FluentProvider fra overlayen har bakgrunnsfarge. Vet ikke helt om vi får kontroll på denne.

**Comment by olemp** [comment]
Nå begynte denne å bli litt uoversiktlig @Remi749. Lukker denne, laget issues for resterende uløst saker.

**Comment by Remi749** [comment]
> Nå begynte denne å bli litt uoversiktlig @Remi749. Lukker denne, laget issues for resterende uløst saker.

Her kunne vi bare fjernet det som er ferdig, vi har historikk på posten hvis vi vil hente det fram.

**Comment by olemp** [comment]
> > > Nå begynte denne å bli litt uoversiktlig @Remi749. Lukker denne, laget issues for resterende uløst saker.
> > 
> > 
> > Her kunne vi bare fjernet det som er ferdig, vi har historikk på posten hvis vi vil hente det fram.
> 
> Men nå gjør vi det slik.

Gjør det mye lettere å involvere teamet, prioritere de ulike taskene, etc etc. @Remi749

**Comment by Remi749** [comment]
> > > > Nå begynte denne å bli litt uoversiktlig @Remi749. Lukker denne, laget issues for resterende uløst saker.
> > > 
> > > 
> > > Her kunne vi bare fjernet det som er ferdig, vi har historikk på posten hvis vi vil hente det fram.
> > 
> > 
> > Men nå gjør vi det slik.
> 
> Gjør det mye lettere å involvere teamet, prioritere de ulike taskene, etc etc. @Remi749

E9
