### ISSUE TITLE
'Hent maldokumenter' not working from project frontpage

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#128]
I'm able to pick documents but no documents are copied.

![image](https://user-images.githubusercontent.com/1837390/66549957-bb0cea00-eb44-11e9-9bf5-bf59f014c212.png)

Version 1.1.1

**Comment by olemp** [comment]
Will be included in `1.1.3`. Date TBA. CHANGELOG updated.
