### ISSUE TITLE
Opprett område not dispalyed on start page

### ISSUE THREAD

**Issue by jahepeters** [Puzzlepart/prosjektportalen365#129]
Hi, deployment ok - but missing "Opprett område" on startpage ( se attached screenshot). Creation needs to be done through sp admin portal ... Suggestions? 
![InkedAnnotation 2019-10-10 111034_LI](https://user-images.githubusercontent.com/47447543/66555539-252a8c80-eb4f-11e9-919a-2884421a5a3b.jpg)

**Comment by olemp** [comment]
Hi @jahepeters,

This is most likely due to tenant settings. Is group creation enabled?

https://www.c5insight.com/Resources/Blog/tabid/148/entryid/749/lock-down-self-service-for-creating-office-365-groups.aspx

**Comment by tarjeieo** [comment]
Som Ole Martin sier så skyldes dette mest sannsynlig at dere har slått av self-service opprettelse av rom og grupper – dette har ikke direkte sammenheng med PP365, men PP365 blir naturlig nok truffet av denne begrensningen. Da må opprettelse av prosjekter håndteres på måte som ikke er helt standard. Alternativer kan være
1.	Alle brukere får tilgang til å lage områder og rom
2.	Brukerne som skal kunne opprette prosjekter (og andre rom) gis tilgang til dette (IT må gjøre dette administrativt)
3.	Brukere får tilgang til å bestille rom fra en liste, IT oppretter basert på bestillingen
4.	Brukere får tilgang til å bestille rom fra en liste, rommet blir opprettet vha. en automatisert rutine

Denne diskusjonen bør tas med intern IT og vi kan selvsagt bistå i om dere er interessert i at vi foreslår løsninger for alternativ 3 og 4 her, da vi har mye erfaring med lignende prosesser. Anbefaler å først høre med O365 admin hva han tenker og hvordan opprettelse av områder og grupper eventuelt løses hos dere.
