### ISSUE TITLE
Project web parts does not work in Edge

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#13]
HTTP403: FORBUDT – Serveren forstod forespørselen, men avslår å fullføre den.
(Fetch)GET - https://pzlcloud.sharepoint.com/sites/Nyttkvalitetssystem/_api/HubSites/GetById('83f93d27-a725-4a14-ab9f-004ca5ff88a9')

Unhandled promise rejection TypeError: Unable to get property '_url' of undefined or null reference

**Comment by olemp** [comment]
fetch() call to /_api/HubSites/GetById('83f93d27-a725-4a14-ab9f-004ca5ff88a9') was missing credentials "include".
