### ISSUE TITLE
Legg til parameteren -SkipTaxonomy

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen365#130]
For kunder som har Prosjektporalten fra før (2.x/365) og gjort endringer i term store, så savnes parameteren -SkipTaxonomy.

Ønsker dette på plass igjen.

**Comment by olemp** [comment]
Added in https://github.com/Puzzlepart/prosjektportalen365/commit/76a65ac77813f608e35fee18af3f4f7d590a05c2.
