### ISSUE TITLE
Prosjektstatus: Navigasjonslinje skal være sticky

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1300]
Prosjektstatus: Navigasjonslinje er ikke sticky, denne skal vises når man scroller, header og commandbar skal ikke vises ved scroll.

**Comment by tarjeieo** [comment]
Vi klarer oss uten denne i 1.9 IMO

**Comment by olemp** [comment]
> Vi klarer oss uten denne i 1.9 IMO

Enig med du!
