### ISSUE TITLE
Gammel "Hjelp tilgjengelig" knapp er fortsatt synlig

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1304]
Gammel "Hjelp tilgjengelig" knapp er fortsatt synlig oppe til høyre, bør legges inn en jobb som fjerner dette ved upgrade

**Comment by olemp** [comment]
Hjelpeinnholdskomponenten finnes ikke lenger, så dette bør ikke by på noen særlige problemer. Tror ikke vi trenger å prioritere denne for 1.9 @tarjeieo @Remi749?

**Comment by Remi749** [comment]
@olemp Hva skjer hos brukere som oppgraderer, hvor de har den gamle komponenten?

**Comment by olemp** [comment]
SPFx webdelen finnes jo ikke lenger når de oppgraderer, så ingenting vil skje. Muligens en feilmelding i console. Et alternativ er å legge den til igjen som komponent, og få den til å fjerne seg selv når den lastes 😊

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
