### ISSUE TITLE
Hjelp tilgjengelig henter ikke inn nytt innhold dersom du navigerer til en annen side

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1305]
Hjelp tilgjengelig henter ikke inn nytt innhold dersom du navigerer deg til en annen side, mangler refresh fetch help content dersom window.location.pathname endrer seg.

**Comment by Remi749** [comment]
Prøvde meg på denne, men kan se ut som vi må flytte hele fetch help content ut fra ApplicationCustomizer og inn i HelpContent funksjonen, tanker? @olemp

**Comment by olemp** [comment]
> Prøvde meg på denne, men kan se ut som vi må flytte hele fetch help content ut fra ApplicationCustomizer og inn i HelpContent funksjonen, tanker? @olemp

Hvorfor det? Kan vi ikke beholde logikken samme sted ved å kjøre fetch på nytt om URL endrer seg? Det skal være en event vi kan koble oss på.

**Comment by Remi749** [comment]
> > Prøvde meg på denne, men kan se ut som vi må flytte hele fetch help content ut fra ApplicationCustomizer og inn i HelpContent funksjonen, tanker? @olemp
> 
> Hvorfor det? Kan vi ikke beholde logikken samme sted ved å kjøre fetch på nytt om URL endrer seg? Det skal være en event vi kan koble oss på.

Har prøvd, men kom ingen vei med noe av det jeg prøvde. Ingen muligheter for componentDidMount eller componentDidUpdate i ApplicationCustomizer.

**Comment by olemp** [comment]
> > > Prøvde meg på denne, men kan se ut som vi må flytte hele fetch help content ut fra ApplicationCustomizer og inn i HelpContent funksjonen, tanker? @olemp
> > 
> > 
> > Hvorfor det? Kan vi ikke beholde logikken samme sted ved å kjøre fetch på nytt om URL endrer seg? Det skal være en event vi kan koble oss på.
> 
> Har prøvd, men kom ingen vei med noe av det jeg prøvde. Ingen muligheter for componentDidMount eller componentDidUpdate i ApplicationCustomizer.

Man kan skal kunne hooke seg på `navigatedEvent`:

```typescript
this.context.application.navigatedEvent.add(this, this.onNavigatedEvent);
```

Da skal man i `onNavigatedEvent` kunne fetche data på nytt og kjøre ny `this.render()`.


ref https://github.com/SharePoint/sp-dev-docs/issues/7583

**Comment by Remi749** [comment]
> > > > Prøvde meg på denne, men kan se ut som vi må flytte hele fetch help content ut fra ApplicationCustomizer og inn i HelpContent funksjonen, tanker? @olemp
> > > 
> > > 
> > > Hvorfor det? Kan vi ikke beholde logikken samme sted ved å kjøre fetch på nytt om URL endrer seg? Det skal være en event vi kan koble oss på.
> > 
> > 
> > Har prøvd, men kom ingen vei med noe av det jeg prøvde. Ingen muligheter for componentDidMount eller componentDidUpdate i ApplicationCustomizer.
> 
> Man kan skal kunne hooke seg på `navigatedEvent`:
> 
> ```ts
> this.context.application.navigatedEvent.add(this, this.onNavigatedEvent);
> ```
> 
> Da skal man i `onNavigatedEvent` kunne fetche data på nytt og kjøre ny `this.render()`.
> 
> ref [SharePoint/sp-dev-docs#7583](https://github.com/SharePoint/sp-dev-docs/issues/7583)

Takk! det funka!
