### ISSUE TITLE
Hjelpeinnhold differensierer ikke på om hjelpeinnholdet er på prosjekt, program eller portefølje.

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1306]
Hjelpeinnhold differensierer ikke på om hjelpeinnholdet er på prosjekt, program eller portefølje. Se tidslinje (her vises både Prosjekt og Portefølje innholdet som faner)

**Comment by olemp** [comment]
Mulig vi må innføre nivå på hjelpeinnholdet @Remi749 @tarjeieo. Ser også at en del av hjelpeinneholdet **naturligvis** ikke matcher med det nye 1.9.0 designet.

**Comment by Remi749** [comment]
> Mulig vi må innføre nivå på hjelpeinnholdet @Remi749 @tarjeieo. Ser også at en del av hjelpeinneholdet **naturligvis** ikke matcher med det nye 1.9.0 designet.

Vi bør innføre nivå ja, det skal gjøre en del jobb der med innholdet i dialogen

**Comment by Remi749** [comment]
@olemp, er dette issuet ferdig? Ser PR er merget, hva gjenstår eventuelt?

**Comment by olemp** [comment]
> @olemp, er dette issuet ferdig? Ser PR er merget, hva gjenstår eventuelt?

Denne skal være klar :)

**Comment by Remi749** [comment]
@olemp , testet dette igår og fikk opp prosjektnivå hjelpeinnhold på porteføljenivå (se Prosjekttidslinje, her dukket det opp en ekstra fane). Hvis innhold fra et annet nivå ikke lengre vises kan denne lukkes

**Comment by Remi749** [comment]
Gjorde samme test nå og nå funger det fint. Lukker.
