### ISSUE TITLE
Prosjektstatus: Feil med fluent provider for datepicker

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1307]
Prosjektstatus: Feil med fluent provider for datepicker (fungerer for dropdowns)

**Comment by Remi749** [comment]
@olemp, tenker jeg prøver opp å oppdatere pakkene for fluent ui, ser om det kanskje fungerer som det skal da, hvis ikke tror jeg vi bare reverterer datepicker til fluent ui 8 slik at vi ikke shipper med bugga ui.

**Comment by Remi749** [comment]
@olemp , fungerer fint etter oppdatering: 
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/bab58bae-ec50-401b-8c3f-b629dbbff81c)
