### ISSUE TITLE
Lenke til Prosjektveiviseren under Nyttige lenker må oppdateres

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1311]
### Beskriv feilen

Lenken til Prosjektveiviseren i quick links web parten på forsiden er deprecated og må oppdateres til "https://prosjektveiviseren.digdir.no"

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/21e127b35114f663a9a54131c311dba28c487d4d
