### ISSUE TITLE
Program: Oversikt og aggregerte oversikter fungerer ikke

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1312]
Oversikt og aggregerte oversikter fungerer ikke, laster ikke inn som det skal.

`Cannot read properties of null (reading 'type')`

**Comment by olemp** [comment]
Ser ut som feilen skjer her:

<img width="759" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/e21edbf2-652b-4841-a6e0-bd559f397a91">

Mangler muligens en .filter(Boolean) for å fjerne "conditional" menyelementer @Remi749

**Comment by olemp** [comment]
Ser ut som Leveranseoversikt laster. Sikker på at det også gjelder aggregerte oversikter @Remi749?

<img width="1719" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/3ba0ee25-0e9f-4d61-a970-048e6bd6cc65">

**Comment by Remi749** [comment]
> Ser ut som Leveranseoversikt laster. Sikker på at det også gjelder aggregerte oversikter @Remi749?
> 
> <img alt="image" width="1719" src="https://user-images.githubusercontent.com/7606007/284836502-3ba0ee25-0e9f-4d61-a970-048e6bd6cc65.png">

Når jeg testet igår lastet ikke Oversikt og Gevinster ihvertfall

**Comment by olemp** [comment]
> > Ser ut som Leveranseoversikt laster. Sikker på at det også gjelder aggregerte oversikter @Remi749?
> > <img alt="image" width="1719" src="https://user-images.githubusercontent.com/7606007/284836502-3ba0ee25-0e9f-4d61-a970-048e6bd6cc65.png">
> 
> Når jeg testet igår lastet ikke Oversikt og Gevinster ihvertfall

Hvilket område testet du på? Ser ut som det kun er Oversikt som ikke laster på https://puzzlepart.sharepoint.com/sites/OsloProgramfortjenesteinnovasjon/.

**Comment by Remi749** [comment]
> > > Ser ut som Leveranseoversikt laster. Sikker på at det også gjelder aggregerte oversikter @Remi749?
> > > <img alt="image" width="1719" src="https://user-images.githubusercontent.com/7606007/284836502-3ba0ee25-0e9f-4d61-a970-048e6bd6cc65.png">
> > 
> > 
> > Når jeg testet igår lastet ikke Oversikt og Gevinster ihvertfall
> 
> Hvilket område testet du på? Ser ut som det kun er Oversikt som ikke laster på https://puzzlepart.sharepoint.com/sites/OsloProgramfortjenesteinnovasjon/.

Kan se ut til at det kun var det programmet der da.

**Comment by olemp** [comment]
> > > > Ser ut som Leveranseoversikt laster. Sikker på at det også gjelder aggregerte oversikter @Remi749?
> > > > <img alt="image" width="1719" src="https://user-images.githubusercontent.com/7606007/284836502-3ba0ee25-0e9f-4d61-a970-048e6bd6cc65.png">
> > > 
> > > 
> > > Når jeg testet igår lastet ikke Oversikt og Gevinster ihvertfall
> > 
> > 
> > Hvilket område testet du på? Ser ut som det kun er Oversikt som ikke laster på https://puzzlepart.sharepoint.com/sites/OsloProgramfortjenesteinnovasjon/.
> 
> Kan se ut til at det kun var det programmet der da.

Har funnet feilen, så kan jeg ta denne nå.

**Comment by olemp** [comment]
Løst i #1313
