### ISSUE TITLE
Forbedringer tiltakshåndtering

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1315]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Dette er relatert til SPFx-komponenten for tiltakshåndtering.

### Beskriv løsningen du ønsker

- Ser ut som tiltaktene havner i Realisere-bøtta? De skal vel i en swimlane som heter "Tiltak", ref. globale innstillinger? [Framtidsbilder Trondheim sentrum 2050 med sentrumsstrategi - Usikkerhet - Alle elementer (sharepoint.com)](https://puzzlepart.sharepoint.com/sites/FramtidsbilderTrondheimsentrum2050medsentrumsstrategi/Lists/Usikkerhet/AllItems.aspx?xsdata=MDV8MDF8fGMxNGExZmVhZTM3MTRjNGQzM2MzMDhkYmQ2YmFhMGEzfGRjYjg5YzEwNjdiODQ4Y2M4ODE5ODVkZTM3ZThhZjkxfDB8MHw2MzgzMzk4NjkyNTAzNjg0NTF8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPakU0TkRkbU1EQTVMV0kwTWpVdE5HVTJNaTA0TWpnMkxXWXlNR1UxTW1aaU4yVm1OVjgwTVdNME1qTXpaUzFpWWpJeUxUUTBaakl0WW1OaU5DMDRaakF4TURZeFl6QmpNamhBZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVFk1T0RNNU1ERXlNelk0TlE9PXw4MjJiNTAyNjk1Y2Y0ZWJjMzNjMzA4ZGJkNmJhYTBhM3w3MzNkYzk3ZjQ5YWU0Y2I5ODI1N2Y1NDI3MWY5ZDk0OA%3D%3D&sdata=WmdSZGRpRGkyRFQ1Nm0rMjF0cjh1NHlNcU45TG9XTmIxR3RIZmRGN1Rqcz0%3D&ovuser=dcb89c10-67b8-48cc-8819-85de37e8af91%2Ctarjeieo%40puzzlepart.com)
- Når man klikker på et tiltak i listen - kan man heller få en preview av tiltaket som dialog, istedenfor å åpne planner? Og så evt en link til å åpne tiltaket i planner for å jobbe mer detaljert?

**Comment by olemp** [comment]
@tarjeieo Hvilke detaljer er aktuelt å vise i Planner task previewen?

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/88fce2f1-40d5-47da-9cde-7848a8e17f36)


```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#planner/tasks(details())/$entity",
    "@odata.etag": "W/\"JzEtVGFzayAgQEBAQEBAQEBAQEBAQEBATCc=\"",
    "planId": "J6oYRz7XGUyKps_eudQNz5cAH4hR",
    "bucketId": "mWL1odn0ikSrCkg3RRYjNpcABYtg",
    "title": "Tittel A",
    "orderHint": "8585009468505622626",
    "assigneePriority": "",
    "percentComplete": 0,
    "startDateTime": null,
    "createdDateTime": "2023-11-22T13:33:54.9153181Z",
    "dueDateTime": null,
    "hasDescription": true,
    "previewType": "automatic",
    "completedDateTime": null,
    "completedBy": null,
    "referenceCount": 1,
    "checklistItemCount": 0,
    "activeChecklistItemCount": 0,
    "conversationThreadId": null,
    "priority": 5,
    "id": "DdMPbaN8m0uFUbrdz0WsjJcACwWe",
    "createdBy": {
        "user": {
            "displayName": null,
            "id": "12c52351-57f2-4cd3-8549-8bc8a61e0f7b"
        },
        "application": {
            "displayName": null,
            "id": "857a1b3f-91be-44f3-a50f-9b19bc59be2b"
        }
    },
    "appliedCategories": {},
    "assignments": {},
    "details@odata.context": "https://graph.microsoft.com/v1.0/$metadata#planner/tasks('DdMPbaN8m0uFUbrdz0WsjJcACwWe')/details/$entity",
    "details": {
        "@odata.etag": "W/\"JzEtVGFza0RldGFpbHMgQEBAQEBAQEBAQEBAQEBATCc=\"",
        "description": "\r\n\r\n",
        "previewType": "automatic",
        "id": "DdMPbaN8m0uFUbrdz0WsjJcACwWe",
        "references": {
            "https%3A//puzzlepart%2Esharepoint%2Ecom/sites/aaskollenungdomsskolemedflerbrukshall/Lists/Usikkerhet/DispForm%2Easpx?ID=4": {
                "@odata.type": "#microsoft.graph.plannerExternalReference",
                "alias": "D",
                "type": null,
                "previewPriority": "8585009468501768889",
                "lastModifiedDateTime": "2023-11-22T13:33:55.3006918Z",
                "lastModifiedBy": {
                    "user": {
                        "displayName": null,
                        "id": "12c52351-57f2-4cd3-8549-8bc8a61e0f7b"
                    }
                }
            }
        },
        "checklist": {}
    }
}
```

**Comment by tarjeieo** [comment]
Ønskeliste:
- Tittel
- Tilordnet til
- Forfallsdato
- Fremdrift
- Beskrivelse

Tror ikke vi skal dra inn sjekklister og vedlegg osv, blir for komplisert...

**Comment by olemp** [comment]
> Ønskeliste:
> 
> * Tittel
> * Tilordnet til
> * Forfallsdato
> * Fremdrift
> * Beskrivelse
> 
> Tror ikke vi skal dra inn sjekklister og vedlegg osv, blir for komplisert...

Med fremdrift mener du `percentComplete`?

Enig med du angående sjekklister og vedlegg.

**Comment by tarjeieo** [comment]
> > Ønskeliste:
> > 
> > * Tittel
> > * Tilordnet til
> > * Forfallsdato
> > * Fremdrift
> > * Beskrivelse
> > 
> > Tror ikke vi skal dra inn sjekklister og vedlegg osv, blir for komplisert...
> 
> Med fremdrift mener du `percentComplete`?
> 
> Enig med du angående sjekklister og vedlegg.

<img width="188" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/0bdd82f6-f2a0-4032-b81e-b7d2d487acb6">

Men dropp det om det er noe custom logikk knyttet til dette

**Comment by tarjeieo** [comment]
Dog bør man se om oppgaven er fullført som et minimum

**Comment by olemp** [comment]
> ```json
> activeChecklistItemCount
> ```

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/a8905e99-9110-4727-9798-c5336a237874)

Sånn som dette?

**Comment by tarjeieo** [comment]
Ja, liker... Hvor routes man om man trykker på oppgaven? Til Oppgavesiden i SP med oppgaven valgt? Eller til planner nettsiden? Tenker det første er mest naturlig, men det andre funker også

**Comment by olemp** [comment]
> Ja, liker... Hvor routes man om man trykker på oppgaven? Til Oppgavesiden i SP med oppgaven valgt? Eller til planner nettsiden? Tenker det første er mest naturlig, men det andre funker også

Vet ikke om førstnevnte støtter parametere, men vi kan sjekke.

**Comment by olemp** [comment]
> > Ja, liker... Hvor routes man om man trykker på oppgaven? Til Oppgavesiden i SP med oppgaven valgt? Eller til planner nettsiden? Tenker det første er mest naturlig, men det andre funker også
> 
> Vet ikke om førstnevnte støtter parametere, men vi kan sjekke.

Ser ikke slik ut, så vi må lenke til Planner.

Fant en "deilig" feil i denne funksjonen.

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/26b007a2-bb65-4658-afed-fa92b5d02661)

Må se om vi kan hente ut dette dynamisk.

**Comment by olemp** [comment]
> > > Ja, liker... Hvor routes man om man trykker på oppgaven? Til Oppgavesiden i SP med oppgaven valgt? Eller til planner nettsiden? Tenker det første er mest naturlig, men det andre funker også
> > 
> > 
> > Vet ikke om førstnevnte støtter parametere, men vi kan sjekke.
> 
> Ser ikke slik ut, så vi må lenke til Planner.
> 
> Fant en "deilig" feil i denne funksjonen.
> 
> ![image](https://user-images.githubusercontent.com/7606007/284947094-26b007a2-bb65-4658-afed-fa92b5d02661.png)
> 
> Må se om vi kan hente ut dette dynamisk.

Ser ut som vi ikke trenger ha med domene:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/a98f8dd8-b342-43c7-8dd1-4393976d6150)

**Comment by tarjeieo** [comment]
Den var godt at du fikk luket ut ja

**Comment by olemp** [comment]
> Den var godt at du fikk luket ut ja

Forbedringer utført i #1317
