### ISSUE TITLE
If default Planner tasks isn't included no Planner is created

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#132]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X] Bug

[ ] Question

#### Summary

If you don't check "Include planner tasks", no planner is created. The expected result is that an empty Plan is created.

#### Version

Please specify what version you are using: [ 1.1.1]

**Comment by olemp** [comment]
Will be included in `1.1.3`. Date TBA. CHANGELOG updated.
