### ISSUE TITLE
Idea Project Data dialog $1.2

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1320]
Hensytar ikke status på idèen, oppretter prosjektdata uansett

**Comment by Remi749** [comment]
Hvis en idé ikke er godkjent kan man ikke lengre opprette prosjektdata
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/e5eabd18-a2e1-4717-bfd6-80ee3f66e18f)
