### ISSUE TITLE
Footer $1.5

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1322]
Fjerne typiske admin lenker fra Nyttige lenker:
Ta bort; 
- Prosjektinnholdskolonner
- Datakilder
- Tillatelseskonfigurasjon
- Fasesjekkliste

Rette lenken til Prosjektveiviseren

Legge til lenke til brukermanualen

Legge på "admin sjekk" på 
- Områdeinstillinger
- Konfigurasjon av Prosjetkportalen

**Comment by Remi749** [comment]
Fjernet lenker, rettet lenke til Prosjektveiviseren og lagt inn lenke til brukermanual.
