### ISSUE TITLE
Verifiser at lenken til "Lenker" er klikkbar og tar deg til listen (tooltip) $1.5.4

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1326]
Listen nyttige lenker må berikes med en form for tilgangskontroll for hver enkelt lenke.

Typ; ny kolonne som stilles inn med hvem som får "se" den enkelte lenke

**Comment by Remi749** [comment]
Lagt til lenke for å nivåstyre hvilke lenker som skal være tilgjengelig for admins/medlemmer. Logikk tas senere.
