### ISSUE TITLE
Verifiser at Hjelp utilgjengelig vises på sider hvor det ikke finnes hjelpeinnhold $1.5.7

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1327]
Hjelp utilgjengelig bør berikes med tooltip lik "Ingen hjelp tilgjengelig for denne siden"

**Comment by Remi749** [comment]
Dette skulle egentlig dukket opp, så her er det en bug som gjør at tooltip ikke vises når knapp er disabled...
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/d452429f-cd6e-429d-8e22-9620cb9aa0ec)

**Comment by Remi749** [comment]
Fant buggen, blir straks fikset.
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/cd244e77-4932-4b20-8a59-405e5612224f)
