### ISSUE TITLE
Verifiser at Konfigurasjon av Prosjektportalen ikke vises med mindre du er admin $1.5.8

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1328]
Hele footeren mangler når man logger på som en vanlig medlem

**Comment by Remi749** [comment]
@olemp, her er det noe rart. Kan ikke finne noe sjekk for admin eller noe som tilgangstyrer init eller render av Footer. Har du mulighet til å sjekke opp i denne? Logg inn med Benjamin Dover brukeren.

**Comment by olemp** [comment]
> @olemp, her er det noe rart. Kan ikke finne noe sjekk for admin eller noe som tilgangstyrer init eller render av Footer. Har du mulighet til å sjekke opp i denne? Logg inn med Benjamin Dover brukeren.

Løst i #1353. Det var ikke så rart egentlig :)
