### ISSUE TITLE
Verifiser at visnings-id legger seg i adressefeltet $2.2.1.3

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1329]
Url oppdateres ikke ved bytte av filter.
Dersom ID skulle havnet i url så skjer altså ikke det.

**Comment by Remi749** [comment]
Denne er kritisk, da flere kunder anvender visnings-id for å lenke til ferdig "filtrerte" visninger som er i toppmeny i SharePoint

**Comment by olemp** [comment]
View ID legger seg i URL som den alltid har gjort:

<img width="1491" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/ae2d4dee-b2eb-4b9f-8f2e-3f18c5feba84">

_Mulig @pzljanb har misforstått, ser han skriver "Url oppdateres ikke ved bytte av filter". URL skal oppdatere seg ved bytte av visning._

**Comment by Remi749** [comment]
@olemp , Dette gjelder Porteføleoversikt. Her er funksjonaliteten borte.

**Comment by olemp** [comment]
Nei, denne gjelder aggregeringswebdelen:

<img width="638" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/bdab99e0-62e4-4ad4-b04f-51108c58e72f">

Jeg opprettet #1355

**Comment by Remi749** [comment]
> Nei, denne gjelder aggregeringswebdelen:
> 
> <img width="638" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/bdab99e0-62e4-4ad4-b04f-51108c58e72f">
> 
> Jeg opprettet #1355 

Alle issues under aggregert er egentlig porteføljeoversikt. Han oppretta bare feil.

**Comment by olemp** [comment]
> > Nei, denne gjelder aggregeringswebdelen:
> > <img alt="image" width="638" src="https://private-user-images.githubusercontent.com/7606007/292167654-bdab99e0-62e4-4ad4-b04f-51108c58e72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTM1NTEsIm5iZiI6MTcwMzE1MzI1MSwicGF0aCI6Ii83NjA2MDA3LzI5MjE2NzY1NC1iZGFiOTllMC02MmU0LTRhZDQtYjA0Zi01MTEwOGM1OGU3MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTAwNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM4YTBmZTI3OWJkNDA3Y2EzYWQxZjFhNGNiZWI0MDljNTgzNDAxYzlmMDE1NGJmODUxNDhmN2NjOGRmZTdhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SWknMrIm6NvYEmis8UwCG2f69J9_05QnPVUO-nTysXg">
> > Jeg opprettet #1355
> 
> Alle issues han opprettet under aggregert er egentlig porteføljeoversikt. Han oppretta bare feil.

Det er jo ett eget punkt for Porteføljeoversikt. Har han blandet disse mener du?

<img width="752" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/f93a5a1c-7125-40af-89e1-a0ec758cefe7">

**Comment by Remi749** [comment]
> > > Nei, denne gjelder aggregeringswebdelen:
> > > <img alt="image" width="638" src="https://private-user-images.githubusercontent.com/7606007/292167654-bdab99e0-62e4-4ad4-b04f-51108c58e72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTM1NTEsIm5iZiI6MTcwMzE1MzI1MSwicGF0aCI6Ii83NjA2MDA3LzI5MjE2NzY1NC1iZGFiOTllMC02MmU0LTRhZDQtYjA0Zi01MTEwOGM1OGU3MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTAwNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM4YTBmZTI3OWJkNDA3Y2EzYWQxZjFhNGNiZWI0MDljNTgzNDAxYzlmMDE1NGJmODUxNDhmN2NjOGRmZTdhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SWknMrIm6NvYEmis8UwCG2f69J9_05QnPVUO-nTysXg">
> > > Jeg opprettet #1355
> > 
> > Alle issues han opprettet under aggregert er egentlig porteføljeoversikt. Han oppretta bare feil.
> 
> Det er jo ett eget punkt for Porteføljeoversikt. Har han blandet disse mener du?
> 
> <img width="752" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/f93a5a1c-7125-40af-89e1-a0ec758cefe7">
> 

Riktig

**Comment by olemp** [comment]
> > > > Nei, denne gjelder aggregeringswebdelen:
> > > > <img alt="image" width="638" src="https://private-user-images.githubusercontent.com/7606007/292167654-bdab99e0-62e4-4ad4-b04f-51108c58e72f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTM1NTEsIm5iZiI6MTcwMzE1MzI1MSwicGF0aCI6Ii83NjA2MDA3LzI5MjE2NzY1NC1iZGFiOTllMC02MmU0LTRhZDQtYjA0Zi01MTEwOGM1OGU3MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTAwNzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM4YTBmZTI3OWJkNDA3Y2EzYWQxZjFhNGNiZWI0MDljNTgzNDAxYzlmMDE1NGJmODUxNDhmN2NjOGRmZTdhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SWknMrIm6NvYEmis8UwCG2f69J9_05QnPVUO-nTysXg">
> > > > Jeg opprettet #1355
> > > 
> > > 
> > > Alle issues han opprettet under aggregert er egentlig porteføljeoversikt. Han oppretta bare feil.
> > 
> > 
> > Det er jo ett eget punkt for Porteføljeoversikt. Har han blandet disse mener du?
> > <img alt="image" width="752" src="https://private-user-images.githubusercontent.com/7606007/292168906-f93a5a1c-7125-40af-89e1-a0ec758cefe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTM3NjAsIm5iZiI6MTcwMzE1MzQ2MCwicGF0aCI6Ii83NjA2MDA3LzI5MjE2ODkwNi1mOTNhNWExYy03MTI1LTQwYWYtODllMS1hMGVjNzU4Y2VmZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTAxMTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQ1MTU5N2FiMDUxYjdjN2U1OWQ0YzBiMzVlNjZkNjU0MDVhOTUxOWJkOGQ4NmUxZDNjNGJmOTI1M2NiMjU2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1IPXc2Ze63JRqGYkt06nQbzsABVtYkOv00lYAhIvWRE">
> 
> Riktig

Ok, det var vanskelig for meg å vite :)
