### ISSUE TITLE
Better support for the Portfolio administrator role 

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#133]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

In many organisations a portfolio administrator roles is used to see the full portfolio. We currently don't support this role too well, i.e. a user with this role needs to be added as member or owner to each and every project

Can we support this in any other way? Can be an "add-on" type of functionality if it's hard to package as part of default install. 

One alternative include AD-group that is added as *SharePoint*-member of each site (don't add as. Will also need to think about smart way to show projects at the portfolio level to avoid the limitation of only showing current user's projects

**Comment by olemp** [comment]
To be discussed offline.

**Comment by olemp** [comment]
Do we want to add them as group members or site members @tarjeieo?

**Comment by tarjeieo** [comment]
I was thinking SharePoint groups, i.e. not O365 group members.

**Comment by olemp** [comment]
We could do something like this @tarjeieo?

![image](https://user-images.githubusercontent.com/7606007/70514236-89f46a00-1b33-11ea-949a-25165d4bc952.png)

**Comment by olemp** [comment]
Implemented.

The "engine" attempts to find the group `Porteføljeadministratorer` on the hub site and its members. If the group exists, it will add its members to the members group of the new project site.

![image](https://user-images.githubusercontent.com/7606007/70939955-9c960400-2049-11ea-805d-325c5696b03f.png)

Fix will be included in next release. CHANGELOG updated.
