### ISSUE TITLE
"Vis visningsvelger" kræsjer dersom man gjør endringer i egenskaper

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1334]
Toggle på "Vis visningsvelger" virker ikke

**Comment by olemp** [comment]
Trenger vi egentlig denne funksjonen, @Remi749? Jeg foreslår å fjerne valget, og dermed gjøre koden en del mindre kompleks (se #1356).

**Comment by Remi749** [comment]
Det er kunder som kun ønsker KUN en spesifikk visning, tror Arbeidstilsynet har dette.

**Comment by olemp** [comment]
> @olemp, det er kunder som kun ønsker KUN en spesifikk visning, tror Arbeidstilsynet har dette.

Skjønner. Det er noen hooks som ikke kjører (eller evt kjører) når man endrer denne til false. Skal se om jeg finner ut av dette. 🧐

**Comment by olemp** [comment]
Endelig fikset. Litt dårlig bruk av hooks (av meg) i Toolbar komponenten. Dette er nå ordnet nok opp i til at det fungerer. https://github.com/Puzzlepart/prosjektportalen365/pull/1535

**Comment by siifux** [comment]
1. Testet å vise visningsvelger, dette gir ingen endring. 

2. Testet å vise programvisninger, dette feiler (kræsjer). I tillegg, dersom man fjerner programvisning igjen, blir fremdeles teksten "Programmer" stående. 

![Image](https://github.com/user-attachments/assets/0ae14e9c-2677-494e-81af-e612b0e24f2c)

**Comment by siifux** [comment]
Denne gjelder Prosjektportalen Hjem (hub). Der fungerer det som det som ønskelig 👍
