### ISSUE TITLE
Resource allocation improvements

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#134]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[X] Enhancement

[ ] Bug

[ ] Question

#### Summary

Improvements
* Colors not matching percentage
* Ability to add resource entries without a person, only as role
* Ability to specify allocation status: Requested, Allocated, Denied

**Comment by tarjeieo** [comment]
One more issue. Columns are not matching content. Looks like dates are wrong.
![image](https://user-images.githubusercontent.com/1837390/67200827-18d2e900-f405-11e9-9bba-12029b62ef7b.png)

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/pull/138
