### ISSUE TITLE
Risk Action - Mangler info og funksjon $4.4

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1340]
Mangler info og funksjon (får ikke noe når jeg hovrer over):

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/5815ecaa-7e8e-40f1-8371-8f66372c7191)

**Comment by olemp** [comment]
Får ikke reprodusert dette. Mulig dette er ett gammel prosjektrom. Vanskelig å få løst denne før @pzljanb er tilbake, da prosjektet skjermbildet er fra ikke eksisterer lenger.

**Comment by olemp** [comment]
> @olemp , her dukket problemet opp på nytt prosjekt, men fungerer fint på eldre prosjekter. Test eventuelt på nytt, hvis det fungerer som det skal så kan den lukkes igjen. Ellers bør vi vente til @pzljanb er tilbake før vi bare lukker.

Om man ikke har nok info til å reprodusere feilen, er det bedre å gjenåpne når man har tilstrekkelig info :)

Har du URL til ett prosjekt hvor det ikke fungerer, @Remi749?

**Comment by Remi749** [comment]
> > @olemp , her dukket problemet opp på nytt prosjekt, men fungerer fint på eldre prosjekter. Test eventuelt på nytt, hvis det fungerer som det skal så kan den lukkes igjen. Ellers bør vi vente til @pzljanb er tilbake før vi bare lukker.
> 
> Om man ikke har nok info til å reprodusere feilen, er det bedre å gjenåpne når man har tilstrekkelig info :)
> 
> Har du URL til ett prosjekt hvor det ikke fungerer, @Remi749?

Det må opprettes nytt prosjekt, da test prosjektene hvor feilene ble oppdaget er slettet.

**Comment by olemp** [comment]
> > > @olemp , her dukket problemet opp på nytt prosjekt, men fungerer fint på eldre prosjekter. Test eventuelt på nytt, hvis det fungerer som det skal så kan den lukkes igjen. Ellers bør vi vente til @pzljanb er tilbake før vi bare lukker.
> > 
> > 
> > Om man ikke har nok info til å reprodusere feilen, er det bedre å gjenåpne når man har tilstrekkelig info :)
> > Har du URL til ett prosjekt hvor det ikke fungerer, @Remi749?
> 
> Det må opprettes nytt prosjekt, da test prosjektene hvor feilene ble oppdaget er slettet.

Da tester jeg dette nå med ett nytt prosjekt.

**Comment by olemp** [comment]
> > > > @olemp , her dukket problemet opp på nytt prosjekt, men fungerer fint på eldre prosjekter. Test eventuelt på nytt, hvis det fungerer som det skal så kan den lukkes igjen. Ellers bør vi vente til @pzljanb er tilbake før vi bare lukker.
> > > 
> > > 
> > > Om man ikke har nok info til å reprodusere feilen, er det bedre å gjenåpne når man har tilstrekkelig info :)
> > > Har du URL til ett prosjekt hvor det ikke fungerer, @Remi749?
> > 
> > 
> > Det må opprettes nytt prosjekt, da test prosjektene hvor feilene ble oppdaget er slettet.
> 
> Da tester jeg dette nå med ett nytt prosjekt.

Ser ut som feltet blir riktig med korrekt ClientSideComponentId, men får følgende feil i console

```
ail to load customizer for column: GtRiskAction,
                  componentId: 32f5eb06-353c-4561-b095-4703e3144989, error: Extension failed to initialize for componentId "32f5eb06-353c-4561-b095-4703e3144989".
```

Må finne ut hvordan man debugger dette :)

**Comment by olemp** [comment]
Løses av #1357. Skjedde noe feil med IDene [her](https://github.com/Puzzlepart/prosjektportalen365/commit/41ca95e83161eeecc99901369e9fc9c312917961#diff-b2d7e9094b2e945147bb93b4a282b030ea672e6f7a930e5edea681c1b146392e) ;)
