### ISSUE TITLE
Siste prosjekter viser slettet prosjekt

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1342]
I vårt dev miljø dukker det opp prosjekt(er) som er slettet.

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/4e88142c-160c-493d-8350-a0dcc3d4f496)

**Comment by Remi749** [comment]
Ser at søket viser treff på dette området selvom det ble slettet for over en måned siden. Ser ut som det skjer dersom man får throttle problemer og holder på å slette et områder at noe henger igjen i SharePoint.

**Comment by Remi749** [comment]
@tarjeieo , dette ser ut til å være SharePoint problematikk. Er det noe grei måte å rydde vekk slettede områder fra søk? Full crawl, reset search index? Har du noe script vi kan kjøre?

**Comment by tarjeieo** [comment]
Får du gjenskapt det i std SP søk? I så fall tenker jeg at det er en support ticket til MS og ikke noe issue i PP365

**Comment by Remi749** [comment]
> Får du gjenskapt det i std SP søk? I så fall tenker jeg at det er en support ticket til MS og ikke noe issue i PP365

Gjenskapes i std SP søk ja. Da lukker jeg denne.
