### ISSUE TITLE
Forside blir ikke vist når prosjektoppsett er ferdig

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1344]
Dersom man velger Standard team (mal fra Microsoft), kan hende andre maler også, så blir ikke prosjekt forsiden vist etter prosjektoppsett er ferdig og holder seg på CollabHome.aspx. Dersom man trykker på "Hjem" fra venstremenyen kommer man til forsiden.

**Comment by olemp** [comment]
Løst i #1351
