### ISSUE TITLE
Programtidslinje har feil webdel og mangler tidslinjeliste (se Prosjektnivå tidslinje)

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1345]
Programtidslinje har feil webdel og mangler tidslinjeliste (se Prosjektnivå tidslinje). Programtidslinje er nå den samme som Tidslinje under Programinnhold. Programtidslinje skal være lik som Tidslinje på prosjektnivå.

Dette har vært riktig tidligere, se [eldre Programmer](https://puzzlepart.sharepoint.com/sites/ProgramFolkehelsearbeidiOslo2023-2027/SitePages/Tidslinje.aspx). Her er et [nytt program](https://puzzlepart.sharepoint.com/sites/Trondheimprogram/SitePages/Tidslinje.aspx) som har feil oppsett.

**Comment by olemp** [comment]
> eldre Programmer

@Remi749 

Programtidslinje ihttps://puzzlepart.sharepoint.com/sites/Trondheimprogram/ bruker `ProgramTimelineWebPart` fra `ProgramWebParts`, mens programtidslinje fra https://puzzlepart.sharepoint.com/sites/ProgramFolkehelsearbeidiOslo2023-2027 bruker `ProjectTimelineWebPart` fra `ProjectWebParts`. 

Den må vel nesten bruke `ProgramTimelineWebPart` for at det skal bli riktig?

**Comment by olemp** [comment]
Løst i #1352
