### ISSUE TITLE
Valuta blir ikke riktig sortert i Porteføljeoversikt

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1346]
Valuta blir ikke riktig sortert i Porteføljeoversikt

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/1f46d246-a708-4196-a1af-2cf66b819f27)

**Comment by tarjeieo** [comment]
Duplikat av https://github.com/Puzzlepart/prosjektportalen365/issues/1369
