### ISSUE TITLE
Phase check list items are copied twice to new projects

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#135]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[X ] Bug

[ ] Question

#### Summary

Phase check list items are copied twice to new projects
![image](https://user-images.githubusercontent.com/1837390/66831531-2d703680-ef58-11e9-93af-ef5f1c3fce70.png)

#### Version

Please specify what version you are using: [ 1.1.2]

**Comment by olemp** [comment]
Will be included in `1.1.3`. Date TBA. CHANGELOG updated.
