### ISSUE TITLE
Visnings-id legger seg ikke i adressefeltet (Porteføljeoversikt)

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1355]
URL oppdateres ikke ved bytte av visning.

**Comment by tarjeieo** [comment]
Denne er viktig, men vi kan ta den i 1.9.1

**Comment by Remi749** [comment]
Til info: Dette fungerer fint i aggregerte oversikter, kun problem i porteføljeoversikt.
