### ISSUE TITLE
Verifiser at Konfigurasjon av Prosjektportalen ikke vises med mindre du er admin $1.5.8

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1359]
Hele Footer seksjonen mangler dersom du kun er Medlem.
Gjelder for Hub-området.

På prosjekt ser det ut til å være riktig

**Comment by Remi749** [comment]
@pzljanb, dette skal nå være fikset. Kan du bekrefte?
