### ISSUE TITLE
Portfolio Insights WebPart $2.7

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1361]
Feil på Visningsvelgeren.
Det er feil visninger som er tilgjengelig.

**Comment by Remi749** [comment]
@pzljanb , kan du utdype denne? Det er ikke gjort noe med Porteføljeinnsikt webdelen og hos meg vises alle visninger fra Porteføljevisninger korrekt: 
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/b32ce11e-bc97-4b29-ae16-6e9b49fef12d)

**Comment by tarjeieo** [comment]
Denne er som forventet og funksjonaliteten skal heller ikke videreføres
