### ISSUE TITLE
Project Timeline WebPart $2.6

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1362]
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/38ff4b8c-4c92-4f65-b448-3c3ceb6b15d2)

Er dette en overlapp som forventet?

**Comment by Remi749** [comment]
Ja, her starter milepæl elementet før fase elementet og på grunn av zoom nivået så havner den oppå.
