### ISSUE TITLE
Program Aggregation WebPart $3.2

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1364]
Filtrering mangler

**Comment by Remi749** [comment]
@pzljanb , fungerer fint hos meg, hvor opplever du problemet? Husk at hvis det ikke er ulike verdier på filtrerbar felt i en aggregert oversikt så dukker ikke dette opp i filterpanel.

**Comment by Petterandre** [comment]
@Remi749 
https://puzzlepart.sharepoint.com/sites/AgderProgram/SitePages/ProgramLeveranser.aspx

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/10527497/0c12785d-c0c8-40f5-a470-2175da0cd33d)

Gjelder alle som bruker Aggregation. Administration og Overview fungerer

**Comment by Remi749** [comment]
> @Remi749 https://puzzlepart.sharepoint.com/sites/AgderProgram/SitePages/ProgramLeveranser.aspx
> 
> ![image](https://private-user-images.githubusercontent.com/10527497/295914293-0c12785d-c0c8-40f5-a470-2175da0cd33d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTkwNDYsIm5iZiI6MTcwNTY1ODc0NiwicGF0aCI6Ii8xMDUyNzQ5Ny8yOTU5MTQyOTMtMGMxMjc4NWQtYzBjOC00MGY1LWE0NzAtMjE3NWRhMGNkMzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEwMDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YzZmOWZlNTg1NjhlNTIyMjUxMTU1OTlmOTA1ZGNhZmNlZDY0M2E5MWJmMmQ4MTY5YWQ2MjEyOTZhY2IxNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10SB6l5iVUL9xlyVxPrIBmMyTPUluqx9h42kZXqQLDE)
> 
> ![image](https://private-user-images.githubusercontent.com/10527497/295914577-c2acebcc-4688-4a2e-91c3-ce240f832ba6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTkwNDYsIm5iZiI6MTcwNTY1ODc0NiwicGF0aCI6Ii8xMDUyNzQ5Ny8yOTU5MTQ1NzctYzJhY2ViY2MtNDY4OC00YTJlLTkxYzMtY2UyNDBmODMyYmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEwMDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZGY5YjUwOGI3ODUxNGZjZWI5OGQxYmVhMWMzNWJiZTY4N2RkZjFiOGI1ZDlhOWE5NGQ3ZjYzMGIxM2QyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ZOB_qCy4S7nhWjbdxzbpqa8m_YSTDYwyK2KN7qDa3E)
> 
> Gjelder alle som bruker Aggregation. Administration og Overview fungerer

Fikset
