### ISSUE TITLE
[Smoke test] Prosjektportalen 1.9 installasjon og oppgradering

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1367]
# 🧪 Smoke test for 1.9 installasjon og oppgradering

Vi må teste installasjon (ny) og oppgradering av 1.9, samt kanaler

### Tenant 1: ny tenant - test channel
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises
### Tenant 2: ny tenant - prod channel
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises
### Tenant 1: installer prod channel side by side test channel
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises
### Tenant 2: installer test channel side by side prod channel
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises
### Tenant 3: eksisterende 1.8.x oppgrader til 1.9 (prod channel)
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises
### Tenant 4: eksisterende 1.7.2 oppgrader til 1.9 (prod channel)
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [ ] Opprett et prosjekt og verifiser forsida
  - [ ] Fyll ut prosjektegenskaper i prosjektet
  - [ ] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [ ] Verifiser at footeren vises og at forventet kanal vises
### Tenant 5: eksisterende 1.4.x oppgrader til 1.9 (prod channel)
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises
### Tenant 5: installer 1.9 test channel side by side
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises
### Tenant 6: installer 1.9.0 test channel i et miljø der det finnes en 1.8.x installasjon
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises
### Tenant 6: Oppgrader 1.8.x installasjon til 1.9.0 prod
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektegenskaper i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises

**Comment by pzlespen** [comment]
Tenant 1 and Tenant 2 test are done, only problem is, missing file in test channel package, and Managed Meta Data in Prosjektinformasjon not showing, only loading.
