### ISSUE TITLE
Verifiser at 'Sett anbefaling' knapp dukker opp ved markering av listeelement $1.1.1.1

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1371]
'Sett anbefaling'-knapp dukker ikke opp ved markering av listeelement.

**Comment by Petterandre** [comment]
Oppleves her https://puzzlepart.sharepoint.com/sites/pp365_87b1e6b/Lists/Ideregistrering/AllItems.aspx
"Gå til idébehandling" knappen er der

**Comment by Remi749** [comment]
@LenaMHalvorsen , da skal dette være i orden, du kan teste videre idémodulen.
