### ISSUE TITLE
Verifiser at innhold for siden du er inne på vises riktig $1.6.1

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1373]
**Porteføljenivå:**

- Prosjekttidslinje - mangler bilder etc, kan evt legge inn nytt bilde uansett pga nytt filterikon

**Prosjekt:**

- Prosjektstatus - toc-tagger må fikses/fjernes
- Oppgaver -  toc-tagger må fikses/fjernes
- Fasesjekkliste -  toc-tagger må fikses/fjernes
- Prosjekttidslinje - Se overflødig tekst "Tekst og bilder" etter "For å zoome inn/ut i tidslinje bruk ALT+musehjul"

**Comment by Remi749** [comment]
Flyttet inn i #1372
