### ISSUE TITLE
Taksonomivalg laster ikke i prosjektegenskaper dersom man kun har engelsk term store språk

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1374]
### Beskriv feilen

Dersom man installerer PP i en tenant som kun har engelsk som term store språk, så fungerer ikke prosjektegenskaper som forventet. Valgene fra taksonomifelter laster ikke, de blir bare hengende.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et prosjekt
 2. Klikk på rediger prosjektinformasjon
 3. Trykk på tjenesteområde
 4. Se at den snurrer evig

### Forventet oppførsel

Alle felter skal la seg redigere

### Skjermbilder

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/f959bdc4-f385-4865-89b9-0498995435b3)
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/8a20fb77-674d-4f08-bf6d-c305fad01c67)

### Ytterligere informasjon

Vi henter kun ut norske termer i koden:
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/951f33a9-1b8b-4df6-9d4b-3be58c05752a)
https://vscode.dev/github/Puzzlepart/prosjektportalen365/blob/releases/1.9/SharePointFramework/shared-library/src/data/SPDataAdapterBase/index.ts#L275

Testing viser at ved å legge til norsk term store språk og sette norsk som default så fungerer det igjen.

### Versjon

1.9.0 (preview)

**Comment by Remi749** [comment]
Fikset i: f0bb5358d0f8f82ce31583aa792093abb4b52f46
