### ISSUE TITLE
Verifiser at som medlem så vises footeren $1.5.9

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1375]
Footeren vises ikke når du går inn på et prosjekt.
Er testet både med Benjamin Dover og Lotta

**Comment by Remi749** [comment]
Kjører igang en UpgradeAllSitesToLatest for å se om dette fikser problemet. Hvis ikke må vi legge til en action der som legger på footer inne på eksisterende prosjekter.

**Comment by Remi749** [comment]
Footer legges ikke på eksisterende prosjekter, her må det inn med en jobb i UpgradeAllSitesToLatest

**Comment by Remi749** [comment]
Bør fikses av denne: https://github.com/Puzzlepart/prosjektportalen365/commit/9f4c1b17913942839ae2f5fb52409313cf6053f4

**Comment by Remi749** [comment]
Da skal dette være i orden etter kjøring av UpgradeAllSitesToLatest for å få med footer på eksisterende prosjekter.
