### ISSUE TITLE
Gå gjennom innstillinger for webdelen og verifiser at endringer fungerer som det skal $3.1.1

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1376]
Første "Tittel" feltet ser ut til å være dobbel opp.
Linje nr 2 fungerer:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/a5656466-4501-480f-a7ef-c272c50ae851)

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/1c0e771f2b907b2dc175fe1a7f25607c97f02d88
