### ISSUE TITLE
Verifiser at du får fjernet ett eller flere underområder $3.1.5

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1377]
Ved fjerning av ett prosjekt dukker det opp 3 nye.
Se bilde før og etter...

PS. Det er de samme 3 som dukker opp falsk ved gjentatte forsøk....

FØR
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/f1768bf0-1a7e-4df4-9b17-32a939d866d2)

ETTER
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/4a0c8273-a5bf-4643-9ce2-89b0fbf8af6d)

**Comment by LenaMHalvorsen** [comment]
@Remi749 Opplever ikke dette på nyopprettede programområder. Mulig det er Agder Programområde det er noe rart med..

**Comment by Remi749** [comment]
Mistenker dette er en rar bug som kun gjelder Agder Programområde. Fjernet alle og da er det ikke mulig å gjenskape problemet lengre. Anser saken som løst da problemet ikke lengre kan gjenskapes. Trolig noe som har hengt igjen fra eldre versjon hvor det har skjedd noe rart med sync.
