### ISSUE TITLE
Program Status WebPart $3.5

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1380]
Økonomitall vises ikke

**Comment by Petterandre** [comment]
Gjelder også fresh install

**Comment by LenaMHalvorsen** [comment]
Statusrapporter viser fortsatt "Ikke publisert" etter publisering.

![statusrappviserfeil](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/94ab3c28-fbba-4f62-965b-ea876dd36ecb)

**Comment by Remi749** [comment]
Da er publisert status fikset, samt økonomi seksjonen:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/4a39407e-8527-4689-865c-b3ee899a1741)
