### ISSUE TITLE
Verifiser at 'Opprett prosjektdata' knapp dukker opp ved markering av listeelement $1.1.1.2

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1381]
Knapp mangler i https://puzzlepart.sharepoint.com/sites/pp365_87b1e6b/Lists/Idebehandling/AllItems.aspx
Ingen feil i konsoll

**Comment by Remi749** [comment]
Dette skyldes at brukeren ikke lå i sikkerhetsgruppen for Idébehandlere. Bruker er lagt til og knapp dukker opp. @Petterandre , test gjerne igjen.
