### ISSUE TITLE
EditViewColumnsPanel (vis/skjul kolonner) $3.2.2

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1386]
Legg til/Endre knapp er deaktivert i program aggregation

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/10527497/44283735-1c67-4dca-94ff-50b15909c70f)

**Comment by Remi749** [comment]
Fikset som en del av en større commit: aed5602adc8bb27d6978682334d7b2c6a909823a
