### ISSUE TITLE
ColumnFormPanel $3.2.3

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1387]
Knapp mangler for legg til, og endring er deaktivert

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/10527497/34e4b1be-8b26-4e33-8f28-e807543c2458)

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/10527497/b90b9079-58bf-4ae5-9119-c14b7166e37f)

**Comment by Remi749** [comment]
Lukker denne, se her for status: #1431
