### ISSUE TITLE
Resource allocation improvements

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#139]
**Is your feature request related to a problem? Please describe.**
We get requests about three scenarios, which we currently don't support
- ~Ability to add resource entries without a person, only as role~ #214
- Ability to specify allocation status: Requested, Allocated, Rejected
- Ability to open more details in a Callout component

**Describe the solution you'd like**

* ~Make the user/allocated resource voluntarely in project resource allocation content type. If not set, the "Role" is also used as the name in the resource allocation overview.~ #214
* Add a field 'Allocation status' to the project resource allocation content type with fields Requested, Allocated, Rejected, Other (describe in comment). This field should be displayed in the resource allocation modal dialog and be filterable in the overview page
* Open a Callout component with details on click
* Add some padding/margin to the bottom of the page

**Additional context**

**Comment by olemp** [comment]
What data/fields do you want to show in the callout, @tarjeieo?

![image](https://user-images.githubusercontent.com/7606007/73279634-b8b2c680-41ed-11ea-97ca-5525ace0fd60.png)

**Comment by tarjeieo** [comment]
Resource name
Role
Allocation %
Start date
End date
Comment
Allocation status

**Comment by olemp** [comment]
Added connected issue #214 to lower the scope of this issue.

**Comment by olemp** [comment]
Fixed in #213. 

_Ability to add resource entries without a person, only as role_ moved to #214
