### ISSUE TITLE
ViewFormPanel $5.9.4

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1392]
Når visning forsøkes lagret er det feilmelding

`Error: Error: Error: Error making HttpClient request in queryable [400]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"nb-NO","value":"An unexpected 'StartArray' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expected."}}}
`

**Comment by Remi749** [comment]
Ettersom vi ikke har funksjonalitet for å opprette visninger fra prosjektnivå, gjør vi det foreløpig likt som med program at vi disabler funksjonaliteten. Flytter issuet til 1.9.1 da funksjonalitet blir disablet her: faf5bbe0204de58da5ab78a9aa92cdcccd967adc

**Comment by Remi749** [comment]
Fikset som en del av en større commit: aed5602adc8bb27d6978682334d7b2c6a909823a
