### ISSUE TITLE
Verifiser at du kommer til KUR siden $1.1.1.3

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1393]
Spesialkarakterer må fjernes fra KUR linken som blir opprettet.
Lagde idé med : kolon i seg, og da feiler linken.
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/10527497/4691dd47-0e15-49e0-b506-f6dd6809aa23)

Den faktiske filen får navnet KUR-Fantastisk-idé--Tester.aspx

**Comment by Remi749** [comment]
Fikset i [e19f0b1](https://github.com/Puzzlepart/prosjektportalen365/commit/e19f0b16182efbeabec63de19c7711cf6f9785a7)
