### ISSUE TITLE
Når prosjektdata er opprettet, fyll ut metadata og angi en områdeadresse til et reelt prosjekt $1.2.2

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1394]
Områdeadresse er ikke lagt til i newform eller editform. Må legges til via Grid view

**Comment by Remi749** [comment]
@Petterandre , dette er riktig oppførsel, det er typisk ekstern løsning eller dialog som dekker dette behovet. Når vi tester manuelt er det riktig å gjøre det via grid view. Lukker issuet.
