### ISSUE TITLE
Verifiser at eksport til excel fungerer $2.3.1.4

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1395]
Eksport fungerer fint, testet med omtrent alle felter og prosjekter. Det eneste som ser litt rart ut er at økonomi-feltene (valuta) kommer med 12 desimaler.

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/2d65069d346709ae5f06977bae405adf3f987f67. Dette løser også problemer med nummer felter.
