### ISSUE TITLE
Verifiser at alle felter fungerer som det skal $2.2.4.2.1

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1397]
Se kommentar for å gjenskape problem

~~(Dette issuet gjelder ikke egentlig feltene, men handler om endring av visning) 
Testet å endre på spørring for visningen Gevinstelementer på porteføljenivå ved å f.eks. fjerne "OR" og siste innholdstype., som gir null resultater. Når jeg deretter endrer visning til Alle gevinstelementer sliter den med å hente resultater for datakilden her selvom det var den andre visningen jeg endret på, og jeg får opp feilmeldingen~~

![gevinstoversiktfeilmldettervisningsendring](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/5679c50f-bfd3-4b24-aa2c-a4501c939ec4)

**Comment by Remi749** [comment]
Klarer ikke lengre å gjenskape. Trolig fikset i tidligere commit.

**Comment by Remi749** [comment]
Klarer å gjenskape feilen ved å gjøre følgende:

1. Gå til gevinstoversikt
2. Angi annen viewId manuelt i url feltet
3. Naviger så til en annen visning
4. Problemer skjer hver gang.
