### ISSUE TITLE
Verifiser at du kan skjule/vise ulike kolonner $2.3.2.3

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1398]
For de fleste kolonner ser det ok ut, men Fase (og GtProjectPhaseTextOWSXTEXT) er litt buggy. Når man vil skjule den igjen etter å ha lagt den til i visning, trykket Bruk og panelet lukkes, henger fortsatt verdiene for kolonnen igjen i oversikten. Om man åpner panelet igjen og velger å vise en annen kolonne legges denne etter verdiene som fortsatt henger igjen fra Fase, så det blir forskjøvet. Dette løser seg med refresh, men kan kanskje plage evt brukere.

![porteføljeoversiktetterfeltendring](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/d47004ca-5d69-43a1-b353-6407b3420f72)

**Comment by LenaMHalvorsen** [comment]
Testet igjen nå, og funnet et par ting til som forekommer litt her og der når man velger "Vis/skjul kolonner" gjennom en annen kolonne:

- Får ikke skjule siste kolonne i oversikten som er huket av i edit view form panel (Assisterende prosjektleder og Målsetting på skjermbilde)
- Om Fase ikke er huket av, og jeg klikker på pil opp/ned den/de siste aktive/avhuket kolonne i oversikten, dupliseres Fase-kolonnen.
- Pil opp/ned på siste avhuket kolonne i oversikten flytter på kolonner lenger opp

**Comment by Remi749** [comment]
Dette skal være fikset i: d7e07ca48bf9baff2a9c92cddac5480ee21f0b5b
