### ISSUE TITLE
Upgrading v0.8.1 to latest fails with "List already exists"

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#140]
**Describe the bug**
Upgrading throws the above error on list "Konfigurasjonsfiler".

**To Reproduce**
Upgrade an old version, e.g. 0.8.1

**Expected behavior**
Upgrade success

**Screenshots**

**About your setup**
 - Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.1.4

**Suggested solution**

Looks like file file /Konfigurasjonsfiler/Planneroppgaver.txt has been provisioned WITHOUT the library /Konfigurasjonsfiler/ having been created first. Suggest to add upgrade step to handle these scenarios - I'm guessing it will happen for several pre v1 versions.

Removed this file manually by 
```
Remove-PnPFile -ServerRelativeUrl /sites/Prosjektportalen/Konfigurasjonsfiler/Planneroppgaver.txt
$f=Get-PnPFolder -Url https://skolenett.sharepoint.com/sites/Prosjektportalen/Konfigurasjonsfiler
$f.DeleteObject()
Invoke-PnPQuery
```

**Comment by olemp** [comment]
It was doc’d at https://github.com/Puzzlepart/prosjektportalen365/wiki/Feils%C3%B8king-etter-installasjon, but now removed.

**Comment by tarjeieo** [comment]
Ah, you're right, it is here: https://github.com/Puzzlepart/prosjektportalen365/wiki/Feils%C3%B8king-installasjon (you looked at the wrong page). Thanks!

**Comment by olemp** [comment]
We could’ve added it to the installation, but I thought there wouldn’t be too many previous installations at that time.

**Comment by tarjeieo** [comment]
> We could’ve added it to the installation, but I thought there wouldn’t be too many previous installations at that time.

I agree!
