### ISSUE TITLE
Verifiser at webdelen lastes og elementer vises riktig på tidslinjen $5.1.1

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1400]
Nytt elemet plukker oppdata fra forrige element 
Og rediger element fungerer heller ikke

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/30dd19f5295e680ef4555a0f9aa941de27cce03c
