### ISSUE TITLE
Tidslinjekonfigurasjon $6.3

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1403]
Visning av leveranse
Binde program og overordnet område tidslinje mot Program knapp (Ikke overordnet)

**Comment by Remi749** [comment]
Fikset for nye program som blir opprettet. Manuel fiks på eksisterende er å endre navnet på "Listenavn" til Programleveranser

**Comment by Remi749** [comment]
Da fungerer "Vis på program" igjen for programleveranser.
