### ISSUE TITLE
Verifiser at filterpanel fungerer som det skal $3.2.1.6

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1406]
Program: Filtre vises ikke på Usikkerheter, Kommunikasjonsplaner

Obs, delvis duplikat av https://github.com/Puzzlepart/prosjektportalen365/issues/1364.

**Comment by LenaMHalvorsen** [comment]
@Remi749 Får fortsatt ikke dette til å fungere her https://puzzlepart.sharepoint.com/sites/program-newupgrade2301/SitePages/ProgramUsikkerheter.aspx#viewId=12

**Comment by Remi749** [comment]
> @Remi749 Får fortsatt ikke dette til å fungere her https://puzzlepart.sharepoint.com/sites/program-newupgrade2301/SitePages/ProgramUsikkerheter.aspx#viewId=12

Det er ikke angitt noe å filtrere på i Datakilden for ProgramUsikkerheter.

**Comment by LenaMHalvorsen** [comment]
Ahaaa. 🙈

**Comment by Remi749** [comment]
> Ahaaa. 🙈

Fort gjort 😄, jeg lager et issue på dette for å unngå at det er tomt uten informasjon: #1444
