### ISSUE TITLE
Site script "Opprett innholdstypen Ressursallokering" fails on sitedesign setup

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#141]
**Describe the bug**
The action fails on setup.

**To Reproduce**
1. Create new project site
2. Note that in the set of site script steps, the above mentioned step fails

Haven't looked into details of the consequence. Looks like the list and CT works in the list.

**About your setup**
 - Browser [e.g. chrome, safari]: Chrome
 - Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]: 1.1.4

**Comment by olemp** [comment]
Custom template @tarjeieo?

**Comment by olemp** [comment]
If it's a custom template, it will need `Parameters` like in https://github.com/Puzzlepart/prosjektportalen365/blob/master/Templates/Portfolio/Prosjektmaler/Standardmal.txt.

This change was done to make it possible to create light templates that do not copy site fields from the hub site.

**Comment by tarjeieo** [comment]
No, default template with 1.1.4.... And this step is the site script step as part of site designs, not the PP template

**Comment by olemp** [comment]
Ahhh, SP yields the error then, not sure what we can do about it. I think the site design need to be reapplied. Should we add to troubleshoot guide?

**Comment by tarjeieo** [comment]
Worked perfectly in a new site with 1.1.5. Will consider reopen if we see this again.

**Comment by olemp** [comment]
Nothing has changed. This was just a SP hickup.
