### ISSUE TITLE
Verifiser at knappen blir skjult etter oppgradering $4.3.2

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1412]
Knappen "Gjør til overordnet prosjekt" forsvinner ikke etter oppgradering, og man får oppgradert minst 2 ganger.

Se https://puzzlepart.sharepoint.com/sites/Prosjektdatatilalle/SitePages/ProjectHome.aspx og https://puzzlepart.sharepoint.com/sites/Smoketest100124/SitePages/ProjectHome.aspx (her forsvant halve venstremenyen etter at siste forsøk på oppgradering kræsja)

![underordnetsmoketestfeil](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/6ae7bca2-8c8d-43a1-ac58-0aefb5b22776)
![underordnetsmoketestfeil2](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/b8bd5f11-6fda-4ac4-a2e0-e039b4793cee)

**Comment by Remi749** [comment]
Samme gjelder fresh: #1389

**Comment by Remi749** [comment]
Fikset i [e2621ee](https://github.com/Puzzlepart/prosjektportalen365/commit/e2621eebbe2af6187fa791bb1d17e3ff485776b3), i tillegg så hadde også "Administrer underområder" knapp forsvunnet helt.
