### ISSUE TITLE
Verifiser at dette fungerer som det skal... $4.4.1

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1414]
Risk action-funksjoner fungerer som de skal, men observert et par ting som kanskje bør endres på:

- RiskActionData som legges inn i risikoen som eier tiltaket bør muligens skjules..

![RiskActionDataverdi](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/274e3b27-6539-4133-8bf3-3742c10631f9)

**Comment by tarjeieo** [comment]
Ser ut til at dette ikke lenger er et issue....
