### ISSUE TITLE
Idékonfigurasjon $6.4

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1415]
Feil på listereferanse medfører ikke feil. Ting bare henger. Burde det være en melding på dette?

**Comment by Remi749** [comment]
@pzljanb , hvor henger det? Er det når du åpner noe dialoger?

**Comment by Remi749** [comment]
Fiks: Skjule "Gå til idébehandling" dersom konfigurasjonen ikke matcher navnet på listen
