### ISSUE TITLE
Project Status WebPart $5.6

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1419]
Samme issues som på program - Økonomitall vises ikke, og publiserte rapporter har fortsatt status "Ikke publisert" 

![statusrappviserfeil](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/b50d9f78-2ff0-4788-a272-46204b71cef2)

**Comment by Remi749** [comment]
Da er publisert status fikset, samt økonomi seksjonen:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/4a39407e-8527-4689-865c-b3ee899a1741)
