### ISSUE TITLE
Dialogbokser åpnes med feil styling første gang

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1421]
### Beskriv feilen

Dialogbokser får ikke riktig styling ved første gangs åpning. Det er kun tynne streker og vanskelig å lese grunnet fonter og gjennomsynlige komponenter

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Hard refresh på side
 2. Klikk på ønsket knapp
 3. Registrer feil styling

### Forventet oppførsel

Riktig styling første gang. 

### Skjermbilder

Eksempler:
Fra: https://puzzlepart.sharepoint.com/sites/pp365_dd92236/Lists/Idebehandling/AllItems.aspx
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/38852cce-c200-4f12-bc76-f30c350fbfc9)

Fra:https://puzzlepart.sharepoint.com/sites/pp365_dd92236/Lists/ideregistrering
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/571ea696-2132-4048-917f-ca110c4b72e3)

### Versjon

1.9.0

**Comment by Remi749** [comment]
Løst i c73ce75082152e77ea34336de87662202f9d5776
