### ISSUE TITLE
Teste oppdatering og synkronisering av tiltak $5.10.2

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1422]
Synkronisering etter opprettelse av tiltak med "Legg til nytt tiltak" på Administrer fungerer fint.

Synkronisering av endringer på tiltak i Planner vises på pop-over i usikkerhetsoversikten.

- Testet også å redigere risiko/mulighetselement i lista og legge inn nye tiltak på den måten. Det fungerer ikke, tiltakene på elementet blir tilbakestilt automatisk, gjenspeiles ikke på elementet i lista, og synkroniseres heller ikke ved bruk av synkroniseringsknappen. Kun tiltak opprettet med "Legg til nytt tiltak" som registreres. Er dette riktig?

**Comment by Remi749** [comment]
> Testet også å redigere risiko/mulighetselement i lista og legge inn nye tiltak på den måten. Det fungerer ikke, tiltakene på elementet blir tilbakestilt automatisk, gjenspeiles ikke på elementet i lista, og synkroniseres heller ikke ved bruk av synkroniseringsknappen. Kun tiltak opprettet med "Legg til nytt tiltak" som registreres. Er dette riktig?

Dette ser ut som det er tiltenkt oppførsel. Flytter denne til 1.9.1 så kan @tarjeieo eller @olemp ta en avgjørelse her om det er riktig oppførsel

**Comment by pzljanb** [comment]
Annen oppfrsel bør ikke aksepteres. Å redigere i Rutenettvisning burde ikke være tillatt.

**Comment by Remi749** [comment]
Bruk av RiskActionData for å ha kontroll? https://github.com/Puzzlepart/prosjektportalen365/issues/1414

**Comment by Remi749** [comment]
Ingen måter å bruke ut-av-boksen for å få Tiltak kolonne til å være "read-only" ved rutenettvisning. Her må bare brukere bli informert om korrekt bruk og oppdatering. Lukker saken.
