### ISSUE TITLE
Teste opprettelse av tiltak til planner $5.10.1

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1423]
"Legg til nytt tiltak" fungerer fint. 

- Testet å migrere tiltak til Planner. Tiltakene blir migrert, men dialogen lukkes ikke (testet i flere minutter), og det er mulig å opprette de samme tiltakene tre ganger. Prøvd å refreshe mellom hvert forsøk. Dialogen lukket seg raskt andre og tredje gang.
- Testet å opprette tiltak fra tomt tiltaksfelt med "Legg til nytt tiltak". Får lagre, men panelet lukker seg ikke. Må trykke avbryt. Da blir tiltaket opprettet i Planner, men ikke på usikkerhetselementet, der står det fortsatt tomt. På de neste forsøkene er det litt av og på om lagre-knappen fungerer. 

![ikkelagrenyttiltakfraknapp](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/0f2655e1-b1ff-4378-bbdd-adf44fa56e0a)

**Comment by Remi749** [comment]
Dette er testet OK nå, ser ut som det var en utdatert FieldCustomizer som var grunnen.
