### ISSUE TITLE
Mangler mulighet for å slette visninger

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1425]
Ved redigering av kolonner, har man muligheten til å slette kolonnen direkte fra redigeringspanelet med dialog for bekreftelse. Dette mangler i redigeringspanel for visninger.

**Comment by pzljanb** [comment]
Personlige visninger bør kunne slettes mens "offisielle" visninger bør håndteres fra "backend"

**Comment by Remi749** [comment]
Videreføres til https://github.com/Puzzlepart/prosjektportalen365/issues/1452. Lukker denne...
