### ISSUE TITLE
Standardvisning (Datakilde) fungerer ikke som tiltenkt

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1426]
Gevinstoversikt - Prosjektnivå

**Fungerer:**

1. Kategori for datakilder
2. Nivå for datakilde
3. Inkluder visningnavn i Excel-filnavn
4. Vis eksport til Excel-knapp

**Endringer på disse gir ikke effekt:**

~~1. Endring i Tittel-felt~~
2. Standardvisning (Datakilde)
~~3. Vis kommandolinje~~
~~4. Vis filtre~~
~~5. Vis visningsvelger~~
~~6. Juster kolonner etter skjermbredde~~

**Comment by Remi749** [comment]
Her er det kun "Standardvisning (Datakilde)" som ikke fungerer...

**Comment by olemp** [comment]
@Remi749 @pzljanb Kan man få litt mer detaljer om hva som ikke fungerer her?

**Comment by Remi749** [comment]
> @Remi749 @pzljanb Kan man få litt mer detaljer om hva som ikke fungerer her?

Egenskapen "Standardvisning (Datakilde)" fungerer ikke, prøv å angi en visning. Refresh og se at det blir ignorert.

**Comment by siifux** [comment]
Testet med å opprette ny visning, og satte denne som standardvisning. Byttet så vekk fra den nye visningen, navigerte fra og til listen og så at den ble resatt til standardvisningen👍 Fungerer som ønsket.
