### ISSUE TITLE
Feil på sortering av gevinstoversikt (List $5.9.1)

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1429]
Gevinstoversikt

Sorteringfungerer ved første klikk, men å hake av igjen gir ikke forventet effekt. Også mulig å hake av på flere sorteringsalternativer, litt ymse oppførsel.

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/eb8dfe8230bf83b55df1088fd0ea89dee119fabe
