### ISSUE TITLE
Idékonfigurasjon $6.4

### ISSUE THREAD

**Issue by trondoe** [Puzzlepart/prosjektportalen365#1430]
Når man oppretter nye lister basert på 
- https://puzzlepart.sharepoint.com/sites/pp365/Lists/Idebehandling
- https://puzzlepart.sharepoint.com/sites/pp365/Lists/Ideregistrering

Så feiler konfigurasjon og oppsett av ny idékonfigurasjon dersom man oppretter de nye listene med apostrof og/eller bindestrek i navnet, for eksempel "Idébehandling-v19".

Gitt at man oppretter listen "Idéregistrering-v19" får den urlen https://puzzlepart.sharepoint.com/sites/pp365/Lists/Idregistreringv19
Gitt at man oppretter listen "Idébehandling-v19" får den urlen https://puzzlepart.sharepoint.com/sites/pp365/Lists/Idbehandlingv19
Gitt at man legger inn "Idébehandling-v19 / Idéregistrering-v19" eller ""Idbehandlingv19 / Idregistreringv19" i Idékonfigurasjon, så feiler det (skjer ingenting) når man prøver å klikke på "Gå til idébehandling etter at man har registrert en ny idé og klikker på "Gå til idébehandling" på  https://puzzlepart.sharepoint.com/sites/pp365/Lists/Idregistreringv19/AllItems.aspx

<img width="617" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/8970087/de718e0d-5a0b-48ba-a093-d97a841a0015">

**Comment by Remi749** [comment]
Reffer inn denne også: #1415
