### ISSUE TITLE
Verifiser at du kan skjule/vise ulike kolonner $3.2.2.3

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1432]
Får ikke skjulet/ slått av følgende kolonner:

Er dette tilsiktet?

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/12cb71c0-0a84-4805-aec0-ed4b221199f2)

**Comment by Remi749** [comment]
Dette fungerer nå og er trolig løst i tidligere commit.
