### ISSUE TITLE
ViewFormPanel $2.2.4

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1439]
Litt overlapp med #1397 på Edit, men oppdaget at dette også skjer når ny visning er opprettet og man deretter bytter visning.

Kan heller ikke slette visning, men det er kanskje ikke funksjonalitet for det enda?

![feilmldAlleelementernyvisning](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/35ce9ecf-9013-4971-b99f-9bf93754dbcf)

**Comment by Remi749** [comment]
Ikke mulighet for sletting av visninger enda.

**Comment by Remi749** [comment]
Klarer ikke lengre å gjenskape. Trolig fikset i tidligere commit. Oppretter issue for å legge til mulighet for å slette visninger
