### ISSUE TITLE
Brukermanual Prosjektportalen 2 link is invalid

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#144]
**Describe the bug**
When clicking the "Brukermanual Prosjektportalen 2" under "Nyttige Lenker" it leads to a dead link

**To Reproduce**
1. Go to the created Prosjektportalen site
2. Scroll down to "Nyttige lenker"
3. Click "Brukermanual Prosjektportalen 2"
4. It directs to https://MyTenant.sharepoint.com/:b:/r/sites/ppdemo_v2/Delte%20dokumenter/Prosjektportalen%202%20brukermanual.pdf?csf=1&e=eCKDxP which is a dead link

**Expected behavior**
Clicking the link should direct the user to the referenced document

**About your setup**
 - Installed version: 1.1.4

**Comment by olemp** [comment]
Thanks! We'll look into this @LostLogic. Clear bug 🍔

**Comment by olemp** [comment]
Dead link removed. Will be included in 1.1.5 You can remove this manually. Installation/upgrade-script doesn't update homepage as users might do modification to it, and we don't want to overwrite.
