### ISSUE TITLE
Oversiktsliste over problemer med porteføljeoversikt

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1441]
En oversiktsliste for å samle problemene som oppleves rundt redigering, opprettelse av kolonner og visninger samt endring av rekkefølge og vis/skjul. Merkede bokser indikerer at problemet er fikset.

**Portefølje (Portfolio Overview WebPart $2.3)**
- [x] Vis/skjul kolonner
  - Drag and drop fungerer fint for eksisterende kolonner, problem oppstår dersom man legger til ny kolonne uten å refreshe, panelet mangler den nye kolonnen. Etter refresh dukker det opp og det fungerer å endre rekkefølge.
- [x] Opprette visninger
  - Visning opprettes, blir ikke angitt og refresher view, må refreshe manuelt
- [x] Redigere visninger
  - Endringer skjer, men blir ikke vist i viewet, må refreshe manuelt 

**Program (Program Project Overview WebPart $3.3)**
- [x]  Vis/skjul kolonner
  - Drag and drop fungerer fint for eksisterende kolonner, problem oppstår dersom man legger til ny kolonne uten å refreshe, panelet mangler den nye kolonnen. Etter refresh dukker det opp og det fungerer å endre rekkefølge.
- [x]  Opprette visninger
  - Visning opprettes, blir ikke angitt og refresher view, må refreshe manuelt
- [x]  Redigere visninger
  - Endringer skjer, men blir ikke vist i viewet, må refreshe manuelt

**Comment by LenaMHalvorsen** [comment]
Opplever at drag and drop på ViewColumnFormPanel på Program Project Overview WebPart $3.3 fungerer nå.

**Comment by Remi749** [comment]
Flyttes til 1.9.1 da det er bare refresh som kreves for å "fikse" problemet

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/3cf14046e4f266ebd606b75712417b9d69f09501
