### ISSUE TITLE
Implementer klarere konsekvenser av å velge "Vis i Porteføljeoversikt" (Edit $2.3.3.2)

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1442]
Testet å redigere kolonne og endre Synlighet for kolonne til å ikke vises på Porteføljeoversikt, men det gir ingen effekt, kolonnen vises fortsatt i oversikten (fungerer for Prosjektforside og Prosjektstatus). 

Lurer også på om denne funksjonaliteten overlapper med Vis/skjul kolonne, om de skal påvirke hverandre, og om det skal fungere å skjule en kolonne ved å fjerne Porteføljeoversikt på Synlighet for kolonne, skal bruker kunne legge den til igjen ved å bruke Vis/skjul kolonne?

**Comment by olemp** [comment]
@Remi749 @LenaMHalvorsen Her er det snakk om hvilke kolonner som skal vises i Prosjektinformasjon-popupen i Porteføljeoversikt. Er dette forstått? Mulig vi trenger en mer _beskrivende_ beskrivelse for dette feltet @Remi749?

**Comment by pzljanb** [comment]
Denne kolonnen: Vis i Porteføljeoversikt vil med dagens nye funksjonalitet (sidepanel) ha 2 funksjoner
- Sidepanel for prosjekter (både fra forside, porteføljeoversikt) viser kun kolonner som er "enablet"
- Porteføljeoversikt visninger; Kun enablede kolonner kan velges inn i visning

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/5a1c6ea9abdaf308faaf787607612fbd43e90b80
