### ISSUE TITLE
Verifiser at prosjektstatus dukker opp opp i bunnen når dette er angitt $5.2.3

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#1443]
Mangler Prosjektstatus selv ved satt status
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/10527497/c58c0b6d-8477-458f-abfa-bb65e8f7cf04)

https://puzzlepart.sharepoint.com/sites/Pzl22011430/SitePages/ProjectHome.aspx

**Comment by LenaMHalvorsen** [comment]
Opplevde også dette nettopp, dukket opp etter enkel endring av prosjektinformasjon.

**Comment by Remi749** [comment]
Feil fikset, det skyldtes henting av rapporter, den hentet kun den første uansett. Dette er fikset, den henter alle og viser data for den siste publiserte.
