### ISSUE TITLE
Verifiser at endret kolonne vises riktig $5.9.3.2.2

### ISSUE THREAD

**Issue by trondoe** [Puzzlepart/prosjektportalen365#1445]
Når man har lagt til en ny kolonne på Gevinstoversikt, og valgt at denne skal være "Grupperbar", så forsvinner dette valget dersom man endrer visningsnavn.

Steg for å reprodusere:
1) Opprett ny kolonne - sett visningsmodus til "Tekst" og huk av for at den skal være "Grupperbar"
2) Klikk på "Rediger kolonne" og endre Visningsnavn til noe annet
3) Verifiser at "Grupperbar" nå er deaktivert.

**Comment by Remi749** [comment]
@trondoe, jeg klarer ikke gjenskape dette. Grupperbar er ikke deaktivert hos meg. Gjør du noe manuelle refreshes mellom stegene. Sjekk også kolonnen du har opprettet i Prosjektinnholdskolonner listen, verifiser at Grupperbar er borte og eventuelt versjonshistorikken for kolonnen.
