### ISSUE TITLE
Verifiser at ny visning vises riktig $5.9.4.1.2

### ISSUE THREAD

**Issue by trondoe** [Puzzlepart/prosjektportalen365#1446]
Når man oppretter en ny visning på Gevinstoverikt og bytter mellom standardvisning ("Alle gevinstelementer for prosjektet") og ny visning ("TØE Gevinstvisning"), så vises det feilmeldingen nedenfor:

<img width="860" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/8970087/b04dcf46-fa35-489a-b268-95595122e746">

Steg for å reprodusere:
1) Gå til https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Gevinstoversikt.aspx og opprett en ny visining
2) Refresh siden https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Gevinstoversikt.aspx
3) Bytt fra standardvisning til den nye visning som ble opprettet i punkt 1)

Se også relaterte feil:
* https://github.com/Puzzlepart/prosjektportalen365/issues/1397
* https://github.com/Puzzlepart/prosjektportalen365/issues/1439

**Comment by Remi749** [comment]
Skal nå være i orden etter 8bbd3c957ec0b948fb3030ced1a6d1c92440beb4 er kjørt inn på siten
