### ISSUE TITLE
Får ikke skjult feltet du trykka på for  komme til rediger visningskolonner i en visning

### ISSUE THREAD

**Issue by trondoe** [Puzzlepart/prosjektportalen365#1447]
Når jeg prøver å redigere visningskolonner for en visning i [Gevinstoversikt](https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Gevinstoversikt.aspx), så er det én kolonne i én bestemt posisjon som ikke kan deaktiveres. I skjermbildet nedenfor er det kolonnen i posisjon 11 ovenfra - "Målt verdi".

<img width="857" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/8970087/287a19ec-2790-4ce9-b2b8-0210d64d51ff">

Tester i Chrome.

**Comment by Remi749** [comment]
Klarer ikke gjenskape, trolig fikset i: d7e07ca48bf9baff2a9c92cddac5480ee21f0b5b

**Comment by pzljanb** [comment]
Dersom du går inn til Vis/Skjul kolonner fra en kolonne kan ikke den kolonnen som du startet ut ifra fjernes.
Den blir henges ved. Men flytter seg til bunn av listen

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/pull/1534

**Comment by siifux** [comment]
Testet og fungerer, både ved å skjule flere kolonner, samt fjerne kolonnen man gikk utifra når man klikker "Vis/Skjul kolonne".
