### ISSUE TITLE
Verifiser at du får opprettet statusrapport $5.6.1

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1449]
Får feilmelding ved opprettelse av **første** statusrapport. Den forsvinner med manuell refresh.

Skjer både på prosjekt og program.

![nystatusrapportfeilmld](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/7d1c421b-73c9-4ea7-8292-59040d1b192c)

**Comment by Remi749** [comment]
Klarer ikke gjenskape, lukker. Mulig dette har hatt noe med at en oppgradering skjedde mens dette ble testet.

**Comment by Remi749** [comment]
Klarte å gjenskape problemet. Det skjer uansett så lenge du har angitt eller oppdatert datofeltet. Det skjer på alle rapporter når som helst.

**Comment by Remi749** [comment]
Problem fikset, var Økonomi seksjonen som forårsaket problemet: https://github.com/Puzzlepart/prosjektportalen365/commit/f4dfa186736548e23af4b4d4d112be82bf8d6371
