### ISSUE TITLE
Installation improvement suggestion: Passing PSCredential values to Install.ps1

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#145]
**Is your feature request related to a problem? Please describe.**
Several times during the installation of Prosjektportalen, the administrator is prompted for credentials

**Describe the solution you'd like**
Passing a PScredential variable into Install.ps1 would allow for seamless installation of the solution

**Additional context**
Adding a PSCredential variable option would also lend itself to automation without having to depend on stored credentials in the credentials repository.

**Comment by olemp** [comment]
Thanks! We'll try to include this in the upcoming `1.1.5` release @LostLogic.

**Comment by olemp** [comment]
Fix will be included in 1.1.5. CHANGELOG updated.
