### ISSUE TITLE
Edit $5.9.3.2

### ISSUE THREAD

**Issue by LenaMHalvorsen** [Puzzlepart/prosjektportalen365#1450]
Testet å redigere kolonne og lagre uten refresh etter opprettelse, men skjer ingenting når jeg trykker lagre. Fungerer etter manuell refresh.

![gevinstoversiktredigerkolonneutenrefreshfeilmld](https://github.com/Puzzlepart/prosjektportalen365/assets/11275588/7980083b-4d6c-476f-8b6d-8ada09a9adbe)

**Comment by Remi749** [comment]
Da dette unngås ved refresh flytter vi denne til 1.9.1

**Comment by Remi749** [comment]
Lukkes da denne er en del av: #1441
