### ISSUE TITLE
Project Timeline WebPart $2.6

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1456]
Fjerne følgende del og lenke til liste i Header:
, dette opprettes i den [sentrale tidslinjeinnhold listen](https://puzzlepart.sharepoint.com/sites/pp365/Lists/Tidslinjeinnhold/AllItems.aspx?Source=https%3A%2F%2Fpuzzlepart.sharepoint.com%2Fsites%2Fpp365%2FSitePages%2FProsjekttidslinje.aspx).

**Comment by Remi749** [comment]
Løst i 1.9.0
