### ISSUE TITLE
Tilpassede feltinnstillinger hensyntas ikke

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1459]
Det som blir oppgitt i Tilpassede feltinnstillinger hensyntas ikke. For programmer hvor dette skulle vært tilpasset vises bare vanlige visningsnavn og beskrivelser.
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/5741e5f8-a518-44ad-ba10-bcfe6e65fc9f)

**Comment by Remi749** [comment]
Fjernet fra changelog og releasenotes: 39345ba949fcdb89a010da7cd9e972591b7a61f0

**Comment by olemp** [comment]
Er dette nye eller gamle programmer @Remi749?

**Comment by Remi749** [comment]
> Er dette nye eller gamle programmer @Remi749?

Dette gjelder både nye og gamle programmer.

**Comment by olemp** [comment]
> > Er dette nye eller gamle programmer @Remi749?
> 
> Dette gjelder både nye og gamle programmer.

Har du eksempel på ett nytt program så kan jeg gjøre en avsjekk? @Remi749

**Comment by Remi749** [comment]
> Er dette nye eller gamle programmer @Remi749?

Sendt på pm

**Comment by olemp** [comment]
> > > > Er dette nye eller gamle programmer @Remi749?
> > > 
> > > 
> > > Dette gjelder både nye og gamle programmer.
> > 
> > 
> > Har du eksempel på ett nytt program så kan jeg gjøre en avsjekk? @Remi749
> 
> Sendt på pm

  
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/98c4fe8c-9510-4bb1-880e-3506f8747f88)

Manglet feltkonfigurasjon "Program" for program-malen. Tror ikke vi oppdaterer malene i data rows @Remi749? :)

**Comment by olemp** [comment]
Fungerer når det er satt:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/8ff1e5d8-1fff-40d4-a5b5-932f7b352a31)

**Comment by Remi749** [comment]
> > > > > Er dette nye eller gamle programmer @Remi749?
> > > > 
> > > > 
> > > > Dette gjelder både nye og gamle programmer.
> > > 
> > > 
> > > Har du eksempel på ett nytt program så kan jeg gjøre en avsjekk? @Remi749
> > 
> > 
> > Sendt på pm
> 
> ![image](https://private-user-images.githubusercontent.com/7606007/303996179-98c4fe8c-9510-4bb1-880e-3506f8747f88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjY1NTQsIm5iZiI6MTcwNzcyNjI1NCwicGF0aCI6Ii83NjA2MDA3LzMwMzk5NjE3OS05OGM0ZmU4Yy05NTEwLTRiYjEtODgwZS0zNTA2Zjg3NDdmODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMDgyNDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZhYzJmZWY0ODg0N2M2NGMzYzQ4MDFmODAzNWZmMjY0MzA5Y2MyMWViZmIzOTU0YWU4MzQyNjQ4YmY4NTYxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iG1gRTDAbhNb4bQVAz-ybQy2ke0cBoq_FE7B6LeKZDc)
> 
> Manglet feltkonfigurasjon "Program" for program-malen. Tror ikke vi oppdaterer malene i data rows @Remi749? :)

Se der ja! Det burde vi ha gjort ja, men da tar jeg det tilbake i Changelog og nevner det i release notes at det må slås på i Maloppsett

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/commit/8a962337ff43598ad943120c0b3c0a9bf9cd948b @Remi749
