### ISSUE TITLE
Installation improvement suggestion - Retry X times before failing on HTTP errors

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#146]
**Is your feature request related to a problem? Please describe.**
Working on online services demand some redundancy. Sometimes a 503 HTTP error is a transient issue that would have solved itself in 30-60 seconds time.

**Describe the solution you'd like**
Whenever a known transient HTTP error is encountered during an upgrade or installation, report back the error with a "Retrying again in X seconds" and do so for X times. If it keeps failing after Y tries, hard-fail the installation.

**Additional context**
This request comes as a reaction to the installation hard-failing on this step:
[INFO] Installing pp-portfolio-web-parts...[ERROR] Failed to install app packages to [https://myTenant.sharepoint.com/sites/Appkatalog]: The remote server returned an error: (503) Server Unavailable.

The installation succeeded on the next run

**Comment by olemp** [comment]
Thanks for great input @LostLogic. We'll have a look at this.
