### ISSUE TITLE
Målinger vises ikke for gevinster på programnivå - List $3.2.1

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1461]
Feltet "målinger" er tomt. Mangler data, og lenke til å åpne form med liste over de siste målingene slik som det er i prosjekt og på portefølje.

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/cb4d8e80-02e9-451d-a264-e7d85eb5557b)

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/476bb8a541e3a498b5b81d89c7b926786056bf7e
