### ISSUE TITLE
Lenke til programområder mangler ettersom SPWebUrl er null

### ISSUE THREAD

**Issue by trondoe** [Puzzlepart/prosjektportalen365#1468]
### Beskriv feilen

Dersom man går inn på et program og klikker på Programinnhold>Administrasjon, så er det noen av programmets områder som blir grået ut, ref skjermbilde 1 nedenfor. Ser vi nærmere i Network-taben i nettleser, ser vi at noen av prosjektene som er grået ut mangler en verdi i managed propertyen "SPWebURL" (skjermbilde 2). Har forsøkt reindeksering av siten, uten at SPWebURL blir populert med verdi i etterkant.

Ettersom managed propertyen "Path" eller "OriginalPath" er populert med riktig verdi, anbefales det å implementere en fallback til å bruke en av disse verdiene gitt at "SPWebURL" er null (skjermbilde 3). Se SharePointFramework\ProgramWebParts\src\components\ProgramAggregation\itemColumn.tsx.

<img width="613" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/8970087/4a164daf-bd83-40a6-b5db-6aceb1d26207">

<img width="755" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/8970087/acf873cb-6697-4fc6-bfe4-ba4aedf42c72">

<img width="383" alt="image" src="https://github.com/Puzzlepart/prosjektportalen365/assets/8970087/930a65a4-c39d-4a31-8246-641bb2a8036d">

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et program (som har programområder)
 2. Klikk på Programinnhold > Administrasjon
 3. Dersom det er programområder som er grået ut, åpne Network-taben i nettleser, og sjekk postquery (Repsonse) om SPWebUrl er null

### Forventet oppførsel

Forventer at managed property "Path" eller "OriginalPath" brukes som fallback url dersom SPWebURL er null.

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.x (forrige stabile)

**Comment by Remi749** [comment]
Løst i [3afa9d0](https://github.com/Puzzlepart/prosjektportalen365/commit/3afa9d06f975f82f8ef13a725c7a649cf5fb684c)
