### ISSUE TITLE
Included SharePoint Powershell module DLLs is blocked by Windows by default

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#147]
**Describe the bug**
When extracting the installation ZIP file on a Windows 10 1909 system, most of, if not all of the DLL files included in the "SharePointPnPPowerShellOnline" folder are blocked and require either manual one-by-one unblocking or a recursive unblock-file command from Powershell to get working

**To Reproduce**
1. On a system where the files have not already been unblocked, open the ZIP file
2. Mark all the files, select Copy
3. Create a new folder and select Paste
4. Navigate into the "SharePointPnPPowerShellOnline" directory, check the properties of a DLL file and notice the Unblock option in the bottom left corner

**Expected behavior**
If it should be included, they shouldn't be blocked.
This might be tricky to accomplish, since blocking is handled by Windows Smart Screen which isn't infalable.

**About your setup**
 - Installed version 1.1.4

**Additional context**
I recommend the script to check if the SharePointPnPPowerShellOnline is already installed and load it as a default. If not, prompt the user if they want to install it.
`if(Get-Module -ListAvailable -Name SharePointPnPPowerShellOnline)
{
Import-Module SharePointPnPPowerShellOnline
}
else
{
       Install-Module SharePointPnPPowerShellOnline
}`

It might be prudent to also do a version check when using the Get-Module to ensure the system is at a requisite level.

**Comment by olemp** [comment]
We recommend 7zip for extracting the installation package: https://github.com/Puzzlepart/prosjektportalen365/wiki/Feils%C3%B8king-installasjon

**Comment by olemp** [comment]
.. or simply unblock the zip before extracting.
