### ISSUE TITLE
Prosjekttidslinje viser kun feilmelding "Det har oppstått en feil"

### ISSUE THREAD

**Issue by Rnjarh** [Puzzlepart/prosjektportalen365#1470]
### Beskriv feilen

Når vi går inn på Prosjektidlinje får vi opp følgende feilmelding:
_Det har oppstått en feil
Cannot read properties of undefined (reading 'Title')_

Fikk opp følgende feilmeldinger ved oppdatering til version 1.9.0 fra version 1.8.4:

- [WARNING] Failed to apply PnP templates to, retrying...

- [WARNING] Failed to run post-install steps: Exception calling "ExecuteQuery" with "0" argument(s): "Ukjent feil"

### Hvordan reprodusere feilen

Oppgader løsningen.

### Forventet oppførsel

Hadde forventet at Prosjekttidslinjen skulle fungere tilsvarende som ved forrige version.

### Skjermbilder

![2020-02-16 Feilmelding_Prosjekttidslinje_1_9_0](https://github.com/Puzzlepart/prosjektportalen365/assets/128399557/a94340eb-1152-4814-9987-2eeaf3c1dc55)

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.9.0 (siste stabile)

### Relevant logg

```shell
### Upgrading Prosjektportalen 365 v1.9.0.f0bb535 #####
########################################################
[INFO] Loaded module PnP.PowerShell v1.11.0 from bundle
[INFO] Installing with user [USER@COPMANY.no]
[INFO] Creating/updating site scripts...  Completed in 15.62s
[INFO] Creating/updating site design Prosjektområde...  Completed in 1.05s
[INFO] Setting default site design for hub https://COPMPANY.sharepoint.com/sites/NAME to Prosjektområde...  Completed in 1.03s
[INFO] Running pre-install upgrade steps
[INFO] Installing SharePoint Framework app packages to https://COPMPANY.sharepoint.com/sites/appcatalog...  Completed in 95.43s
[INFO] Applying PnP template Taxonomy (B&A) to https://COPMPANY.sharepoint.com/sites/NAME ...  Completed in 0.46s
[INFO] Applying PnP template Portfolio to https://COPMPANY.sharepoint.com/sites/NAME...     [WARNING] Failed to apply PnP templates to, retrying...Completed in 1978.75s
[INFO] Applying PnP content template to https://COPMPANY.sharepoint.com/sites/NAME...  Completed in 38.19s
[INFO] Clearing QuickLaunch...  Completed in 0.62s
[INFO] Importing Search Configuration...  Completed in 5.01s
[INFO] Running post-install steps
[INFO] Post-install action: Disabling content types for lists
[SUCCESS] Post-install action: Disabling content types for lists
[INFO] Post-install action: Ensuring default project templates
[SUCCESS] Post-install action: Ensured default project templates
[INFO] Post-install action: Adding list content to template setup
[WARNING] Failed to run post-install steps: Exception calling "ExecuteQuery" with "0" argument(s): "Ukjent feil"
[INFO] Running post-install upgrade steps
[INFO] In version v1.9.0 we introduced data source levels. Adding default level 'Portfolio' to existing data sources...
[SUCCESS] Data sources updated
[SUCCESS] Successfully ran post-install upgrade steps
[SUCCESS] Upgrade completed in 00:36:14.0884438
[INFO] Logged installation entry
PS C:\Users\USER\Downloads\pp365-1.9.0>
```

**Comment by Remi749** [comment]
Hei @Rnjarh , er UpgradeAllSitesToLatest scriptet kjørt etter oppgradering. Hvis ikke er dette viktig å utføre. Oppleves feilen på nye prosjekter eller kun eksisterende prosjekter (og gjelder det alle eller noen)?

**Comment by Rnjarh** [comment]
Hei,

Har ikke fått testet ut om feilmeldingen inntreffer på nye prosjekter.
Alle eksisterende prosjekt har samme feilmelding.

Har du/dere noen anbefalt fremgangsmetode for å kjøre UpgradeAllSitesToLatest scriptet?

Roger Njærheim
AATT

**Comment by Remi749** [comment]
> Hei, Har ikke fått testet ut om feilmeldingen inntreffer på nye prosjekter. Alle eksisterende prosjekt har samme feilmelding. Har du/dere noen anbefalt fremgangsmetode for å kjøre UpgradeAllSitesToLatest scriptet? Roger Njærheim AATT

Hei @Rnjarh,
UpgradeAllSitesToLatest er et script som følger med i den nedlastede zip filen for versjon 1.9.0. Du kan lese mer om det her: [Oppgrader eksisterende prosjekter med PowerShell](https://github.com/Puzzlepart/prosjektportalen365/wiki#-steg-2-optional-oppgrader-eksisterende-prosjekter-med-powershell)

**Comment by Rnjarh** [comment]
Har kjørt UpgradeAllSitesToLatest er et script. Får opp samme feilmelding.

**Comment by Remi749** [comment]
> Har kjørt UpgradeAllSitesToLatest scriptet. Får opp samme feilmelding.

Hei @Rnjarh,
det kan hende det er noe galt med ett eller flere prosjekttidslinje elementer som ligger i den sentrale prosjekttidslinjeinnholdslisten. Kontakt meg på remi.blom-ohlsen@puzzlepart.com, så kan vi avtale en eventuell skjermdeling.
