### ISSUE TITLE
Knappen for gjør om til overordnet område endrer seg ikke etter at overordna-mal er lagt på

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1474]
### Beskriv feilen

Konvertering til overordna område fungerer, men knappen endrer seg ikke etter at jobben er ferdig.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et prosjekt
 2. Gjør om til overordna
 3. Se at knappen ikke endrer seg når jobben er ferdig

### Forventet oppførsel

Knappen skal endre oppførsel

### Skjermbilder

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/c2f6c411-b8db-48f3-8bea-4ff386cc1c95)

### Versjon

1.9.0 (siste stabile)

**Comment by Remi749** [comment]
Duplikat: https://github.com/Puzzlepart/prosjektportalen365/issues/1412
