### ISSUE TITLE
Dersom man renamer M365 gruppen til et prosjekt så vises ikke tidslinjeelementer lenger

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1477]
### Beskriv feilen

Dersom man renamer M365 gruppen til et prosjekt så vises ikke tidslinjeelementer lenger. De ligger fortsatt i lista sentralt åpenbart.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et prosjekt, legg inn elementer i tidslinjemodulen
 2. Gi prosjektet nytt navn
 3. Observer at ingenting vises i tidslinjemodulen
 4. Rediger prosjektegenskaper slik at nytt navn synces til hub
 5. Observer at elementene er tilbake i tidslinjemodulen

### Forventet oppførsel

Tidlsinjemodulen må virke selv om man renamer et prosjekt

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.9.0 (siste stabile)

**Comment by olemp** [comment]
Bør vel være mulig å filtrere på lookup ID, istedenfor Title @Remi749 @tarjeieo?

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/018567e6b6f679136fc5babe470d41f0105f3318
