### ISSUE TITLE
Fravær in Ressursallokering has an option that's not translated from the variable during install

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#148]
**Describe the bug**
The drop-down list for Fravær when creating a new element in Ressursallokering has an option called {resource:Choice_GtResourceAbsence_Linetasks}. This seems like a bug

**To Reproduce**
1. Click Ressursallokering at the top of a newly created Prosjektportal
2. Click "sentrale ressursallokeringslisten"
3. Click "Ny"
4. Click the arrow to the right on the dropdown list by Fravær

**Expected behavior**
{resource:Choice_GtResourceAbsence_Linetasks} should be a more legible option

**Screenshots**
![image](https://user-images.githubusercontent.com/7568950/68675348-f80b3880-0557-11ea-880d-ce4f7e135e74.png)

**About your setup**
 - Browser: Edge Chromium Canary
 - Installed version: 1.1.4

**Comment by olemp** [comment]
Thanks! Looks a typo in the resource file @LostLogic 🚑

**Comment by olemp** [comment]
Resource for `Choice_GtResourceAbsence_Linetasks` was missing. Supposed to be _Linjeoppgaver_. Fix will be included in 1.1.5. CHANGELOG updated.

**Comment by olemp** [comment]
@LostLogic While waiting for `1.0.5` you can manually update the `GtResourceAbsence` field on the portfolio level, and new project sites should have the updated field.

**Comment by LostLogic** [comment]
> @LostLogic While waiting for `1.0.5` you can manually update the `GtResourceAbsence` field on the portfolio level, and new project sites should have the updated field.

Could you write up a little more detailed instruction? I'm not that versed in where to find field values and updating them

**Comment by LostLogic** [comment]
Figured out where to go. Was... A lot easier than I'd suspected. Thanks! :)

**Comment by olemp** [comment]
../_layouts/15/fldedit.aspx?field=GtResourceAbsence
