### ISSUE TITLE
Install fails with error "Finner ikke feltet med navnet GtProductAcceptanceDate"

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#150]
**Describe the bug**
When applying portfolio template, the following error occurs:
powershell.exe Error: 0 : 2019-11-19 16:46:23.9968	[Fields]	[10]	[Error]	Updating field {ce9474dd-407b-4480-951a-5381857fad6a} failed: Finner ikke feltet med navnet GtProductAcceptanceDate. :    ved Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)

**To Reproduce**
Install the thing

v1.1.6

**Comment by olemp** [comment]
We don't support installing on a PP2 site.

**Comment by tarjeieo** [comment]
PEBCAK
