### ISSUE TITLE
Synkronisering av egendefinerte taksonomi-felter fra prosjekt

### ISSUE THREAD

**Issue by gjerm** [Puzzlepart/prosjektportalen365#1505]
### Beskriv feilen

Tidligere har det vært mulig å lage et egendefinert taksonomi-felt som ble synkronisert til porteføljeområde ved lagring av prosjektinformasjon, uten å måtte lage et tilsvarende felt som slutter med Text. Virker som at dette ikke lengre fungerer etter oppgradering til 1.9.0? I 1.8.4:
https://github.com/Puzzlepart/prosjektportalen365/blob/b81831658ef0bd850bdece26553aaec8efd6badd/SharePointFramework/ProjectWebParts/src/data/SPDataAdapter/index.ts#L162-L175

Så vidt jeg ser vil ikke `syncToProject` være satt, så den prøver å hente matchende Text-felt men faller tilbake på skjult TextField. I 1.9.0:
https://github.com/Puzzlepart/prosjektportalen365/blob/5fb9b32b80cc80cab2caf92fa7d78390d8b446e8/SharePointFramework/shared-library/src/data/SPDataAdapterBase/index.ts#L387-L401

Her ser det ut til at sync fra prosjekt ikke setter `useSharePointTaxonomyHiddenFields`, og dermed vil den eneste måten å få sync fungerende skje hvis et matchende Text-felt finnes (på samme måte som GtProjectPhase/GtProjectPhaseText).

### Hvordan reprodusere feilen

Trinn for å gjenskape:

1. I Prosjekt-innholdstypen, lag et egendefinert taksonomi-felt ref [Guide for tilpasninger](https://github.com/Puzzlepart/prosjektportalen365/wiki/Tilpasninger-i-Prosjektportalen-365).
2. Lag et prosjekt
3. Rediger prosjektinformasjon, legg en verdi i feltet, og lagre.

### Forventet oppførsel

Forventet at taksonomi-feltet skulle oppdateres tilbake i Prosjekter-listen på porteføljeområdet

### Ytterligere informasjon

Hvis jeg lager et matchende felt med `Text` på slutten, og setter `ShowInEditForm=FALSE` likt `GtProjectPhaseText`, ser det ut til å fungere som forventet.

### Versjon

1.9.0 (siste stabile)

**Comment by Remi749** [comment]
Hei @gjerm,
kravet for å ha opprettet eget felt med `Text` på slutten mot et matchende taksonomi felt er noe som har vært i Prosjektportalen 365 fra starten av. Dette er for å unngå å måtte mappe opp Taksonomi-felter til en `Refinable...`.

Ved fasebytte og synkronisering av prosjektinformasjon vil disse feltene populeres på porteføljenivå.
