### ISSUE TITLE
[Smoke test] Prosjektportalen 1.9.1 installasjon og oppgradering

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1514]
# 🧪 Smoke test for 1.9.1 installasjon og oppgradering

Her må også følgende endring(er) som er gjort på scriptene verifiseres

- [x] Forbedret skript for å oppgradere eksisterende prosjektområder #1475, #1487

### Tenant 1: Ny tenant - test channel
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektinformasjon i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises

### Tenant 2: Ny tenant - prod channel
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektinformasjon i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises

### Tenant 3: Eksisterende 1.8.x oppgrader til 1.9.1 (prod channel)
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektinformasjon i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises

### Tenant 3: Eksisterende 1.9.0 (test channel) oppgrader til 1.9.1 (test channel)
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektinformasjon i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises

### Tenant 4: Eksisterende 1.9.0 oppgrader til 1.9.1 (prod channel)
  - [x] Skriptene går gjennom uten feil
  - [x] Verifiser at forsida snurrer
  - [x] Opprett et prosjekt og verifiser forsida
  - [x] Fyll ut prosjektinformasjon i prosjektet
  - [x] Verifiser at termlageret er likt etter gjennomførte scenarioer
  - [x] Verifiser at footeren vises og at forventet kanal vises

**Comment by pzlespen** [comment]
All things good except Test Channel Site Design showing twice on upgrade from 1.9.0
