### ISSUE TITLE
Feil med summeringsfelt i prosjektstatusseksjoner

### ISSUE THREAD

**Issue by stigre** [Puzzlepart/prosjektportalen365#1515]
Hvis feltet som er konfigurert som summeringsfelt ikke finnes i listen på et prosjekt vises fortsatt beskrivelsen uten verdi:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/40488522/40ac69c3-6af8-46e6-b2f3-0c5a415883c0)

I tilfellet hvor feltet ikke eksisterer burde heller ikke beskrivelsen være synlig.

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/517615511be713bd6c8648e9ee710190bc38d70a
