### ISSUE TITLE
"Gå til idébehandling"-knapp fungerer ikke

### ISSUE THREAD

**Issue by stigre** [Puzzlepart/prosjektportalen365#1516]
Knappen "Gå til idébehandling" på listen for idéregistrering fungerer ikke:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/40488522/ba03b67b-a21c-4e5a-9003-e9127267def9)

Også testet i fersk installasjon med standard konfigurasjon

**Comment by tarjeieo** [comment]
Good cactch! Og kanskje vi skulle droppe alerts med feilmeldinger i 2024? 😁

**Comment by stigre** [comment]
> Good catch! Og kanskje vi skulle droppe alerts med feilmeldinger i 2024? 😁

Absolutt!

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/39c3d9c104dec7200dd3cd4e8c7bf2e51efa7785

Vi får ha det på planen når vi jobber med 1.10 at vi går gjennom dette med alerts 👍
