### ISSUE TITLE
Ikke mulig å oppdatere tittel på et prosjekt

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1518]
### Beskriv feilen

Som en konsekvens av sidepanelet for å redigere prosjektinformasjon er Tittel-feltet blitt skjult. Tittel-feltet i Prosjektegenskaper-listen brukes som prosjektnavn på forsiden av huben, i porteføljeoversikter osv.

Nå er det i praksis ikke mulig å endre prosjektnavn som skal vises overalt

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et prosjekt
 2. Rediger prosjektinformasjon - ikke mulig å endre Tittel
 3. Rediger områdeinformasjon. Her kan du endre tittel, men det blir ikke videreført til hub-nivå

### Forventet oppførsel

Det må være mulig og enkelt å endre prosjektets navn/tittel.

Jeg foreslår at prosjektinformasjon-sync til hub tar med seg navn på området/M365-gruppen og lagrer det som tittel i prosjektet på hub. Da vil vi LIKEVEL ha en mismatch mellom redigering av prosjektinformasjon og områdeinformasjon mtp tittel, men vi må kanskje leve med det? Forslag?

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.9.0 (siste stabile)

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/523017bfe315c197d1e486cbff378d650a71cade
