### ISSUE TITLE
Feil i excel-eksport på aggregerte oversikter

### ISSUE THREAD

**Issue by stigre** [Puzzlepart/prosjektportalen365#1519]
Excel-eksport av ressursallokering har diverse feil/mangler:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/40488522/1b511bc3-ce58-452e-9557-e7e31299a8a4)

Tittel settes til "DispForm.aspx" som ser litt rart ut, feltene Startdato, Sluttdato, Belastning viser ikke verdi selv om de er satt, Opprettet dato mangler og Endret av vises ikke på "menneskevennlig" format.

Eksporten er gjort fra webdelen som viser ressursallokeringer for underområder på program-nivå.

Feilen med datofelter gjelder alle aggregerte oversikter.

**Comment by olemp** [comment]
@tarjeieo @stigre @Remi749 Tittel-feltet er skjult i Ressursallokering-listen, så den bør nok ikke være med i denne visningen. Den viser DispForm.aspx siden Tittel er `null` (ikke satt).

Når det gjelder Startdato, Sluttdato, Belastning må jeg ta en titt på webdelen for å se hva som foregår.

**Comment by olemp** [comment]
Dette skal være løst av https://github.com/Puzzlepart/prosjektportalen365/pull/1533. Nå ble det bedre gitt 🪨

**Comment by siifux** [comment]
Fungerer som det skal på usikkerhetsoversikt

**Comment by pzljanb** [comment]
Det rapporteres fortsatt "DispForm.aspx":
![Image](https://github.com/user-attachments/assets/cbe6f85e-bce3-49ea-bccd-7512d41c84fe)
