### ISSUE TITLE
Adding a / at the end of the URL during inital creation cause installation to fail

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#152]
**Describe the bug**
Installing a new Prosjektportal with the URL ending in a / cause the installation to fail

**To Reproduce**
1. Start a new installation with the URL set to https://mytenant.sharepoint.com/sites/MyCoolProsjekt/
2. Installation will start, but fail when trying to connect to it after Hub site promotion with a 404 error

**Why does it happen**
Since an alias is passed with an illegal character, namely /, Sharepoint will reinterprit the / as a dash, causing the alias of https://mytenant.sharepoint.com/sites/MyCoolProsjekt/ which is "MyCoolProsjekt/" to become "MyCoolProsjekt-"

**How to fix**
Change line 83 to:
$Alias = $Uri.Segments[2].TrimEnd('/')

**Comment by olemp** [comment]
You're welcome to add a pull request ⚡️

**Comment by LostLogic** [comment]
> You're welcome to add a pull request ⚡️

I'd love to, but my Git knowledge (and lack thereof) would likely cause more of a mess than either project participant would be happy with 😅|

**Comment by olemp** [comment]
@LostLogic https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by olemp** [comment]
PR Looks good
