### ISSUE TITLE
Det blir ikke lagret rett lenke til KUR-side i Idébehandlingslisten

### ISSUE THREAD

**Issue by stigre** [Puzzlepart/prosjektportalen365#1520]
Endringen gjort i [e19f0b1](https://github.com/Puzzlepart/prosjektportalen365/commit/e19f0b16182efbeabec63de19c7711cf6f9785a7) fjerner spesialtegn ved opprettelse av siden, men lenken som lagres i listen har fortsatt spesialtegn og fungerer ikke.

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/40488522/469fc6aa-136e-414e-8203-dabb457a9ac0)

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/40488522/62666205-ca4f-44a5-80fc-90825877f9f0)

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/40488522/0831fffc-cd0d-41e3-b59e-3f52a0bf7ca1)

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/6068b37b97f2f60f3f75a89fcfa7eceaad4e9411

**Comment by Remi749** [comment]
Var fortsatt noe problemer, skrev om måten vi angir URL. Løst her: https://github.com/Puzzlepart/prosjektportalen365/commit/975dd5f5dadd938fa2e03026f03fa948d01ff134
