### ISSUE TITLE
Mal for fasesider må oppdateres

### ISSUE THREAD

**Issue by stigre** [Puzzlepart/prosjektportalen365#1521]
Fasesider.txt trenger en oppdatering med vertical sections. Webdelene bruker ikke plassen på siden optimalt:

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/40488522/ab84b132-94da-4d02-93a1-7a71e1fabbc7)

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/538edb98fb4118ee096b6dac4fead6dce72a978a
