### ISSUE TITLE
Rettet et problem hvor sorteringsindikatorene for kolonner i aggregerte oversikter ikke var riktig sjekket av

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1523]
Sortering fungerer ikke som tenkt.
Gjelder flere visninger og typer kolonner.

**Comment by pzljanb** [comment]
hensyntar ikke stor liten bokstav:
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/58074707/0f3a3954-1061-4a19-af06-fe955a5715ae)

**Comment by pzljanb** [comment]
Porteføljevsiningen; med visningen "Økonomi"-> Her er begge sorteringene på Økonomi i stigende rekkefølge. Det er kun bestemt om tallene kommer før eller etter de "blanke"

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/ddf0a54b9e0d5f3ab9f1751dfbd8e3e70871031a
