### ISSUE TITLE
Tiltak lar seg ikke migrere

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1524]
### Beskriv feilen

Når jeg forsøker å migrere tiltak vil ikke pop-up lukke seg.

Om jeg lukker pop-up manuelt og sjekker så har tiltaket blitt opprettet i Planner
Ved neste migreringsforsøk på samme tiltak funker det (om listen har blitt refreshet)
Men vi får da 2 tiltak på samme tiltak

### Versjon

1.8.x (forrige stabile)

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/b1bdca2c90e737cf33bae593928d15db29135317
