### ISSUE TITLE
Økonomi seksjon verdier vises ikke som valuta

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1526]
### Beskriv feilen

Økonomi seksjon viser verdier som heltall istedenfor valuta med `kr` som prefix.

### Forventet oppførsel

Tallene (dersom valuta) skal vises riktig.

### Skjermbilder

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/29ad0afb-9b84-42c3-8b88-996c4fe4d09a)

### Versjon

1.9.0 (siste stabile)

**Comment by olemp** [comment]
Skulle nesten tro det har blitt endret noe i kolonne-lista @Remi749. Vanskelig å finne ut noe mer her uten å vite hvilket prosjekt det gjelder.

**Comment by olemp** [comment]
Lukkes for nå.
