### ISSUE TITLE
Nye planner oppgaver blir ikke sortert riktig ved provisjonering

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1530]
Nye planner oppgaver blir ikke sortert riktig ved provisjonering. Dersom man legger inn et nytt elementer i Planneroppgaver listen, angir en rekkefølge som er i midten av en kategori, vil denne komme inn øverst i kategorien ved provisjonering. Dette skyldes at alle planner oppgaver elementer blir sortert på ID først og deretter sortert på rekkefølge innenfor hver kategori.

**Comment by Remi749** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/5f8d158aa2f4044d752f76f64f024dfdd4fa7494

**Comment by siifux** [comment]
Testet, og opprettet ny oppgave som ble lagt på riktig plass i utlistingen.
