### ISSUE TITLE
Omgjøring til overordnet prosjekt resetter TemplateParameters

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1532]
### Beskriv feilen

Ved konvertering til overordnet blir Prosjektegenskaper-feltet TemplateParameters resatt. Antar det blir resatt til konfigen for overordnet fra Maloppsett.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et prosjekt konfigurert med bygg/anlegg/vei/custom prosjektmal som har egen statusrapport
 2. Rapporter status
 3. Gjør om til overordnet
 4. Rapporter status. Se at det er andre felter etc.

### Forventet oppførsel

Vi må beholde den samme setupen i TemplateParameters.

### Skjermbilder

Denne viser før og etter konvertering
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/1837390/a8a7b112-c537-4db6-98a8-d4d7a215ae8e)

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.9.0 (siste stabile)

**Comment by olemp** [comment]
Se over #1543 @tarjeieo. Støtte for ny egenskap `skipUpdateTemplateParameters` i `ProjectSetup`.

**Comment by siifux** [comment]
Opprettet statusrapport, gjort til overordnet og opprettet ny rapport. Felter blir værende slik som forventet 👍
