### ISSUE TITLE
Bakgrunnsfarge på konfigfelter (fargefelt)

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1537]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Vanskelig å se hva fargen er når ikke fargen vises med annet enn kode

### Beskriv løsningen du ønsker

Tilsvarende som Tidslinjekonfigurasjon er det ønskelig at felter av typen fargekode er vist med den aktuelle fargen som bakgrunn slik at det er lettere å se hva som er konfigurert

### Ytterligere informasjon

Gjelder for eksempel for Prosjektkolonnekonfigurasjon

**Comment by olemp** [comment]
Løst av https://github.com/Puzzlepart/prosjektportalen365/commit/e8eb86303ee3f9ea066b079f28a676f981cfc6da
