### ISSUE TITLE
Feil med URL felt ved opprettelse av Prosjektstatus

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1546]
Dersom det tidligere er angitt verdi i et URL felt (før 1.9.0) og man trykker på `Opprett` knappen i Prosjektstatus vil det feile:
![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/739d58c5-88ce-4523-a4ce-547228558094)

Nye statusrapport blir opprettet, men uten verdier i URL feltet. Så hvis brukeren refresher fungerer alt igjen, men det mangler verdi.

Det er split her som feiler i `createFieldValueMap.ts`: 

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/4b3b4bef-b0ff-40bb-8aa2-66e617a1824c)

Må også teste at dette fungerer dersom man trykker `Rediger`, verifiser at verdier i URL feltet dukker opp korrekt.

**Comment by Remi749** [comment]
Fixed in [77dba1ecbafd0ea04b4c9964ac5ce9d1a51f640a](https://github.com/Puzzlepart/prosjektportalen365/commit/e1e8da1bb687f86651cea2d80d2520e09e407a6b)

**Comment by siifux** [comment]
Finner ikke prosjekt å teste dette på. Sjekket i pp365 og pp365-test
