### ISSUE TITLE
Provisjonering av dokumentbibliotek henter bare 100 elementer

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1547]
Det mangler en getAll() etter select her (se bilde)

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/28678468/ea52cc21-4efd-4120-87f0-c4e98b4ad1be)

**Comment by siifux** [comment]
Etter opprettelse fikk nytt område over 100 dokumenter med. Som forventet 👍
