### ISSUE TITLE
Tillatelseskonfigurasjon feiler dersom man ikke er eier på portefølje/hub

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1549]
### Beskriv feilen

Dersom brukeren som setter opp et område ikke er eier på porteføljeområdet, feiler tillatelseskonfigurasjonen.

Ofte vil jo brukeren som oppretter områder også være eier på hub, men dette er ikke alltid tilfelle. For eksempel der man benytter en provisjoneringsløsning kan jo prosjektområdene få egne eiere, uten at de har noe annet enn medlems-tilgang på huben - faktisk er dette nærmest en anbefalt tilnærming. Dette fungerer da ikke sammen med tillatelseskonfigurasjon.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Sørg for at brukeren som man tester med ikke har mer enn medlem-tilgang på hub
 2. Opprett et område, gi brukeren eiertilgang. Knytt området til huben.
 3. Men brukeren, åpne wizard og kjør oppsett. Har gjerne browser-console oppe.
 4. Se feil logges til console.

### Forventet oppførsel

Tillatelseskonfigurasjon bør settes opp riktig selv om brukeren ikke er eier på hub.

### Skjermbilder

![image](https://github.com/user-attachments/assets/61f53907-f7a3-4dbb-8667-da844f1998ca)

### Ytterligere informasjon

Det er tydelig endepunktet /_api/web/sitegroups som gir 403 Forbidden, og vi må hente gruppene på en annen måte. I andre tilfeller har vi jo hentet ut enkeltgrupper. 

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.x (forrige stabile)

**Comment by siifux** [comment]
Testet opprettelse av nytt område med bruker som ikke er eier av Hub. Satte samme bruker som eier av nytt område. 
Tillatelse fra tillatelseskonfigurasjon blir ikke lagt til, derav feiler denne.  

Prosjekt opprettet og konfigurert av Ben Dover (ikke eier av hub): https://puzzlepart.sharepoint.com/sites/benDoversProsjekt
Eksempelvis, prosjekt opprettet av Lotta Powa (eier av hub): https://puzzlepart.sharepoint.com/sites/SindresByggogAnlegg

Under Tillatelser (avansert) vil man se at Redaktører gruppen har blitt lagt ved i prosjekt opprettet av Lotta Powa, men ikke i prosjekt opprettet av Ben.

**Comment by siifux** [comment]
Testet opprettelse av prosjekt og sett at tillatelsekonfig blir gjennomført. Eksempelvis, blir redaktører nå tatt med - Bestilte opp prosjekt med Ben Dover (uten eierskap til hub) 

![Image](https://github.com/user-attachments/assets/2d11b735-8e05-4fa0-8774-35e9651f5a76)
