### ISSUE TITLE
Eiere av personlige visninger får ikke redigert visningen

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1553]
Eiere av personlige visninger får ikke redigert visningen. Vis/skjul kolonner er låst pga isSiteAdmin sjekk.

Personlige visninger bør kunne slettes, redigeres av personen som opprettet mens "offisielle" visninger bør håndteres fra konfigurasjonslistene. Vis eller skjul kolonner må også være tilgjengelig for personen som opprettet visningen selvom om persmission checken isSiteAdmin blir false.

**Comment by pzljanb** [comment]
Klarer ikke å teste denne.
@Remi749 -> Kan du vise mer hva som her har blitt påvirket, og hvordan vi kan teste?

**Comment by Remi749** [comment]
> Klarer ikke å teste denne. @Remi749 -> Kan du vise mer hva som her har blitt påvirket, og hvordan vi kan teste?

Gjensto en liten ekstra sjekk fiks slik at brukeren får opp opprett/rediger knappene i visningsvelgeren. Du kan godt teste nå.

Det som er gjort er:
- Personlige visningner kan redigeres, samt brukere med tilganger kan også opprette personlige visninger. De skal ikke kunne redigere globale visninger med mindre de har riktige rettigheter

**Comment by pzljanb** [comment]
Som medlem får du ikke satt en personlig visning til Public.
Årsaken er at "Default visning" er by default satt til True, og dette har ikke en medlem lov til å endre på.

Ergo må endring fra Private -> Public medføre at Default visning er satt til False
