### ISSUE TITLE
Porteføljeoversikt - "Programmer" seksjon i nedtrekksmeny for visning vises selvom det ikke er noen programmer

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1559]
Porteføljeoversikt - "Programmer" seksjon i nedtrekksmeny for visning vises selvom det ikke er noen programmer

![image](https://github.com/user-attachments/assets/d9f43c44-0953-4c07-b64e-4875e608073c)

**Comment by Remi749** [comment]
Løst i 0ecde0f4e9530c29a0d92204f2654c7ab62de725

**Comment by siifux** [comment]
Testet OK
