### ISSUE TITLE
Porteføljeoversikt viser ikke prosjekter

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#156]
Ingenting dukker opp; https://pzlcloud.sharepoint.com/sites/pp3test/SitePages/Portef%C3%B8ljeoversikt.aspx#viewId=2

**Comment by olemp** [comment]
Har dette med oppdatering av ‘office-ui-fabric-react’ og ‘react’ å gjøre mon tro? Er det noen feil i konsollet?

**Comment by tarjeieo** [comment]
Merk: Dette er PP365. Ser ingen relevante feil... Prosjekter kommer ikke opp:
![image](https://user-images.githubusercontent.com/1837390/69700008-b054e700-10e9-11ea-9f69-451abfdb23a5.png)

**Comment by olemp** [comment]
Lagt inn fiks som fungerer for oss i vår tenant, men det er mulig vi har first release eller at noe nytt testt hos oss.

**Comment by olemp** [comment]
Noe rart skjer igjen @tarjeieo...

![image](https://user-images.githubusercontent.com/7606007/70511839-f66d6a00-1b2f-11ea-80a5-4e5bb7ffcead.png)

**Comment by tarjeieo** [comment]
Microsoft liker å leke med oss <3

**Comment by JimmyHang** [comment]
Har samme issue hos en kunde, siden er blank

**Comment by JimmyHang** [comment]
![image](https://user-images.githubusercontent.com/18226765/70746912-0d29e180-1d27-11ea-845b-20bd0d395d4b.png)

From my browser session..

**Comment by JimmyHang** [comment]
I just found another tenant where the webpart worked and compared the output:

Form the one that worked, have only two error during page load related to quick actions:
![image](https://user-images.githubusercontent.com/18226765/70802036-b36df980-1db0-11ea-8998-f5a4ed3edabb.png)

From the one that this don't work, seems to relate to "unsafe header":

![image](https://user-images.githubusercontent.com/18226765/70802120-e1533e00-1db0-11ea-8971-b29cf2781f4a.png)

**Comment by olemp** [comment]
These are error messages from SharePoint Online, so I don’t think they are related. Can you attach a screenshot of the whole screen?

**Comment by JimmyHang** [comment]
The one that dont work:

![image](https://user-images.githubusercontent.com/18226765/70803918-6f312800-1db5-11ea-8935-b3148118cd1c.png)

**Comment by JimmyHang** [comment]
Sorry, it just stopped working for the other tenant also just now

**Comment by JimmyHang** [comment]
Update on this, so the webpart works if the tenant is set to "Standard Release" if the tenant is set to "Targeted release" obviously backend code breaks the webpart. Below si a screenshoot of a tenant where it didn't worked and I rolled back to "standard release", now the webpart works as expected. 
Next is to figure out what backend update broke it... :)


![image](https://user-images.githubusercontent.com/18226765/70812664-5aaa5b00-1dc8-11ea-918f-b66c6d722701.png)

**Comment by olemp** [comment]
There’s some changes to the page layout. We don’t know how to handle it yet.

**Comment by olemp** [comment]
As @JimmyHang mentions above, the webpart fails for "first release" tenants @tarjeieo. So not sure how to handle this?

**Comment by olemp** [comment]
Fix for first release tenants will be added in the next release.
