### ISSUE TITLE
Programvisninger forblir aktiv selvom visningsvelger skrus av

### ISSUE THREAD

**Issue by siifux** [Puzzlepart/prosjektportalen365#1566]
### Beskriv feilen

Når man har valgt å vise visningsvelgeren og programvisninger men deaktiverer visningsvelger igjen, så forblir programvisninger aktiv i grensesnittet. 

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til porteføljeoversikten
 2. Rediger oversikten
 3. Aktiver visningsvelger og programvisninger
 4. Lagre og refresh
 5. Deaktiver visningsvelger
 6. Se at programvisninger fremdeles syntes i grensesnittet

### Forventet oppførsel

Forventer at både visningsvelger og programvisning deaktiveres dersom visningsvelgeren skrus av.

### Skjermbilder

![image](https://github.com/user-attachments/assets/5a81a499-0faa-4a2f-9512-cc9e23524d07)

### Ytterligere informasjon

Testet i v. 1.10.0 (Test) 

### Versjon

1.9.0 (siste stabile)

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/pull/1570 @siifux
