### ISSUE TITLE
Fjern "Legg til kolonne"-knappen ved siden av kolonnene i porteføljeoversikten

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#157]
**Is your feature request related to a problem? Please describe.**
Den er litt misvisende siden den åpner "ny kolonne"-skjemaet og er sånn sett altfor avansert for 99% av brukere.

**Describe the solution you'd like**
Om vi skulle beholdt den måtte den fungert på denne måten
1. Åpne en liste med alle konfigurerte kolonner
2. La brukere velge de kolonnene de vil vise i visningen
3. Lagre gjeldende visning

Men jeg tror det enkleste er å skjule denne funksjonaliteten.

**Comment by olemp** [comment]
Solved in https://github.com/Puzzlepart/prosjektportalen365/commit/adce7fe1080c7f0a62413b4703a8675e48809b3c
