### ISSUE TITLE
Feilaktig formatering av tiltak i Usikkerhetsoversikt

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#1577]
#### Beskrivelse
I **Usikkerhetsoversikten** får tiltak feilaktig formatering der HTML-kode vises i stedet for riktig formatert tekst. Dette fører til at tekst blir vanskelig å lese.

#### Forventet oppførsel
Tiltak skal vises med korrekt tekstformatering uten at rå HTML-kode vises. Eventuelle formateringskoder skal tolkes og vises som tilsiktet (f.eks. fet, kursiv, punktlister osv.).

#### Steg for å reprodusere
1. Gå til **Usikkerhetsoversikt**.
2. Angi tiltak som synlig kolonne og se på tiltak som er angitt for elementer i oversikten.
3. Merk at HTML-kode vises i stedet for formateringen.

#### Teknisk informasjon
- Det ser ut til at HTML-kode ikke blir riktig behandlet når tiltak vises i oversikten, og dette fører til at rå kode blir synlig i stedet for riktig formatering.

**Comment by marmjel** [comment]
Fungerer når "Tiltak" kolonne i prosjektets usikkerhetsliste er i "Enkel tekst". Med rik eller utvidet tekst ser det slik ut i prosjektet:

![Image](https://github.com/user-attachments/assets/0f4a785f-dbec-4b70-84bd-0272bc68834e)
(HTML-kode vises)

Slik ut i overordnet "Usikkerhetsoversikt":

![Image](https://github.com/user-attachments/assets/3152e4a8-0172-4b49-8a29-3f482d5cbb87)
(Formatering og pkt. liste fjernes)
