### ISSUE TITLE
Visninger på overordnet område lagres ikke ved endring av rekkefølge på kolonner

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#1584]
### Beskriv feilen

Når man endrer rekkefølgen på kolonner gjennom panelet på overordnet område oppdateres det riktig etter at det "lagres" ved hjelp av Bruk.
Men det viser seg at den ikke lagres "Ordentlig".
Så fort man går bort fra siden, og tilbake igjen er rekkefølgen satt tilbake til "original" konfigurasjon.

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til et program og siden for risiko / underordnet innhold
 2. Klikk på en kolonne og velg vis/skjul kolonner
 3. Endre rekkefølgen og trykk "Bruk"
 4. Observer at kolonner er justert riktig i forhold til dine justeringer
 5. Gå helt ut av siden og deretter inn igjen
 6. Observer at kolonnerekkefølge er tilbake til slik den var FØR din justering

Feilen gjelder både på sidene for Risiko, Leveranser og Gevinst.

### Forventet oppførsel

Forventer at endringer blir lagret og beholdes etter at man forlater siden.

### Ytterligere informasjon

Øvrige sider som benytter samme typen webpart må også sjekkes.

Gjelder versjon 1.10 - Testet i Prosjektportalen tenanten her: https://prosjektportalen.sharepoint.com/sites/AIibevilgningavsosialsttte/SitePages/OverordnetUsikkerheter.aspx#viewId=22

### Versjon

Eldre (spesifiser over)

**Comment by Remi749** [comment]
Løst i 6593946310666c28e158b25fc8705a456f343027
