### ISSUE TITLE
[ERROR] Failed to apply PnP templates to [https://.....]: On e or more errors occurred. during installation

### ISSUE THREAD

**Issue by aslamnm** [Puzzlepart/prosjektportalen365#159]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**About your setup**
 - Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]

**Additional context**

**Comment by olemp** [comment]
@aslamnm We need some more details about the issue.

**Comment by olemp** [comment]
Closing due to lack of details.
