### ISSUE TITLE
Området er ikke klart: Feil profilspråk.

### ISSUE THREAD

**Issue by selvaag** [Puzzlepart/prosjektportalen365#160]
#### Home / Project Team Site

Have installed the solution with the install.ps1 script on 3 different tenant. Site Collection is with Norwegian Language, Admin User with Norwegian Profile. The Team Site throw following error, no list or libraries included on the site:

![Error](https://user-images.githubusercontent.com/46810402/70127692-cfb8ba80-167b-11ea-85c7-88b64c6e36c2.JPG)

Please advise for this error. Is there a reason for this, and how can we resolve this issue so that each Team Site is provisioned and listed in Portfolio.

![ErrorHome](https://user-images.githubusercontent.com/46810402/70127848-19a1a080-167c-11ea-8e03-81c78682e896.JPG)

**Comment by tarjeieo** [comment]
Hi,

First error - are you creating the new site using "Create site" and selecting O365 group and "Prosjektområde" as template?

Second error looks to be related to the app not being granted access? See our [wiki ](https://github.com/Puzzlepart/prosjektportalen365/wiki)here in GitHub with howto.

-Tarjei

**Comment by selvaag** [comment]
Hi,
Thanks for feedback. I've got the second error sorted out, but still have problem with first one. We're using the "Create site" and select template "Prosjektområde" as template. The O365 am not sure is coming up. The O365 group is private and autopopulated.

The Team Site ("Prosjektområdet") is not provisioned as expected. Still having the "Området er ikke klart: Feil profilspråk.".

**Comment by olemp** [comment]
Something is wrong with the language of the site @selvaag, as you can see in the navigation in the background.

Did you select Norwegian when you created the site/group?

Have you tried refreshing the page? As the text describes, sometimes it takes some time before the language settings are ready.

You can try to go to `[YOUR_SITE_URL]//_layouts/15/muisetng.aspx`.

**Comment by selvaag** [comment]
Yes, we selected Norwegian when created the Team Site ("Prosjektområdet") by template.

![Muisetng](https://user-images.githubusercontent.com/46810402/70215921-d1978200-173e-11ea-9be6-4c585b2cbb0e.JPG)

**Comment by olemp** [comment]
Try turning of English under _Alternate language(s)_.

**Comment by selvaag** [comment]
Hi Ole,

Thanks!! worked perfectly :-) 

we're considering translate solution to English, which areas is affected, e.g. Projectområde - as this current issue language checkelds etc.?

**Comment by olemp** [comment]
Are you sure the profile language is set to Norwegian? It shouldn't use an alternative language if the profile language is the default language.

**Comment by selvaag** [comment]
The default language is currently "Norwegian", but consider translate code content to English. The language check is this only when create team site ?

**Comment by olemp** [comment]
The default language is Norwegian, but I think the profile language of the user is English

Prosjektportalen does not work with team sites with English as default language.

**Comment by tarjeieo** [comment]
Looks like this can be solved in a quite stable way by the following 
![image](https://user-images.githubusercontent.com/1837390/72535577-13a4ff00-3879-11ea-9973-7804cb8480a8.png)

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen365/commit/d890bb62497b3c3970c805e3fa26bc31e15dbb9d
