### ISSUE TITLE
Install-script doesn't log in the install list. Add-PnPListItem : String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#161]
**Describe the bug**
In the post deploy steps, when logging to the install log, the step fails with Add-PnPListItem : String was not recognized as a valid DateTime. Nothing is added to the install log list. 

**To Reproduce**
Run a new install/upgrade

**Comment by olemp** [comment]
Probable due to environment differences in date format @tarjeieo?

**Comment by olemp** [comment]
@tarjeieo @pzlespen 

Hmm, this is according to docs:

```powershell
$InstallEndTime = (Get-Date).ToUniversalTime().ToString("MM/dd/yyy HH:mm")

$InstallEntry = @{
    InstallStartTime = $InstallStartTime; 
    InstallEndTime   = $InstallEndTime; 
    InstallVersion   = "VERSION_PLACEHOLDER";
    InstallCommand   = $MyInvocation.Line.Substring(2);
}
```

https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnplistitem?view=sharepoint-ps

**Comment by tarjeieo** [comment]
Interesting.... Might be like you say that it differs based on the original site locale?

**Comment by olemp** [comment]
Seems like it, not sure how to handle it @tarjeieo!

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen365/commit/2e6b52c5a2e1ae60fbe2a9fb628b219dc66e78f6

**Comment by tarjeieo** [comment]
Just got this issue again

**Comment by olemp** [comment]
I've googled and googled and haven't found a solution. Are you still getting an error message? It should be sent to dev null. See https://github.com/Puzzlepart/prosjektportalen365/commit/2e6b52c5a2e1ae60fbe2a9fb628b219dc66e78f6.

**Comment by tarjeieo** [comment]
But I want it logged, not nulled :) Will try to debug here now

**Comment by tarjeieo** [comment]
Looks like `get-date -format o` did the trick
