### ISSUE TITLE
"Gevinstansvarlig" only applies at the portfolio level. In the "Gevinstrealisering" list it should be called "Gevinsteier"

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#162]
Se mer info: https://www.prosjektveiviseren.no/roller/gevinstansvarlig

**Comment by olemp** [comment]
This is a bigger change. We're reusing the field `GtGainsResponsible` for the list right now. We could try to change the display name in field ref.

**Comment by tarjeieo** [comment]
I think we need to create a new field to support different descriptions and so forth. PP365 doesn't have critical usage yet, and I think it's safe to do this without anyone being mad or sad they have to input the name again.

**Comment by olemp** [comment]
We also need to add a new mapping if it should be searchable, or add a util function that takes the display name of the user from the out of the box search field @tarjeieo.

**Comment by olemp** [comment]
How do we do it with the search mappings @tarjeieo?

**Comment by olemp** [comment]
> How do we do it with the search mappings @tarjeieo?

Input here?

**Comment by olemp** [comment]
cc @tarjeieo

**Comment by tarjeieo** [comment]
Guess we need a new property and add Gevinsteier? RefinableString74?

**Comment by olemp** [comment]
I can do a draft PR for this one, could you then add the search mappings? You're more up to speed there 🐎
