### ISSUE TITLE
Planner web part is blank on the "Oppgaver" page in project sites

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#164]
**Describe the bug**
The Oppgaver page is blank.

Works if you create a new page and add the Planner web part again. Might be a change in the web part config.

**Comment by olemp** [comment]
This is the properties we use at the moment:

```json
{
  "title": "Oppgaver",
  "isFullScreen": true,
  "plannerViewMode": "board",
  "planId": "{parameter:defaultPlanId}"
}
```

**Comment by olemp** [comment]
Maybe `isFullScreen` is not supported anymore?

**Comment by olemp** [comment]
Working again in our tenant, so mos def a Office 365 issue. Will reopen if it occurs in other environments.

**Comment by olemp** [comment]
Set properties to:

```json
{
  "plannerViewMode": "board",
  "planId": "{parameter:defaultPlanId}"
}
```

Seems like `isFullScreen` is not supported anymore.

Fix will be included in next release. CHANGELOG updated.

**Comment by Lysakers** [comment]
Same issue in our environment, though it works for some users but not for others.
How can i change (or check) the properties?

**Comment by olemp** [comment]
@Lysakers Check out the `Set-PnPClientSideWebPart` commandlet from PnP-PowerShell.

You need to remove `isFullScreen` property (see above).

**Comment by Lysakers** [comment]
I am not able to do anything with the page through the powershell cmdlets.
All i get is this error when trying to get the Oppgaver page:
`Get-PnPClientSidePage : Objektreferanse er ikke satt til en objektforekomst.`

Without getting it I can't set it.

**Comment by olemp** [comment]
Seems like a PnP-PowerShell bug. Not sure how to do it then. Any idea @tarjeieo?

**Comment by Lysakers** [comment]
@olemp  Is it possible to change the defaults in order to fix this for future created projects?

I can find this in the "Prosjektmaler" settings:
`        {
            "Name": "Oppgaver.aspx",
            "Title": "Oppgaver",
            "PageLayoutType": "SingleWebPartAppPage",
            "CommentsDisabled": true,
            "Sections": [
                {
                    "Columns": [
                        {
                            "Factor": 12,
                            "Controls": [
                                {
                                    "Id": "39c4c1c2-63fa-41be-8cc2-f6c0b49b253d",
                                    "Properties": {
                                        "title": "Oppgaver",
                                        "isFullScreen": true,
                                        "plannerViewMode": "board",
                                        "planId": "{parameter:defaultPlanId}"
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
`

**Comment by tarjeieo** [comment]
1) Might be easier to delete the page, create a new page and add the Planner web part (edit WP properties to show tasks)
2) I think it's removed/fixed in the dev-branch
