### ISSUE TITLE
Adding a new diagram on the Porteføljeinnsikt page just refreshes the page and nothing happens

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#165]
**Describe the bug**
Adding a new diagram on /SitePages/Porteføljeinnsikt.aspx yields nothing - the page just refreshes.

**About your setup**
 - Browser [e.g. chrome, safari]: Chrome and Edge
 - Installed version: 1.1.6

**Additional context**
The issue doesn't happen in our environment, but can be reproduced in 2 customer tenants

**Comment by olemp** [comment]
Need logs from console. 🍔 ⚒

**Comment by tarjeieo** [comment]
I can't see anything relevant in console! 😢

**Comment by tarjeieo** [comment]
Gets a 500 from sp-pages-assembly when clicking the link - not sure if relevant: GET https://XXX.sharepoint.com/sites/prosjektportalen/_vti_bin/homeapi.ashx/sites/followed/isFollowed?siteId={348f4b89-6c03-49f1-b09b-ad65f1ff6131}&webId={a049f312-9d1e-41e2-8d8c-79dfa5a8d5bc}&url=https%3A%2F%2Fohincloud%2Esharepoint%2Ecom%2Fsites%2Fprosjektportalen

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen365/commit/67faf25fa9634c937639824215f6d542f0c480c1 should solve this. Will include in next patch version, but you can do the fix already @tarjeieo. Not sure why it was missing in the template.
