### ISSUE TITLE
Project status report - creating a new report dont have the budget numbers

### ISSUE THREAD

**Issue by JimmyHang** [Puzzlepart/prosjektportalen365#167]
**Describe the bug**
Not sure if this is a bug or should be an enhancement. But when we add a new status report, the numbers for "Totalbudsjett, Kostnader, Prognose" is cleared blank. Shouldn't these numbers be copied from the previous report or from the original report? As project budget should be fixed..

**To Reproduce**
1. Go to a project
2. Create a new report

**Expected behavior**
Expect "Totalbudsjett for prosjektet", "Kostnader påløpt totalt" and "Prognose for prosjektet" to be copied from previous report.

**Screenshots**
![image](https://user-images.githubusercontent.com/18226765/70747664-c210ce00-1d28-11ea-8059-843826385890.png)

**About your setup**
 - Browser : Chrome
 - Installed version: 1.1.6

**Comment by olemp** [comment]
Fix will be included in next release. CHANGELOG updated.
