### ISSUE TITLE
Link til prosjektområde mangler - får ikke opprettet prosjekter

### ISSUE THREAD

**Issue by tovebjornbakk** [Puzzlepart/prosjektportalen365#168]
**Describe the bug**
Vi har fulgt installasjonsbeskrivelsen på https://github.com/Puzzlepart/prosjektportalen365/wiki/Installasjon til punkt og prikke. Også etterarbeidet, med å redigere innstillinger på HUB-området, hvor jeg gav rettigheter til meg selv og de som skal teste portalen.

**To Reproduce**
1. Åpne prosjektportalen i Chrome nettleser

**Expected behavior**
Jeg forventet at link til prosjektområdet var tilgjengelig, så vi kunne opprette nytt prosjekt.

**Screenshots**
![feilmeldinger](https://user-images.githubusercontent.com/58508887/70794006-f0c88c00-1d9c-11ea-9a4b-df83bfec6b4c.jpg)

**About your setup**
 - Browser Chrome
 - Installed version 1.1.6

**Additional context**
Jeg fikk tips om å sjekke ut logg https://github.com/Puzzlepart/prosjektportalen365/issues/163 av Ole Martin Pettersen.

Jeg kjørte 
Get-PnPSiteDesign -Identity "Prosjektområde" 

Og deretter
Get-PnPSiteDesignRights -Identity 00be3b86-5d26-4fa7-a5c4-606cdd470dbc 
men fikk ikke noe som helst opp her.

**Comment by olemp** [comment]
@tovebjornbakk 

Har samtlige tilgang til rotområdet?

Har dere skrudd på group creation i tenanten?

**Comment by tovebjornbakk** [comment]
@olemp 

Alle som skal teste Prosjektportalen er lagt inn som Eier på <tenant>.sharepoint.com/sites/prosjektportalen.

Det er mulig å opprette gruppeområder i vår Shareoint online tenant, så jeg regner med det er slått på. Kan du angi hvor jeg kan sjekke det om du mener noe annet?

**Comment by tovebjornbakk** [comment]
@olemp 
Har forhørt meg på Drift, og group creation er skrudd på for begrensa antall brukere. Det er skrudd på for meg og han som skal teste ut prosjektportalen.

**Comment by Lysakers** [comment]
Jeg må si meg meg truffet av samme utfordring.
Har fått innstallert prosjektportalen med litt hjelp, og får i grunn opprettet prosjekt via Sharepoint admin senteret - som også dukker opp under "Mine prosjekter" på hub siten.
Men jeg har også låst ned group creation i mitt miljø, og får derfor ikke knappen for å kunne opprette nye prosjekt direkte på hub siten.
Er det ikke mulig å få dette til å fungere når man låser ned group creation?

**Comment by olemp** [comment]
Nei, Prosjektportalen 365 fungerer ikke når man låser ned group creation, da det baserer seg på "Opprett område" og områdeutfomringer.

**Comment by tovebjornbakk** [comment]
@olemp 
Må Group creation være åpent for alle, eller holder det at de som skal bruke prosjektportalen har fått tilgang?
@Lysakers Du opprettet prosjekt via Sharepoint admin senteret, er prosjekt bare en Sharepoint gruppe?

**Comment by Lysakers** [comment]
@tovebjornbakk Jeg ble vist en fremgangsmåte å opprette prosjekt via admin senteret slik at det ble en fullverdig Office 365 gruppe. Man måtte da lage gruppen som en team site med korrekt mal type, samt manuelt knytte den mot prosjektportalen.

@olemp  Da skjønner jeg at opprettelse biten ikke vil fungere ved nedlåsing av group creation.
Vil det da også si at det ikke jobbes med noen løsning for oss som har nedlåsning?
Jeg antar da eneste veien å gå er en egenlaget provisjonersing løsning?

**Comment by olemp** [comment]
@Lysakers Det er ikke noe planlagt enda. Prosjektportalen 365 er enda i `prerelease`, så vil i hvert fall få til en ordenlig release før vi ser på dette. Tror ikke det blir så lett, så blir nok muligens en egenlaget provisjoneringsløsning som blir alternativet.

**Comment by tovebjornbakk** [comment]
@Lysakers Jeg skulle gjerne fått den fulle beskrivelse av fremgangsmåten, så vi også kan starte å teste Prosjektportalen! :) Kunne jeg fått den på epost?

**Comment by tarjeieo** [comment]
Hub-site tilganger dokumenert fra MS - "for the record"; https://docs.microsoft.com/en-us/sharepoint/modern-experience-sharing-permissions#hub-site-permissions

**Comment by rolfgj** [comment]
Ble det noen løsning på dette? Har nettopp installert Prosjektportalen 368 v 1.2.1.a1af0af. Får ikke knappen for nye prosjekter. Brukerne som tester har rettigheter til å opprette grupper. Rettigheten til å opprette grupper er begrenset til spesifikke grupper. Er det som er skrevet tidligere i denne tråden, slik å forstå at opprettelse av grupper MÅ være åpent for alle, ikke bare en spesifikk gruppe?
SiteDesignSecurityGroupID er satt til gruppen som kan opprette grupper.
