### ISSUE TITLE
Missing permission to edit Prosjektstatus

### ISSUE THREAD

**Issue by JimmyHang** [Puzzlepart/prosjektportalen365#176]
**Describe the bug**
Not sure what happens here, but I don't have permission to edit the prosjektstatus page.

![image](https://user-images.githubusercontent.com/18226765/71067230-7caf2f00-2174-11ea-91b8-e71a04aba990.png)

**Comment by olemp** [comment]
Then you don't have permissions to the hub site list `Prosjektstatus`. Project status are dependent on the hub site @JimmyHang.

**Comment by JimmyHang** [comment]
I have this issue only for one project, i can edit other projects status fine. To be more presise
This project site was created before I implemented "prosjektportalen 365", I later ran the site scripts and project setups, and thinks looks rite but there is some connections missing?

**Comment by olemp** [comment]
Hmm, there is some connection missing. I've never tried the case where you create the site before you create the portal I'm afraid.

Is it a lot of data in the project? Could you recreate it?
