### ISSUE TITLE
Taxonomy.pnp is installed after portefolje.pnp causing invalid field error

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#18]
When running install.ps1 the taxonomy.pnp package is installed after portefolje.pnp, for customers installing the pp365 for the first time this will cause errors when applying portefolje.pnp at the portfolio site

**Comment by olemp** [comment]
Solved by @okms in https://github.com/Puzzlepart/prosjektportalen365/pull/21. Closing. Reopen if this is not correct @okms
