### ISSUE TITLE
When modifying values in "Statusseksjoner" nothing happens

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen365#180]
**Describe the bug**
In "statusseksjoner" I try to change the values for "Vis i statusseksjonen" and "Vis som egen seksjon", but nothing happens in the project.

**About your setup**
 - Browser: all browsers
 - Installed version: version 1.1.6

**Comment by olemp** [comment]
PR merged. Will be included in next release.
