### ISSUE TITLE
In "Ressursallokering" the project name is hard to read

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen365#181]
**Describe the bug**
When you are in the central page "Ressursallokering". If a project has started a while ago, the view does not show the project name and role clearly. Is there a way to make this more visible?

**Screenshots**
![image](https://user-images.githubusercontent.com/24522890/71726349-180ff780-2e37-11ea-9bbc-3d943d909127.png)

**About your setup**
 - Installed version : version 1.1.6

**Comment by olemp** [comment]
Can't you just drag the timeline back some weeks/months @pzlespen? The timeline supports mouse drag.
