### ISSUE TITLE
Projectsetup don't remember selections when switching between tab's

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#182]
**Describe the bug**
When moving between the tab's 'Prosjekttillegg' and 'Standardinnhold' selections made resets when going back to previous tab

**To Reproduce**
In baprosjekt365......
1. Go to 'Prosjekttillegg'
2. Select 'Godkjente dokumenter'
3. Go to 'Standardinnhold'
4. Select 'Interessentregister'
5. Go to 'Prosjekttillegg'
6. Verify 'Godkjente dokumenter' has been deselected
5. Go to 'Standardinnhold'
6. Verify 'Interessentregister' has been deselected

**Expected behavior**
Selections should not be deselected when going back to the tab

**About your setup**
 - Installed version 1.1.6  (Indentified in 'Oppsett av prosjektområde' dialogboks

**Comment by olemp** [comment]
Reproduced succesfully.

**Comment by olemp** [comment]
Added fix.
