### ISSUE TITLE
PowerShell write to output which user the installation is connected with

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#187]
**Is your feature request related to a problem? Please describe.**
In some cases there might be uncertainties around which user the connection has been done with - e.g. in cases where PnP is picking up active/stored credentials or Windows credentials.

**Describe the solution you'd like**
Output from the installation script

**Comment by olemp** [comment]
```powershell
$ctx = Get-PnPContext
Get-PnPProperty -Property CurrentUser -ClientObject $ctx.Web
```

**Comment by olemp** [comment]
Added in https://github.com/Puzzlepart/prosjektportalen365/commit/b0710fb4621dc3d0745abe8aba37163214a7b6d2
