### ISSUE TITLE
Permission requests listed multiple time under API managment

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#19]
After running install.ps1 there are multiple entries for each permission request under API managment. After approving one, approving the others causes an error. Note that this issue is only visible under API managment in the new SharePoint Admin Center and may very well be caused by a bug there

**Comment by olemp** [comment]
This happens every time you upload/deploy a package with `webApiPermissionRequests` specified. It's a  SharePoint Admin Center bug.
