### ISSUE TITLE
Portfolio overview wrong offset in production release tenants

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#191]
**Describe the bug**
The portfolio overview is overlapping other content in 1.1.8.

**Screenshots**
![image](https://user-images.githubusercontent.com/1837390/72413619-78286700-3770-11ea-9c10-fdd6025d3d8c.png)

Difference in how SharePoint is rendering the web part between targeted release and production release:
Production release tenants:
![image](https://user-images.githubusercontent.com/1837390/72413682-a0b06100-3770-11ea-9bac-6c0b190fe6c4.png)

Targeted release tenants:
![image](https://user-images.githubusercontent.com/1837390/72413737-b9207b80-3770-11ea-81b2-5c9054c8e4a0.png)

**About your setup**
 - Browser [e.g. chrome, safari]: Edge Chromium, Chrome
 - Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]: 1.1.8

**Comment by olemp** [comment]
I'm not sure how we can handle this. Right now we've scoped the solution to first release tenants. It seems like the users of Prosjektportalen 365 is about 50% first release. It will be hard to maintain separate versions for first release and production release?

Any thoughts @okms @tarjeieo?

(cc @damsleth)

**Comment by tarjeieo** [comment]
Completely agree we cannot handle two versions of the product. Was hoping we could fix this with some CSS that replicates some of the changes in targeted release markup/CSS. Investigating now.

**Comment by olemp** [comment]
The problem is we need CSS that support both scenarios. It might not be impossible, but I haven't found a solution yet.

**Comment by tarjeieo** [comment]
This should in theory fix this, but how can I add global CSS to a page with SPFx?

```
.ms-Fabric {
  .ms-SPLegacyFabricBlock {
    .portfolioOverview {
      .container {
        .ms-ScrollablePane {
          top: 260px;
        }
      }
    }
  }
  article {
    .ms-SPLegacyFabricBlock {
      .portfolioOverview {
        .container {
          .ms-ScrollablePane {
            top: 75px;
          }
        }
      }
    }
  }
}

```

**Comment by tarjeieo** [comment]
![image](https://user-images.githubusercontent.com/1837390/72798265-fee2b580-3c42-11ea-8f36-23993fe41254.png)

Still an issue in production-tenants

**Comment by olemp** [comment]
@tonnesr Would you have a look?

**Comment by tonnesr** [comment]
The [documentation](https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane) of ScrollabelPane says that you'll need a container with "position: relative", and a static height.

So you can "fix" the issue by adding { position: relative, height: 800px } to the parent container of scrollablePane. But it will really only add more problems to the mix (no automatic height from css, and scrollablepane not being as good anymore).

I haven't been able to find a solution that actually fixes the problem. The best solution we have might be to use top, and get the height of containers above our work area?

**Comment by tarjeieo** [comment]
Looks to be fixed, MS probably rolled out a fix to GA
