### ISSUE TITLE
Error in 'Hent dokumentmal' extension when using another document library then default 'Dokumenter'

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#197]
**Describe the bug**
Hent dokumentmal formen husker viser ikke hvilket bibliotek som er valgt når du velger et annet bibliotek enn 'Dokumenter'

**To Reproduce**
Velg et annet dokument enn default valgte 'Dokumenter'

**Expected behavior**
Etter at du velger et bibliotek forventes det at det nyvalgt biblioteket vises i drop-down boksen

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/72519202-2dcde580-3857-11ea-9a58-5cdf55da3344.png)

**About your setup**
 - Browser [chrome]
 - Installed version [1.1.7]

**Comment by olemp** [comment]
Doesn't build @tonnesr. State variable `selectedLibraryOptionKey` is not defined in the state interface.
