### ISSUE TITLE
Building the install package fails

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#20]
When building the install package the following fails
- No files under /Apps
- Projects under SharePointFramework will not build if you have not previously run pnpm i for each project
- build output from projects under SharePoint framework is piped to /dev/null causing any build failures to be swallowed. Build output should ALWAYS be visible, and a failed build should fail the packaging of the project

**Comment by olemp** [comment]
Solved by @okms in https://github.com/Puzzlepart/prosjektportalen365/pull/22. Closing. Reopen if this is not correct @okms
