### ISSUE TITLE
Proteføljeoversikt throws error

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#208]
**Describe the bug**
When clicking the link for Porteføljeoversikt we are met with "Finner ikke anigtt visning"

![image](https://user-images.githubusercontent.com/7568950/72890889-40db2c80-3d13-11ea-91a8-1542d4d1caab.png)

But if I add #viewId=1 to the URL it loads just fine.

This happens only to one of the two Prosjektportal sites on our sharepoint.
I've tried re-running the 1.1.9 installation without the Upgrade switch, but no luck.

**To Reproduce**
1. Open Prosjektportal in Sharepoint
2. Click Porteføljeoversikt
3. See error

**Expected behavior**
The Porteføljeoversikt loads without issue.

**Screenshots**
Added i description

**About your setup**
 - Browser: Microsoft Edge Chromium
 - Installed version: 1.1.9

**Additional context**
n/a

**Comment by olemp** [comment]
Could you add the console output @LostLogic?

**Comment by LostLogic** [comment]
[luftambulanse.sharepoint.com-1579693994819.log](https://github.com/Puzzlepart/prosjektportalen365/files/4097023/luftambulanse.sharepoint.com-1579693994819.log)
Here you go :)

**Comment by olemp** [comment]
Strange. Can't see anything on first look. Is there a view set as default view in the list _Porteføljevisninger_?

**Comment by LostLogic** [comment]
Ah. It seems one of the owners had made some changes to the Porteføljeoversikt.aspx. I reverted it back to the version with the comment "Published by provisioning" and it's back to working again.
Sorry for the touble and thank you for the help!

**Comment by olemp** [comment]
Oh, good! You got me worried here ;)

No problem!
