### ISSUE TITLE
"Porteføljeoversikt" er plutselig uten innhold 

### ISSUE THREAD

**Issue by bomullspad** [Puzzlepart/prosjektportalen365#210]
**Describe the bug**
Når vi går inn på Porteføljeoversikt, får vi ikke opp noen resultater. Dette gjelder alle brukere. 
I Chrome og Edge får vi bare opp en tom liste. Vi er inne på Porteføljeoversikt, men listen som står på siden er "Leveranseoversikt". 
I IE får vi en feilmelding. Se skjermbilder. 
Problemet ble oppdaget i går 22.01.2020. 

**To Reproduce**
1. Gå til https://[].sharepoint.com/sites/Prosjektportalen365/SitePages/Porteføljeoversikt.aspx

**Expected behavior**
En tom liste (Leveranseoversikt i stedet for Porteføljeoversikt) eller en feilmelding, avhengig av nettleser. 

**Screenshots**

**About your setup**
 - Installed version 1.1.3

**Additional context**
![feil Porteføljeoversikt chrome og Edge](https://user-images.githubusercontent.com/37407287/72968168-38422f00-3dc3-11ea-9d9a-4e8537b4876f.PNG)
![feil Porteføljeoversikt IE](https://user-images.githubusercontent.com/37407287/72968170-38422f00-3dc3-11ea-8c24-d05a50b57ebe.PNG)

**Comment by tarjeieo** [comment]
Har du noe versjonshistorikk? Virker jo som noen har tukla her egentlig. Minner også litt om https://github.com/Puzzlepart/prosjektportalen365/issues/156.

Uansett kan du jo prøve å slette siden og så oppdatere på nytt? Ser du er på en ganske gammel versjon.

**Comment by olemp** [comment]
Her ser det veldig ut som noen har tukla som @tarjeieo sier. Det er ikke noen problemer med Porteføljeoversikten i IE/Chrome/Edge på noen av installasjonene vi har (i ulike tenants).

**Comment by bomullspad** [comment]
I versjonshistorikken er det ingen endringer siden vi satte opp Prosjektportalen 16.10.2019. Denne feilen ble oppdaget denne uken.

**Comment by bomullspad** [comment]
Hvordan oppdaterer jeg til siste versjon? Vil vi miste noe av dataene vi har lagt inn?

**Comment by bomullspad** [comment]
Nå ser vi at "Oppgaver" på alle prosjektene våre også er tomme. Ingen endringer er gjort på disse sidene siden oktober i fjor. 
https://[].sharepoint.com/sites/[prosjekt]/SitePages/Oppgaver.aspx

Vi må nok prøve en oppdatering. Må vi slette alle de tomme sidene før oppdatering? Er det bare å installere prosjektportalen på nytt for å få siste versjon?

**Comment by olemp** [comment]
Kjør installasjonen med -Upgrade switchen.

https://github.com/Puzzlepart/prosjektportalen365/wiki/Installasjon

Problemet med Oppgaver-siden er løst her https://github.com/Puzzlepart/prosjektportalen365/issues/164
