### ISSUE TITLE
Porteføljestatuskolonner viser ingenting

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#211]
**Describe the bug**
Porteføljestatuskolonner viser ingenting i porteføljeoversikten

**Expected behavior**
Porteføljestatuskolonner viser verdier i porteføljeoversikten

**Screenshots**
![image](https://user-images.githubusercontent.com/1837390/72981782-e9ee5980-3ddd-11ea-8e48-39bc89b706c9.png)

**About your setup**
 - Browser [e.g. chrome, safari]: Chrome
 - Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]: 1.1.9

**Comment by olemp** [comment]
Dette er fordi prosjektstatusene ikke er publiserte.
