### ISSUE TITLE
Ability to add resource entries without a person, only as role

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#214]
**Is your feature request related to a problem? Please describe.**
- Ability to add resource entries without a person, only as role

**Describe the solution you'd like**

* Make the user/allocated resource voluntarely in project resource allocation content type. If not set, the "Role" is also used as the name in the resource allocation overview.

**Comment by olemp** [comment]
How would this look UI wise @tarjeieo?

**Comment by tarjeieo** [comment]
Replace Name with Role... Any specific places you're wondering about?

**Comment by olemp** [comment]
So add the roles to the left navbar with the names? Don't see how that'll be UX wise.

**Comment by tarjeieo** [comment]
Hmm, I don't see any other option. Maybe add them as "Role: <Specific role>" - or at least sort them together, at the end of the list.

**Comment by tarjeieo** [comment]
We could also discuss this topic this friday with ༼ つ ◕_◕ ༽つ

**Comment by olemp** [comment]
Yes, I don't see the point in this. Will it be used to show demand for a role in a project? Will project owners/leaders really use Prosjektportalen for this?

**Comment by tarjeieo** [comment]
Yeah, several requests for this. The plan resources ahead and know they need e.g. an ITPro, but don't care if it's "Espen" or "Martin".

**Comment by olemp** [comment]
Added roles. Sorted to they end up at the bottom. We need to distungish between users/resources and roles somehow @pzljanb @tarjeieo. Ideas? I'm thinking icons.

![image](https://user-images.githubusercontent.com/7606007/74733880-8a089880-524d-11ea-9bb6-d96cb340db2e.png)

**Comment by olemp** [comment]
Italic style should do the trick @tarjeieo @pzljanb 

![image](https://user-images.githubusercontent.com/7606007/74736810-db1b8b00-5253-11ea-9b75-4bc025a341c3.png)
