### ISSUE TITLE
Problem with creating diagrams from versions older than 1.1.9, even after upgrade to 1.1.9

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#220]
**Describe the bug**
When going to "Porteføljeinnsikt" and trying to create a new diagram the page just refreshes and doesn't show the new form for creating the diagram selected. This happens for all the types of diagram: "Sektor, stolpe, kolonne and egendefinert diagram"

The problem persist even after upgrading to 1.1.9 which should have fixed the problem, but only for clean 1.1.9 install it seems.

This could mean that all previous pp365 installs that is older than 1.1.9 and or has been recently upgraded to 1.1.9 has this problem were they cannot add diagrams, which leaves the "Porteføljeinnsikt" site as broken for now.

A fix for this for now is to manually delete the elements listed in "Grafkonfigurasjon" list, and then afterwards remove all the connected contenttypes and adding them with PnP and adding the elements to the "Grafkonfigurasjon" list afterwards. This has fixed the issue on two sites that had previously 1.1.8 installed and were recently upgraded to 1.1.9

**To Reproduce**
1. Go to 'https://*tenant*.sharepoint.com/sites/*pp*/SitePages/Porteføljeinnsikt.aspx'
2. Click on 'Ny'
3. Select one of the diagrams
4. See error.

**Expected behavior**
When selecting new diagram you should be sent to the new form.

**About your setup**
 - Browser [chrome]
 - Installed version [1.1.9, previously 1.1.8]

**Comment by olemp** [comment]
Probably the content types on the list doesn't get updated.

Would love if you could have a look @Remi749. We might just use new form/edit form urls from the list, not the content types. They won't differ from content type to content type. Bad design by myself truly.

**Comment by tarjeieo** [comment]
What's the conclusion here @olemp? Fixed in 1.2.0 for old installations as well?

**Comment by olemp** [comment]
> What's the conclusion here @olemp? Fixed in 1.2.0 for old installations as well?

Yes, it will be fixed when upgrading to `1.2.0` (unreleased). 

`PortfolioInsights no longer dependent on NewFormUrl from chart content types #223`
