### ISSUE TITLE
Version history from "Vis versjonshistorikk" not working, always shows latest version

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#221]
**Describe the bug**
Version history in projects only shows the latest version. 

**To Reproduce**
1. Perform changes in project properties
2. See that version history only shows the current data, no history

**Expected behavior**
Expect to see version by version changes

**About your setup**
 - Browser [e.g. chrome, safari]: Chrome
 - Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]: 1.1.9

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen365/blob/master/Templates/Portfolio/Objects/Lists/Prosjekter.xml#L1

**Comment by tarjeieo** [comment]
https://pzlcloud.sharepoint.com/sites/Eiendomsskattikommunen/_layouts/15/versions.aspx?list=82209356-edfd-4ec8-95f9-34609cd94677&ID=1

**Comment by olemp** [comment]
Ah, the local list.

We just need to add the property for enabling versioning here: https://github.com/Puzzlepart/prosjektportalen365/blob/master/SharePointFramework/%40Shared/src/services/PortalDataService/index.ts#L115 (line 115)

**Comment by tarjeieo** [comment]
Aight, sweet, was worried it was something more serious wrt how syncing is done. Lets do it before 1.2.0

**Comment by olemp** [comment]
Might be:

```json
targetWeb.lists.ensure(listName, '', 100, false, { Hidden: true, EnableAttachments: false, EnableVersioning: true }),
```

But I'm not sure if it's called `EnableVersioning`. Could you have a look?

**Comment by tarjeieo** [comment]
` AdditionalSettings: { EnableVersioning: true }` is what we're using elsewhere

**Comment by olemp** [comment]
Awesome, then that's the way to go!
