### ISSUE TITLE
New column "Vis i prosjektkonfigurator" to the list "Listeinnhold"

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#227]
**Is your feature request related to a problem? Please describe.**
Missing this functionality from Prosjektportalen 2.0, where the functionality where used to "Force" import of some content.
To maintain this functionality this function needs to be added to PP365 as well.

**Describe the solution you'd like**
New column "Vis i Prosjektkonfigurator" of the type "YES/NO"
to the list "Listeinnhold", with default value = "YES"

When enabled the item should be shown in the configurator window, 
and the user can choose to select the item to be included when the project is configured.
If this selector is disabled and the value "Standard" = "YES" the item should be imported to the project.

**Comment by olemp** [comment]
Solved in #231.

Added a `Skjult` field instead with description `Om elementet skjules, kan det ikke velges av brukerne i dialogen for oppsett av nytt prosjektområde.`. It's better that the field is opt-out.
