### ISSUE TITLE
Planner content to support "cascade import"

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#228]
**Is your feature request related to a problem? Please describe.**
When I use different Planner tasks for different type of projects I need to have the same basic tasks in all of my configurations (SP list(s)).

**Describe the solution you'd like**
I would like to enable a type of "cascade import" (same way as all other "Listeinnhold" to enable import of more than one set of planner tasks when projects is configured.
With this functionality I can split my planner tasks into several SP list(s) and select more than one source in the project configurator.

Together with Github issue no:227 I can also force import of some Planner tasks.

**Additional context**
I still want to keep all tasks in one common Planner.

**Comment by olemp** [comment]
> With this functionality I can split my common planner tasks into a singel file and have this one selected together with one of my Project type specific files.

You say file @pzljanb? The configuration for planner tasks are now in SP list(s).

**Comment by pzljanb** [comment]
SPL lists(s) the same way as the other content like (Interessentregister)?
Perfect, Its a step in the right direction :-)

**Comment by olemp** [comment]
> SPL lists(s) the same way as the other content like (Interessentregister)?
> Perfect, Its a step in the right direction :-)

Yes, update the description of the issue please 🙏

**Comment by olemp** [comment]
Solved in #230. This issue should have been auto-closed by merging that PR, but no, not this time.
