### ISSUE TITLE
Rerun project configurator on already configured projects

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#229]
**Is your feature request related to a problem? Please describe.**
I sometimes/always forget some of the project setup features I want to be added on to my project.
But after the first setup, I cant redo this, and needs to delete project an create a new project to include the correct features.

**Describe the solution you'd like**
Give the Site Owner of the project-site the possibility to rerun the project configurator.
As a minimum I would like content like navigation, listitems, documents and "new" content (lists/document libraries) to be imported.

**Additional context**
The 3 different tabs "Prosjektmal", "Prosjekttillegg" and "Standardinnhold" need to be analyzed.
Is there a problem if a Project template, or a list/site page is imported once more?

**Comment by olemp** [comment]
I'm unsure about this. Adds some complexity. Let's discuss on next status meeting 🍖

**Comment by olemp** [comment]
We won't implement this.
