### ISSUE TITLE
Issues installing v1.2.0

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#242]
**Describe the bug**
Issues installing v1.2.0. Fails at update of site scripts.

**Screenshots**
![image](https://user-images.githubusercontent.com/7606007/75037853-6a73a900-54b5-11ea-8dc0-518afcf7d2e0.png)

**Comment by olemp** [comment]
@pzlespen Could you paste the full install command you used?

**Comment by pzlespen** [comment]
.\Install.ps1 -Url https://pzlcloud.sharepoint.com/sites/pp3test -Upgrade -UseWebLogin

**Comment by olemp** [comment]
I'm loading `SharePointPnPPowerShellOnline` in my PS profile, so that might be why it's working. I'll check without the profile.

**Comment by tarjeieo** [comment]
For some reason one environment had duplicate site scripts. Doesn’t look like an issue with this release. Closing until we see this again
