### ISSUE TITLE
Read-only access to portfolio (project properties and project status)

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#243]
**Is your feature request related to a problem? Please describe.**
In some instances you might want to give some users read access to all projects in the portfolio (ledergruppen, rådmann). This is hard to achieve today without giving the users read-access or member-access to all projects.

**Describe the solution you'd like**
A good solution could be to create a portfolio group "Prosjektinnsyn" that automatically gives it's members overview of all projects in the portfolio overview page. This enables them to see project properties, project status reports, but does not give them access to the projects themselves.

**Comment by tarjeieo** [comment]
This issue solves access to all projects for members of the SharePoint-group "Prosjektinnsyn" in the Portfolio. Other use cases, e.g. access to all projects on the frontpage, will be solved in separate issues.

**Comment by olemp** [comment]
Solved in #305
