### ISSUE TITLE
The SPListItem being updated was not retrieved with all taxonomy fields

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#245]
**Describe the bug**
Same issue as https://github.com/Puzzlepart/prosjektportalen/issues/567. Got this when saving the project properties form in a project for the phase-fieldvalue.

**About your setup**
 - Browser [e.g. chrome, safari]: NA
 - Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]: 1.2.0

**Additional context**
The issue was resolved by removing the phase field from the project properties list and re-adding it, setting phase manually again.

**Comment by tarjeieo** [comment]
The issue was resolved by removing the phase field from the project properties list and re-adding it, setting phase manually again.

**Comment by olemp** [comment]
Brand new project? Haven’t seen this bug in a while.

**Comment by tarjeieo** [comment]
Not sure, possibly created around version 1.1.6
