### ISSUE TITLE
Upgrades are overwriting customer-configured default documents and other content

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#246]
An upgrade should not touch files in Standarddokumenter and data items in Standardoppgaver, fasesjekkliste and so forth. Need to check this and change to Updatebehaviour=Skip for these items.

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/commit/5eb65d7332a66e3490f0528760b211819f83a531 and will be merged with #286
