### ISSUE TITLE
Support for copying templates to General folder and organize templates in folders

### ISSUE THREAD

**Issue by Osmund** [Puzzlepart/prosjektportalen365#251]
When using the get document template function (Hent dokumentmal) the document is created in root in the document library. If you are using Teams with a project site, you have to manually move the documents to the General folder for them to be visible in Teams. 

- [ ] It would be nice if you could choose if you would copy the document templates to library root or to the General folder.
- [ ] It would be nice if you could organize the document templates in folders in the template library. If you create a folder in the template library today, no templates is shown in the template selector.

**Comment by olemp** [comment]
> It would also be nice if you could organize the document templates in folders in the template library. If you create a folder in the template library today, no templates is shown in the template selector.

This could easily be included in the next version.

> It would be nice if you could choose if you would copy the document templates to library root or to the General folder.

We'll have a look at what we can do.

**Comment by olemp** [comment]
We’ll try to get this ready for the ‘1.2.1’ release @Osmund. We have no set date, but hopefully during the next few weeks.

**Comment by olemp** [comment]
We will include this in the next version!
