### ISSUE TITLE
Kan ikke legge til ny statusrapport under Prosjektstatus 

### ISSUE THREAD

**Issue by bomullspad** [Puzzlepart/prosjektportalen365#253]
**Describe the bug**
Alle brukere hos oss har problemer med å legge inn ny statusrapport. Detskjer ingenting dersom vi trykker på "Ny statusrapport" og "Rediger status" er grået ut. Gjelder alle brukere. Feilen ble oppdaget på fredag.  

**To Reproduce**
1. Gå inn på et prosjektområde og inn på Prosjektstatus. 
2. KLikk på "Ny statusrapport"
3. Se at ingenting skjer. 

**Screenshots**

![image](https://user-images.githubusercontent.com/37407287/76200176-75d30e00-61f1-11ea-855e-6b7b055c0a32.png)

**About your setup**
 - Browser Edge, Chrome, Firefox
 - Installed version 1.1.9

**Comment by olemp** [comment]
Hei @bomullspad,

Om statusen er publisert, kan den ikke redigeres.

Vi trenger noe mer informasjon, da vi ikke kjenner til dette problemet.

Får du i Chrome åpnet utviklerverktøy hvor det skal være en tab "Console"/"Konsoll", for så å trykke "Ny statusrapport"? Da bør det komme noen feilmeldinger i "konsollet. Disse kan du legge inn her i issuet.

**Comment by bomullspad** [comment]
![image](https://user-images.githubusercontent.com/37407287/76200912-b0897600-61f2-11ea-8902-892fa1ac97bc.png)

Her er en screenshot fra utviklerverktøy i Chrome når jeg trykker på Ny statusrapport. .

**Comment by olemp** [comment]
@bomullspad Kan dere oppgradere til 1.2.0 (https://github.com/Puzzlepart/prosjektportalen365/releases/tag/v1.2.0) for å se om det løser problemet?

**Comment by bomullspad** [comment]
Da har vi oppgradert til siste versjon, og det ser ut til å ha fikset problemet. Vår tenant er på norsk. 
Det står i releasen "Each project needs to edit project properties and save (you don't have to do any changes)."

Hvor finner jeg Project properties? Er det prosjektstatus?

**Comment by olemp** [comment]
> Da har vi oppgradert til siste versjon, og det ser ut til å ha fikset problemet. Vår tenant er på norsk.
> Det står i releasen "Each project needs to edit project properties and save (you don't have to do any changes)."
> 
> Hvor finner jeg Project properties? Er det prosjektstatus?

Så flott.

Det er webdelen _Prosjektinformasjon_ i høyre kolonne på prosjektforsiden.
