### ISSUE TITLE
Feilmeldinger ved installasjon av ny prosjektportal 

### ISSUE THREAD

**Issue by bomullspad** [Puzzlepart/prosjektportalen365#254]
**Describe the bug**
Vi ønsker å teste det å ha en egen prosjektportal for avsluttede prosjekter. Når jeg kjører installasjonsscriptet får jeg nye feilmeldinger hver gang. 

Er det noe spesielt som må gjøres før og underinstallasjon for å kunne opprette to prosjektportaler i samme tenant?

Vi har prøvd å installere siste versjon. Den eksisterende Prosjektportalen er også på siste versjon. 

**Screenshots**
Her er noen av feilmeldingene jeg har fått når jeg har installert PP:

[ERROR] Failed to install app packages to [https://...sharepoint.com/sites/aap]: 503 SERVICE UNAVAILABLE

[ERROR] Failed to create/update site design: The data is not available. The query may not have been executed.

[ERROR] Failed to create/update site scripts: The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

[ERROR] Failed to apply PnP templates to [https://...sharepoint.com/sites/Prosjektportalen-avsluttedeprosjekter]: Nullable object must have a value.

**Additional context**
Jeg har prøvd på 3-4 forskjellige SharePoint-sites.

**Comment by olemp** [comment]
Hei @bomullspad. Office 365 har ytelseproblemer i disse dager, og dette er relatert til det. Dette vil løse seg av seg selv når Microsoft får løst opp i flokene. Enn så lenge kan du prøve å kjøre scriptet om igjen til det fungerer. Det kan ta 5-6 forsøk før det går gjennom.
