### ISSUE TITLE
"Cannot read property 'departmentId' of undefined" when navigating in the hub menu

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#255]
**Describe the bug**
When navigating in the hub menu, you get an error saying "Cannot read property 'departmentId' of undefined". When clicking the menu item one more time, it works.

**To Reproduce**
1. Go to any page of projects or portfolio (?)
2. Click on one of the pages in the hub menu

**Expected behavior**
The browser should navigate to the page, not throw error

**Screenshots**

![depiderror](https://user-images.githubusercontent.com/1837390/77679567-00a65d80-6f93-11ea-8aa6-bf499defd912.png)

**About your setup**
 - Browser: Edge Chromium
 - Installed version: 1.2.0

**Additional context**

Is this related to the issue where you have to click twice to navigate sometimes? Looks like a SharePoint bug to me, but not sure. The 'departmentid' is used in queries on pages, right?

**Comment by olemp** [comment]
Confirmed as a SharePoint bug. Hopefully they'll roll out a fix soon!

**Comment by tarjeieo** [comment]
Seems to work in our tenant now actually. Probably fixed in TR then...
