### ISSUE TITLE
Possibility to add attachment in the "Tasks" module

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#256]
In the "Tasks" module that uses "Planner" it is not possible to add file attachments, only Sharepoint and links. In planner, for the same tasks, files can be added as attachments (upload from local PC)

Can this be added to PP365?

**Comment by olemp** [comment]
No, attachments must be uploaded to SharePoint. Planner have no separate storage.

And it's not "Planner", its's Planner 🚀
