### ISSUE TITLE
Possibility to set priority in the "Tasks" module

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#257]
In the "Tasks" module Priority is not an option and seems to be missing, can this be added to PP365?

**Comment by olemp** [comment]
What is the "Tasks" module?

**Comment by Remi749** [comment]
"Oppgaver siden" in SharePoint, Tasks page*

**Comment by olemp** [comment]
> In the "Tasks" module Priority is not an option and seems to be missing, can this be added to PP365?

No this is the default Planner web part by Microsoft, and we can't add new fields. The user can add labels or buckets though to "fake" priority.
