### ISSUE TITLE
Query for Risk Matrix in ProjectStatus showing opportunities, ignoring query

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#258]
"Risk or opportunities can be entered under uncertainty.
In the project status uncertainty matrix, opportunities are also presented as risks in the same matrix.

Suggestion: Enter a separate matrix for the opportunity page."

![image](https://user-images.githubusercontent.com/28678468/78031511-f0f89180-7363-11ea-8a32-299c8d3afa84.png)

![image](https://user-images.githubusercontent.com/28678468/78031542-f950cc80-7363-11ea-894c-8f1dc7057265.png)

I've looked into this and the default query that comes with the Risk Statussection in PP365 doesn't seem to work. Opportunities are showing with the following query:

`<OrderBy>
    <FieldRef Name="GtRiskFactor" Ascending="FALSE" />
</OrderBy>
<Where>
    <And>
        <Neq>
            <FieldRef Name="GtRiskStatus" />
            <Value Type="Text">Ikke lenger aktuell</Value>
        </Neq>
        <Eq>
            <FieldRef Name=\"ContentType\" />
            <Value Type=\"Computed\">Risiko</Value>
        </Eq>
    </And>
</Where>`

**Comment by Petterandre** [comment]
Similar issue in pp2 https://github.com/Puzzlepart/prosjektportalen/issues/739 - potentially related.

**Comment by olemp** [comment]
This was solved in https://github.com/Puzzlepart/prosjektportalen365/commit/4d19ea5e91d1fb1a7362b66b0d1e2af0c882672f
