### ISSUE TITLE
Opportunity not showing in Portfolio if marked to be shown.

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#259]
When an uncertainty is recorded, it's possible to select "View in portfolio"
Only uncertainties of type Risks are displayed at the portfolio level.

Suggestion alternatives
~~1. Display both risks  and opportunities in the portfolio overview. The module must then be called Uncertainty Overview and not Risk Overview~~
2. Eliminate the "Show in Portfolio" option on project opportunities. ✔️

**Comment by Petterandre** [comment]
Incompatibility with #269 - Pushed solution, will leave it to others to make the choice. Personally prefer 269

**Comment by olemp** [comment]
> Incompatibility with #269 - Pushed solution, will leave it to others to make the choice. Personally prefer 269

Create a PR and I can look 🚀
