### ISSUE TITLE
Suggestion: Remove Planner web part on the front page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#260]
**Is your feature request related to a problem? Please describe.**
Visitors does not have access to Planner, and will receive an error on the front page.

**Describe the solution you'd like**
Suggest to remove the web part from the front page. Keep the link in the left menu. Can even consider adding another page with Planner statistics details?

We could also consider adding this as a default "extension" that can be toggled on a per-project or per-organization basis.

**Comment by olemp** [comment]
I don't think we should remove it.

**Comment by tarjeieo** [comment]
Your input here @pzljanb?

**Comment by pzljanb** [comment]
I think we should keep the front page as is.
(I assume most of the users don't have this problem with vistors access.)

But it's a good idea to keep is an a extension. Develop it and put it in 'Prosjekttillegg'

**Comment by olemp** [comment]
We need to find out if people are using it first. I think this encriches the frontpage and makes it look more alive, and not just full of lists and libraries, and text.

**Comment by pzljanb** [comment]
As discussed;
Lest keep the front page as is.
(Most users don't have this problem with vistors access.)

Add an extension for a Home page without Planner part and have this included in the PP365 package. Make the extension Visible and disabled by default.

**Comment by olemp** [comment]
> Make the extension Visible and disabled by default.

https://github.com/Puzzlepart/prosjektportalen365/issues/264
