### ISSUE TITLE
Spørsmål ang prosjektområder 

### ISSUE THREAD

**Issue by bomullspad** [Puzzlepart/prosjektportalen365#261]
**Describe the bug**
Hei! Håper dere kan svare oss på et lite spørsmål. Vi har opprettet en egen Prosjektportal for avsluttede prosjekter. Når vi endrer Hub-tilknytning på et prosjektområde fra prosjektportalen til den nye prosjektportalen for avsluttede prosjekter, blir ikke prisjektet flyttet ordentlig. 

Inne i prosjekt-rommet ser man at det er "Prosjektportal for avsluttede prosjekter" som kommer opp i toppmenyen. Men den befinner seg fortsatt i oversikten i Prosjektportalen365, samtidig som det ikke er noe som helst i den nye portalen.

Hva mer enn å endre hub-tilknytning må til for å flytte et prosjekt mellom prosjektportaler?

På skjermbildet under ser man at Avsluttede prosjekter er øverst i prosjektrommet.
![image](https://user-images.githubusercontent.com/37407287/79233095-a77e6b00-7e68-11ea-9e9e-ea7f43dac155.png)

Inne på prosjektportalen for avsluttede prosjekter finner ingen info om prosjektet annet enn at det ble opprettet. 
![image](https://user-images.githubusercontent.com/37407287/79233631-6cc90280-7e69-11ea-9b83-65b444222221.png)

**Comment by olemp** [comment]
Hei,

Prosjektportalen 365 er ikke lagt opp til å gjøre dette veldig enkelt slik løsningen er i dag.

Egenskapene for prosjektene ligger i en liste `Prosjekter` på porteføljeområdet. Hvert prosjekt har et listeelement i denne listen. I tillegg har et prosjekt 0 eller flere listelementer i listen `Prosjektstatus`. For å flytte over prosjektet fullstendig, må disse listeelementene flyttes over til den nye porteføljen manuelt.
