### ISSUE TITLE
Installation fails with currently bundled pnp version

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#263]
Need to upgrade to latest pnp powershell and release

**Comment by olemp** [comment]
> Need to upgrade to latest pnp powershell and release

Error details? Are you sure it's not related to the service unavailability issues?

**Comment by tarjeieo** [comment]
*value cannot be null* when applying portfolio.pnp. Seen it twice now, and since I don't see any drawbacks of upgrading I don't see why not :)

**Comment by olemp** [comment]
> _The 'value' argument cannot be null_ when applying portfolio.pnp. Seen it twice now, and since I don't see any drawbacks of upgrading I don't see why not :)
> 
> ```
> Message          : The 'value' argument cannot be null. Parameter name: value
> Stacktrace       :    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
>                       at SharePointPnP.PowerShell.Commands.Provisioning.Site.ApplyProvisioningTemplate.ExecuteCmdlet()
>                       at SharePointPnP.PowerShell.Commands.PnPCmdlet.ProcessRecord()
> ScriptLineNumber : 275
> ```

No drawbacks at all! It might be related to the service unavailability issues, but it doesn't hurt to upgrade to latest PnP PowerShell.

**Comment by olemp** [comment]
Due to service unavailability issues. Closing.
