### ISSUE TITLE
Missing phase metadata in the phase checklist for new projects

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen365#265]
**Describe the bug**
The phase metadata is missing in the phase checklist for newly created projects. See the following screenshot.
![image](https://user-images.githubusercontent.com/29536394/80375033-e31d2a00-8897-11ea-9008-9d691a9e287a.png)

The phase metadata is present in the source list, but for some reason not copied along with the rest of the list items.

The tenant has two instances of PP365 installed, where the first instance works as expected. The second one is having the issue with missing metadata in the phase checklist.

Any idea why the list items are copied, but the phase metadata is missing?

**About your setup**

Chrome / Edge Chromium
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]
1.2.0

**Comment by olemp** [comment]
@marlowandre Is there any errors in console?

**Comment by marlowandre** [comment]
Quite a few. The errors start at the step "Legger på mal Standardmal". Here's a snip:
![image](https://user-images.githubusercontent.com/29536394/80377568-bbc85c00-889b-11ea-940b-2c3f8c71081b.png).

Here's a snip of the error that appears when its copying the phase checklist:
![image](https://user-images.githubusercontent.com/29536394/80377640-d8fd2a80-889b-11ea-963c-8bfa15ed1aff.png)

**Comment by olemp** [comment]
> Quite a few. The errors start at the step "Legger på mal Standardmal". Here's a snip:
> ![image](https://user-images.githubusercontent.com/29536394/80377568-bbc85c00-889b-11ea-940b-2c3f8c71081b.png).
> 
> Here's a snip of the error that appears when its copying the phase checklist:
> ![image](https://user-images.githubusercontent.com/29536394/80377640-d8fd2a80-889b-11ea-963c-8bfa15ed1aff.png)

That's what I thought. It needs the `TaxCatchAll` property to set the phase. Is the list created manually or are you using the one from the installation?

**Comment by marlowandre** [comment]
Using the installation.

**Comment by olemp** [comment]
> Using the installation.

Have had this happen once earlier. What I did was recreate the list. First you could try to go the list, go to field "Fase", and just save. That might solve it.

**Comment by marlowandre** [comment]
Just saving the column didn't help. I deleted the list and applied the PnPProvisioningTemplate again to recreate the list. That solved it 🙂

Thanks for the help 🙂👍
