### ISSUE TITLE
Show only benefits(gevinster) that are toggled as "Show at portfolio level"

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#268]
**Is your feature request related to a problem? Please describe.**
Showing all benefits at portfolio level can create a bit too detailed/too many items.

**Describe the solution you'd like**
Add the column "Show in portfolio" to benefits items and to data queries

**Comment by olemp** [comment]
Please note that we're using data sources for portfolio aggregations.

/Lists/Datakilder/AllItems.aspx

![image](https://user-images.githubusercontent.com/7606007/80708549-2b348a80-8aec-11ea-81f0-46f078935ee8.png)

![image](https://user-images.githubusercontent.com/7606007/80708656-54edb180-8aec-11ea-98f3-7e4f5e94cc87.png)

So we can keep the "all" data source, and add a new which filters on **Show in portfolio** that we select as default.

You can create a draft PR and we can work on this together if you like. We're finally getting some good use of this data source functionality! 🚀

**Comment by tarjeieo** [comment]
That's brilliant! <3 Means that we can actually create another data source for this instead of just overwriting the default? Awesome

**Comment by olemp** [comment]
> That's brilliant! <3 Means that we can actually create another data source for this instead of just overwriting the default? Awesome

Yes we can!

**Comment by olemp** [comment]
Included as part of https://github.com/Puzzlepart/prosjektportalen365/pull/286.

Had to do some adjustments to this PR to make it work.
