### ISSUE TITLE
Include References in "Planneroppgaver"

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#274]
**Is your feature request related to a problem? Please describe.**
The planner tasks are often related to either a document or a instruction.
To have the neccessary and correct referancec I would like to have the possibility to add references (attachments and/or links) to a Planner task thru the list "Planneroppgaver" 

**Describe the solution you'd like**
I would like to have the possibility to add references (attachments and/or links) to a Planner task thru the list "Planneroppgaver"

**Comment by olemp** [comment]
It's doable, but I would prefer to do this without an extra list.

This is the format of **references** when creating a new task (see https://docs.microsoft.com/en-gb/graph/api/plannertaskdetails-update?view=graph-rest-1.0&tabs=http):

```
    references: {
      "https%3A//contoso%2Esharepoint%2Ecom/teams/agile/documents/AnnualReport%2Epptx":
      {
        "@odata.type": "microsoft.graph.externalReference",
        "alias": "Agile Team Annual Report",
        "lastModifiedDateTime": "2015-09-21T17:45:12.039Z",
        "previewPriority": "0009005756397228702",
        "type": "PowerPoint"
      }
    }
```

We can do it by adding another field for **references**. What we need in this field is at least **url** (that's the object key), **alias** and **type**.

To support several references we should separate values with `|` or `;`.

We can either do `url,alias,type|url,alias,type` or `url=url,alias=alias,type=type|url=url,alias=alias,type=type`.

cc @pzljanb @okms @tarjeieo

**Comment by olemp** [comment]
Going for alternativ 1, type will default to `Other`.

Will add a field `GtAttachments`.
