### ISSUE TITLE
Milestones and timeline (Gannt) for PP365 similar to PP2.0

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#275]
**Describe the solution you'd like**
Customer question from an assist issue:

> Det ble tidligere opplyst om at milepæler og tidslinje (Gannt) skulle komme tilbake som funksjonalitet i Prosjektportalen.
> Hva er status på dette arbeidet?
> Vil det være noen sammenheng mellom tidslinjen og prosjektleveransene?

Our answer from the assist issue:

> Vi har ikke konkrete planer om milepæler og tidslinje i PP365. Vi har håpet og håper fortsatt at dette er noe Microsoft kan levere, f.eks. ved å visualisere Planner-oppgaver i en tidslinjevisning vi kan bruke i portalen. Vi har diskutert noe rundt å implementere støtte for dette, men foreløpig er konklusjonen at det vil kreve mye skreddersøm å utvikle og det fører også til at det blir mer å forvalte.
> 
> Vi er forsåvidt åpne for innspill rundt dette og hvordan en slik funksjon bør fungere, og jeg vil ikke si at dette er noe vi aldri kommer til å få på plass, men det hadde altså vært nyttig om Microsoft hadde levert noe vi kunne bruke som utgangspunkt.

**Additional context**
This issue is created based on a customer question through our assist channel about missing functionality in PP365 compared to PP2.0 and wether this will be implemented in future releases for PP365.

**Comment by olemp** [comment]
No plans for this as I'm aware of https://github.com/Puzzlepart/prosjektportalen365/issues/266
