### ISSUE TITLE
Switch in Risk section of Statusreport missing

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#279]
**Describe the bug**
The switch to toggle between values before/ after measures is missing

**To Reproduce**
Missing on statuspage

1. Go to 'prosjektstatus'
2. Scroll down to 'Risiko seksjonen'
4. Look for toggelswitch

**Comment by olemp** [comment]
@pzljanb When toggling to show post action, do we want to show only post action or also original? 

![image](https://user-images.githubusercontent.com/7606007/90244299-c6016c80-de30-11ea-832c-bee94e3a9205.png)

**Comment by olemp** [comment]
> @pzljanb When toggling to show post action, do we want to show only post action or also original?
> 
> ![image](https://user-images.githubusercontent.com/7606007/90244299-c6016c80-de30-11ea-832c-bee94e3a9205.png)

@tarjeieo

**Comment by olemp** [comment]
> > @pzljanb When toggling to show post action, do we want to show only post action or also original?
> > ![image](https://user-images.githubusercontent.com/7606007/90244299-c6016c80-de30-11ea-832c-bee94e3a9205.png)
> 
> @tarjeieo

bump @pzljanb

**Comment by pzljanb** [comment]
Toggle is the same behavior as PP2.0, thats the easy solution.

If we should include both post action and original action; we need to separate post from original by colouring the circles in some kind of nice way.

**Comment by tarjeieo** [comment]
After toggle, I think we should only show post actions

**Comment by olemp** [comment]
Awesome. That's the approach done in https://github.com/Puzzlepart/prosjektportalen365/pull/293. Will be included in next release then.
