### ISSUE TITLE
Query used in Risiko section fails

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#281]
**Describe the bug**
The query in 'Risikoseksjon' configured in 'Statusseksjoner' seems not to be executed.

**To Reproduce**

1. Go to 'Statusseksjoner/Risikoseksjon'
2. Verify query
3. Go to 'Prosjektstatus'
4. Verify result is matching the query

**Expected behavior**
Query should be executed and result should be printed accordingly

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/pull/282
