### ISSUE TITLE
Wizard fails after aplying site design in v1.2.2 

### ISSUE THREAD

**Issue by martinfy** [Puzzlepart/prosjektportalen365#283]
**Describe the bug**
TypeError: Cannot read property 'ID' of undefined

**To Reproduce**
1. Created new nb-no team site from SP admin center
2. Associated site with Prosjektportalen hub
3. Applied site design
4. Wizard triggers, but fails with error "TypeError: Cannot read property 'ID' of undefined"

**Screenshots**

![image](https://user-images.githubusercontent.com/35626603/85553554-5cc95e00-b624-11ea-9437-295c08071aa9.png)

**About your setup**

- Browser: Edge Chromium
- Installed version 1.2.2

**Comment by olemp** [comment]
Thanks for reporting! This issue is now resolved.

The issue was that custom template(s) was referencing content type `Milepæl` which is no longer included in site design. See  https://github.com/Puzzlepart/prosjektportalen365/issues/266.
