### ISSUE TITLE
English version of PP

### ISSUE THREAD

**Issue by THVitec** [Puzzlepart/prosjektportalen365#291]
Category
[ ] Enhancement

[ ] Bug

[X] Question

Environment
[X] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

Browser
[X] Chrome

[X] Internet Explorer

[X] Edge

[X] Safari

[X] Other

Expected / Desired Behavior / Question
Hi!
Is there a current english version of PP available? Any possibilities of seeing an english version in the near future?
Ofcourse one could always translate the src or do some post configuration/translation but then you won't be able to apply future updates I reckon.

Thanks in advance!

**Comment by olemp** [comment]
We are looking at releasing an English version of the project portal, but I cannot give an exact timetable to when it will be released.

Its possible to install as many instances of PP365 as you need in your tenant. Each instance will be a hub site with associated project sites (groups)

You can translate parts of the project templates, but currently its not recommended to invest heavily in doing so. Any multilingual version of PP will use resource files not present in the current release
