### ISSUE TITLE
Risk matrix missing i Status report

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#294]
**Describe the bug**
Risk matrix is not visible in "status rapport"

**To Reproduce**
1. ENter a Installation of Prosjektportalen v.1.2.2
2. Click on 'Usikkerhet'
3. Add a new 'Usikkerhet'
4. Click on 'Prosjektstatus'
5. If not created, create 'Ny statusrapport'
6. Scroll down to the section 'Risiko'
7. The risk matrix will not be visible in the section.

**Expected behavior**
The riss matrix should be visible in the section.

**Screenshots**
Correct behavior is visible in attached image
![image](https://user-images.githubusercontent.com/58074707/90011642-3cbc2f80-dca2-11ea-8b53-1a48fa565f29.png)

**About your setup**
- Installed version 1.2.2

**Additional context**
This is working as expected in v.1.2.0 (and v.1.2.1?)

**Comment by olemp** [comment]
@pzljanb The issue was the syntax of the view query for the Risk section. Fix will be included in `v1.2.3`.

![image](https://user-images.githubusercontent.com/7606007/90239689-3c4da100-de28-11ea-8289-499e0f8fb3d2.png)

The correct is:

```xml
<OrderBy>
    <FieldRef Name="GtRiskFactor" Ascending="FALSE" />
</OrderBy>
<Where>
    <And>
        <Neq>
            <FieldRef Name="GtRiskStatus" />
            <Value Type="Text">Ikke lenger aktuell</Value>
        </Neq>
        <Eq>
            <FieldRef Name="ContentType" />
            <Value Type="Computed">Risiko</Value>
        </Eq>
    </And>
</Where>
```

The issue was the use of `\"`. See https://github.com/Puzzlepart/prosjektportalen365/pull/296/files.

**Comment by pzljanb** [comment]
In meantime (until upgrading to 1.2.3) I assume that installations running on version 1.2.2 can manually be updated with this correct code to be working properly if needed?

**Comment by olemp** [comment]
> In meantime (until upgrading to 1.2.3) I assume that installations running on version 1.2.2 can manually be updated with this correct code to be working properly if needed?

Yes! Exactly why I wrote such a detailed comment 🎉
