### ISSUE TITLE
Risks with 'Ikke lenger aktuell' shows up in 'Risikooversikt' on Portfolio level

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#297]
**Describe the bug**
'Risikooversikt' on Portfolio level is not excluding risks checked with 'Status usikkerhet' = 'Ikke aktuell'

**To Reproduce**
A Risk checked with:
'Vis i Portefølje' = Yes  AND 'Status usikkerhet' = 'Identifisert' 
will be shown in 'Risikooversikt' on Portfolio level AND in the Risk matrix within the ' Status report'
If the same Risk is changed to 'Status usikkerhet' = 'Ikke aktuell', 
it will be removed from Risk matrix in the 'Status Report' but not from the 'Risikooversikt' on Portfolio level.

**Expected behavior**
The behavior should be equal for these two dispalys.
E.g.  'Risikooversikt' on Portfolio level should not include risks tha its checked with 'Status usikkerhet' = 'Ikke aktuell'

**Comment by olemp** [comment]
Query updated to:

`ContentTypeId:0x0100A87AE71CBF2643A6BC9D0948BD2EE89701* DepartmentId:{{sitecollectionid}} GtShowInPortfolioOWSBOOL:1 -GtRiskStatusOWSCHCS="Ikke lenger aktuell"`

Will be included in next release.
