### ISSUE TITLE
Feilmelding ved opprettelse av prosjekt

### ISSUE THREAD

**Issue by gselvag** [Puzzlepart/prosjektportalen365#299]
**Describe the bug**
Jeg får opp følgende feilmelding ved opprettelse av prosjektområde:

**"Det skjedde en feil under initialisering av prosjektegenskaper"**
"The value does not fall under expected range"

Hvilke verdier refereres til her og hvordan løser jeg problemet?

**To Reproduce**

1. Opprett prosjektområde 

**Screenshots**
![Annotation 2020-08-25 052418](https://user-images.githubusercontent.com/64530840/91119358-4460d880-e693-11ea-8b1d-3f2bd4b8497d.png)

**About your setup**
- Chrome Browser
- Installed version 1.2.2.

**Comment by tarjeieo** [comment]
Hei, beklager dårlig oppfølging på denne. Har du kommet noe videre her? Du kan evt prøve med siste versjon som ligger ute nå. Ellers er vel den mest typiske feilen at område har fått engelsk språk og derfor feiler det, men kan ikke si den feilmeldingen matcher dette egentlig.

**Comment by tarjeieo** [comment]
Antar denne er fikset i 1.2.3 eller 1.2.4 som kommer ila dagen
