### ISSUE TITLE
Add description to elements in the projectportal configuration page

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#300]
**Describe the solution you'd like**
Add description to elements in the projectportal configuration page.

Improvement example:
![image](https://user-images.githubusercontent.com/28678468/92474289-e0cec300-f1db-11ea-8fde-8f73595a8ec9.png)

**Comment by tarjeieo** [comment]
See new web part design internally; /sites/ppintern/SitePages/Konfigurasjon.aspx. Suggest that we update the texts on that page.
![image](https://user-images.githubusercontent.com/1837390/92474490-373c0180-f1dc-11ea-906a-a18f613cc04f.png)

**Comment by olemp** [comment]
Love this idea @Remi749 @tarjeieo 💯

**Comment by Petterandre** [comment]
![image](https://user-images.githubusercontent.com/10527497/92589897-91e86280-f29b-11ea-834a-5a4336b4a694.png)

I would like some input towards the actual descriptions. The ones I have currently are rather lacking.

**Comment by olemp** [comment]
> ![image](https://user-images.githubusercontent.com/10527497/92589897-91e86280-f29b-11ea-834a-5a4336b4a694.png)
> 
> I would like some input regarding the descriptions. The ones I have currently are rather lacking.

It's a great start! @pzljanb @tarjeieo  any input?

**Comment by Petterandre** [comment]
Went through items with Jan, PR coming up.
