### ISSUE TITLE
Select view dropdown in portfolio overview is not displayed for viewers

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#304]
**Describe the bug**
Select view dropdown in portfolio overview is not displayed for viewers

**To Reproduce**
Go to portoflio overview as a visitor.

**Expected behavior**
Should be displayed for everyone with access to the portfolio site. 

**Version**
1.2.2

**Comment by Petterandre** [comment]
![image](https://user-images.githubusercontent.com/10527497/93215364-95ca2800-f766-11ea-852d-884831a776fa.png)
