### ISSUE TITLE
Test av 1.2.3

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#312]
## Testing the new version before creating new release

Checklist for testing the additions, changes and fixes

# Version 1.2.3

### Descriptions on configuration page #301

**How to test:**

- [ ] Apply ClientSidePages template, view /SitePages/Konfigurasjon.aspx

### New group "Porteføljeinnsyn". Grants users in this group insight into all projects in the portfolio #305

**How to test:**

- [ ] Add user to "Porteføljeinnsyn" group.
- [ ] View "Porteføljeoversikt"

### "Porteføljeinnsyn" button on configuration page for adding users to the group #306

**How to test:**

- [ ] Go to {site}/SitePages/Konfigurasjon.aspx
- [ ] Add a user to the group
- [ ] Check Porteføljeoversikt if projects are visible

### Risk matrix toggle: Before and after risk reduction measures #293

**How to test:**

- [ ] ...

### Support for planner tasks references/attachments #287

**How to test:**

- [ ] ...

### View in portfolio overview was not changeable for non-admin users #308

- [ ] Have a regular user view Portfolio Overview to see if he/she can choose view

### Projects set to Avsluttet are no longer visible on the front page #307

- [ ] Set a project status to "Avsluttet"
- [ ] Go to the front page to see if it is not showing

### Disabled "Ny statusrapport" when a report is unpublished. #309

**How to test:**

- [ ] 1. Create a new report.
- [ ] 2. The button "Ny statusrapport" will stay disabled until you publish the report.
- [ ] 3. The button will also be disabled if you navigate between other reports while having an unpublished report
- [ ] 4. Create a new report and the button should be disabeled once again
- [ ] 5. Select an older published report.
- [ ] 6. Verify that the button "Ny statusrapport" stays disabled

**Comment by pzljanb** [comment]
På mange måter enig med @Petterandre  i at denne er bra
+Oversiktlig
+Gir oss full kontroll på testingen
det negative på den annen side
-Mye manuell jobb
-Mistenker at vi fort kan miste oversikten

**Comment by Remi749** [comment]
Vi tar i bruk #313 og lukker denne
