### ISSUE TITLE
Required: true in FieldRefs on the Phase field in Project Template does not set the Phase required field 

### ISSUE THREAD

**Issue by jklevel** [Puzzlepart/prosjektportalen365#320]
Required: true in FieldRefs on the Phase field in Project Template does not set the Phase required field

### Steps to reproduce the behavior:

1. Change project template field settings for Documents / Phase to:
```json
{
  "Title": "Documents",
  "Description": "",
  "Template": 101,
  "ContentTypesEnabled": false,
  "AdditionalSettings": {
    "EnableVersioning": true
  },
  "FieldRefs": [
    {
      "ID": "325543a5-815d-485d-a9a5-e0773ad762e9",
      "Name": "GtProjectPhase",
      "Required": true,
      "DisplayName": "Phase"
    }
  ]
}
```
2. Save and check in project templates
3. Create project room based on modified template
4. The Phase field is not required

Expects the Phase field in Documents to be required

**Comment by tarjeieo** [comment]
Jeg ser samme oppførsel her, men jeg har sett det har fungert på andre lister... Hmm...
