### ISSUE TITLE
Ability to export project status report as snapshot/image/PDF

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#324]
**Is your feature request related to a problem? Please describe.**
Project snapshotting is useful for persisting the full project status page, including list data. We should look into how this can be solved.

**Describe the solution you'd like**
When a report is published, we could also snapshot the report (as PDF or image) and save it as an attachment to the published status report.

**Comment by tarjeieo** [comment]
@pettersh - related to this, should we also hide lists in the statuspage when browsing old status reports? Since list data is always showing latest

**Comment by Petterandre** [comment]
Considering that the list data is always up to date, yes. I also realized we should date stamp the snapshots with more than file title.

**Comment by tarjeieo** [comment]
Good point, agreed! 💥
