### ISSUE TITLE
Bug: Prosjektinnsyn does not work for users added as part of AD-group

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#332]
**Describe the bug**
The new Prosjektinnsyn SP group should give access to see the whole portfolio. Looks like this is not working when an AD group is added to the SP group.

**To Reproduce**

1. Add an AD group to Prosjektinnsyn SP group
2. Check that the user you're testing with does not see all projects

**Expected behavior**
The users should see all projects when they are added to Prosjektinnsyn, even through AD-groups.

**Comment by tarjeieo** [comment]
Might need to do something in the lines of https://stackoverflow.com/questions/43654587/how-to-check-if-user-belongs-to-a-sharepoint-ad-group-or-not-using-rest-javascri

**Comment by olemp** [comment]
Solved by #338
