### ISSUE TITLE
Improve logging of errors during project creation

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#336]
**Is your feature request related to a problem? Please describe.**
When creating new projects, and e.g. using a custom template, errors might happen. We should improve the logging in these cases. Currently the errors can be quite hard to comprehend and analyse. 

Example: Cannot find ID of undefined.

**Describe the solution you'd like**
A better error message saying
* Which step the error happened in
* For which element/component/list/field the error happened for
* **Also log the error message to the central list Lists/Logg**

**Dependent on**
#865

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/pull/896
