### ISSUE TITLE
Install log not updated in v 1.2.4

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#348]
**Describe the bug**
The changelog does not affect the upgrade to v1.2.4 
Similar behavior on the "Oppsett av prosjektområde" dialog box.

**To Reproduce**
Have a look at the install log of https://puzzlepart.sharepoint.com/sites/pp365/Lists/Installasjonslogg/AllItems.aspx

**Expected behavior**
The log should be updated with the corresponding version number

![image](https://user-images.githubusercontent.com/58074707/100059456-66e9c580-2e2b-11eb-91f9-4ec52a8ef642.png)

**Comment by olemp** [comment]
We've updated to 1.2.4. CI is running now https://github.com/Puzzlepart/prosjektportalen365/actions/runs/380640780. This will also fix the resource name bug.

**Comment by olemp** [comment]
@pzljanb Ready to test again <3

![image](https://user-images.githubusercontent.com/7606007/100082250-4a0fbb00-2e48-11eb-92ca-e36040b7a76e.png)
