### ISSUE TITLE
Display name of default extension incorrect

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#349]
**Describe the bug**
Display Name not showing

**To Reproduce**
Have a look at the list: https://puzzlepart.sharepoint.com/sites/pp365/Prosjekttillegg/Forms/AllItems.aspx

**Expected behavior**
DisplayName should be "Standard"

**Screenshots**

![image](https://user-images.githubusercontent.com/58074707/100059102-ceebdc00-2e2a-11eb-9346-2844adb49926.png)

**About your setup**
https://puzzlepart.sharepoint.com/sites/pp365/Prosjekttillegg/Forms/AllItems.aspx

#328

**Comment by Petterandre** [comment]
![image](https://user-images.githubusercontent.com/10527497/100061544-80404100-2e2e-11eb-8864-488d0f45f268.png)

Does exist in resource file. Is the resource file not applied when using -Upgrade ?

**Comment by olemp** [comment]
It's pebmac, fixed in https://github.com/Puzzlepart/prosjektportalen365/commit/4ad225aae9c4e1b68ab4572f8a9bac2f5370c8bd

**Comment by olemp** [comment]
CI is building @pzljanb https://github.com/Puzzlepart/prosjektportalen365/actions/runs/380614247 Upgrade ready in 20-30 minutes.
