### ISSUE TITLE
Page 'Prosjektstatus.aspx' unable to load on projects without any statusreports

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#350]
**Describe the bug**
Prosjektstatus.aspx not loading properly on newly created projects. (Created after upgrade to v1.2.4)
https://puzzlepart.sharepoint.com/sites/Lykkepillen124c/SitePages/Prosjektstatus.aspx

- Same faulty behavior experienced also on older projects without any status reports.
https://puzzlepart.sharepoint.com/sites/Trolljegerne/SitePages/Prosjektstatus.aspx

- Loading correctly on older projects with an existing statusreport from before v1.2.4
https://puzzlepart.sharepoint.com/sites/Endringavformueskatt/SitePages/Prosjektstatus.aspx#selectedReport=11

**To Reproduce**
Visit the different locations described above

**Expected behavior**
Prosjektstatus page should open correct every time

**About your setup**

- Browser [Chrome]
- Installed version https://puzzlepart.sharepoint.com/sites/pp365

**Comment by olemp** [comment]
CI is building as we speak. Should be ready for testing in the test environment shortly (approx 30 minutes).

**Comment by olemp** [comment]
Should now be fixed. Testable in test env.
