### ISSUE TITLE
Portfolio content not limited to access level

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#352]
**Describe the bug**
Users granted access to information from all projects independent of membership status in projects or project type (public / private)
The group Porteføljeinnsyn should be used to give access to information from projects wher ethe user have no access (like private projects), but this group seems to be passed and access is given regardless of your membership status.

**To Reproduce**
Verify with the user 'Christine MacDonald-Berger'
Check the:
 - Group 'Porteføljeinnsyn'  -> Empty
 - Project Lykkepillen124d  -> Christine--- is a member of this private project
 - Project Lykkepillen124c  -> Christine--- is NOT a member of this private project
 - Project Endring av formueskatt -> Is a public project

Christine has access to all projects in Porteføljeoversikt.

**Expected behavior**
Christine should have a lot less access. And the indications on Tittel column should be accordingly.

**Related issues**
#332 
#243

**Comment by olemp** [comment]
See #354 

> In order for #332 to work OnlyAllowMembersViewMembership needs to be set to true for the Porteføljeinnsyn group in our template.

Fixed for our test tenant, and confirmed working.
