### ISSUE TITLE
Cannot exit portfolio filter mode

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#353]
**Describe the bug**
When using the portfolio filter functionality, there is no way to exit the dialog in 1.2.4

**To Reproduce**

1. Go to Portoflio overview
2. Click on Filter button
3. Try to exit

**Expected behavior**
Close the dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/1837390/100366940-cc8faa80-3001-11eb-8df4-e87f6499b4e5.png)

**About your setup**

- Browser [e.g. chrome, safari]: Edge chromium
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.2.4

**Additional context**

I think it would be nice to have both a close-button, plus allow clicking outside the dialog to close it.

**Comment by Remi749** [comment]
Probable solution:

Add the following props to the FilterPanel component

`onLightDismissClick={() => this.setState({ showFilterPanel: false })}`
`isLightDismiss`

it wil be dismissable by clicking outside of the filter panel
