### ISSUE TITLE
Customer/ local installation configuration overview

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#358]
**Is your feature request related to a problem? Please describe.**
After installation of PP365 the customer is told that local lists e.g. 'Fasesjekkliste' can be added and configured to make the PP365 installation "richer" and more "spot on" for the local needs.

Due to the architecture of PP365 default lists (like the 'Fasesjekkliste) this is a bit tricky for the customer.

**Describe the solution you'd like**
Extend the page 'Konfigurasjon av Prosjektportalen' with 2 more sections:
- Standard content (move content elements from todays page into this section)
- Customer content, and make existing lists visible 
     - Fasesjekkliste
     - Planneroppgaver
     - Interessenttregister

Further on, the customer can add links to his locally created lists into the Customer content

**Additional context**

**Comment by tarjeieo** [comment]
Adding on to this, it would be really nice with a web part to list all available lists from "List contents" list, as a separate web part on the "Konfigurasjon av Prosjektportalen" page. Should be a really simple web part that lists all standardinnhold-lists with info and links to their lists.

**Comment by pzljanb** [comment]
This issue is no longer actual due to unhidden list from PP installation (Planner and Fasesjekkliste)
