### ISSUE TITLE
Library 'Prosjektmaler' missing version history

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#359]
**Describe the bug**
The document library 'Prosjektmaler' have version history disabled.

**To Reproduce**
Have a look at the settings on the library

**Expected behavior**
Version history should be enabled on all lists and libraries containing some sort of cofiguration.

![image](https://user-images.githubusercontent.com/58074707/101771929-f6a99800-3aea-11eb-88c0-3f4054792fa9.png)

**About your setup**
1.2.4

**Comment by tarjeieo** [comment]
Fixed as part of next release

**Comment by pzljanb** [comment]
Have not identified a PR for this change but have verified the setting in a newly cretaed project in 1.2.6 of PP365
- [ ] Upgrade/ install a PP365 installation on v1.2.6
- [ ] Verify versioncontrol is enabled in the library 'Prosjhektmaler'

**Comment by pzljanb** [comment]
Seems to be correct :-)
