### ISSUE TITLE
Not possible to apply template with latest PnP PowerShell

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#362]
**Describe the bug**
When trying to apply with the latest version of PnP PowerShell, we're getting the following error:
[ERROR] Failed to apply PnP templates to [https://xxx.sharepoint.com/sites/xxx]: Your template contains artifacts that require an access token. Please provide consent to the PnP Management Shell application first by executing: Register-PnPManagementShellAccess

See related: https://github.com/pnp/PnP-Sites-Core/issues/2750. Seems to be an issue with PnP:Header, which we're using for all portoflio clientsidepages.

**To Reproduce**

1. Update SharePointPnPPowerShellOnline to latest
2. Try to install/update

**Expected behavior**
Should be possible to install with latest PnP

**About your setup**

- Installed version 1.2.4

**Comment by tarjeieo** [comment]
Update: Had to revert to June Intermediate 2 to get around this bug. Can ofc also use the bundled version (which I believe is Dec 2019)

**Comment by olemp** [comment]
@tarjeieo Can you test on the PR #377.

If you gave [GitHub CLI](https://cli.github.com/) just use:

```powershell
gh pr checkout 377
```
