### ISSUE TITLE
Issue with syncing custom fields to projects

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#365]
**Describe the bug**
Changes to fields are not populated to projects

**To Reproduce**

1. Create a new choice field and add to the Project content type
2. Create a new project
3. Edit metadata of new project
4. Change the field at the hub level (e.g. add a choice to a choice field)
5. Observe that the field is not updated at the project level

**Expected behavior**
The field should be changed everywhere, at least after the sync has been performed

**About your setup**

- Browser: **Edge chromium**
- Installed version: **1.2.4**

**Comment by tarjeieo** [comment]
AFAIK this is related to that the changes are not catched by the sync method, right @olemp ? Looks like we're only adding new fields, not catching updates to existing fields, e.g. new choices in a choice field?

**Comment by olemp** [comment]
This is correct. If the field already exists on the project properties list on the project site/group, it's not updated. There's no good way to update the field, and it can't be recreated (as the data will be lost). The field can't be updated with field XML it seems, so we need to update properties independently meaning we need to set which properties to update.

The complexity is quite high.

**Comment by tarjeieo** [comment]
Let's skip updates of existing choice field changes for now - and keep this issue related to the issue which the title indicates: Can't sync custom fields when adding to a custom project content type. TemplateParameter-property is not set in the code, and it defaults to blank which again makes the sync job default to the default CT

**Comment by olemp** [comment]
We'll keep it open until fix is confirmed working.

**Comment by olemp** [comment]
Fixed in #378
