### ISSUE TITLE
Error Could not load file

### ISSUE THREAD

**Issue by tonjewaasjo** [Puzzlepart/prosjektportalen365#366]
1. Using the latest version of SharePoint Online Management Shell and has also tried latest version of PowerShell. Both as administrator
2. Run .\Install.ps1 -Url "https://....sharepoint.com/sites/prosjektportalen" -TenantAppCatalogUrl "https://....sharepoint.com/sites/appcatalog" where ... is name of tentant
3. Answer R on security warning for Install.ps1 and SharePointPnP.PowerShell.Online.Commands.Format.ps1xml
4. Get error: Import-Module : Could not load file or assembly 'file:///C:\Users\tonwa\Downloads\prosjektportalen365-.2.4.b1e69cc\SharePointPnPPowerShellOnline\SharePointPnP.PowerShell.Online.Commands.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

**Comment by tarjeieo** [comment]
I belive this is caused by the zip-file being blocked by your operating system. Check this; https://github.com/Puzzlepart/prosjektportalen365/wiki/Feils%C3%B8king-installasjon#du-st%C3%B8ter-p%C3%A5-sikkerhetsadvarselen-run-only-scripts-that-you-trust--eller-could-not-load-file-or-assembly
