### ISSUE TITLE
Show status report summary on the front page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#368]
**Is your feature request related to a problem? Please describe.**
The project column configuration list includes all the project status fields, but changing the value of "Show in portfolio", "Show on frontpage" etc has no effect. This is kindof a bug, at least it looks like that for the user. 

**Describe the solution you'd like**
We could solve this by adding another webpart on the front page (or extend the "Project information" web part) called "Project status", where we're showing various fields from the most recent, published, status report. We will need to query the central Project Status list, get the newest, published, report and grab the necessary field values from that item. We should also keep the same formatting rules (colors, icons) as we're using on the project status page.

**Comment by Remi749** [comment]
Suggestion: Make Status report webpart highly responsive.

**Comment by okms** [comment]
We need to clarify if we want to include "prosjektstatus" in the "prosjektinformasjon" webpart, or if this should be deferred to another webpart entirely

**Comment by olemp** [comment]
Show status report summary on the front page. It can be toggled on and off in the web part properties and required data will only be fetched if it's set to visible.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/7606007/199504808-61b0a613-e7de-4eb7-9057-afc478a21e93.png">

It's set to be hidden by default.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/7606007/199505202-7ce6fe0d-5bf9-46a6-9d34-0cfa36fbc89b.png">


If _Avkort kommentarer_ is set it will truncate the comments to the specified length and show the full status element in a tooltip.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/7606007/199505114-3df52078-45e5-4c37-9159-94b1e6fb9346.png">
