### ISSUE TITLE
Stamp Project Template name to a field in the Project Properties list

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#369]
**Is your feature request related to a problem? Please describe.**
It would be useful to see what project template was used for a project.

**Describe the solution you'd like**
Create a new field "Project template"/"Prosjektmal" available in the Projects-list at root and Project properties in projects. When a new project is created (or when project metadata is set the first time) we set this value. I believe the project template is already stamped in the web property bag. The field should have ShowInEditForm=false and ShowInNewForm=false.

**Additional context**
Suggest that migration is handled manually, e.g. by scripting the field value of existing projects.

The purpose is to show the template name in the portfolio overview, to indicate which template is used for which project, for instance very relevant in the "bygg og anlegg" module.

**Comment by olemp** [comment]
@tarjeieo I'm not sure we can handle migration as we don't know the project template of "old" projects.

**Comment by tarjeieo** [comment]
Suggest that migration is handled manually, e.g. by scripting the field value of existing projects.

The purpose is to show the template name in the portfolio overview, to indicate which template is used for which project, for instance very relevant in the "bygg og anlegg" module.
