### ISSUE TITLE
"Hent dokumentmal" should support folders in the template directory

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#370]
**Is your feature request related to a problem? Please describe.**
Some organizations have tens, sometimes hundreds, of templates. Today this is really hard to navigate when selecting templates, and information about what folder has what files is lost.
![image](https://user-images.githubusercontent.com/1837390/105818340-16bbea80-5fb7-11eb-9a0a-318908fbcd97.png)

**Describe the solution you'd like**
It would be nice to be able to navigate in folders at the template level, as one can do when selecting destination folder.

**Comment by tarjeieo** [comment]
We should also add a description field to the template list and show this field in the picker

**Comment by olemp** [comment]
> We should also add a description field to the template list and show this field in the picker

Added #379

**Comment by olemp** [comment]
Fixed in #382
