### ISSUE TITLE
Show "sub phase text" as part of the phase web part

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#371]
**Is your feature request related to a problem? Please describe.**
Sometimes it's necessary to give some more information about a phase, or give an alternative phase name. 

**Describe the solution you'd like**
We should add the alternative text below the phases, and show it in the phase overlay dialog. 
![image](https://user-images.githubusercontent.com/1837390/105999709-4d286100-60ae-11eb-9758-e978f67ce77d.png)
![image](https://user-images.githubusercontent.com/1837390/105999737-51ed1500-60ae-11eb-8ecd-4b8fc6e8ed15.png)

**Additional context**
Use the same term property names as in PP2 for the phase - "SubText"? (verify with PP2 code)

**Comment by olemp** [comment]
Need some styling adjustments.

![image](https://user-images.githubusercontent.com/7606007/107764678-e56e4900-6d30-11eb-80cd-73228b983773.png)

**Comment by olemp** [comment]
> Need some styling adjustments.
> 
> ![image](https://user-images.githubusercontent.com/7606007/107764678-e56e4900-6d30-11eb-80cd-73228b983773.png)

Adjusted in #392
