### ISSUE TITLE
Gevinstoversikt only shows gevinst-items for which you have added measurement indicators

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#372]
**Describe the bug**
In the gevinst overview, we should see gevinst items also when they don't have connected measurement items or data followup.

**Comment by olemp** [comment]
This is by design - not a bug. Several indicators can have the same benefit (gevinst).

We're retrieving benefits, measurements and indicators and using indicators as the master:

```typescript
  private _postTransform(results: any[]): any[] {
    const benefits = results
      .filter((res) => res.ContentTypeID.indexOf(CONTENT_TYPE_ID_BENEFITS) === 0)
      .map((res) => new Benefit(res))

    const measurements = results
      .filter((res) => res.ContentTypeID.indexOf(CONTENT_TYPE_ID_MEASUREMENTS) === 0)
      .map((res) => new BenefitMeasurement(res))
      .sort((a, b) => b.date.getTime() - a.date.getTime())

    const indicactors = results
      .filter((res) => res.ContentTypeID.indexOf(CONTENT_TYPE_ID_INDICATORS) === 0)
      .map((res) => {
        const indicator = new BenefitMeasurementIndicator(res)
          .setMeasurements(measurements)
          .setBenefit(benefits)
        return indicator
      })
      .filter((i) => i.benefit)
    return indicactors
  }
```

**Comment by tarjeieo** [comment]
So the question is - can we show benefits without measurements in addition? Or do you suggest a separate page/view.

**Comment by olemp** [comment]
> So the question is - can we show benefits without measurements in addition? Or do you suggest a separate page/view.

I think that's too complex - I'd suggest a separate web part or view. What's the rationale for showing benefits that are not being worked on?

**Comment by tarjeieo** [comment]
Because they're identifying the benefits early in the project - concept/planning - but they are not really working on realizing them until closing/realization. Still they want to show them aggregated for all projects. But we can definitively live with a separate view.

**Comment by olemp** [comment]
> Because they're identifying the benefits early in the project - concept/planning - but they are not really working on realizing them until closing/realization. Still they want to show them aggregated for all projects. But we can definitively live with a separate view.

https://github.com/Puzzlepart/prosjektportalen365/issues/373
