### ISSUE TITLE
Separate view for all benefits (gevinster)

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#373]
**Is your feature request related to a problem? Please describe.**
The current benefit overview only shows benefits, but with indicators as the master, meaning benefits that are not being worked on, will not be shown.

**Describe the solution you'd like**
A separate view showing all benefits.

**Additional context**
_Originally posted by @tarjeieo in https://github.com/Puzzlepart/prosjektportalen365/issues/372#issuecomment-770761261_

**Comment by tarjeieo** [comment]
Might be resolved by #394

**Comment by tarjeieo** [comment]
We don't create a default page for this, but it can be resolved by the feature of #394
