### ISSUE TITLE
Update field descriptions

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#386]
Update field descriptions across PP with more information and better quality.

Field descriptions (internal): [Field descriptions](https://pzlcloud.sharepoint.com/:x:/r/sites/prosjektportalen/Shared%20Documents/General/Hjelpetekster%20og%20nytt%20B%26A%20innhold.xlsx?d=w06568fea5d8c4dda928631d79c2528ea&csf=1&web=1&e=ieDg6a)

**Comment by pzljanb** [comment]
Tested OK

**Comment by olemp** [comment]
Latest updates confirmed OK

_Originally posted by @pzljanb in https://github.com/Puzzlepart/prosjektportalen365/issues/474#issuecomment-833441782_
