### ISSUE TITLE
Copy permissions from configuration list to projects

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#387]
**Is your feature request related to a problem? Please describe.**
When creating new projects, you might want to copy permissions to the new projects. This is today done with the "Portfolio administrators" group. This is a working approach, but not a flexible one.

**Describe the solution you'd like**
I suggest using a portfolio list that holds the configuration for the permission configuration. The PP setup wizard iterates through this list and copies permissions to the project. This will only be applied to the SharePoint-site of the project, not the M365 group/Team.

Tasks to complete this

- A list "Permission Configuration" at the portfolio level with the following columns
    - SharePoint group name
    - Permission level (`Read`, `Edit`, `Full Control` - prob needs to be in norwegian though, `Les`, `Rediger`, `Full kontroll`). Description: Definerer rettighetsnivå på SharePoint-området til prosjektet.
- A default item in this list: **"Portfolio administrators"** with permission level `Full control` (replaces the setting from the wizard).
- Update wizard code. Use this list to set initial permissions. Remove the "give portfolio administrators access" switch

NB: It is possible for group owners to remove the permissions after the wizard has run. This is intended.

**Comment by olemp** [comment]
Done in #395. Can be tested in testing environment.
