### ISSUE TITLE
Show "Last report date" on the status report page and as a column in portfolio view

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#393]
**Is your feature request related to a problem? Please describe.**
When browsing projects and status report values in the portfolio overview/portfolio status, it would be nice to see when the last report was made.

**Describe the solution you'd like**
* Show a datefield on the project status page that will be included as part of the project status page snapshot.
* Show a datefield for when the last report was made in the portfolio overview (if you select this column).

**Additional context**
This is by default stored in the "modified" field - however, this field is also used by the project properties item as well. Not sure how we handle this in a good way. Input @olemp ?

**Comment by tarjeieo** [comment]
Solution proposal: We create a new field on the project status page: Report Publish Date. We can set this automatically when we publish a report. This date can then also be shown on the project status page and on the snapshot. This column can also be added as a portfolio column and shown in the portfolio overview.

Think this should be quite doable!

**Comment by olemp** [comment]
> Solution proposal: We create a new field on the project status page: Report Publish Date. We can set this automatically when we publish a report. This date can then also be shown on the project status page and on the snapshot. This column can also be added as a portfolio column and shown in the portfolio overview.
> 
> Think this should be quite doable!

That's doable 

(\____/)
( ͡ ͡° ͜ ʖ ͡ ͡°)
\╭☞ \╭☞

**Comment by pzljanb** [comment]
Like 1.2.6 doable I presume/ hope for :-)

**Comment by olemp** [comment]
> Like 1.2.6 doable I presume/ hope for :-)

Depends on when we want to release 1.2.6 obviously.

**Comment by Petterandre** [comment]
![image](https://user-images.githubusercontent.com/10527497/114559526-1d7c0480-9c6c-11eb-81d1-4224f7797386.png)

![image](https://user-images.githubusercontent.com/10527497/114559519-1b19aa80-9c6c-11eb-8dcf-f5e082b602ae.png)

Thoughts about the look? Considering MM/dd/yyyy date, but uncertain what could happen with different locales

**Comment by tarjeieo** [comment]
Looks good!

**Comment by olemp** [comment]
looking hawt

**Comment by pzljanb** [comment]
Format is self-explaining, and no risk for misunderstandings here, good job @Petterandre

**Comment by pzljanb** [comment]
Tested OK
