### ISSUE TITLE
Flexible portfolio aggregation views web parts

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#394]
**Is your feature request related to a problem? Please describe.**
The project portfolio is a great example of a dynamic and flexible overview page - where users can customize fields, query, grouping, filtering and so forth. A+ feature.

However, the other overview pages are not flexible in the same regard. The query is dynamic from the Data Sources config list, but the fields, field order etc. are not available for configuring. 

**Describe the solution you'd like**
I propose that we create a new, flexible web part that allows ANY datasource and ANY column configuration. This web part can then be reused for other type of aggregated content as well.

Of course, some overview web parts will be special and can probably not be supported with this config. Benefits overview (with calculated achievement percentage) and risk overview (with risk matrix) needs to be handled differently, but it would be great if the columns and queries were flexible here as well.

Configuration options in play
* Data sources - existing list that defines a KEY and a query. Is used today
* Column configuration - JSON file? Notefield with JSON? Should have a format similar to what is in the code today.

```
{
    key: 'SiteTitle',
    fieldName: 'SiteTitle',
    name: PortfolioWebPartsStrings.SiteTitleLabel,
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
    onRender: (item: any) => (
      <a href={item.SPWebUrl} rel='noopener noreferrer' target='_blank'>
        {item.SiteTitle}
      </a>
    ),
    isGroupable: true
  },
  {
    key: 'Title',
    fieldName: 'Title',
    name: strings.TitleLabel,
    minWidth: 220,
    maxWidth: 250
  },
  {
    key: 'GtProjectLogDescriptionOWSMTXT',
    fieldName: 'GtProjectLogDescriptionOWSMTXT',
    name: strings.LogDescriptionLabel,
    minWidth: 100,
    maxWidth: 150,
    isResizable: true
  },
  {
    key: 'GtProjectLogResponsibleOWSCHCS',
    fieldName: 'GtProjectLogResponsibleOWSCHCS',
    name: strings.ResponsibleLabel,
    minWidth: 100,
    maxWidth: 150,
    isResizable: true,
    isGroupable: true
  },
```

**Comment by olemp** [comment]
@tarjeieo I’d prefer to replace the web parts for risks, deliveries and log elements with this flexible web parts as they’re all very similiar. 

We then need to find a way to allow overwrite of these client side pages when upgrading, but then allow changes by the customers before the next updates.

Any ideas?

**Comment by olemp** [comment]
> @tarjeieo I’d prefer to replace the web parts for risks, deliveries and log elements with this flexible web parts as they’re all very similiar.
> 
> We then need to find a way to allow overwrite of these client side pages when upgrading, but then allow changes by the customers before the next updates.
> 
> Any ideas?

Need your input here @tarjeieo.

Also did some adjustments in #403. This is currently being built in this [GitHub action run](https://github.com/Puzzlepart/prosjektportalen365/actions/runs/581085552).

I've added documentation for the web part [here](https://github.com/Puzzlepart/prosjektportalen365/tree/dev/SharePointFramework/PortfolioWebParts).

**Comment by tarjeieo** [comment]
What we did with PP2 is handling upgrading from specific versions with special script actions, e.g.
From pre-1.2.6: Delete the pages before upgrade
From 1.2.6: Don't do anything

**Comment by olemp** [comment]
> What we did with PP2 is handling upgrading from specific versions with special script actions, e.g.
> From pre-1.2.6: Delete the pages before upgrade
> From 1.2.6: Don't do anything
> 
> And then we can have "overwrite=false" on the pages to allow changes by customers and not "resetting" pages

Deprecated client side components can be an issue in the future aswell.

Decided to do a script `RemoveDeprecatedPages.ps1` that removes pages with deprecated components. It runs if the installation is ran with the `-Upgrade` switch.

```powershell
$DeprecatedIds = @(
    "d8558017-1e3b-4d13-82fa-2520e845297b", 
    "3ec6bcaf-28bc-4f2e-9e90-77e8cebf0b5f", 
    "57530c94-4fb2-4ca2-9279-16c57881fa19"
)

$Pages = Get-PnPFolder -Url SitePages -Includes Files | Select-Object -ExpandProperty Files

$Pages | ForEach-Object {
    $DeprecatedComponents = Get-PnPClientSideComponent -Page $_.Name | Where-Object { $DeprecatedIds.Contains($_.WebPartId) }
    if($DeprecatedComponents.Count -gt 0) {
        Remove-PnPClientSidePage $_.Name -Force
    }
}
```

**Comment by olemp** [comment]
> > What we did with PP2 is handling upgrading from specific versions with special script actions, e.g.
> > From pre-1.2.6: Delete the pages before upgrade
> > From 1.2.6: Don't do anything
> > And then we can have "overwrite=false" on the pages to allow changes by customers and not "resetting" pages
> 
> Deprecated client side components can be an issue in the future aswell.
> 
> Decided to do a script `RemoveDeprecatedPages.ps1` that removes pages with deprecated components. It runs if the installation is ran with the `-Upgrade` switch.
> 
> ```powershell
> $DeprecatedIds = @(
>     "d8558017-1e3b-4d13-82fa-2520e845297b", 
>     "3ec6bcaf-28bc-4f2e-9e90-77e8cebf0b5f", 
>     "57530c94-4fb2-4ca2-9279-16c57881fa19"
> )
> 
> $Pages = Get-PnPFolder -Url SitePages -Includes Files | Select-Object -ExpandProperty Files
> 
> $Pages | ForEach-Object {
>     $DeprecatedComponents = Get-PnPClientSideComponent -Page $_.Name | Where-Object { $DeprecatedIds.Contains($_.WebPartId) }
>     if($DeprecatedComponents.Count -gt 0) {
>         Remove-PnPClientSidePage $_.Name -Force
>     }
> }
> ```

cc @tarjeieo

**Comment by tarjeieo** [comment]
Cool, I don't see an issue with this. Like! ╰(*°▽°*)╯

**Comment by olemp** [comment]
Solved ╰(°▽°)╯

**Comment by tarjeieo** [comment]
What about columns - how can we change which columns to show in the views?

**Comment by tarjeieo** [comment]
Sorry - saw the documentation now!

**Comment by olemp** [comment]
> Sorry - saw the documentation now!

Yes, should all be there in the [README](https://github.com/Puzzlepart/prosjektportalen365/tree/dev/SharePointFramework/PortfolioWebParts)!
