### ISSUE TITLE
Documents is not copied to new projects when they are added to portfolio document libraries

### ISSUE THREAD

**Issue by danielwiese** [Puzzlepart/prosjektportalen365#397]
**Describe the bug**
I tried to place a document in the document library which is copied when creating new projects. It was not copied, as i expected it to be.

**To Reproduce**

1. Go to https://prosjektportalen.sharepoint.com/sites/PPByggAnlegg/Standarddokumenter_Anlegg/Forms/AllItems.aspx and add some documents
2. Click on Create new site
3. Go to the document section in the new created project
4. See that the added document is not being copied

**Expected behavior**
I expected it to work in the same way as when creating new folders, which is being copied to new project

**Screenshots**
![image](https://user-images.githubusercontent.com/61320379/108203063-4a0b1880-7122-11eb-8704-b14b61fa0347.png)
![image](https://user-images.githubusercontent.com/61320379/108203224-79218a00-7122-11eb-80da-2c860ea9b217.png)

**About your setup**

Edge
PP B&A 1.2.4

**Additional context**

**Comment by olemp** [comment]
@danielwiese @tarjeieo Is the libraries configured in the "Listeinnhold" list?

**Comment by olemp** [comment]
Fixed in #399

**Comment by olemp** [comment]
@danielwiese @tarjeieo 

Working in testing environment:

![image](https://user-images.githubusercontent.com/7606007/108355526-3c6d9580-71eb-11eb-84c1-ba110caaaba5.png)

The installation package can be found [here](https://github.com/Puzzlepart/prosjektportalen365/suites/2067612915/artifacts/41783970). This will be included in `1.2.6`.
