### ISSUE TITLE
Use Project Status Content Type Id from TemplateConfig when creating new status reports

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#398]
**Is your feature request related to a problem? Please describe.**
If several project status content types are available, when clicking "New status report" the deault CT will always be chosen. If it's another type of project (e.g. "byggprosjekt"), this can lead to confusion.

**Describe the solution you'd like**
Lets use the content type ID of the project status from the JSON template, and use this as a parameter in the "new status report" button, and add &ContentType=0x01.... to the URL of the form, to automatically select the correct template.

The JSON template already has this parameter:

```
"Parameters": {
        "ProvisionSiteFields": "{{SiteFields_Project_Group}}",
        "ProjectContentTypeId": "0x0100805E9E4FEAAB4F0EABAB2600D30DB70C",
        **"ProjectStatusContentTypeId": "0x010022252E35737A413FB56A1BA53862F6D5"**
    },
```

![image](https://user-images.githubusercontent.com/1837390/108214566-98271880-7130-11eb-961c-c31e74191e48.png)

URL to the form would then be e.g.
`https://prosjektportalen.sharepoint.com/sites/Prosjektportalenbyggoganlegg/Lists/Prosjektstatus/EditForm.aspx?ID=2&ContentType=0x010022252E35737A413FB56A1BA53862F6D5&Source=https%3A%2F%2Fprosjektportalen.sharepoint.com%2Fsites%2FAnleggTestFeb04%2FSitePages%2FProsjektstatus.aspx%23`

**Comment by olemp** [comment]
> **Is your feature request related to a problem? Please describe.**
> If several project status content types are available, when clicking "New status report" the deault CT will always be chosen. If it's another type of project (e.g. "byggprosjekt"), this can lead to confusion.
> 
> **Describe the solution you'd like**
> Lets use the content type ID of the project status from the JSON template, and use this as a parameter in the "new status report" button, and add &ContentType=0x01.... to the URL of the form, to automatically select the correct template.
> 
> The JSON template already has this parameter:
> 
> ```
> "Parameters": {
>         "ProvisionSiteFields": "{{SiteFields_Project_Group}}",
>         "ProjectContentTypeId": "0x0100805E9E4FEAAB4F0EABAB2600D30DB70C",
>         **"ProjectStatusContentTypeId": "0x010022252E35737A413FB56A1BA53862F6D5"**
>     },
> ```
> 
> ![image](https://user-images.githubusercontent.com/1837390/108214566-98271880-7130-11eb-961c-c31e74191e48.png)
> 
> URL to the form would then be e.g.
> `https://prosjektportalen.sharepoint.com/sites/Prosjektportalenbyggoganlegg/Lists/Prosjektstatus/EditForm.aspx?ID=2&ContentType=0x010022252E35737A413FB56A1BA53862F6D5&Source=https%3A%2F%2Fprosjektportalen.sharepoint.com%2Fsites%2FAnleggTestFeb04%2FSitePages%2FProsjektstatus.aspx%23`

How did you reproduce this?

We are setting the correct content type ID:

![image](https://user-images.githubusercontent.com/7606007/108344165-18a35300-71dd-11eb-85ed-692d74b53b3b.png)

**Comment by tarjeieo** [comment]
Ah, never seen it work tbh. See e.g. https://prosjektportalen.sharepoint.com/sites/Anleggsprosjekt/SitePages/Prosjektstatus.aspx - log in with prosjektportalen.admin

**Comment by olemp** [comment]
> Ah, never seen it work tbh. See e.g. https://prosjektportalen.sharepoint.com/sites/Anleggsprosjekt/SitePages/Prosjektstatus.aspx - log in with prosjektportalen.admin

I can check now..

I see it's at least set on the item:

![image](https://user-images.githubusercontent.com/7606007/108345355-74221080-71de-11eb-9ea9-98953912a246.png)

**Comment by olemp** [comment]
Should be solved by #400

**Comment by olemp** [comment]
@tarjeieo CI is currently running https://github.com/Puzzlepart/prosjektportalen365/actions/runs/577975369

Can be tested after the CI is done. It will post to Slack.

The installation package will be added as an artifact to the CI action, and can be used for upgrading other installations aswell.

**Comment by olemp** [comment]
> @tarjeieo CI is currently running https://github.com/Puzzlepart/prosjektportalen365/actions/runs/577975369
> 
> Can be tested after the CI is done. It will post to Slack.
> 
> The installation package will be added as an artifact to the CI action, and can be used for upgrading other installations aswell.

[Installation package is ready.](https://github.com/Puzzlepart/prosjektportalen365/suites/2068053599/artifacts/41796497)
