### ISSUE TITLE
Add Description column to list  "Usikkerhet"

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#402]
**Is your feature request related to a problem? Please describe.**
Missing field to describe a risk / opportunity

**Describe the solution you'd like**
Add Description column

**Additional context**
To be solved as already included in existing customer solution

**Comment by tarjeieo** [comment]
Lets use this one (already implemented for a specific customer)

`<Field DisplayName="Beskrivelse av usikkerhet" Group="Kolonner for Prosjektportalen (Prosjekt)" ID="{E930090A-480E-414A-BD4A-0EF5BCA31443}" Name="GtRiskDescription" StaticName="GtRiskDescription" Type="Note" UnlimitedLengthInDocumentLibrary="TRUE" NumLines="3" />`

**Comment by olemp** [comment]
> Lets use this one (already implemented for a specific customer)
> 
> `<Field DisplayName="Beskrivelse av usikkerhet" Group="Kolonner for Prosjektportalen (Prosjekt)" ID="{E930090A-480E-414A-BD4A-0EF5BCA31443}" Name="GtRiskDescription" StaticName="GtRiskDescription" Type="Note" UnlimitedLengthInDocumentLibrary="TRUE" NumLines="3" />`

Added this in #410
