### ISSUE TITLE
New settings for permission configuration does not show up after upgrade

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#425]
**Describe the bug**
The new setting for configuring permissions (and permission "inheritance") does not show up on the PP configuration page after an upgrade.

See original issue #395 

![image](https://user-images.githubusercontent.com/1837390/110114279-ab82e680-7db4-11eb-9800-54a1e1ee7529.png)

**Version**
1.2.6

**Comment by pzljanb** [comment]
Tested OK
