### ISSUE TITLE
Caching issue when adding additional columns in the flexible aggregation web part

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#426]
**Describe the bug**
The new flexible aggregation web part has an issue when adding multiple new columns. The first time you add a column, everything is fine. For subsequent columns, the form is "cached" or reused, so you get the same values in the fields as you previously filled out.

**To Reproduce**

1. Go to e.g. prosjektleveranser
2. Edit page. Click on new column. Fill out fields.
3.  Save and click on new column again.
4. Observe that fields are filled out with values from the last column added

**Expected behavior**
The form should be new and clean.

**Screenshots**

**About your setup**

- Browser [e.g. chrome, safari] Edge chromium
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.2.6

**Additional context**
Workaround: Close the form and click add column again. Then it's empty again as expected.

**Comment by olemp** [comment]
It's not cached per say, the state is not reset. It was on purpose since I was thinking people would add similiar fields and they wouldn't need to add all the data again. I can fix it in a PR.

**Comment by olemp** [comment]
[CI is running](https://github.com/Puzzlepart/prosjektportalen365/actions/runs/624414865) with the fix from #427 now. Sorry for the delay!

**Comment by tarjeieo** [comment]
Nice, good intention, but in reality fields does usually have different name, internal name etc.... Thinks this is better. Thanks for a quick fix

**Comment by olemp** [comment]
> Nice, good intention, but in reality fields does usually have different name, internal name etc.... Thinks this is better. Thanks for a quick fix

True.. Was a easy fix.

**Comment by pzljanb** [comment]
@tarjeieo ;
Can't find this issue in the changelog for v1.2.7, please confirm/ update

**Comment by pzljanb** [comment]
Tested OK, we leave it out of Changelog
