### ISSUE TITLE
Issues when using default view in web part properties for Portfolio overview web part

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#428]
**Describe the bug**
Web part portfolio overview crashes when setting default view in web part property pane.

**To Reproduce**

1. Go to SitePages/Porteføljeoversikt.aspx
2. Edit page
3. Set a value for "Standardvisning" in property pane
4. Refresh SitePages/Porteføljeoversikt.aspx

**Expected behavior**
The default view selected in web part property pane should be the default view. Not make the page crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/7606007/110464519-843d5980-80d3-11eb-8977-762a5bf3c2d8.png)

**About your setup**
N/A

**Additional context**

**Comment by pzljanb** [comment]
Tested OK
