### ISSUE TITLE
Projectimeline webpart

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#429]
Add a new webpart to the portfolio.

A projecttimeline webpart listing each project based on GtStartDate and GtEndDate with additional props in the callout card on click. The properties comes from the list "Prosjekter".

Example of solution developed previously
![image](https://user-images.githubusercontent.com/28678468/110519862-1bbf9e00-810e-11eb-9332-6d1c0d4bd171.png)
![image](https://user-images.githubusercontent.com/28678468/110521232-c4bac880-810f-11eb-99eb-bb2f68aa490c.png)

Add the following props to the callout card
- Url to project
- Current phase
- Startdate
- Enddate

Also possiblity to filter by project

This webpart will be developed further in issue #434

UPDATE:

Image of the webpart
![image](https://user-images.githubusercontent.com/28678468/111277142-66727600-8638-11eb-82f5-cf38d0c7bd71.png)

**Comment by Remi749** [comment]
Branch: https://github.com/Puzzlepart/prosjektportalen365/tree/feature/project-timeline-webpart

**Comment by olemp** [comment]
WE NEED MORE INFORMATION!

**Comment by olemp** [comment]
Merged PR https://github.com/Puzzlepart/prosjektportalen365/pull/435 from @Remi749. Solid work. Will check PP365 after `dev` CI has done its thing.

**Comment by olemp** [comment]
Let's test it a bit after dev `CI` upgraded https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Home.aspx. We can create new issues if we decide to do more adjustments.

**Comment by Remi749** [comment]
Sure thing!
