### ISSUE TITLE
Expand projecttimeline with phases, milestones ++

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#434]
This issue covers the expansion of the Projectimeline webpart from issue #429

Image from the projecttimeline
![image](https://user-images.githubusercontent.com/28678468/111277090-55296980-8638-11eb-924d-346e7468b18f.png)

Expansions:

A new hubsite list with possibility to add new and connect items such as phases, milestones, etc. to projects. These elements will then show up in the new projecttimeline webpart for each project.

The list will contain the following columns
- Title
- Type (Choice: Fase, Milepæl, Delfase)
- StartDate
- EndDate
- Budget
- Cost
- SiteId (Lookup field -> Prosjekter)

The timeline
1. Project (start-end dates)
2. Milestones indicated by diamond (enddate)
3. Phases and subphases (start-end dates, sorted by startdate)

The timeline elements will be easlity identified by a unique color.

Possiblity to filter on type

More information coming at a later time...

How to test
 1. Add items to list: "Tidslinjeinnhold"
 2. Check out 'Prosjekttidslinje' webpart

**Comment by Remi749** [comment]
Feature branch: https://github.com/Puzzlepart/prosjektportalen365/tree/feature/project-timeline-expansion

**Comment by olemp** [comment]
> Feature branch: https://github.com/Puzzlepart/prosjektportalen365/tree/feature/project-timeline-expansion

Create a draft PR and we connect it to the issue.

**Comment by Remi749** [comment]
> > Feature branch: https://github.com/Puzzlepart/prosjektportalen365/tree/feature/project-timeline-expansion
> 
> Create a draft PR and we connect it to the issue.

Good idea 👍

**Comment by Remi749** [comment]
Images of the progress so far...
![image](https://user-images.githubusercontent.com/28678468/112449130-5f8fe580-8d53-11eb-9f96-05394f16c321.png)
![image](https://user-images.githubusercontent.com/28678468/112449238-78000000-8d53-11eb-9bb6-b306bf3a0442.png)

**Comment by olemp** [comment]
> Images of the progress so far...
> ![image](https://user-images.githubusercontent.com/28678468/112449130-5f8fe580-8d53-11eb-9f96-05394f16c321.png)
> ![image](https://user-images.githubusercontent.com/28678468/112449238-78000000-8d53-11eb-9bb6-b306bf3a0442.png)

This progress can be compared to [this progress](https://images.superstickers.com/SS9083_1.jpg)

**Comment by olemp** [comment]
@Remi749 I propose to add the resources in a separate PR, ref review in https://github.com/Puzzlepart/prosjektportalen365/pull/437

**Comment by olemp** [comment]
What's going on the right side here @Remi749?

![Uploading image.png…]()

**Comment by olemp** [comment]
Something weird going on [here](https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Prosjekttidslinje.aspx) @Remi749 

![image](https://user-images.githubusercontent.com/7606007/113134207-d2e89a00-9220-11eb-80e8-16b1ccb4d84c.png)

**Comment by olemp** [comment]
Would also be nice to add it to the configuration page, and potentially set it to HIdden like the other configuration lists.

![image](https://user-images.githubusercontent.com/7606007/113134453-13481800-9221-11eb-8323-55436be745c3.png)

**Comment by Remi749** [comment]
> Something weird going on [here](https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Prosjekttidslinje.aspx) @Remi749
> 
> ![image](https://user-images.githubusercontent.com/7606007/113134207-d2e89a00-9220-11eb-80e8-16b1ccb4d84c.png)

Not seeing this here (1440p resolution)
![image](https://user-images.githubusercontent.com/28678468/113134558-3e326c00-9221-11eb-9c48-5e53e1846172.png)

**Comment by Remi749** [comment]
> Would also be nice to add it to the configuration page, and potentially set it to HIdden like the other configuration lists.
> 
> ![image](https://user-images.githubusercontent.com/7606007/113134453-13481800-9221-11eb-8323-55436be745c3.png)

@pzljanb, what was the reason why we did not want to do this? if there is no reason then I agree with @olemp

**Comment by olemp** [comment]
@Remi749 3072 × 1920

**Comment by olemp** [comment]
Looks good anyways

![image](https://user-images.githubusercontent.com/7606007/113134936-c31d8580-9221-11eb-8afa-e7178f164152.png)


Just a typo here. "Siste publiserte statusrapport" => "Siste publiserte statusrapport**er**"

**Comment by Remi749** [comment]
> Looks good anyways
> 
> ![image](https://user-images.githubusercontent.com/7606007/113134936-c31d8580-9221-11eb-8afa-e7178f164152.png)
> 
> Just a typo here. "Siste publiserte statusrapport" => "Siste publiserte statusrapport**er**"

As there might be a chance that the link will show an unpublished status report, maybe it should say "Gå til statusrapport" instead?

**Comment by olemp** [comment]
> > Looks good anyways
> > ![image](https://user-images.githubusercontent.com/7606007/113134936-c31d8580-9221-11eb-8afa-e7178f164152.png)
> > Just a typo here. "Siste publiserte statusrapport" => "Siste publiserte statusrapport**er**"
> 
> As there might be a chance that the link will show an unpublished status report, maybe it should say "Gå til statusrapport" or "Gå til siste statusrapport" instead? Since the link takes the user to the statusreport page and shows the latest statusreport.

.. or it could actually list the latests status reports? That'd be a different task/issue though. Don't want to scope-creep this one 🐛

**Comment by Remi749** [comment]
> > > Looks good anyways
> > > *image*
> > > Just a typo here. "Siste publiserte statusrapport" => "Siste publiserte statusrapport**er**"
> > 
> > 
> > As there might be a chance that the link will show an unpublished status report, maybe it should say "Gå til statusrapport" or "Gå til siste statusrapport" instead? Since the link takes the user to the statusreport page and shows the latest statusreport.
> 
> .. or it could actually list the latests status reports? That'd be a different task/issue though. Don't want to scope-creep this one 🐛

That would've been nice. 👍 I'll change it to "Gå til siste statusrapport" in #450

**Comment by Remi749** [comment]
Photo of finalized solution:

![image](https://user-images.githubusercontent.com/28678468/113136675-ee08d900-9223-11eb-8c82-0fa45c513c47.png)
![image](https://user-images.githubusercontent.com/28678468/113136717-fb25c800-9223-11eb-96b4-2b87f84628c6.png)

**Comment by olemp** [comment]
> Photo of finalized solution:
> 
> ![image](https://user-images.githubusercontent.com/28678468/113136675-ee08d900-9223-11eb-8c82-0fa45c513c47.png)
> ![image](https://user-images.githubusercontent.com/28678468/113136717-fb25c800-9223-11eb-96b4-2b87f84628c6.png)

Holy moly!

**Comment by olemp** [comment]
Almost like it's inspired by resource allocation!! 🚀

**Comment by Remi749** [comment]
> Almost like it's inspired by resource allocation!! 🚀

"Rebuilt from the ground up" -Apple 😂

**Comment by pzljanb** [comment]
> > Would also be nice to add it to the configuration page, and potentially set it to HIdden like the other configuration lists.
> > ![image](https://user-images.githubusercontent.com/7606007/113134453-13481800-9221-11eb-8323-55436be745c3.png)
> 
> @pzljanb, what was the reason why we did not want to do this? if there is no reason then I agree with @olemp

We should for sure add the list to the Configuration page :-)

**Comment by pzljanb** [comment]
In the future we should add functionality to both view and edit a projets timeline from the project itself, just like we do with statusreport

**Comment by pzljanb** [comment]
Tested OK
