### ISSUE TITLE
Add support for using field group instead of field prefix for project properties sync

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#439]
**Is your feature request related to a problem? Please describe.**
Add support for using field group instead of field prefix for project properties sync.

We'll add the group name to the template parameters for `Standardmal`. The default will be `Egendefinerte kolonner for Prosjektportalen`. 

**Describe the solution you'd like**
See #438 

**Additional context**
See discussion https://github.com/Puzzlepart/prosjektportalen365/discussions/438

_Until this issue is resolved and a new version is released, custom fields need to be prefixed with Gt_

**Comment by olemp** [comment]
@pzljanb This can now be tested in the test enviroment.

See [wiki/Egne-prosjektegenskaper](https://github.com/Puzzlepart/prosjektportalen365/wiki/Egne-prosjektegenskaper)

**Comment by pzljanb** [comment]
> @pzljanb This can now be tested in the test enviroment.
> 
> See [wiki/Egne-prosjektegenskaper](https://github.com/Puzzlepart/prosjektportalen365/wiki/Egne-prosjektegenskaper)

@olemp Column is showing up in projects as described, this part looks good.
But what about the use in Portfolio section of PP?
- Should the new column show up as a selectable column in view definition of e.g. 'Porteføljeoversikt'?
- And what about 'Prosjektkolonner' in configuration part of PP365, will the new column  show up here?

Or else, the only visible location of this column is in the 'Prosjektegenskaper' of the Project Home page?
