### ISSUE TITLE
Read-only access to portfolio frontpage project view

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#443]
**Is your feature request related to a problem? Please describe.**
In some instances you might want to give some users read access to all the project cards on the frontpage. This is hard to achieve today without giving the users read-access or member-access to all projects. Similar to what was done in #243 / #305 

**Describe the solution you'd like**
If someone is in the group "Porteføljeinnsyn" they will be able to view all projects in the portfolio frontpage project view. User is not able to enter the project, only view the cards

Related to ASSIST-3389 (16h)

**Comment by Rundez** [comment]
**A Toggle prop in the projectlist web part**
![image](https://user-images.githubusercontent.com/38385042/126759495-238f1842-01f3-4551-8b32-cac892a0dd82.png)

**When toggled, an additional toggle appers (should maybe only appear if the user is in "porteføljeinnsyn" group?**
![image](https://user-images.githubusercontent.com/38385042/126759761-1f7e38b1-105d-4ced-8695-7538cd424d2f.png)

**If the user toggles, all PP projects will be shown **
![image](https://user-images.githubusercontent.com/38385042/126759928-dffbf56e-6db7-4fc2-ae1c-faae588e3d6c.png)

**The same with the listview. The clickable hyperlink is grayed out**
![image](https://user-images.githubusercontent.com/38385042/126760205-3bdd363c-b270-436a-bc68-c4082b77d827.png)

**Comment by Rundez** [comment]
Merged and done.
