### ISSUE TITLE
Incorrect "ProjectContentTypeId" used when retrieving Project Properties in "Project Status"

### ISSUE THREAD

**Issue by balle3201** [Puzzlepart/prosjektportalen365#446]
**Describe the bug**
When provisioning new projects based on custom content type(s) for Project (ProjectContentTypeId), Project Properties on the front page works as intended (although lack of documentation). However, the Project Information on the "Project Status"-page always retrieves fields (entityfields) without passing the custom ProjectContentTypeId to the entityservice, resulting in the default Project-ContentTypeId being used.

**To Reproduce**

1. Create a new custom Project Content Type
2. Provision a new Project Site based on the new Content Type (incl. setting up Project Templates, etc.)
3. Fill inn necessary custom fields in the Project Properties
4. Open the "Project Status" page, and look at the Project Properties section
5. The fields listed up are only the non-empty fields, as specified by the default ProjectContentTypeId (0x0100805E9E4FEAAB4F0EABAB2600D30DB70C)

**Expected behavior**
Expected behaviour would be that the correct project property fields, as specified by the custom content type + project column config, would show as intended on the Project Status-page.

- Browser: Chrome
- Installed version: 1.26

**Comment by olemp** [comment]
Thanks! Good find and great details!

We’ll look into this for the next version! 🙏
