### ISSUE TITLE
Incorrect API-Request Url in ProjectSettings-Page resulting in 404-error

### ISSUE THREAD

**Issue by balle3201** [Puzzlepart/prosjektportalen365#447]
**Describe the bug**
It appears that some of the request url's towards SharePoint's API are incorrect, and includes "/SitePages/" as part of the request-path. This is the case at least in the Project Status-page, and results in 404-Errors, and forces the component(s) to retrieve data from the portal instead.

**To Reproduce**

1. Go to a Project Site, and navigate to "Project Status"-page
2. Open the developer toolbar in your browser
3. Look at the console-output, where you will see one or more 404 errors, due to incorrect request-urls

**Expected behavior**
The expected behaviour would be that the correct url is being used when requesting the current project's properties (in context of the current site), and not having to retrieve this from the Project Portal (in those cases where the Project Properties Item actually is present on the contextual site)

**Screenshots**
![image](https://user-images.githubusercontent.com/4190483/112443537-5d2a8d00-8d4d-11eb-8e89-616776a8efe8.png)

**About your setup**
- Browser: Google Chrome
- Installed version: 1.26

**Comment by olemp** [comment]
Thanks @balle3201! We'll look into this.
