### ISSUE TITLE
Enforce a specific Project Template for pre-provisioned Project Sites

### ISSUE THREAD

**Issue by balle3201** [Puzzlepart/prosjektportalen365#448]
**Is your feature request related to a problem? Please describe.**
We are using the Prosjektportalen 365 in conjunction with a custom provisioning solution where we create new sites/teams (various types) based on user requests. In the case of project sites, we are performing the following steps:

1. Create a new Team Site
2. Adjust settings related to sharing capabilities, guest access etc.
3. Invoking the required Site Design for "Prosjektportalen 365"
4. Adding Hub-Site association towards the Project Portal 
4. Pre-provisioning the "Project Properties" (Prosjektegenskaper) List, where we are mimicing the logic from Prosjektportalen 365 and creating a custom list and provision fields/columns based on a specific (custom) Content Type.
5. Creating an initial List Item for the specific projects (to be able to specifiy related metadata from other business applications)
6. Updating the listitem with the correct "TemplateParameters".
6. Creating a "cloned" List Item in the "Projects" (Prosjekter) List (at portal level) to ensure that we have initial data synced at both locations.

However, although we are pre-provisioning the site based on a specific Project Content Type (ProjectContentTypeId), which in turn decides which fields to "add" as the associated Project Properties Content Type (ProjectContentTypeId), the end-user can still chose to setup and configure the project site based on any of the other (potential) Project Templates (which may or may not be configured for the given Project Portal instance)

**Describe the solution you'd like**
Based on the "challenge" as described above, we suggest that you could implement a way to enforce a specific Project Template to be used when configuring the Project Site. As we see it, this could potentially be solved by storing a value along with the "TemplateParameters" which the "Project Configuration Wizard" then could resolve (against available Project Templates, as specified at portal-level) and enforce as a locked Project Template for the given site.

By doing this, you would be able to use Prosjektportalen 365 in conjunction with a custom provisioning solution, and still be able to have multiple types of projects in one single Prosjektportalen 365-instance, and enforce that the correct project template is being applied by the end-user (owner etc.) 

As of now, the only way to use Prosjektportalen 365 in conjunction with our custom provisioning solution (which requires us to have multiple types of projects), is to have multiple Project Portals, one for each of the templates we need (with a single Project Template). This is doable, but it would be far more maintainable to have all the different project types in one single portal.

**Comment by tarjeieo** [comment]
Great idea, and should be quite solvable as you say by storing a "preselected" template in a field/property bag in the site.

**Comment by balle3201** [comment]
Yes, the template reference could also be stored in the property bag on the site, as we have more control (and sufficient permissions) to do so when provisioning the site through a non-clientside context. Either place would work great in my opinion ;-)

**Comment by olemp** [comment]
Do you want to automatically start the provisioning/configuring if the site is stamped with a template or do you want to adjust default content etc in the dialog?

**Comment by balle3201** [comment]
> @balle3201 Do you want to automatically start the provisioning/configuring if the site is stamped with a template or do you want to adjust default content etc in the dialog?

I think it could be useful to be able to adjust for both scenarios? The only issue as I can see is that the optional content(s) are not tied to a specific template, unless the configuration says so (by enforcing List Content), so in that case it might be better to force a specific one which could start by itself.

**Comment by tarjeieo** [comment]
After discussion with customer: Don't auto-start the wizard, just open the wizard and have the template pre-selected (and unable to change/field deactivated).

**Comment by balle3201** [comment]
Perhaps the Property Bag on the provisioned Site could be a suitable location for this flag to be stored. That way, one would not be required to also provision the Project Properties List. In most cases a custom provisioning solution will run in a non-client environment, so storing this flag in the Property Bag would work fine (as opposed to Client Side script, where the property bag is read-only, I remember correctly).

Just a thougth :-)

**Comment by tarjeieo** [comment]
@balle3201 agreed - exactly what me and @Remi749 figured out as well. We have just implemented this, the wizard is now looking for a property "pptemplate" which should be the filename of the template.

E.g. "pptemplate"="Standardmal.txt".

We have an open PR with this change, and expect it to make it to version 1.2.7 :D

**Comment by olemp** [comment]
> @balle3201 agreed - exactly what me and @Remi749 figured out as well. We have just implemented this, the wizard is now looking for a property "pp_template" which should be the filename of the template.
> 
> E.g. "pp_template"="Standardmal.txt".
> 
> We have an open PR with this change, and expect it to make it to version 1.2.7 :D

Added support in https://github.com/Puzzlepart/prosjektportalen365/commit/039369bb45519faf4137545f6bc314f15e9b762c

**Comment by balle3201** [comment]
Excellent, @tarjeieo :-) 

Changes iare already implemented on our end here now, so we are ready for the next release.
