### ISSUE TITLE
Add FNs bærekraftsmål as column

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#454]
**Is your feature request related to a problem? Please describe.**
The relation to FNs bærekraftsmål is not available in PP365

**Describe the solution you'd like**
Add solution for 'FNs bærekraftsmål' with both:
- Termset
- Project column
- Column configuration where column by default is hidden in "all" views

Add solution for 'FNs bærekraftsdimensjoner' with both:
- Termset
- Project column
- Column configuration where column by default is hidden in "all" views

[Til FNs bærekraftsmål](https://www.fn.no/om-fn/fns-baerekraftsmaal)
[FNs bærekraftdimensjoner](https://www.fn.no/tema/fattigdom/baerekraftig-utvikling)

**Comment by olemp** [comment]
Added in #852

**Comment by olemp** [comment]
We still need a proper way to render it though.

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/7606007/198635666-783e33b2-1cd2-4c44-b8ac-d78761b536b6.png">

The current render type `Tags` doesn't use multiple lines, so the column will potentially be very wide. The coolest solution would be to actually use the images, but that's also the most advanced solution. Anyways, we need some funding to make some changes here. At least the field is ready to be filled in  🚀 

FYI @tarjeieo @pzljanb @Remi749 @okms

**Comment by pzljanb** [comment]
Could we add images to the termset along with tags, description etc?
Within the solution we then could select what to use in different settings:
Images in the portolio overview
Tags on project home
Description in status report

Or something similiar

**Comment by Remi749** [comment]
> We still need a proper way to render it though.
> 
> <img width="1681" alt="image" src="https://user-images.githubusercontent.com/7606007/198635666-783e33b2-1cd2-4c44-b8ac-d78761b536b6.png">
> 
> The current render type `Tags` doesn't use multiple lines, so the column will potentially be very wide. The coolest solution would be to actually use the images, but that's also the most advanced solution. Anyways, we need some funding to make some changes here. At least the field is ready to be filled in  🚀 
> 
> FYI @tarjeieo @pzljanb @Remi749 @okms 

FYI: We have multiline tags on the aggregated webparts. So should be a fast fix to implement.

**Comment by olemp** [comment]
> Could we add images to the termset along with tags, description etc?
> Within the solution we then could select what to use in different settings:
> Images in the portolio overview
> Tags on project home
> Description in status report
> 
> Or something similiar

Yes, endless possibilities. All about the funding. Easiest solution is tags multiline like @Remi749 mentions.
