### ISSUE TITLE
Change reference to projects properties

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#457]
**Describe the bug**
The column 'Prosjekttilknytning' in 'Tidslinjeinnhold' refer to the item in the hubsite list 'Prosjekter',
this should be changed to the current projects 'Rediger prosjektegenskaper' (list 'Prosjektegenskaper')

**To Reproduce**
Go to the list 'idslinjeinnold' and observe the link connecion on a project reference

1. Go to 'https://puzzlepart.sharepoint.com/sites/pp365/Lists/Tidslinjeinnhold/AllItems.aspx'
2. Click on the project link 'TestJan' in column 'Prosjekttilknytning'
3. Observe the links connection to the hubsites list 'prosjekter'

**Expected behavior**
Link should be to the projects 'Rediger egenskaper'

**About your setup**
- https://puzzlepart.sharepoint.com/sites/pp365

**Comment by Remi749** [comment]
@pzljanb This is OOTB, what should be done? Do you want to introduce another column for a link to the project?

**Comment by pzljanb** [comment]
> @pzljanb This is OOTB, what should be done? Do you want to introduce another column for a link to the project?Use the same column for loolkup, but add Title as a secondary column to show.
Hide original lookup column form view.

**Comment by Remi749** [comment]
Additional thing to fix: If a project is deleted, don't try to show timeline items for that project.

**Comment by Remi749** [comment]
@pzljanb, it doesn't seem possible to add additional fields in the provisioning schema for the "Tidslinjeinnhold" list and then hide the main column with the link. @tarjeieo any thoughts here?

**Comment by tarjeieo** [comment]
Discussed this with Remi. As we now will have the per-project app for administrating project timeline entries, this issue does not have that much merit anymore. And as it's not super-easy to implement either, I suggest closing it.
