### ISSUE TITLE
Multiple login prompts during install - try to avoid this

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#46]

**Comment by olemp** [comment]
We are connecting to several sites. If we can clone connections it might be possible.

**Comment by tarjeieo** [comment]
Yup. Not very important, but we can have a look if time allows

**Comment by olemp** [comment]
Doesn't look like there's a way, be can reopen if things changes.

https://github.com/SharePoint/PnP-PowerShell/issues/849
