### ISSUE TITLE
Export to excel does not work in flexible portfolio web part

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#460]
**Describe the bug**
When clicking "export to excel" nothing happens

**To Reproduce**

1. Go to e.g. Gevinstoversikt
2. Click on Export to Excel
3. Observe that nothing happens

**Expected behavior**
We should get a nice and sexy Excel file downloaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/1837390/115028771-8c07cf00-9ec5-11eb-91a2-6d11860683e5.png)

**About your setup**

- Browser [e.g. chrome, safari] Edge
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.2.6

**Comment by Petterandre** [comment]
https://github.com/Puzzlepart/prosjektportalen365/blob/f5ab531cd4fb76ef51fe0ceaaafec24a7573e65d/SharePointFramework/%40Shared/src/services/ExcelExportService/index.ts#L30

@olemp 
Got any input as to why this fails? Struggling to wrap my head around the line. It's within loadDeps().

**Comment by olemp** [comment]
> https://github.com/Puzzlepart/prosjektportalen365/blob/f5ab531cd4fb76ef51fe0ceaaafec24a7573e65d/SharePointFramework/%40Shared/src/services/ExcelExportService/index.ts#L30
> 
> @olemp
> Got any input as to why this fails? Struggling to wrap my head around the line. It's within loadDeps().

Ancient function.. We wanted (and want) to include the excel libs dynamically when the user exports. This was a common workaround for issues with `window.define` when using webpack - and loading scripts externally. It works for the other components - right? Or is this happening for all the web parts now?

**Comment by Petterandre** [comment]
> > https://github.com/Puzzlepart/prosjektportalen365/blob/f5ab531cd4fb76ef51fe0ceaaafec24a7573e65d/SharePointFramework/%40Shared/src/services/ExcelExportService/index.ts#L30
> > 
> > @olemp
> > Got any input as to why this fails? Struggling to wrap my head around the line. It's within loadDeps().
> 
> Ancient function.. We wanted (and want) to include the excel libs dynamically when the user exports. This was a common workaround for issues with `window.define` when using webpack - and loading scripts externally. It works for the other components - right? Or is this happening for all the web parts now?

The two instances I've found; AggregatedPortfolio and PortfolioOverview both fail to export anything. However, the behavior is different between the two. While AggregatedPortfolio fails with the error mentioned by Tarjei, PortfolioOverview appears to fail its try and catch with no error,

**Comment by tarjeieo** [comment]
Where are we here? What is required to get to the bottom of this one? 🤔

**Comment by olemp** [comment]
This was they to work around dynamically loading the required libs for Excel export back in the day. Maybe we changed the version of webpack or something since then. We need to find another way to load them if this doesn't work without these define statements (removing the `_define` "hack" and checking if it works).

**Comment by Petterandre** [comment]
@olemp @tarjeieo 
We have a solution, but it somewhat defeats the purpose of scriptjs. XLSX refuses to load through Scriptjs. It is working fine for Filesaver, but the xlsx property on window remains empty, unlike "saveAs" which is retrieved from Filesaver. We did try a few different versions with no luck.

I can draft a PR if you want to look closer at it?
