### ISSUE TITLE
Issue after upgrading PP from v 1.2.0 to 1.2.6

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#476]
**Describe the bug**
After upgrading and adding a new site, applying the new template and refreshing - An error show up with the title "Det skjedde en feil" and text description "Det skjedde en feil under uthenting av data fra hubområdet."

**To Reproduce**
1. Go to the Hub area
2. Click "Opprett Område"
3. Select "Gruppenettsted"
4. Select "Prosjektområde" from the dropdown list
5. Add a name and finish the wizard.
6. Wait for the template to apply to the new site
7. Refresh page
8. Error show up

**Expected behavior**
The configurator should show at step 8

**Screenshots**
![image](https://user-images.githubusercontent.com/7568950/117448011-79ba0780-af3e-11eb-8034-421c2c75fb8b.png)

**About your setup**

- Browser : Edge Chromium v.92 (Dev)
- Installed version 1.2.6 - The page /Lists/Installasjonslogg/AllItems.aspx is completely blank which is weird
![image](https://user-images.githubusercontent.com/7568950/117448571-344a0a00-af3f-11eb-9f8d-bb96d794e34c.png)
 

**Additional context**
The upgrade was done with the following command:
.\Install.ps1 -UseWebLogin -Url $url -Upgrade $true -SiteDesignSecurityGroupId $GroupID
$url and $GroupID was pre-populated with the correct info.

**Comment by LostLogic** [comment]
After about 5 minutes after posting this issue, the two main issues seems to have resolved themselves. But a new one has poked out.
After running the configuration wizard on the new prosjekt page it terminates with the following message:
![image](https://user-images.githubusercontent.com/7568950/117450163-29907480-af41-11eb-8b01-47cb6e65e382.png)

The user that created the site and ran the configuration is the same user that Install / Upgrade Prosjektportalen and is a SharePoint Admin in addition to being an owner of the ProsjektPortalen hub site and the new site.

**Comment by LostLogic** [comment]
It's worth noting that someone removed the option for users to create new sites. This setting has later been reverted and everyone should now be allowed to create new sites. But I fear that it might be something else that was disabled when the site creation option was switched off that isn't automatically switched back on again.

**Comment by trillian74** [comment]
Possible my situation? [Sharepoint 6993](https://github.com/SharePoint/sp-dev-docs/issues/6993) ? check it and add to the 6993 issue at sharepoint if same?

**Comment by tarjeieo** [comment]
Got this reported this morning from one customer, now we're seeing several reports of this error. Looking into a workaround or possibly feedback from MS if this is an intended change or an error.

Looking for customers with MS Premier Support to escalate this quicker.

**Comment by tarjeieo** [comment]
Workaround for a single project is to set DenyAddAndCustomizePages to false for the new site, and then rerun the wizard.

```
Connect-PnPOnline -Url https://tenant-admin.sharepoint.com/ -UseWebLogin
Set-PnPTenantSite -Url https://tenant.sharepoint.com/sites/projectname -DenyAddAndCustomizePages:$false
```

**Comment by tarjeieo** [comment]
Works again now it seems like, see linked issue
