### ISSUE TITLE
Word wrapping in risk section of Project status report

### ISSUE THREAD

**Issue by kiwihansen** [Puzzlepart/prosjektportalen365#477]
**Is your feature request related to a problem? Please describe.**
The user is unable to see the entire content of the risk, proximity and measure column if they exceed a character count based on column size.

**Describe the solution you'd like**
The user would like the free text fields in the risk section to use word wrapping, so the full description of the risk, proximity and measures columns is readable without adjusting the size of the columns.

**Additional context**
![image](https://user-images.githubusercontent.com/69144808/118270780-c6fb2380-b4c0-11eb-8169-40154a1c46a6.png)

**Is this something your organization is willing to contribute to financially?**
I will check with IMDI - Martin H

**Comment by danielwiese** [comment]
Fixed in #493
