### ISSUE TITLE
Change focus to newly created status report

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#479]
**Is your feature request related to a problem? Please describe.**
When creating (and saving) a new status report you will leave edit form and return to the previous report shown.

**Describe the solution you'd like**
When creating a second status report for the first time I would like to get this new report in focus when leaving the edit form by saving the report.

**Additional context**

**Comment by olemp** [comment]
@pzljanb Is this the edge case where you in the same session create a new status report, publish it, and then creates a new one right away? Requires some changes to implement this so the question is - is this a **nice to have** or is it very important?

**Comment by pzljanb** [comment]
Expected behavior should be as the user returns to the report created when saving a new report.

Maybe a indicator on the repot header indicating last report or not.

**Comment by okms** [comment]
@siifux  The "new report" form is indeed the out of the box NewForm for the status report list, so you can try to change the redirect url as you mention. Good catch!

relevant code:

https://github.com/Puzzlepart/prosjektportalen365/blob/dev/SharePointFramework/ProjectWebParts/src/components/ProjectStatus/index.tsx#L359

**Comment by siifux** [comment]
I have found out that the Url we are redirected to after saving a new report is created as a `&Source` param in the form-Url. This seems to be set in the method `editFormUrl()` under _/@shared/src/modelsStatusReport.ts_. I think we should change the param from `window.location.href` since it will grab the status report you are focusing when creating a new one, and therefore redirect you back to that spesific report. I also noticed that when refreshing the project status page without any report-Id, you are redirected to the latest one by default, so it may be an idea to just make the `&Source` param point to that url..

**Comment by olemp** [comment]
> I have found out that the Url we are redirected to after saving a new report is created as a `&Source` param in the form-Url. This seems to be set in the method `editFormUrl()` under _/@shared/src/modelsStatusReport.ts_. I think we should change the param from `window.location.href` since it will grab the status report you are focusing when creating a new one, and therefore redirect you back to that spesific report. I also noticed that when refreshing the project status page without any report-Id, you are redirected to the latest one by default, so it may be an idea to just make the `&Source` param point to that url..

New form URL probably should be the `window.location.href` without the query params. Nice find!

**Comment by siifux** [comment]
> 
> 
> > I have found out that the Url we are redirected to after saving a new report is created as a `&Source` param in the form-Url. This seems to be set in the method `editFormUrl()` under _/@shared/src/modelsStatusReport.ts_. I think we should change the param from `window.location.href` since it will grab the status report you are focusing when creating a new one, and therefore redirect you back to that spesific report. I also noticed that when refreshing the project status page without any report-Id, you are redirected to the latest one by default, so it may be an idea to just make the `&Source` param point to that url..
> 
> New form URL probably should be the `window.location.href` without the query params. Nice find!

Indeed! After checking the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Location), I'm thinking we use window.location.origin + window.location.pathname, which should make the url we want, leaving the query param behind! I'll make a draft PR on it..

**Comment by olemp** [comment]
Please close this @siifux
