### ISSUE TITLE
No project is listed

### ISSUE THREAD

**Issue by Mirandur** [Puzzlepart/prosjektportalen365#482]
**Describe the bug**
I did a fresh install of 1.2.7, following the documentation as closely I could. After creating a few test sites (both group- and communication sites), they show up under "Siste prosjekter" after some time has passed. But they are not listed anywhere else in the portal, even though my user is a member or owner of the project sites. In SharePoint admin I see they are connected to the Hub as they should be.

Thinking the installation didn't go well, I deleted the portal site and associated resources, and tried installing the older version 1.2.6, with a new site name and title, but the same thing happened there.

"Porteføljeoversikt", "Gevinstoversikt", "Erfaringslogg", "Leveranseoversikt", "Risikooversikt", and "Ressursallokering" are all empty, even hours after site creation through the portal. 
"Porteføljeinnsikt" say "Ingen prosjekter funnet." ("No project found").
The search list of projects on the "Hjem" tab says "Søket ga ingen resultater" (no search results - see screenshot below).

For installation, I used an account that is Global Admin in our Tenant, and also admin on needed SharePoint services (term store and app catalog). I used a different user to create the test sites, which has been given rights to associate sites to the hub.

**Expected behavior**
I expected the created projects to be listed.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/84563380/119103581-a0d30780-ba1b-11eb-85f0-24400354d390.png)

**About your setup**

- Browser: Google Chrome 90.0.4430.212, Microsoft Edge 90.0.818.62
- Installed version: 1.2.6, 1.2.7

**Additional context**
Both versions I tried were installed with the *-SiteDesignSecurityGroupId* switch, referencing the AD/AzureAD security group my test user for creating sites is a member of. Though because the documentation is not clear, I tried with the ObjectID for one (1.2.7), and the group name for the other (1.2.6). Does not seem to make a difference? Our SharePoint is set to allow all users to create sites.

**Comment by olemp** [comment]
Hi @Mirandur,

How long did you wait after creating the project sites?

This webpart is using search and the delay can vary from some home hours to some days in the worst cases we've seen.

**Comment by Mirandur** [comment]
5 days after the latest installation the situation is still the same...
They did show up under "Siste prosjekter" after an hour or so, but nowhere else.

**Comment by olemp** [comment]
> 5 days after the latest installation the situation is still the same...
> As mentioned, they did show up under "Siste prosjekter" after an hour or so, but nowhere else.

Hmm, not heard of this behavior before. This might have confused the search indexing a bit:

> Thinking the installation didn't go well, I deleted the portal site and associated resources, and tried installing the older version 1.2.6, with a new site name and title, but the same thing happened there.

**Comment by Mirandur** [comment]
When deleting the previous installation, I also removed the apps from the App Catalog and the Term Store folder for the installation, wanting to remove all parts before installing with the older version. The old Site and associated AAD group were permanently deleted, not just left in "Deleted Sites/Groups" in SharePoint and AAD. Might this have affected it, too? -I'm fairly new to SharePoint, and don't know much about the search indexing, yet, among other things...

**Comment by olemp** [comment]
> When deleting the previous installation, I also removed the apps from the App Catalog and the Term Store folder for the installation, wanting to remove all parts before installing with the older version. The old Site and associated AAD group were permanently deleted, not just left in "Deleted Sites/Groups" in SharePoint and AAD. Might this have affected it, too? -I'm fairly new to SharePoint, and don't know much about the search indexing, yet, among other things...

I'll try a fresh installation at my end. Would help if I could reproduce the same issues you're experiencing.

**Comment by olemp** [comment]
Tried with a fresh installation now @Mirandur.

Created 4 project sites (selected **Prosjektområde** site design).

![image](https://user-images.githubusercontent.com/7606007/119665742-f9980b00-be34-11eb-88b7-8fca0d238f05.png)


They all show up after a few minutes.

![image](https://user-images.githubusercontent.com/7606007/119665688-ed13b280-be34-11eb-8c84-ff04059c876f.png)



Can you take us through the steps you did?

**Comment by Mirandur** [comment]
Ah. I think I understand.

When clicking "Opprett område":
![image](https://user-images.githubusercontent.com/84563380/119667860-f271fc80-be36-11eb-936c-1f77098f2177.png)

I didn't realize/didn't see I had to select the "Prosjektområde" site design, the default is "Gruppenettsted":
![image](https://user-images.githubusercontent.com/84563380/119668032-17666f80-be37-11eb-83ae-1f0666999d29.png)

Creating a new test site with the correct site design, it now works.......
![image](https://user-images.githubusercontent.com/84563380/119668357-67ddcd00-be37-11eb-95f0-91517540efbf.png)

So sorry. (>.<)

I guess this issue can be closed.
