### ISSUE TITLE
GtChecklistStatus missing all choices in v1.2.7 for projects

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#484]
After changes to _jsontemplate in PR #473 all new projects are missing options for the field GtChecklistStatus 

This is the line causing the issue
https://github.com/Puzzlepart/prosjektportalen365/blob/35f2666a243c3cd6c32550dfa14545d0528f138b/Templates/_JsonTemplate.json#L693

Problem is we are redefining GtChecklistStatus for this list, where we previously were only overriding the Title column

Mitigating actions: 
1. revert change for L693 and push json file to any an all new installations we have done
2. create a delta pnp template to fix any projects created where GtChecklistStatus are missing choises
3. release new installation
4. inform customers on upgrade path

**Comment by Remi749** [comment]
Could it be the singlequotes in the Description causing this problem?

**Comment by olemp** [comment]
When was the GtChecklistStatus "override" added @Remi749 @okms?

**Comment by Remi749** [comment]
When merging this commit: cd5509f68fc1f9133d5e30550e14bc755b00e7f6

**Comment by Remi749** [comment]
We tested it, and the overriden values where never applied so we scrapped it as we were also hurrying to release the new version. The best here would probably be to just remove the fields array.

**Comment by olemp** [comment]
> We tested it, and the overriden values where never applied so we scrapped it as we were also hurrying to release the new version. The best here would probably be to just remove the fields array.

Agreed.
