### ISSUE TITLE
Porteføljeoversikt - dates in excel report is not recognized and is difficult to parse

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#487]
**Describe the bug**
I porteføljeoversikt kan man eksportere data til Excel. Det er vanvittig irriterende at startdato og sluttdato for prosjektene kommer over med feil dato, og på et format som ikke er kompatibelt med Excel. 

**To Reproduce**
1. Navigate to 'Porteføljeoversikt', e.g.

https://universityofbergen.sharepoint.com/sites/Admprosjekter/SitePages/Portef%C3%B8ljeoversikt.aspx#viewId=6

2. Download excel report
3. Open in excel, convert imported data to table (ctrl+t)

Results, dates are not formatted, even when explicitly setting the cell format as "date"

1) Startdato 11.mai 2021 blir i Excel 2021-05-10T22:00:00Z
2) Sluttdato 18.12.2024 blir i Excel 2024-12-17T23:00:00Z

**Expected behavior**
Dates are recognized by excel and parsed correctly. Time of day is not included, as its not needed.

**Additional context**
A workaround is to use a separate column to parse dates using formulas, e.g.

`=DATEVALUE(MID(G2;1;10))+TIMEVALUE(MID(G2;12;8))`

A sample report is attached. Note that the two last columns has been added and is using the above formula as a workaround.

[sample-report.xlsx](https://github.com/Puzzlepart/prosjektportalen365/files/6701762/sample-report.xlsx)

**Comment by danielwiese** [comment]
Fixed in #495
