### ISSUE TITLE
Set default site design for hubsite on install

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#491]
Currently we install the "Prosjektområde" site design upon installation of prosjektportalen. It is however up to the users to select the correct site design when creating a new Microsoft 365 group.

It has come to our attention that with the new site template experience currently being rolled out to targeted release customers we will no longer be able to select a site design/site template up front but rather after the Microsoft 365 group is created. This increases the manual steps for creating new projects, but is a viable workaround for tenants who have been enrolled in the new experience. 

![image](https://user-images.githubusercontent.com/170147/124770624-c5872e00-df3a-11eb-9686-81cc741865d4.png)
_selecting template after group creation_

Moving forward we should leverage the "default site design for joined sites" capabilites which exists for hub sites. This causes any new site being joined to this hub site to have the specified site design applied after creation. The net gain will be that moving forward we will have *fewer* steps when creating new pojects 

 `Set-PnPHubSite -Identity "https://puzzlepart.sharepoint.com/sites/pp365" -SiteDesignId (Get-PnPSiteDesign -Identity Prosjektområde).Id`

## Related issues
#490

**Comment by tarjeieo** [comment]
Somewhat related; I investigated if we could set the preview image for prosjektområde, but this is not possible as far as I can tell. I logged an issue over at PnP PowerShell; https://github.com/pnp/powershell/issues/1029

**Comment by olemp** [comment]
Closed by #492

**Comment by olemp** [comment]
@okms @tarjeieo This is not working with the latest installs from CI (dev). Any idea why?

**Comment by tarjeieo** [comment]
Because the CI is executing Install.ps1 with -SkipSiteDesign param, and the assosiaction is done within that scriptblock. Guess we should move the association (https://github.com/Puzzlepart/prosjektportalen365/blob/main/Install/Install.ps1#L236) to after the scriptblock?

**Comment by olemp** [comment]
> Because the CI is executing Install.ps1 with -SkipSiteDesign param, and the assosiaction is done within that scriptblock. Guess we should move the association (https://github.com/Puzzlepart/prosjektportalen365/blob/main/Install/Install.ps1#L236) to after the scriptblock?

Nice find. We could move it, indeed.
