### ISSUE TITLE
[Security Issue] Users with limited access have full access to all projects

### ISSUE THREAD

**Issue by LostLogic** [Puzzlepart/prosjektportalen365#496]
**Describe the bug**
Any user with access to the Prosjektportal Hub, can access projects they are not a member of with full read and write access regardless of project membership.

**To Reproduce**
1. Enter the Project Portal hub with a user who are only assigned limited access rights to one single project.
2. When entering the Project Portal, everything looks correct. Only the project the user has access to show up.
3. When clicking the menu option "Porteføljeoversikt", all the projects are listed regardless of whether the user has access or not
4. Clicking any project in the "Porteføljeoversikt" list takes the user to the project and they are able to read and change all info in the project. They enter the projects with full rights in other words and can change project status for instance

**Expected behavior**
The user is limited to viewing and editing the projects they are members of.

**About your setup**

- Browser - Edge Chromium
- Installed version - 1.2.7

--
This is quite important to fix as most projects contain personal sensitive data that are authorized for viewing only by the users of the project team.

**Comment by LostLogic** [comment]
This issue was flagged by Norsk Luftambulanse

**Comment by tarjeieo** [comment]
Hi @LostLogic, this is indeed  not expected behavior and quite surprising to me if this is a bug with Prosjektportalen. Can you verify that 
- The projects are not Public
- All employees have not been granted contribute permissions (e.g. through the "Copy groups" functionality")

Feel free to contact me at tarjeieo at puzzlepart.com to setup a screen sharing session :)

**Comment by LostLogic** [comment]
This might be an issue with how the projects are created. When you mentioned public projects, I did a spot-check and indeed found that of the projects I checked with this issue, all where public.
Is it possible to switch it over to private, or is it "locked in" once it's created as public?

**Comment by tarjeieo** [comment]
Good to find out! 👍 You can absolutely change this after they have been created, through Site information settings.

**Comment by LostLogic** [comment]
Thanks! I've forwarded the info with a step-by-step instruction on how to switch it to Private. I'll close the issue once I've confirmed with them that it resolves this issue.
Cheers!

**Comment by LostLogic** [comment]
As stated earlier, this seems to be a user usage issue. Thank you for the feedback.
Closing issue
