### ISSUE TITLE
Projecttimeline project webpart page

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#497]
Add a new webpart to projects that connects the projecttimeline webpart developed earlier for the portfolio #429 .

A projecttimeline webpart for single projects similar to the portfolio variant but filtered for a certain project. The user will be able to edit and update where the changes will be synced to the portfolio list.

The projectimline webpart page is set up with the following content:
- Timeline view filtered on current project
- Display the timeline data for the current project
  - Must be able to edit existing data
  - Must be able to add new data for their project

Additions:
- Include new columns for displaying hours (cost/budget)
- #457 

Extra:
- Ability to delete timeline items from project

**Comment by olemp** [comment]
@Remi749 @tarjeieo Added content type etc to #503 and merged it as-is. CI is now building, then we can check the functionality in the new installation made by the CI.

https://github.com/Puzzlepart/prosjektportalen365/actions/runs/1333205080
