### ISSUE TITLE
Add a new project status section "Project timeline"

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#506]
**Is your feature request related to a problem? Please describe.**
We're currently developing https://github.com/Puzzlepart/prosjektportalen365/issues/497 which adds a web part to a page in each project. This web part would be really nice to also show in the project status page.

**Describe the solution you'd like**
Add a new status in the central list for status configuration. This needs to be a new content ttype in the list which has a custom section type - see how gevinstoversikt is implemented as a section in the project status.

Width should match the start-stop date for the project.

**Comment by olemp** [comment]
> We'll postpone this due to issues (#551). Setting milestone to 1.4.0 for now.

Are we planning on any refactoring of ProjectTimeline @Remi749? I guess we shouldn't add more timeline stuff (like this one) before that's done (if we're planning it).

**Comment by Remi749** [comment]
> > We'll postpone this due to issues (#551). Setting milestone to 1.4.0 for now.
> 
> Are we planning on any refactoring of ProjectTimeline @Remi749? I guess we shouldn't add more timeline stuff (like this one) before that's done (if we're planning it).

Yes, so this should be "Low priority". I've updated the labels.

**Comment by olemp** [comment]
Closed as wontfix.
