### ISSUE TITLE
Template selector extension in document web part on front page doesn't look good

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#51]
Not enought width for it.

![image](https://user-images.githubusercontent.com/7606007/62608505-36ada900-b900-11e9-81c2-ff37e5e44941.png)

**Comment by olemp** [comment]
Proposed solution:

Move Documents to a 1 column row:

![image](https://user-images.githubusercontent.com/7606007/62608554-51801d80-b900-11e9-969d-ce3b8a9fd46b.png)

and put news and calendar on the bottom in a 66-33 row

![image](https://user-images.githubusercontent.com/7606007/62608606-6b216500-b900-11e9-9af7-f0a2b34b9fdd.png)

**Comment by olemp** [comment]
Any input @tarjeieo?

**Comment by olemp** [comment]
Any input @okms @damsleth @tarjeieo?

**Comment by olemp** [comment]
Any input @okms @damsleth @tarjeieo?

**Comment by olemp** [comment]
Implemented in https://github.com/Puzzlepart/prosjektportalen365/issues/63

**Comment by damsleth** [comment]
> Any input @okms @damsleth @tarjeieo?

Good solution. Alternative would be to drop text, i.e. "icon only" for smaller screens.
1 column row works better IMO.
👍
