### ISSUE TITLE
Change phase dialog does not trigger update

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#518]
**Describe the bug**
When changing phase directly from 'change phase dialog' a update is not triggered.
Leaving the central 'prosjekter' liste with old values.
Related to #381 ?

**To Reproduce**
- Select a project from Portfolio Home
- In central 'prosjekter' list verify value of 'Fase (text)' value
- From project home page select a phase to be set
- Observ values in central project list not being updated
Repeat:
- Select a project from Portfeføljeoversikt
- In central 'prosjekter' list verify value of 'Fase (text)' value
- From project home page select a phase to be set
- Observ that values in central project this time is updated

**Expected behavior**
Update of project metadata to central prosjekter liste to be triggered on all attempts, regardless of entrypoint into project

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/132511767-30de0725-77fa-4cae-a830-2b8480914fab.png)

**About your setup**

- Chrome
- 1.2.8

**Additional context**

**Comment by okms** [comment]
fixed in pr #519 , backported to dev
