### ISSUE TITLE
Regressions caused by node 12 / ui fabric upgrade (PR #509)

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#521]
**Describe the bug**
PR #509 upgraded the spfx solutions to node 12 and as part of the upgrade, ui fabric was upgraded from 6 to 7. This issue is for collecting UI issues caused by this upgrade.

**To Reproduce**
Pull dev branch, build, install in you tenant.

**Screenshots**
## Project setup dialg
Issue: alignment of buttons. Box not tall enough, should match old size. 
### Old dialog
![image](https://user-images.githubusercontent.com/170147/132520718-84bbaf90-6ef8-4294-a10d-08a49da8e8f4.png)

### New dialog
![image](https://user-images.githubusercontent.com/170147/132520759-4e823259-e8b8-4d02-b854-1a1d6eb7f22b.png)

**Comment by olemp** [comment]
@okms We could revert the `office-ui-fabric-react` version or try to use the `@fluentui/react` package?

**Comment by okms** [comment]
[some context](https://github.com/microsoft/fluentui/issues/14789) if we upgrade to `@fluentui/react`
