### ISSUE TITLE
Filter bug when switching list-view

### ISSUE THREAD

**Issue by siifux** [Puzzlepart/prosjektportalen365#545]
**Describe the bug**
When I choose a filter and switch view, the filter still works, but when opening the filtering menu, it's not toggled anymore. See video for reference..

**To Reproduce**

1. Go to '[Porteføljeoversikt](https://prosjektportalen.sharepoint.com/sites/pp365/SitePages/Portef%C3%B8ljeoversikt.aspx)'
2. Select one or more filter(s)
3. Switch to a new view
4. Check that the filter checkboxes are not toggled anymore

**Expected behavior**
I expect that the checkboxes for filters are toggled, when I select certain filter(s) and switch views.

**Screenshots**
https://user-images.githubusercontent.com/36504406/136960733-f906cc2b-7a62-4efe-8360-dcf221e6043d.mp4

**Comment by tarjeieo** [comment]
#620 closes this
