### ISSUE TITLE
Automatic versioning of spfx packages based of the main package.json

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#552]
All versioned artefacts contained in a pp365 release should have the same version number. The rationale behind this is 

a) simplify support. By checking the version number we can ensure all artefacts have been updated and are 1:1 with what was included in the release package
b) simply creating new releases. Currently, updating the version number of spfx packages adds to the manual load when creating a new release and can be forgotten
c) we do not want to have to test each prosjektportalen release against a set of supported spfx packages. each release supports the spfx packages associated with that release. 

Suggested solution from @olemp is to add a node script for automatically stamp version number on the spfx packages during build. We should set the version to be the same as the one in our main [package.json](https://github.com/Puzzlepart/prosjektportalen365/blob/main/package.json)

cc: @pzljanb @tarjeieo @olemp

**Comment by olemp** [comment]
@okms @tarjeieo Versioning script is added as part of #561. I suggest we go straight ahead to `v1.3.4` after the release of `v1.3.0` due to the shared package being the furthest ahead version wise at `v1.3.4`. Republishing **npm** packages is a nightmare.
