### ISSUE TITLE
Own projects not selectable in Porteføljeoversikt

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#553]
**Describe the bug**
Project not highlighted and selectable in Porteføljeoversikt

**To Reproduce**

1. While loged in as our admin user
2. Go to 'https://puzzlepart.sharepoint.com/sites/pp365/SitePages/Portef%C3%B8ljeoversikt.aspx#viewId=1'
2. Identify thar project is unable to select
3. Go to 'https://puzzlepart.sharepoint.com/sites/TestJanv130_5/SitePages/ProjectHome.aspx'
4. Verify access as expected

**Expected behavior**
Project shouls be selectable

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/137134903-f7364fc2-f4f9-4146-bab4-8f3428f93c58.png)

![image](https://user-images.githubusercontent.com/58074707/137134838-ea055df3-29ed-428c-adf8-dece95d15c69.png)

**About your setup**

- Browser [Edge]
- Installed version [Dev]

**Additional context**

**Comment by Rundez** [comment]
Seems like this problem is fixed. 5-10 minutes after project creation it goes from gray to selectable. Can you verify? @pzljanb
