### ISSUE TITLE
Prosjektstøtte not showing in Porteføljevisning

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#555]
**Describe the bug**
Selected values for Prosjektstøtte not showing in Porteføljeoversikt

**To Reproduce**
Have a look at TestJanv130_5

1. Go to 'TestJanv130_5'
2. Verify selected values
3. Go to Porteføljevisning
4. Verify missing values in corresponding report

**Expected behavior**
Values as selected in Project should be visible in Porteføljevisning

**Screenshots**

**About your setup**

- Browser [Edge]
- Installed version [Dev]

**Additional context**
Same error in both upgraded and new installation

**Comment by Rundez** [comment]
Found the problem. Its mapped to refinablestring60, while prosjektkolonner pointed to 61.

**Comment by tarjeieo** [comment]
Confirmed working
