### ISSUE TITLE
Add the project with start and stop dates to the project's timeline

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#562]
**Is your feature request related to a problem? Please describe.**
When using the new project timeline feature within a project, I don't see the start and stop dates for the whole project.

**Describe the solution you'd like**
Add a timeline entry as the first entry in the timeline overview with the project's start and stop dates. Example:
![image](https://user-images.githubusercontent.com/1837390/137354637-dbcc23cb-273c-4c12-8b1a-248d4db0f7d3.png)

If this is super-simple @Remi749 we should aim to squeeze it inside 1.3.0 - if this requires a bit more work let's save it for the next release. Up to you ;)

**Comment by Remi749** [comment]
It uses REST request to retrieve. Try to replicate the bug with a new Project.

**Comment by tarjeieo** [comment]
The bug happens each time... Not sure why. Doesn't help to refresh, navigate back and forth either. Investigating the network tab, I see that the REST-queries to Prosjektegenskaper is being executed successfully and the date values are in the returned JSON.

`{"odata.metadata":"https://puzzlepart.sharepoint.com/sites/EspensEgenOnlyFansSamling/_api/$metadata#SP.ListData.ProsjektegenskaperListItems/@Element","odata.type":"SP.Data.ProsjektegenskaperListItem","odata.id":"8bdc3e41-ab73-439c-acd4-b9c87ee003d2","odata.etag":"\"2\"","odata.editLink":"Web/Lists(guid'c30e70a0-16b1-49f7-90b3-59a91ee80f51')/Items(1)","FileSystemObjectType":0,"Id":1,"ServerRedirectedEmbedUri":null,"ServerRedirectedEmbedUrl":"","ContentTypeId":"0x01008A1A30AE8F8ED14EAD4391A595325FF1","Title":"Espens Egen OnlyFans Samling","ComplianceAssetId":null,"GtProjectFinanceName":null,"GtProjectNumber":null,"GtArchiveReference":null,"GtProjectServiceArea":[],"GtProjectType":[],"GtProjectPhase":null,"GtProjectManagerId":null,"GtProjectManagerStringId":null,"GtProjectOwnerId":null,"GtProjectOwnerStringId":null,"GtProjectSupportId":null,"GtProjectSupportStringId":null,"GtGainsResponsibleId":null,"GtGainsResponsibleStringId":null,"GtStartDate":"2021-10-01T22:00:00Z","GtEndDate":"2022-10-28T22:00:00Z","GtProjectGoals":null,"GtGroupId":null,"GtSiteId":"00000000-0000-0000-0000-000000000000","GtSiteUrl":null,"GtLastSyncTime":null,"GtProjectLifecycleStatus":"Aktivt","GtProjectPhaseText":null,"GtProjectServiceAreaText":null,"GtProjectTypeText":null,"GtProjectTemplate":null,"ID":1,"Modified":"2021-10-14T20:59:42Z","Created":"2021-10-14T20:55:19Z","AuthorId":9,"EditorId":9,"OData__UIVersionString":"2.0","Attachments":false,"GUID":"1627ac20-db7e-470e-97b7-877ede4622ee"}`
