### ISSUE TITLE
Project dialog does not display in the portfolio overview when selecting a project

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#563]
**Describe the bug**
In the portfolio overview, when selecting a project, I expect a popup dialog with information about the project and a link to the project site. Currently, the row is selected and nothing happens.

**To Reproduce**

1. Go to Portfolio overview
2. Click on a project

**Expected behavior**
 I expect a popup dialog with information about the project and a link to the project site.

**Screenshots**
![image](https://user-images.githubusercontent.com/1837390/137355462-53fec71b-833e-463e-b067-0bfcb9a8b32a.png)

**About your setup**

- Browser [e.g. chrome, safari] Edge
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.3.0

**Comment by olemp** [comment]
> https://puzzlepart.sharepoint.com/sites/pp365_1355733343/SitePages/Portef%C3%B8ljeoversikt.aspx#viewId=2

It can take more than 35 minutes.

It works for all projects [on this installation](https://puzzlepart.sharepoint.com/sites/pp365_1345050985/SitePages/Portef%C3%B8ljeoversikt.aspx#viewId=2).
