### ISSUE TITLE
Retain historic list data in project status after publishing

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#566]
**Is your feature request related to a problem? Please describe.**
Replacement of #374 

**Describe the solution you'd like**
If we had some way of retaining the different list elements at time of publishing, we could still show list elements instead of removing the content completely. A kind of version history. 

Could storing the different listelements as JSON objects in the Prosjektstatus list element be a possible solution? This would require a relatively large change.

Very much up for discussion, but the general idea I have is:
- Create one field in the Prosjektstatus list per list.
- At the time of publishing, save list elements as JSON in corresponding list fields
- When browsing reports, have a check for whether it is Published or not.
- If published, parse JSON to the list views.

I have not researched technical possibility, may not even be possible. Discussion/Feedback encouraged.

**Comment by olemp** [comment]
Fixed in #882
