### ISSUE TITLE
Avoid refreshing after deleting project timeline item from project

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#569]
**Is your feature request related to a problem? Please describe.**
Can we avoid refreshing the page after deleting a timeline item?

**Describe the solution you'd like**
-

**Additional context**
![image](https://user-images.githubusercontent.com/7606007/137478363-f73d657b-bd57-4385-b6e4-a82523194a51.png)

**Comment by tarjeieo** [comment]
#596 closes this
