### ISSUE TITLE
Redirected to wrong portfolio view when browsing project portfolio

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#575]
**Describe the bug**
When navigation to project portfolio, I'm being redirected to the wrong view, not the default one.

**To Reproduce**

1. Go to portfolio overview
2. Observe that the default view is not selected

**Expected behavior**
I expect to be redirected to the default view when I'm not selecting a specific view

**Environment**
Seeing this in two different PP instances with version 1.3.0 in Edge

**Comment by tarjeieo** [comment]
Seeing that this is actually a setting in the web part props!? And it's set to "Avsluttede prosjekter".
![image](https://user-images.githubusercontent.com/1837390/137998036-e1631c91-b497-4a64-afca-f3d6b64b239a.png)

@olemp do you min clarifying this? Does this override the default view setting of the portfolioviews list? And is it safe to assume that someone has tukla with it in our instance?

**Comment by olemp** [comment]
> Seeing that this is actually a setting in the web part props!? And it's set to "Avsluttede prosjekter". ![image](https://user-images.githubusercontent.com/1837390/137998036-e1631c91-b497-4a64-afca-f3d6b64b239a.png)
> 
> @olemp do you min clarifying this? Does this override the default view setting of the portfolioviews list? And is it safe to assume that someone has tukla with it in our instance?

The default view can be set in the web part properties aswell as on the view itself - this is to allow for different webparts on different pages to have a different default.

**Comment by olemp** [comment]
> > > Seeing that this is actually a setting in the web part props!? And it's set to "Avsluttede prosjekter". ![image](https://user-images.githubusercontent.com/1837390/137998036-e1631c91-b497-4a64-afca-f3d6b64b239a.png)
> > > @olemp do you min clarifying this? Does this override the default view setting of the portfolioviews list? And is it safe to assume that someone has tukla with it in our instance?
> > 
> > 
> > The default view can be set in the web part properties aswell as on the view itself - this is to allow for different webparts on different pages to have a different default.
> 
> Awesome feature! I assume that someone has tukla in our environment then. Closing this issue

![image](https://user-images.githubusercontent.com/7606007/138057437-5985b0d2-243c-47d8-8d63-bbc5470fa4a4.png)
