### ISSUE TITLE
Support rendering of user fields in project information

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#576]
**Describe the solution you'd like**
Support rendering of multi-user fields in project information.

E.g. Persona like in the portfolio overview.

**Additional context**
![image](https://user-images.githubusercontent.com/7606007/138245462-43cd2004-5bf3-4a80-97d3-de97c6952433.png)

**How to test**

- Add prosjektstøtte-members to a project
- Observe that the users are displayed in a beatiful way on the frontpage of the project

**Comment by tarjeieo** [comment]
How to test:
1. Add prosjektstøtte-members to a project
2. Observe that the users are displayed in a beatiful way on the frontpage of the project
3. Observe that the users are displayed in a beatiful way in the project tooltip in the project portfolio overview

**Comment by olemp** [comment]
> How to test:
> 
> 1. Add prosjektstøtte-members to a project
> 2. Observe that the users are displayed in a beatiful way on the frontpage of the project
> 3. Observe that the users are displayed in a beatiful way in the project tooltip in the project portfolio overview

Won't be visible in portfolio overview for 1.3.0. Updated issue description with "How to test".
