### ISSUE TITLE
Edit timeline item on double click

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#581]
**Is your feature request related to a problem? Please describe.**
It's just a suggestion for now, mates.

**Describe the solution you'd like**
I'd like to edit a timeline item by double clicking it.

**Additional context**
![image](https://user-images.githubusercontent.com/7606007/138090705-e77b8389-b0fe-4509-9198-7fa690187442.png)

**Comment by okms** [comment]
Legg til en knapp på callouten istedenfor dobbelklikk. Mer oppdagbart
