### ISSUE TITLE
Have anyone installed 2 portals - each in a separate site collection scoped app catalogue on the same tenant? #notabugbutaquestion

### ISSUE THREAD

**Issue by trillian74** [Puzzlepart/prosjektportalen365#593]
Sorry for not labelling this correct, but i wanted to check with you if it's possible? Before i mess things up:)

**Comment by tarjeieo** [comment]
Multiple installations should work fine. Not tried with site collection app catalogs, as some of the resources will need to be available from projects. Feel free to share any findings if you tried :)

**Comment by trillian74** [comment]
thanx for feedback, your thoughts are the same as mine - and i think i'll refrain because i don't see how the installed webparts on projectsites will get picked from the portefolio site's app catalogue. i'll close this @tarjeieo
