### ISSUE TITLE
Avoid refreshing the page after deleteing status report

### ISSUE THREAD

**Issue by TinHoangVu** [Puzzlepart/prosjektportalen365#597]
**Is your feature request related to a problem? Please describe.**
Can we avoid refreshing the page when deleting a status report?

**Describe the solution you'd like**
Would like to avoid refreshing the whole page when deleting a status report.

**Additional context**
![image](https://user-images.githubusercontent.com/88658344/144017266-704d0891-adbd-4a1f-b72f-101bb402f0cf.png)

**Comment by tarjeieo** [comment]
Closed by #599
