### ISSUE TITLE
Multiple project property elements can be created by the setup wizard

### ISSUE THREAD

**Issue by Rundez** [Puzzlepart/prosjektportalen365#603]
**Describe the bug**
If a user aborts a project setup that is started, an element will still be written to "Prosjektegenskaper". This can also happen if provisioning solutions that reuse the wizard is used. 

**To Reproduce**

1. Create a new project
2. Select a template and run the wizard
3. Abort the setup (do a page refresh)
4. The wizard will now restart
5. Let the wizard completely setup the project
6. Check /lists/prosjektegenskaper
7. Two elements should be displayed

**Expected behavior**
The wizard should do a check if a Prosjektegenskaper list element already exists and update it, rather than creating a new element. 

**Additional context**
I have been working with a solution in program. Will soon link a PR to this issue.

**Comment by tarjeieo** [comment]
Should be closed by #604
