### ISSUE TITLE
Planner web part does not show tasks for last column 

### ISSUE THREAD

**Issue by Rundez** [Puzzlepart/prosjektportalen365#605]
**Describe the bug**
The planner web part in each project are missing the tasks from the last swimlane/column.  If the view is changed to "tavle", all columns are displaying the right information. I have noticed this issue in multiple tenants. 
![image](https://user-images.githubusercontent.com/38385042/145988233-ed7bcbc8-86d9-4464-9c61-596abda63798.png)

**To Reproduce**
Create a project. When the project is created, the tasks in the last column will not be shown.
This also happens if you add the web part to an arbitrary site. 

**About your setup**
- Happens in Chrome, Edge
- Have cleared cache

**Additional context**
I have created a MS-support ticket.

**Comment by Rundez** [comment]
MS-support is on this, but it could take a while.

**Comment by tarjeieo** [comment]
Closing this as there is nothing we can do
