### ISSUE TITLE
Project timeline does not work if the project doesn't have a start or end date

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#609]
**Describe the bug**

**To Reproduce**

1. Go to a new project
2. Click on project timeline
3. Add timeline elements
4. See that they are not visible in the web part

**Expected behavior**
Timeline elements should be visible.

**About your setup**

- Browser [e.g. chrome, safari]: Edge
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]: 1.3.0

**Additional context**
If you add start and end date in the project properties, timeline elements are visible.

**Comment by TinHoangVu** [comment]
This does not seem like an issue anymore. Tested on multiple tenants.
