### ISSUE TITLE
Project home page: Add button for setting title, description and privacy settings

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#61]
On the project home page, next to the "rediger egenskaper" / "edit properties" button we should have another button to set title, description and privacy settings for the project

The OOB js method _spLaunchSiteSettings() will launch the correct panel, we need to add a hyperlink with href=javascript:_spLaunchSiteSettings()

**Comment by olemp** [comment]
Implemented in https://github.com/Puzzlepart/prosjektportalen365/commit/b06560c5ea3bb48022861efb70ec58e114193ed9
