### ISSUE TITLE
Help text beneath "Vis i portefølje" in the form for "Gevinstanalyse og gevinstrealiseringsplan" display "Risiko" insted of "Gevinst"

### ISSUE THREAD

**Issue by danielwiese** [Puzzlepart/prosjektportalen365#615]
**Describe the bug**
Help text beneath "Vis i portefølje" in the form for "Gevinstanalyse og gevinstrealiseringsplan" display "Risiko" insted of "Gevinst"
It looks like the help text is ment for the "Risiko" form, so the text must be changed to suit the "Gevinst" form.

**To Reproduce**
Go to a project, open "Gevinstanalyse og gevinstrealiseringsplan", click "Ny" and scroll down to "Vis i portefølje", read the helo text and see that it says "risiko".

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/61320379/148357033-9308a9e0-9832-49af-a153-6030caf1cc56.png)

**About your setup**

- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]

**Additional context**

**Comment by Petterandre** [comment]
@tarjeieo 

We are using the same GtShowInPortfolio column for Uncertainties and Benefits.

Should we just reformulate the description from 

"Velg 'Ja' dersom usikkerheten skal synliggjøes i den sentrale risikooversikten på porteføljenivå (gjør risikoen synlig for alle med tilgang til prosjektporalen og prosjektet)"

To :
"Velg 'Ja' dersom elementet skal synliggjøes i den sentrale oversikten på porteføljenivå (gjør elementet synlig for alle med tilgang til prosjektportalen og prosjektet)"

Thoughts?

(Also found a typo here)

**Comment by tarjeieo** [comment]
It's a good solution - go for it!
