### ISSUE TITLE
Visuell oppgradering av prosjektkortene

### ISSUE THREAD

**Issue by siifux** [Puzzlepart/prosjektportalen365#621]
**Please describe.**
We want to upgrade the visuals of the PP365 project cards. It would be a lot better if we could improve how they look and feel. Today the pictures takes up a lot of space, and it doesn't really look great when a project is missing one as well. 

**Additional context**
Screenshot for referance: 
![image](https://user-images.githubusercontent.com/36504406/150766606-f45e4b93-77b4-4bb9-9baf-4da6a1554ea7.png)

**Comment by tarjeieo** [comment]
Feedback/tasks

- [ ] Show the project status (GtProjectLifecycleStatus)
- [ ] Have the phase label colors be customizable in one way or another
- [ ] Try squared tiles

**Comment by olemp** [comment]
@siifux Could you also add shimmer while loading?

**Comment by siifux** [comment]
> 

The Phase level is not customizable, but I have made it so that it will be either green og blue based on the GtPhaseLevel!

**Comment by siifux** [comment]
> Feedback/tasks
> 
>     * [x]  Show the project status (GtProjectLifecycleStatus)
> 
>     * [x]  Remove start date
> 
>     * [x]  Try squared tiles
> 
>     * [x]  Label for Tjenesteområde (GtProjectServiceArea)
> 
>     * [x]  Label for Prosjekttype (GtProjectType)
> 
>     * [x]  Have the phase label colors be customizable in one way or another

The Phase level is not customizable, but I have made it so that it will be either green og blue based on the GtPhaseLevel!

**Comment by olemp** [comment]
Could you create a draft PR from your branch @siifux?

**Comment by siifux** [comment]
> Could you create a draft PR from your branch @siifux?

Will do ✅

**Comment by siifux** [comment]
> Could you create a draft PR from your branch @siifux?

You can access the created PR [here](https://github.com/Puzzlepart/prosjektportalen365/pull/691)

**Comment by olemp** [comment]
> > Could you create a draft PR from your branch @siifux?
> 
> You can access the created PR [here](https://github.com/Puzzlepart/prosjektportalen365/pull/691)

I also connected the PR to this issue.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/7606007/161556705-b7dfb732-4aaa-44b3-b115-20660c116b35.png">

You can also add the following in the PR description:

`Closes #621`

.. and it will link the PR to the issue automatically.

**Comment by olemp** [comment]
Tried to get `dev` changes into your branch https://github.com/Puzzlepart/prosjektportalen365/tree/design-facelift @siifux, but the branches are just too different now. 

What is the main changes you did, and did you plan to do anything else?

**Comment by siifux** [comment]
@olemp Could we maybe set 30 minutes off in the calender whenever you got time, and go through the changes together? Been a while but it would be great to get into it again.
