### ISSUE TITLE
Project home site "Phase bar" does not sync to portfolio when used to change project phase

### ISSUE THREAD

**Issue by danielwiese** [Puzzlepart/prosjektportalen365#628]
**Describe the bug**
When I try to change or set phase from the project home site using the phase bar, the phase change is not syncronized to portfolio level as it automatically should do. This results in the portfolio overview not beeing updated with the correct project phase.

If I hit F5 after the phase has been change, then I see te pop-up telling me it is beeing synced to portfolio level, but if I don't manually refresh the page, nothing happens. 

Also, if I use the project properties form to change phase, then the sync pop-up is visible on screen as soon as I have saved the form and the home page is loaded, as expected. 

I have seen and tested this in multiple tenants using the 1.3.0 and 1.3.1 version of PP365, including our own demo tenant; prosjektportalen.sharepoint.com

**To Reproduce**

**Expected behavior**
Sync to portfolio should be done automatically as soon as the phase change has been done

**Screenshots**

**About your setup**

- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]

**Additional context**

**Comment by okms** [comment]
Confirmed. It appears the dialog does not force a page refresh on close, which is the expected behaviour
