### ISSUE TITLE
Duplikates on Konfigurasjon.aspx

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#631]
**Describe the bug**
Konfigurasjon.aspx page keeps 2 items for 'Maloppsett'

**To Reproduce**

1. Go to [Test instanse](https://puzzlepart.sharepoint.com/sites/pp365_1780255026)
2. Verify [Konfigurasjon.aspx page](https://puzzlepart.sharepoint.com/sites/pp365_1780255026/SitePages/Konfigurasjon.aspx)
3. See error reflected in double up of 'Maloppsett'
4. See picture for inspiration

**Expected behavior**
Only one item of this element on the konfigurasjon.aspx page

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/152104721-58325b1b-c972-4ead-a03b-ea8ddc1288a0.png)

**About your setup**

- Browser [Chrome]
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]

**Additional context**

**Comment by tarjeieo** [comment]
Resolved
