### ISSUE TITLE
Old version number used in build

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#632]
**Describe the bug**
version number is not updated in the Project configurator window

**To Reproduce**

1. Go to '...'[Test Project not configured](https://puzzlepart.sharepoint.com/sites/TestJlin_SlettMeg)
2. Verify project configurator window is displayed (refresh page if not)
3. See wrong verioning number in upper right corner
4. Verify the same error with different outcome in [Installasjonslogg](https://puzzlepart.sharepoint.com/sites/pp365/Lists/Installasjonslogg/AllItems.aspx)

**Expected behavior**
'v1.3.2' to be displayed instead of v1.3.0 / v1.3.1

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/152106164-a0072fa0-aea1-431d-95e2-da7ccde2de61.png)
![image](https://user-images.githubusercontent.com/58074707/152106756-bf60cc0a-2dd1-4e70-87aa-c0ef97370d4c.png)

**About your setup**

- Browser [chrome]
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]

**Additional context**

**Comment by tarjeieo** [comment]
Will be updated when the official release is out
