### ISSUE TITLE
Incorrect formating of currency fields in Porteføljeoversikt

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#635]
**Describe the bug**
Currency fields nor properly formatted in views on Portfolio level

**To Reproduce**

1. Go to [Portfolio view](https://puzzlepart.sharepoint.com/sites/pp365_1780255026/SitePages/Portef%C3%B8ljeoversikt.aspx#viewId=4)
2. Make sure the view 'Økonomi' is selected
3. See faulty formatting
4. Compare with data in statusreport from [Project](https://puzzlepart.sharepoint.com/sites/TestJlin_132_01)

**Expected behavior**
Currency should have been formatted equally in all positions where used.
This includes currency symbol (kr, $, ....)

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/152141397-bc78070d-efaf-4905-91ec-ab5ba35c5aeb.png)

**About your setup**

- Browser [chrome]
- Installed version [1.3.2]

**Additional context**

**Comment by olemp** [comment]
@pzljanb I don't see what's wrong with the formatting here? (cc @tarjeieo)

**Comment by tarjeieo** [comment]
Might be that we should add thousand separator?

**Comment by olemp** [comment]
> Might be that we should add thousand separator?

That makes sense. I didn't read that from the issue desription.

**Comment by olemp** [comment]
Solved in #694

**Comment by pzljanb** [comment]
> > Might be that we should add thousand separator?
> 
> That makes sense. I didn't read that from the issue desription.

Not the best description form my side, but the case was that we had different formatting in the statusreport compared with the portfolio overview

**Comment by olemp** [comment]
> > > Might be that we should add thousand separator?
> > 
> > 
> > That makes sense. I didn't read that from the issue desription.
> 
> Not the best description form my side, but the case was that we had different formatting in the statusreport compared with the portfolio overview

I wouldn't call it _faulty formatting_. Missing thousand separator would be better. Anyways, it's fixed and ready for next patch version.

**Comment by pzljanb** [comment]
> > > > Might be that we should add thousand separator?
> > > 
> > > 
> > > That makes sense. I didn't read that from the issue desription.
> > 
> > 
> > Not the best description form my side, but the case was that we had different formatting in the statusreport compared with the portfolio overview
> 
> I wouldn't call it _faulty formatting_. Missing thousand separator would be better. Anyways, it's fixed and ready for next patch version. 🙌

That's fine, and a nice update. But on the time of Issue creation there was some uncertainty related to change to be done in the portfolio overview or the statusreport
