### ISSUE TITLE
"Title" field is not visible when duplicating existing "Fasesjekkliste" or "Planneroppgaver" in "Områdeinnhold" from portfolio level

### ISSUE THREAD

**Issue by danielwiese** [Puzzlepart/prosjektportalen365#636]
**Describe the bug**
During testing of 1.3.2 I have been testing the new template arcitecture. When I try to duplicate existing "Fasesjekkliste" or "Planneroppgaver" from "Områdeinnhold" I see that I am missing the "Title" field in the new list which results in not being able to use "Ny" to create new list elements.

I can use "Rediger i hurtigvisning" and fill in the title field from there, this also updates the list, and is a workaround for now, but end users will need the "Ny" form to contain "Title" for it to make sense for them.

I have tried to create a new blank list in the same portfolio, then duplicate this list, and this turns out as expected, with "Title" field visible. I have also tried to create a new list in another teamsite, this also works fine, so the issue only applies to "Fasesjekkliste" and "Planneroppgaver" on PP365 portfolio level.

I experience the same issue when testing in 1.3.1 in our demo environment prosjektporalen.sharepoint.com

**To Reproduce**

Go to "Områdeinnhold" on PP365 portfolio level
Click "Ny" and select list
Choose "Fra eksisterende liste" and choose e.g "Fasesjekkliste" or "Planneroppgaver"
Give it a name and save
Click the list and try to add list element using "Ny" button
See that "Title" is not visible
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/61320379/152150027-2251aa4e-3c97-49e9-a903-9282e0ddf6a3.png)

**About your setup**

- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]

**Additional context**

**Comment by olemp** [comment]
@danielwiese I wouldn't recommend duplicating the list. Just create a new list and add the content type "Sjekkpunkt".

_Not sure we can do anything to resolve this @tarjeieo (fyi @okms)_

**Comment by danielwiese** [comment]
Ok, thank you @olemp. As a minimum this should inlcuded in the admin manual for those who dare doing this themselves. cc: @pzljanb

**Comment by olemp** [comment]
> Ok, thank you @olemp. As a minimum this should inlcuded in the admin manual for those who dare doing this themselves. cc: @pzljanb

Agreed.

This seems like an issue with the duplicate functionality. We're just creating a regular list and adding our content type. Not anything we can do from a technical perspective.
