### ISSUE TITLE
Status report: New status adds a new element and associates it with the project. User is redirected to the EditForm, NOT NewForm

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#64]
When adding a new status report, a new element is added to the Status Report List over at the hub site, before the user is redirect to the edit form for the new element. This status report thus can be associated with the correct project. The new element can be a copy of the last status report for the current project

**Comment by olemp** [comment]
I might be complicating things thinking month/year for the reports. Should we just do date (use Created date)?

**Comment by olemp** [comment]
I might be complicating things thinking month/year for the reports. Should we just do date (use Created date) @okms @tarjeieo?

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/issues/64
