### ISSUE TITLE
HubSite service failing

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#640]
**Describe the bug**
sp-hubsite-service fails when trying to fetch hubsite web. To avoid this, we need to implement a hubsite service in Shared 

**To Reproduce**
Create a new instance of PP
Immediately create a new project
The project setup dialog fails

**Expected behavior**
It should not be necessary for the search to catch up for projects to be creatable

**Fix**

We will create a new HubSiteService in @Shared and remove the use of sp-hubsite-service npm package

**Comment by Petterandre** [comment]
@pnp/sp/hubsites is exclusive to version 2. Stuck with this for now

**Comment by olemp** [comment]
> @pnp/sp/hubsites is exclusive to version 2. Stuck with this for now

Yes, the npm package works well for now. We can reopen this at a later time if needed.

**Comment by olemp** [comment]
We moved the usage of `sp-hubsite-service` to PortfolioDataService in https://github.com/Puzzlepart/prosjektportalen365/pull/923.

**Comment by olemp** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/7606007/209309894-5110c519-a1b2-48c9-9124-6139dedae57b.png">

**Comment by olemp** [comment]
> <img alt="image" width="1135" src="https://user-images.githubusercontent.com/7606007/209309894-5110c519-a1b2-48c9-9124-6139dedae57b.png">

Fixed in #934
