### ISSUE TITLE
Add possibility to "lock" project template configurations

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#645]
**Is your feature request related to a problem? Please describe.**
With the new maloppsett, it's easy to create templates and connect default project extension files and default data. However, it's possible when creating a project to deselect the preselected extensions. 

**Describe the solution you'd like**
It would be nice if we can configure the templates and allow the ability to lock the pre-selected extensions and default data. This way, users that are creating new projects won't be able to deselect the template configuration.

**Additional context**
![image](https://user-images.githubusercontent.com/1837390/154229131-751a2ce4-20d7-43f6-ae99-92a8a9d5d33c.png)

**Comment by frankok** [comment]
This looks very good. Maybe have a flag on the Template Setup (Maloppsett) where you enable/disable the possibility for users to make changes under Prosjekttillegg and/or Standardinnhold.

**Comment by tarjeieo** [comment]
Yes, exactly what I was thinking. Do we need to be able to independently lock "Prosjekttillegg" and "Standardinnhold" - or can we have a shared setting "Lock default options"?

**Comment by frankok** [comment]
I don't have all the necessary info regarding future use here. So if it's not too much extra work setting this up independently, I would recommend setting up one flag for each tab.
