### ISSUE TITLE
Slow rendering of project images (project cards)

### ISSUE THREAD

**Issue by siifux** [Puzzlepart/prosjektportalen365#648]
**Describe the bug**
When loading project cards, the project-image loads in very slowly. 

**To Reproduce**

1. Go to 'https://prosjektportalen.sharepoint.com/sites/pp365'
2. See project images

**Expected behavior**
Expects the images to load quicker, this will affect the customer experience in a better way. 

**Screenshots**

https://user-images.githubusercontent.com/36504406/155351830-052b9513-9971-4796-baaf-553075b58a96.mp4

**About your setup**

- Tested in chrome. Customers have told us they have experienced this as well.

**Comment by siifux** [comment]
I am not sure if this is fixable, but worth checking out.

**Comment by olemp** [comment]
We're currently doing batch requests to the Graph API to fetch the images/logo.. Maybe we could change this to just using ../_api/siteiconmanager/getsitelogo as image source? @siifux @tarjeieo

**Comment by olemp** [comment]
We'll see if there's anything we can do in #621
