### ISSUE TITLE
Bug when there are more than six elements in "Listeinnhold"

### ISSUE THREAD

**Issue by TinHoangVu** [Puzzlepart/prosjektportalen365#658]
**Describe the bug**
Can only choose the first 6 elements in "standardinnhold" in project-setup when creating a new project. 

**To Reproduce**

1. Go to 'Listeinnhold' on "Konfigurasjon av prosjektportalen" and create more than 6 elements.
2. Setup a new project
3. See that u can't choose any options after the sixth position in "standardinnhold"

**Expected behavior**
Can add more than six elements in "listeinnhold" and choose them in projectsetup.

**Screenshots**

![image](https://user-images.githubusercontent.com/88658344/157403534-52527442-952f-4b84-bfaa-c20122eb2038.png)

**About your setup**

- Browser: Chrome
- Installed version 1.4.0

**Comment by olemp** [comment]
@pzljanb @tarjeieo @Petterandre We might need to push this to 1.5.1 or later. We have limited time this week if we want to release this Friday.

**Comment by tarjeieo** [comment]
We can live with that!

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/commit/15ce688725d4b9af1ca575fde7bb2b026f311358
