### ISSUE TITLE
Risk and economics sections still show in projectstatus report, even though it has no data/value.

### ISSUE THREAD

**Issue by TinHoangVu** [Puzzlepart/prosjektportalen365#669]
**Describe the bug**

The projectstatus contains sections that has no value/data. 

**To Reproduce**

1. Remove the required fields from projecstatus contenttype. 
2. Create a new projectstatus-report without any value in "Risiko" and "Økonomi"
3. See that the sections are included in the report even if it has no values or data.

**Expected behavior**
Sections should not show if i does not have any value/data

**Screenshots**
![image](https://user-images.githubusercontent.com/88658344/159283637-71f36ff1-3b8e-4746-afc6-2959b1833c9d.png)
![image](https://user-images.githubusercontent.com/88658344/159283167-c6e4e00b-33f6-4c2c-9246-ab33413b5ad0.png)

**About your setup**

- Browser Chrome
- Installed version 1.4.0

**Comment by olemp** [comment]
@pzljanb @tarjeieo @Petterandre We might need to push this to 1.5.1 or later. We have limited time this week if we want to release this Friday.

**Comment by olemp** [comment]
> Remove the required fields from projecstatus contenttype.

They are not supposed to be removed.

**Comment by olemp** [comment]
Fixed in #689
