### ISSUE TITLE
Ability to hide certain parts of the Project Information webpart

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#670]
**Describe the solution you'd like**

Ability to hide certain certain part of the 'ProjectInformation' webpart through webpart props. 

Solution:
- Hide all buttons
- Toggle visible per button

Additional change:
- Change name of webpart based on responses from userforum, new name will be: "Prosjektinformasjon", this includes the buttons
- Also hide "Vis alle egenskaper" when in edit mode.

**Comment by tarjeieo** [comment]
Web part options to 
- Hide all buttons
- Toggle visible per button

**Comment by Remi749** [comment]
Addition to issue:
- Change name of webpart based on responses from userforum, new name will be: "Prosjektinformasjon", this includes the buttons

**Comment by olemp** [comment]
@Remi749 

<img width="426" alt="image" src="https://user-images.githubusercontent.com/7606007/194559458-f7e1e197-aa81-47e2-9e06-aafc4194a046.png">

<3

**Comment by Remi749** [comment]
> @Remi749
> 
> <img alt="image" width="426" src="https://user-images.githubusercontent.com/7606007/194559458-f7e1e197-aa81-47e2-9e06-aafc4194a046.png">
> 
> <3

<3 <3

**Comment by olemp** [comment]
Fixed in #798

**Comment by pzljanb** [comment]
@olemp 
Burde vi benyttet "informasjon" i stedet for "egenskaper" på: 
- "Vis alle egenskaper" 
- "Rediger egenskaper"
?

**Comment by Remi749** [comment]
> @olemp 
> Burde vi ikke benyttet "informasjon" i stedet for "egenskaper" på "Synkroniser prosjektegenskaper" også?
> ?

This will be the case when #777 is closed. As the sync button was added in that issue.
