### ISSUE TITLE
Improvements for program admin page

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#676]
**Is your feature request related to a problem? Please describe.**
It's a improvement suggestion.

**Describe the solution you'd like**
Take a look at [this screen recording](https://user-images.githubusercontent.com/7606007/160790041-b66534ab-0dff-4a3b-afae-2016670a78ae.mov).

1. I think we should have a fixed width for the dialog to avoid this "glitch".
2. Should not be able to "select yourself"
3. We should show a message (or something) when no projects are selected as sub-project. Right now it looks like it didn't load properly

**Comment by olemp** [comment]
@Petterandre I might have time to pick this up if you're filled up with other tasks.

**Comment by Petterandre** [comment]
> @Petterandre I might have time to pick this up if you're filled up with other tasks.

I think I'd be able to do it, by the earliest tomorrow, so if you have time, go for it!
