### ISSUE TITLE
Statusrapport - rapportdato og "Vis alle egenskaper"

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#682]
**Describe the bug**
Når en ny statusrapport opprettes vises 1.1.1970 som dato før første publisering.
Dette gjelder kun første statusrapport.
Samme feil dukker opp både i gamle (før 1.5.0) og nye prosjekter.
Knappen "Vis alle egenskaper" dukker også opp i rapporten. Dette er feil

**To Reproduce**
1. Opprett en ny statusrapport i et prosjekt som ikke har statusrapport fra tidligere.
2. Legg inn data og lagre
3. Se dato
4. Se knappen "Vis alle egenskaper"

**Expected behavior**
-Riktig dato
-Uten knappen

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/161256113-e7e46d70-77ba-45ca-98a0-e1c50e692ddd.png)

**About your setup**

- Edge

**Additional context**

**Comment by olemp** [comment]
Fixed in #684
