### ISSUE TITLE
UI/UX improvements to Program

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#693]
**Describe the solution you'd like**
A list of various UI/UX improvements found throughout the Program module.

All points are open for debate of course.

**Comment by Remi749** [comment]
Added points, 9-11

**Comment by tarjeieo** [comment]
Love these improvements - feel free to work on them if you have time

**Comment by Remi749** [comment]
I agree, I'll add it as a point

**Comment by Remi749** [comment]
## Solved

1. Decorate links in "Administrasjon av underområder" the same way as other lists (see 'Gevinster' list for programs).
  a. This also applies for the "Legg til prosjekt" dialog 
2. Dialog with loading/shimmer when pressing "Legg til område" changes size after projects are loaded. Keep the same size.
7. For consistency, searchlabel in OverordnetUsikkerheter should say "Søk i alle usikkerheter" Or the other lists should say something about "Søk i program..."
8. Add a visual indication wether a project is "standard" or "Overordnet", either on the frontpage or elsewhere where it would be necessary.
10. Update all column descriptions used in Program lists to mention program instead of project. (See description for "Programleveranser - Leveransebeskrivelse")
13. After removing all "underområder" the "Fjern underordnet område" command button is still active, needs refresh to disable the state. This should become disabled when removing all sites (see image below of active state after deleting sites)
14. Remove duplicate "Title" webpart prop from "Administrasjon av underområder" webpart page or rename the duplicate if needed.
15. The webpart titles should be consistent. [See comment](https://github.com/Puzzlepart/prosjektportalen365/issues/693#issuecomment-1091372968)

**Comment by olemp** [comment]
> Add InformationMessage to "Administrasjon av underområder"

What information message, @Remi749?

**Comment by Remi749** [comment]
> > Add InformationMessage to "Administrasjon av underområder"
> 
> What information message, @Remi749?

Could be something like:

"Velg en eller flere prosjekter du ønsker å knytte til området. Området vil dukke opp som forelder for prosjektene som er valgt under Prosjektinformasjon."

**Comment by olemp** [comment]
> > > Add InformationMessage to "Administrasjon av underområder"
> > 
> > 
> > What information message, @Remi749?
> 
> Could be something like:
> 
> "Velg en eller flere prosjekter du ønsker å knytte til området. Området vil dukke opp som forelder, for prosjektene som er valgt, under Prosjektinformasjon."

Show it as a tooltip to avoid taking up the space all the time, @Remi749?

<img width="856" alt="image" src="https://user-images.githubusercontent.com/7606007/200547827-b83ce9e9-8d56-41f8-bc8d-c0eb8180c46e.png">

**Comment by Remi749** [comment]
> > > > Add InformationMessage to "Administrasjon av underområder"
> > > 
> > > 
> > > What information message, @Remi749?
> > 
> > 
> > Could be something like:
> > "Velg en eller flere prosjekter du ønsker å knytte til området. Området vil dukke opp som forelder, for prosjektene som er valgt, under Prosjektinformasjon."
> 
> Show it as a tooltip to avoid taking up the space all the time, @Remi749?
> 

Good idea, I like it!
