### ISSUE TITLE
In case of no default planner-elements, create a blank plan to avoid planner-webpart error on the front page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#702]
**Is your feature request related to a problem? Please describe.**
Today, if you don't select default planner content, the planner web part on the front page bombs, which can be confusing to some.

**Describe the solution you'd like**
Create an empty planner plan for the project.

**Comment by olemp** [comment]
Fixed in #703

**Comment by olemp** [comment]
[CI is running](https://github.com/Puzzlepart/prosjektportalen365/actions/runs/2257380997)
