### ISSUE TITLE
Feil ved installasjon når tenant setter url /teams og ikke /sites

### ISSUE THREAD

**Issue by danielwiese** [Puzzlepart/prosjektportalen365#716]
**Is your feature request related to a problem? Please describe.**
Ved nyinstallasjon av PP365 stopper scriptet opp dersom tenant står til /teams
![image](https://user-images.githubusercontent.com/61320379/172364741-88258c1b-570b-49e1-a49d-63a99c8f2160.png)

**Describe the solution you'd like**

Wiki bør oppdateres til å også inneholde et enkelt punkt og skjermbilde ang dette, og at det kan ta opp 60 min fra man gjør endringen til nye områder får /sites

**Additional context**

**Comment by tarjeieo** [comment]
We should also support installing to /teams/

**Comment by olemp** [comment]
@danielwiese Is this the issue you're experiencing?

![image](https://user-images.githubusercontent.com/7606007/193820221-8167ed55-5823-4eb0-8f42-26c5e510405d.png)

**Comment by danielwiese** [comment]
Sorry, but it is hard to tell as It´s been so long since I reported this issue, but It looks to be associated with the same experience.

**Comment by olemp** [comment]
Fixed in #863 and should work from the next release on.
