### ISSUE TITLE
Legg til mulighet for å velge previewType på Planner-oppgaver

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#718]
**Is your feature request related to a problem? Please describe.**
Når man oppretter Planner-oppgaver med lenke får man en kjempestor binders som preview på Planner-kortene. Dette gjør oppgaveoversikten vanskelig å lese og blir uoversiktelig.

![image](https://user-images.githubusercontent.com/1837390/172580934-4f31bc40-4e47-45bf-8c90-6ed9dfa93936.png)

**Describe the solution you'd like**
Kan vi ta med preview type som en kolonne på standard Planner-oppgaver? Default kan være automatic. https://docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-1.0

> This sets the type of preview that shows up on the task. The possible values are: automatic, noPreview, checklist, description, reference.

**Comment by olemp** [comment]
Fixed in #783
