### ISSUE TITLE
Option for showing all projects you're member of on the front page

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#724]
**Is your feature request related to a problem? Please describe.**
Many organizations have a very open permission policy, where all users have read access to all projects. Currently, the web part on the front page only shows the projects you're a member of. This can lead to confusion when users are looking for specific projects

![image](https://user-images.githubusercontent.com/1837390/174741020-e36c53eb-7673-406b-9bf2-6fd7a4f6fb30.png)

**Describe the solution you'd like**
We need to rethink how the top verticals should work, and which projects should be displayed and clickable. I suggest having the following verticals

- Tilgang til (default)
- Medlem av
- Overordnede
- Program
- Alle

For all verticals, the tiles you have access to should be clickable (i.e. current user is able to return the site in search).

Would be nice if we could have on-hover descriptions that give a bit better description.

In the web part setting, we should be able to set which is the default view, and if some should be toggled hidden.

**Comment by okms** [comment]
this is related to #765

**Comment by pzljanb** [comment]
The proposed default vertical "Tilgang til" is a bit tricky due to access only to SharePoint content. In reality the access level is more like "begrenset tilgang til". Planner and Teams will not be available. The same goes fopr other content living on the M365 group level (chat, wiki ++)

**Comment by pzljanb** [comment]
Har ikke testet den veldig mye enda, men ser veldig bra ut.

**Comment by olemp** [comment]
> Looks good 👍 @olemp : Will settings be global for all users or user spesific?

Web part properties, so global.
