### ISSUE TITLE
Adjustments to project information modal dialog

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#725]
**Describe the bug**
The project dialog at the portfolio level needs some adjustments.

1. The positioning should be adjusted to avoid cropping the dialog outside of the current browser window
2. The buttons for editing and showing all project properties should not be visible

**To Reproduce**

1. Go to one of the portfolio overview pages
2. Observe the errors as indicated by the screenshot below

**Expected behavior**
1. Positioning should be automatic and within the boundaries of the browser window (if at all possible)

**Screenshots**
![image](https://user-images.githubusercontent.com/1837390/174978310-1e087f6e-e2f4-43ef-9859-d9b2abe090f1.png)

**About your setup**

- Browser [e.g. chrome, safari] Edge
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.5.4

**Comment by okms** [comment]
as a minimum effort solution lets add scrolling if content overflows the modal bounds vertically
