### ISSUE TITLE
Persist field changes in the aggregated webparts to the 'Prosjektinnholdskolonner' list

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#727]
**Is your feature request related to a problem? Please describe.**
When browsing the overviews, you can edit the page and adjust field attributes. When changing the attributes of the field, saving the changes, and saving the page, (and refreshing), the field is updated in the view. However, the changes you made are only persisted "locally" in the web part - not in the Prosjektportalenkolonner list.

**Describe the solution you'd like**
I think it makes sense to persist the changes in the Prosjektportalenkolonner list as well.

Also, it would be nice to rerender the component upon save, to avoid having to refresh the page to see your changes.

**Additional context**

![image](https://user-images.githubusercontent.com/1837390/174981023-ce7d902b-fd79-4d9c-8ecf-0fc186bb63f9.png)

**Comment by Remi749** [comment]
For now data type and min width is supported

**Comment by tarjeieo** [comment]
Remaining: Also persist "Justerbar" and "Grupperbar" to the Prosjektinnholdskolonner list
