### ISSUE TITLE
Field type defaults to wrong field type when editing existing fields

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#730]
**Describe the bug**
Editing the fields of the overview pages, the field type defaults to an incorrect field type. When saving, the field type is then wrong.

**To Reproduce**

1. Go to Erfaringslogg
2. Edit the page, edit the "Aktører" field
3. Click save, and save the page
4. Observe that "Aktører" now has a wrong field type

**Expected behavior**
Expect the field type drop down to have the correct field type based on the value in the prosjektinnholdskolonner list.

**Screenshots**

![image](https://user-images.githubusercontent.com/1837390/174994321-677bd9af-8af1-442a-9722-62012f8911b4.png)
![image](https://user-images.githubusercontent.com/1837390/174994416-fa6d7dab-cb38-481a-9821-26ed21e99eff.png)
![image](https://user-images.githubusercontent.com/1837390/174994505-2e089245-5e3b-4acc-b814-a30984cc64ad.png)
![image](https://user-images.githubusercontent.com/1837390/174994589-214c9dcf-bf68-4223-b40c-f4108d136b70.png)

**About your setup**

- Browser [e.g. chrome, safari] Edge
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.6.0

**Additional context**

**Comment by Remi749** [comment]
@tarjeieo, can you test again, it should be fixed now.

**Comment by tarjeieo** [comment]
Works after the latest PR, GJ!
