### ISSUE TITLE
Legg webdeler i den vertikale webdelsonen på høyre side

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#731]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could take advantage of the vertical column for the project home page, to use more of the available page width.

**Describe the solution you'd like**
Support vertical column in the sp-js-provisioning framework.

**Additional context**
![image](https://user-images.githubusercontent.com/1837390/175034403-3fd1289e-037c-4d77-8673-d6ef61202d46.png)

See https://github.com/Puzzlepart/sp-js-provisioning/blob/main/src/handlers/clientsidepages.ts

**Comment by olemp** [comment]
I agree it would be nice, but this is not supported in `@pnp/sp`.

**Comment by Remi749** [comment]
> I agree it would be nice, but this is not supported in `@pnp/sp`.

Isn't it something we can implement in our [sp-js-provisioning](https://github.com/Puzzlepart/sp-js-provisioning) repo?

This was mentioned in the issue:

> **Describe the solution you'd like**
> Support vertical column in the sp-js-provisioning framework.

**Comment by olemp** [comment]
> > I agree it would be nice, but this is not supported in `@pnp/sp`.
> 
> Isn't it something we can implement in our [sp-js-provisioning](https://github.com/Puzzlepart/sp-js-provisioning) repo?
> 
> That was the desired solution and it was mentioned in the issue:
> 
> > **Describe the solution you'd like**
> > Support vertical column in the sp-js-provisioning framework.

It's the `@pnp/sp` package that doesn't support it, but support was implemented in v2 of `@pnp/sp`, so I'm trying it out now.

**Comment by olemp** [comment]
I've investigated a bit and this required to upgrade `@pnp/sp` throughout the project, so I think we should go directly for v3.

https://pnp.github.io/pnpjs/transition-guide/

So this is quite a bit of work to be honest.

**Comment by olemp** [comment]
> I've investigated a bit and this required to upgrade `@pnp/sp` throughout the project, so I think we should go directly for v3.
> 
> https://pnp.github.io/pnpjs/transition-guide/
> 
> So this is quite a bit of work to be honest.

This is dependent on #865 which will be quite some work. Especially since they removed `.get()`.

**Comment by tarjeieo** [comment]
Amazing!!!
