### ISSUE TITLE
Update aggregated webparts for ProgramWebParts 

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#740]
**Describe the solution you'd like**
The aggregated webparts made for ProgramWebParts should be removed and instead have a ProgramAggregation webpart and create the clientsidepages directly in the json template file as was done with benefits webpart on Project level.

The following webparts will be removed and remade:
- ProgramBenefits, ProgramDeliveries, ProgramRiskOverview

These program client side pages will then use a separate datasource if needed.

**Important note**: This is the reason why ProgramWebParts and ProjectWebParts use pp365-portfoliowebparts v1.5.4-679.2.

**Comment by okms** [comment]
3-4 days worth of work

**Comment by olemp** [comment]
> The BenefitsWebPart for Projects should also be redone and be based on the new aggregated webparts.

Isn't it already @Remi749?

**Comment by Remi749** [comment]
> > The BenefitsWebPart for Projects should also be redone and be based on the new aggregated webparts.
> 
> Isn't it already @Remi749?

As of now the BenefitsWebPart in ProgramWebPart is used the same way ProjectWebParts were used before but as it's own separate webpart with a unique ID. It should use the same ID as the PortfolioAggregationWebPart, same with ProjectWebParts. This is also the case with all the other program webparts that ue PortfolioAggregation.

If anything is unclear, hit me up.

**Comment by olemp** [comment]
Will be done as part of #800

Note to self:
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/7606007/194901602-a63a716f-7d3e-42a6-8fd9-bd08e7faf1f6.png">
