### ISSUE TITLE
Showing Prosjektleveranser on the timeline does not work at project level

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#742]
**Describe the bug**
When enabling "Vis Prosjektleveranser" in the project timeline web part at project level, nothing is displayed. I have added Prosjektleveranse in the project timeline configuration list.

**To Reproduce**

1. Go to a project, go to Prosjekttidslinje
2. Edit page, select "Vis prosjektleveranser"
3. Refresh the page

**Expected behavior**

**Screenshots**

The message is "Cannot read properties of undefined (reading 'length')". Seems like it's trying to get a list with name undefined: https://xxx.sharepoint.com/sites/yyyy/_api/web/lists/getByTitle('undefined')/items?$select=Title,GtDeliveryDescription,GtDeliveryStartTime,GtDeliveryEndTime&$top=500

**About your setup**

- Browser [e.g. chrome, safari] Edge
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.6.0

**Additional context**
Can be reproed in Prosjektportalen-tenant

**Comment by Remi749** [comment]
hotfix pushed to dev branch
