### ISSUE TITLE
Create a stop function when someone tries to add site template "Prosjektområde" at portfolio level

### ISSUE THREAD

**Issue by danielwiese** [Puzzlepart/prosjektportalen365#744]
**Describe the bug**

Some users tries from time to time to add the site template "Prosjektområde" to portfolio level, and some even runs the entire wizard which creates the portfolio level as a project. 

**To Reproduce**

**Expected behavior**
It would be nice to have a function which stops the action if site template "Prosjektområde" is added to portfolio level to make this not possible to do.

**Screenshots**

**About your setup**

- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx]

**Additional context**

**Comment by tarjeieo** [comment]
The Project Setup Dialog should check if current siteid is hub site id, and if it is, the custom action/extension should remove itself. Check ProjectExtensions/...

**Comment by okms** [comment]
Note: we should check if we can use [Grant-PnPSiteDesignRights](https://pnp.github.io/powershell/cmdlets/Grant-PnPSiteDesignRights.html) to restrict visibility of the project template. I'm not sure if this will cause problems when a site design is set as default for a hub-site. The idea is to restrict visibility to only a select group (e.g. administrators and product owners).
