### ISSUE TITLE
Suppress error message in Planner webpart when caused by access

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#750]
**Describe the bug**
When the current user only has visitor access given through SharePoint site level, access to the Planner within the M365 group is not granted. In this case the Planner webpart display an error message telling that something is wrong and that the user should contact the administrator if the errors persists.

**To Reproduce**

1. Identify a project where your user only has visitor access given through SP (no M365 membership)
2. Enter the project with a Planner webpart on the front page
3. Wait for the Planner webpart to fail

**Expected behavior**
The user should be notified that he **does not have access** to the plan due to lack of rights

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/183579664-880992b6-9ba7-402f-9331-8576d14d86fd.png)

**About your setup**

- Browser [chrome]
- Installed version [1.5.4]

**Additional context**

**Comment by olemp** [comment]
> The user should be notified that he does not have access to the plan due to lack of rights

How should he/she be notified @pzljanb? We don't control this webpart :)

**Comment by olemp** [comment]
Out of scope.
