### ISSUE TITLE
Prosjekttidslinje - Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by havardd** [Puzzlepart/prosjektportalen365#755]
**Describe the bug**
Etter oppdatering til versjon 1.6.1 er det ikke mulig å vise prosjekttidslinjen på et enkelt prosjekt. Vises på porteføljenivå. Får feilmeldingen: Cannot read properties of undefined (reading 'length')

**To Reproduce**

1. Go to Prosjektrom
2. Click on Prosjekttidslinje

**Expected behavior**
Prosjekttidslinjen til prosjektet vises

**Screenshots**
![image](https://user-images.githubusercontent.com/10496174/185574702-c1383e47-40a0-48a5-b732-f22e1fe2fac5.png)

**About your setup**
* Office365
* Norsk

- Installed version: ![image](https://user-images.githubusercontent.com/10496174/185575334-a7481977-94f7-444d-b80a-2b917c7c9577.png)

**Additional context**

**Comment by Remi749** [comment]
@havardd, I heard you've been in touch with us regarding this today. Is this still a problem? Is the problem for a particular project or all projects?

**Comment by havardd** [comment]
@Remi749, Ja fortsatt et problem, og feilen gjelder alle prosjektrom i tenanten, feilen kom etter oppgradering. Prosjekttidslidslinjen på overordnet nivå viser prosjektene ut i tid. Men ikke innholdet som er lagt inn på det enkelte prosjekt sin tidslinje. Usikker på om det faktisk er lagt inn noe på prosjekttidslinjene, siden det ikke er mulig å se tidslinjen pr prosjekt. Denne feilen kommer kun i testmiljø i annen tenant. Ikke i livemiljøet vårt.

**Comment by pzljanb** [comment]
@havardd , behøver å sjekke ut dette tilfellet. Kan du ta en liten sjekk av den sentrale listen Tidslinjeinnhold.
Det jeg lurer på er om dere i default view har med en kolonne av typen 'Person eller gruppe' typisk 'Endret av', eller 'Opprettet av'.
Kan du forsøke å fjerne de av den typen om de er med og se om dette hjelper?

**Comment by havardd** [comment]
Gikk inn på XYZ.sharepoint.com/sites/Prosjektportalen365/Lists/Tidslinjeinnhold/
Se bilde av standardvisningen i bilde under. Ingen koloner av typen du refererer til @pzljanb 

![image](https://user-images.githubusercontent.com/10496174/189292857-08215b6f-1120-428a-b8a0-59ed6bfb590a.png)

**Comment by pzljanb** [comment]
Og dette er listen på testmiljøet deres @havardd ?

**Comment by havardd** [comment]
det stemmer @pzljanb  ... Feilen er på prosjektnivå, ikke på overordnet nivå...

**Comment by pzljanb** [comment]
Etter en sjekk av den sentrale listen viser det seg at denne innehar dobbelt opp med kolonner for feltene Type og Prosjekttilhørighet.
Workaround: Flytt data til de nye feltene med internnavn med prefiks 'Gt'
Slett deretter de gamle kolonnene uten prefiks 'Gt'

![image](https://user-images.githubusercontent.com/58074707/189311759-e6f39e08-bf42-4826-aff8-1009d0ff9c9b.png)

**Comment by Remi749** [comment]
@havardd , added better error handling for ProjectTimelines (Portfolio and project level), this will make it easier to figure out why you are experiencing this error and be able to fix it.

This will be available in 1.7.0
