### ISSUE TITLE
Vise oversikt over muligheter på porteføljenivå som er registrert i usikkerhetslisten i prosjektene

### ISSUE THREAD

**Issue by havardd** [Puzzlepart/prosjektportalen365#756]
**Is your feature request related to a problem? Please describe.**
Nei

**Describe the solution you'd like**
Dagens risikooversikt tar ikke med seg mulighetene fra usikkerhetslisten i prosjektrommene. 
Det er ønskelig å samle en oversikt over alle muligheter på porteføljenivå, tilsvarende det er for risikoer.

**Additional context**
![image](https://user-images.githubusercontent.com/10496174/185579898-45b17c34-0f3d-4d0d-87a5-7a9e69f6ca8b.png)

![image](https://user-images.githubusercontent.com/10496174/185580323-fb2890c8-1bbc-4626-8425-1c96ce654b99.png)

**Comment by Remi749** [comment]
Usikkerhetsoversikt -> Filtrere på Muligheter og risikoer -> Vis/skjul matrise for risiko og muligheter

**Comment by olemp** [comment]
@Remi749 @pzljanb In #886 I switched the Risikooversikt.aspx page with Usikkerhetsoversikt.aspx. But we need to do some changes to the upgrade/install scripts aswell. Thoughts here @Remi749?

![image](https://user-images.githubusercontent.com/7606007/201052312-3f665f0a-ae15-4b3d-8cd0-e868aa97cfd4.png)

**Comment by olemp** [comment]
> @Remi749 @pzljanb In #886 I switched the Risikooversikt.aspx page with Usikkerhetsoversikt.aspx. But we need to do some changes to the upgrade/install scripts aswell. Thoughts here @Remi749?
> 
> ![image](https://user-images.githubusercontent.com/7606007/201052312-3f665f0a-ae15-4b3d-8cd0-e868aa97cfd4.png)

How do we handle this @Remi749?

**Comment by olemp** [comment]
> > @Remi749 @pzljanb In #886 I switched the Risikooversikt.aspx page with Usikkerhetsoversikt.aspx. But we need to do some changes to the upgrade/install scripts aswell. Thoughts here @Remi749?
> > ![image](https://user-images.githubusercontent.com/7606007/201052312-3f665f0a-ae15-4b3d-8cd0-e868aa97cfd4.png)
> 
> How do we handle this @Remi749?

A second brain on this one would be nice @Remi749 🧠 We've done some postinstall and preinstall stuff previously for Risikooversikt.aspx page. Now we are replacing Risikooversikt with Usikkerhetsoversikt. Would be nice if we could update the navigation.

**Comment by olemp** [comment]
> Adjusted install steps for Usikkerhetsoversikt

Fixed in https://github.com/Puzzlepart/prosjektportalen365/commit/2a44700d0a08fcc7b59adb01af77b1a90c2cc030
