### ISSUE TITLE
Version number not updated in new versions

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#757]
**Describe the bug**
Version number displayed in upper right croner og the Project wizard is showing the old version number (not current)

**To Reproduce**

Compare the Installed version number from installation log with the number in the project wizard on a site upgraded to 1.6.1

**Expected behavior**
Version number should be identical where ever it is dispalyed.

Version number should be read from a common location and reused with a internal tag or similar to avoid faulty identifications. 

**Screenshots**

**About your setup**

- Installed version [1.6.1]

**Additional context**

**Comment by pzljanb** [comment]
Install log shows a "long" number looking like this: [1.6.1.f45071d]
While in all reused locations it would be enough to have the first part [1.6.1] dispalyed
Any thoughts @okms @Remi749 ?

**Comment by okms** [comment]
Could you please provide some screenshots @pzljanb ?

**Comment by pzljanb** [comment]
![image](https://user-images.githubusercontent.com/58074707/185618071-dcc37e8e-ec32-45f5-86f4-b5ebe914a322.png)
![image](https://user-images.githubusercontent.com/58074707/185618200-a22ff49d-d231-4319-84e3-e547ff1f8240.png)

**Comment by Remi749** [comment]
Looks like the build pipeline probably failed to create ProjectExtension based on the 1.6.1 manifest. The version 1.6.1 is specified in the manifest. When building 1.7.0 this should be fixed, but before closing the issue we should double check the version number in the projectUpgrade extension.

**Comment by okms** [comment]
Lets keep the semantic versioning to major.minor.patch and keep version hash in the install log
