### ISSUE TITLE
Portfolio log list to log info/warnings/errors from portfolio and projects

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#763]
**Describe the solution you'd like**
A log list similar to what we had in Prosjektportalen2.0. Instead of only logging errors occuring during projectSetup. We want to log the following:

- Portfolio: information (example: changes done to webparts), warnings and errors
- ProjectSetup: info,warnings and errors
- Project: info, warnings and errors

List columns
- Level (info,warning,error)
  - Formatted column
- Type: example: webpart, extension
- Component: example: ProjectPhase,ProjectInformation, BenefitsOverview
- Url
- ~Executing User~ (superfluous: use Author)
- ~DateTime~ (superfluous: use Created)
- Message

We need a generalized function that is used for logging to the list with needed properties to create an element.

Deliveries:
- New projects get a "Log" list with specified fields
- Build on list logger in @Shared/logging/ListLogger.ts

Adding listlogger to different web-parts is a separate task

**Comment by olemp** [comment]
@Remi749 Done and dusted. See #796 for details!

**Comment by pzljanb** [comment]
I update this with the v1.7.0 Milestone

**Comment by olemp** [comment]
> I update this with the v1.7.0 Milestone

🍌
