### ISSUE TITLE
Give granular control over who can perform tasks in custom web parts

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#765]
**Is your feature request related to a problem? Please describe.**
Currently we only check if a user is Site Collection administrator when deciding wether or not they are allowed to perform certain tasks within our custom WebParts. For example to edit project properties, you need to be Site Collection administrator. 

This is too blunt a tool for many larger customers, where only a select few are Group owners (and thus are admins).  We should allow our customers to allow other functions such as Project owner, Project leader or some custom roles defined centrally, to use these features. 

**Describe the solution you'd like**
There is need of a more granulated access control for these functions:

- Edit project properties
- Alter phase
- Project status (optional)

Roles that must be selectable for this configuration are the following:
- Roles from project properties: 
  - Projectmanager
  - ProjectOwner
  - Project support
  - Gains responsible
- Groups defined on portfolio level in 'Tillatelseskonfigurasjon'

As a "fallback" solution we can keep 'IsAdmin' as is, and add the new functionality in this Issue as a supplement.

**Comment by pzljanb** [comment]
For inspiration have a look at ...
[https://pzlcloud.sharepoint.com/:b:/r/sites/prosjektportalen/Shared%20Documents/General/Replace%20-%20IsAdmin.pdf?csf=1&web=1&e=pGQO5L](url)

**Comment by pzljanb** [comment]
First iteration can start with a common admin role for the project. This role is given access to bort edit properties, change phase and more...

Could perheps been solved with a new select field within project properties. This could be pre-loaded with default values based on project tempalte configuration.
![image](https://user-images.githubusercontent.com/58074707/190130115-ad9e233d-07ee-47de-846e-56144e95f614.png)
![image](https://user-images.githubusercontent.com/58074707/190130144-99bc3418-dd22-47d3-bc48-b96a2d03e1bd.png)

For configuration purpose a central configuration list must be kept updated and in sync on the hub.
![image](https://user-images.githubusercontent.com/58074707/190130800-006479cb-2edc-4486-8444-071f028ca599.png)

In this list configuration must keep info on "where" to check for "membership".

**Comment by pzljanb** [comment]
Kontrollerer nå denne med brukere av portalen

**Comment by olemp** [comment]
Completed
