### ISSUE TITLE
Text color in project timeline webpart not readable

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#767]
**Describe the bug**
Description text of both activity bars and diamonds is not readable. This appears in cases when either the length of the bar (and diamonds?) is shorter than the text and the text color / bar color and/or background color gives poor contrast and results in unreadable text.

**To Reproduce**
Have a look at your Projecttimeline webpart. Experiment with short bars / long description text.

**Expected behavior**
A combination of:
- The text color should be configurabel
- Text bakground should not transparent when text uses more space than the bar it is connected to
- Webpart background could be adjusted to text colors selected and auto adjusted to give good readability

**Screenshots**
Text color not configurable. With configurable text color, bad contrast could be avoided.
![image](https://user-images.githubusercontent.com/58074707/193801550-5ec1718b-1894-47a1-95b3-64aa49989d1b.png)
![image](https://user-images.githubusercontent.com/58074707/193801589-b5ea5e47-90be-42e5-b840-dc95bddf4454.png)

Text background is transaprent and the text disappears on the white background:
![image](https://user-images.githubusercontent.com/58074707/193801766-f2a7f3a0-9b9b-4ce4-8253-752d0fda6937.png)
![image](https://user-images.githubusercontent.com/58074707/193801849-bd982419-39be-42d0-8f1c-553cafbe13cf.png)

**About your setup**

- Edge
- Installed version 1.6

**Comment by olemp** [comment]
Some screenshots would help a lot here @pzljanb

**Comment by pzljanb** [comment]
Text color not configurable. With configurable text color, bad contrast could be avoided.
![image](https://user-images.githubusercontent.com/58074707/193801550-5ec1718b-1894-47a1-95b3-64aa49989d1b.png)
![image](https://user-images.githubusercontent.com/58074707/193801589-b5ea5e47-90be-42e5-b840-dc95bddf4454.png)

Text background is transaprent and the text disappears on the white background:
![image](https://user-images.githubusercontent.com/58074707/193801766-f2a7f3a0-9b9b-4ce4-8253-752d0fda6937.png)
![image](https://user-images.githubusercontent.com/58074707/193801849-bd982419-39be-42d0-8f1c-553cafbe13cf.png)

**Comment by olemp** [comment]
Added support for setting text color aswell as background color. The custom formatting uses the color from the new field.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/7606007/199461855-a6fd97db-3f62-408d-a9d2-70b1960bf52f.png">
