### ISSUE TITLE
Improved layout of elements within the Projecttimeline webpart

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#768]
**Is your feature request related to a problem? Please describe.**
Elements with dates close to each other is lined up closely in a way that gives low readibility to the user.

Example: 3 elements: bar + diamond + bar registered with only 1 day between stop/start will show up on the same line in the webpart. This type of immediately following elements is a common use case and is seen on a regular basis.

**Describe the solution you'd like**
- Space to be occupied by an element should be wider than the timeframe of the element.
- The extra space to be occupied should be dynamic related to the zooming of the webpart

**Additional context**
A type of deadband or something to give more space would be preferable.

**Comment by olemp** [comment]
Do we have fine grained control on how the timeline items are rendered in the component we are using, @Remi749?

**Comment by Remi749** [comment]
> Do we have fine grained control on how the timeline items are rendered in the component we are using, @Remi749?

Yup

**Comment by olemp** [comment]
@pzljanb @Remi749 

I suggest to have type as the default group by, and also zoom in a bit more by default.

Input?

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/7606007/199244035-592405ad-e525-4b09-acc9-32f6ea26745f.png">

**Comment by pzljanb** [comment]
> @pzljanb @Remi749
> 
> I suggest to have type as the default group by, and also zoom in a bit more by default.
> 
> Input?

Well, a better defined zoom would be great.

When it comes to default grouping I would like to start with mentioning that the group 'Prosjekt' more likely should be named 'Ingen', since this choice in reality represent no grouping.

It would be nice if default groupøing could be difned as a webpart property individual for each project. By default 'Type' is a good choice but we should then make sure the sorting is correct, in the above picture the order is not correct

**Comment by Remi749** [comment]
> > @pzljanb @Remi749
> > I suggest to have type as the default group by, and also zoom in a bit more by default.
> > Input?
> 
> Well, a better defined zoom would be great.
> 
> When it comes to default grouping I would like to start with mentioning that the group 'Prosjekt' more likely should be named 'Ingen', since this choice in reality represent no grouping.
> 
> It would be nice if default grouping could be defined as a webpart property individual for each project. By default 'Type' is a good choice but we should then make sure the sorting is correct, in the above picture the order is not correct

Regarding your comments about grouping. I would say grouping by 'Prosjekt' is still valid, as all the elements are infact grouped by the Project itself.

**Comment by olemp** [comment]
> > > @pzljanb @Remi749
> > > I suggest to have type as the default group by, and also zoom in a bit more by default.
> > > Input?
> > 
> > 
> > Well, a better defined zoom would be great.
> > When it comes to default grouping I would like to start with mentioning that the group 'Prosjekt' more likely should be named 'Ingen', since this choice in reality represent no grouping.
> > It would be nice if default grouping could be defined as a webpart property individual for each project. By default 'Type' is a good choice but we should then make sure the sorting is correct, in the above picture the order is not correct
> 
> Regarding your comments about grouping. I would say grouping by 'Prosjekt' is still valid, as all the elements are infact grouped by the Project itself.

Agreed.

**Comment by olemp** [comment]
> > @pzljanb @Remi749
> > I suggest to have type as the default group by, and also zoom in a bit more by default.
> > Input?
> 
> Well, a better defined zoom would be great.
> 
> When it comes to default grouping I would like to start with mentioning that the group 'Prosjekt' more likely should be named 'Ingen', since this choice in reality represent no grouping.
> 
> It would be nice if default grouping could be defined as a webpart property individual for each project. By default 'Type' is a good choice but we should then make sure the sorting is correct, in the above picture the order is not correct

Added default group by and default zoom level to project properties.

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/7606007/199449034-5414e90f-ef3a-432c-b7d8-970c429bd4b1.png">

Type is the default group by, by default, and is the recommended approach for the example in this issue: 

>  3 elements: bar + diamond + bar registered with only 1 day between stop/start will show up on the same line in the webpart. This type of immediately following elements is a common use case and is seen on a regular basis.
