### ISSUE TITLE
Include site pages for all phases for easier implementation of dynamic home pages

### ISSUE THREAD

**Issue by danielwiese** [Puzzlepart/prosjektportalen365#784]
**Describe the solution you'd like**
Prospects and customers loves the idea of dynamic home page for each of the phases. To make it easier for customer to include this we should add one site page for each default phase. The new site pages could as default be similar to the basic home page, but this will also make it easier for customers to edit these pages them selves, and with this, adding more value to the solution.

**Comment by olemp** [comment]
It could be offered as an extension @Remi749 @danielwiese. It would be increase the setup time quite a bit for those who don't need this functionality.

**Comment by olemp** [comment]
@Remi749 @danielwiese  I don't think we should include this in the default template, but the customers that wants it can add it as a locked "Prosjekttillegg".

<img width="967" alt="image" src="https://user-images.githubusercontent.com/7606007/198303684-895e2083-3340-4ad2-91ca-7dba863f2769.png">

See attached file.

[Fasesider.txt](https://github.com/Puzzlepart/prosjektportalen365/files/9880021/Fasesider.txt)

**Comment by olemp** [comment]
Customers also have different phases set up, so we really can't include it in the default template. The recommended solution is to use the "Fasesider.txt" as a "Prosjekttilegg".

**Comment by Remi749** [comment]
> > Fasesider.txt
> 
> Gotcha! We can include [Fasesider.txt](https://github.com/Puzzlepart/prosjektportalen365/files/9880021/Fasesider.txt) as an extension (if you do a QA of it)? 🚀

Will do <3

**Comment by danielwiese** [comment]
Yes, as mentioned by Bloom, my suggestion is only to prepare the solution for this feature, but make it optional to use it. I think you suggestion to include it as «Prosjekttillegg» is suitabl, and of course it will customization if customeres uses different phases.

PS: Denne mailen ble sendt fra telefon, vennligst overse eventuelle skriveleifer dette kan ha medført.

Med vennlig hilsen

Daniel Wiese-Møller
Kundeansvarlig og prosjektleder
(+47) 95 94 21 73
Puzzlepart AS

________________________________
Fra: Bloom ***@***.***>
Sendt: Thursday, October 27, 2022 3:57:14 PM
Til: Puzzlepart/prosjektportalen365 ***@***.***>
Kopi: Daniel Wiese-Møller ***@***.***>; Mention ***@***.***>
Emne: Re: [Puzzlepart/prosjektportalen365] Include site pages for all phases for easier implementation of dynamic home pages (Issue #784)


@Remi749<https://github.com/Remi749> @danielwiese<https://github.com/danielwiese> I don't think we should include this in the default template, but the customers that wants it can add it as a locked "Prosjekttillegg".

img

See attached file.

Fasesider.txt<https://github.com/Puzzlepart/prosjektportalen365/files/9880021/Fasesider.txt>

This is what was intended, not to be included as standard, but something that comes with PP365 and customers can activate

**Comment by Remi749** [comment]
Looks good @olemp, we can use this.

**Comment by olemp** [comment]
> Looks good @olemp, we can use this.

Included in #851
