### ISSUE TITLE
Inline help content

### ISSUE THREAD

**Issue by TinHoangVu** [Puzzlepart/prosjektportalen365#788]
**Is your feature request related to a problem? Please describe.**
The problem is that the availability of help content is not sufficent.

**Describe the solution you'd like**
Show help button on pages where help is available. 
Configuration of help content available through configuration page. 
Help to be displayed in a dialog box when button is clicked. 
Predefined help content to each menu point in the standard project template and portfolio navigation. 

**Additional context**
Dialogbox displayed with tabs. Each tab represent one line in the configuration list:
- Content in the tab consist of a link to an external site.
- Rich text configured locally in the configuration list.
- Embeded content from external site. 

Configuration list consist of these fields: 
- GtResourceLink / Link til ressurs
- GtExternalURL / Ekstern URL 

Link on configuration page: 
- icon: Et eller annet lurt
- text: Hjelpeinnhold

![image](https://user-images.githubusercontent.com/88658344/193822172-f1c96ec8-938d-4054-a766-ec70fe6504bf.png)
![image](https://user-images.githubusercontent.com/88658344/193822361-06efdd1b-1f22-4d51-97ae-d2da922202e0.png)

**Comment by olemp** [comment]
Merged to dev.
