### ISSUE TITLE
Predefined listelements in HelpContent list 

### ISSUE THREAD

**Issue by TinHoangVu** [Puzzlepart/prosjektportalen365#799]
**Describe the solution you'd like**
Would like to have predefined list elements in help content list, with links and content to PP user manual for each navigation element in project and portfolio.

**Additional context**
Add links in column "Ekstern URL" from PP user manual from github.

![image](https://user-images.githubusercontent.com/88658344/194509078-963c49d3-7a9f-45ec-be99-4427ebaafd03.png)

**Comment by olemp** [comment]
@pzljanb @TinHoangVu Ser det er lagt til elementer for Porteføljenivå, men det er kun prosjektnivå som har custom action for Hjelpeinnhold.

![image](https://user-images.githubusercontent.com/7606007/195093561-50038d3b-701c-48ad-872f-369076bccbaf.png)

**Comment by olemp** [comment]
Fixed in #802
