### ISSUE TITLE
Issues with timeline for Program

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#807]
**Describe the bug**
Issues with timeline for Program.

**Please note:** This is an issue in the _dev_ branch.

**Additional context**
![image](https://user-images.githubusercontent.com/7606007/195311629-b48abc06-bd04-4d5a-a2c8-99c8394c1e85.png)

**Comment by olemp** [comment]
Hopefully fixed by [this job run](https://github.com/Puzzlepart/prosjektportalen365/actions/runs/3234079491/jobs/5296752210).

**Comment by olemp** [comment]
It's loading! <3

![image](https://user-images.githubusercontent.com/7606007/195332702-e13e3a55-e9fa-4d10-89e2-274dcfda08d6.png)

**Comment by olemp** [comment]
Or nawwwt... Still happening on https://puzzlepart.sharepoint.com/sites/TestProgram/SitePages/ProgramTidslinje.aspx

![image](https://user-images.githubusercontent.com/7606007/195333208-eba5a0e9-8302-48c8-9549-e9d36b684c42.png)

**Comment by olemp** [comment]
Can't reproduce this anymore. How about you @Remi749? Can you confirm before we close this one.

**Comment by Remi749** [comment]
Will check thismyself before closing

**Comment by olemp** [comment]
Should be solved in #818
