### ISSUE TITLE
Show multi taxonomy terms as labels in 'ProjectInformation' webpart

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#827]
**Describe the solution you'd like**
Show multi taxonomy terms as labels in 'ProjectInformation' webpart

| Before | After |
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/28678468/196376064-76d197fe-44c9-4bed-ae0f-db64b24d8baa.png) | ![image](https://user-images.githubusercontent.com/28678468/196376007-1b5bd528-babb-448c-95b0-4491d6e1eb8d.png) |

Another image with two multi term fields:
![image](https://user-images.githubusercontent.com/28678468/196416921-00e564a2-b5fa-47ef-9a0e-a8696dee1256.png)

- Base background-color on themePrimary

**Comment by olemp** [comment]
Fixed in #828 by @Remi749
