### ISSUE TITLE
Log errors to list for main components

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#842]
**Describe the solution you'd like**
Log list has been introduced to Prosjektportalen 365, ref: #763, so far it logs when a ProjectSetup starts and if it is successful, should log errors when running ProjectSetup.

| Component          | What to log       | Levels |
| ------------------ | ----------------- | ------ |
| ProjectSetup       | Creating project  | Error  |
| ProjectPhases      | Update phase      | Error  |
| ProjectInformation | Update properties | Errors |

~~More to come...~~ Add to separate issues.

~~Also add Log list as an element on the configuration page~~ Added as separate issue #897

**Comment by olemp** [comment]
_Add logging throughout Prosjektportalen for every main component for every level_

This needs some more description @Remi749. I guess there's no point in logging from all components just for the sake of it? We're already doing a lot of requests to SharePoint and I think we should be careful on how much we log. I'd rather like us to add bit by bit for the most important parts.

I've tested some of our pages with the _Page diagnostics for SharePoint_ Edge extension, and we're already recommended to limit our number of SP requests.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/7606007/199216811-28cd5708-b737-4c5b-bafd-c2f614cd3d9c.png">

**Comment by Remi749** [comment]
Updated issue, reopening.

**Comment by olemp** [comment]
Completed in https://github.com/Puzzlepart/prosjektportalen365/commit/c6b779b6f0ca17823e4f56272ea33f6a5ad0f55c https://github.com/Puzzlepart/prosjektportalen365/commit/44eb1576efabc3fe91be733530110cf7fcd828f3 https://github.com/Puzzlepart/prosjektportalen365/commit/dfd058a74d96cb6c09e63ec9b09c43bb4def22de
