### ISSUE TITLE
Add '? Hjelp tilgjengelig'  button to existing projects

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#844]
**Describe the solution you'd like**
Add '? Hjelp tilgjengelig'  button from 'Hjelpeinnhold' to existing projects.

As of now the button '? Hjelp tilgjengelig' is only available for new projects. Add this to the UpgradeAllSitesToLatest script.

**Comment by olemp** [comment]
Included in #855
