### ISSUE TITLE
Add setting to Project Information showIconsOnly for Project Status

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#869]
**Is your feature request related to a problem? Please describe.**
New feature / web part setting.

**Describe the solution you'd like**
Add new web part setting to Project Information `showIconsOnly` for Project Status.

![image](https://user-images.githubusercontent.com/28678468/199506674-c89de328-33a2-4441-be2d-c7767e74c8df.png)

**Comment by olemp** [comment]
Here you go @Remi749 🚀 

<img width="979" alt="image" src="https://user-images.githubusercontent.com/7606007/199520005-26a160be-59bc-48cc-9d46-f0abbd484b4a.png">

**Comment by Remi749** [comment]
> Here you go @Remi749 🚀
> 
> <img alt="image" width="979" src="https://user-images.githubusercontent.com/7606007/199520005-26a160be-59bc-48cc-9d46-f0abbd484b4a.png">

Beautiful ❤️
