### ISSUE TITLE
Search experience

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#884]
**Describe the bug**
The search experience in different modules differs.

**To Reproduce**

"Oppsett av prosjektområde" with 3 selected projects
![image](https://user-images.githubusercontent.com/58074707/200770370-c572bb2d-ce50-4713-951d-895163c58353.png)

The 3 projects are hard to locate in the list, but will remain visible when you search:
![image](https://user-images.githubusercontent.com/58074707/200770559-5593c3dc-20bc-4da9-be74-c6b4404d6f84.png)

"Legg til prosjetker" dialog within Program; selected projects shows up on top:
![image](https://user-images.githubusercontent.com/58074707/200770723-77ea03c5-94f8-4950-a8c4-df9766d4ac16.png)

In the moment you select another one the list expands and "selectd in top rows" is cancelled until you search again:
![image](https://user-images.githubusercontent.com/58074707/200770860-8c692cd6-1c65-43ab-bdf3-0ed608cbb82c.png)

**Expected behavior**
We should have a common search experience within the solution. Open for suggestions in regards of what to be the preferred solution.
As a minimum we should implement a counter of selected items together with a deselct all function. (Similar to the one in a regular SP list)

**About your setup**
- Installed version 1.7.3

**Additional context**
Its important to use out of box solutions as mutch as possible. Also to implememt common functionality wherever search is implemented.

**Comment by olemp** [comment]
Fixed in #885
