### ISSUE TITLE
Typing error in "Hent dokumentmal"

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#889]
**Describe the bug**
Typing error n the form

**To Reproduce**

1. Go to 'Dokumenter'
2. Click on 'Hent dokumentmal'

**Expected behavior**
kopering to be kopiering

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/201060279-1b6c5fc4-e217-4ce7-b27d-6292007f0b21.png)**About your setup**

- Installed version [v1.7.2]

**Additional context**

**Comment by olemp** [comment]
Fixed in commit https://github.com/Puzzlepart/prosjektportalen365/commit/9a77cea49469061c736059954ac45ef8276fd332.
