### ISSUE TITLE
Stop using refinable properties as base for filters in PortfolioOverview

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#89]

**Comment by tarjeieo** [comment]
Can we skip search alltogether on the portfolio overview page? Don't see the point anymore... If we can get all metadata from list and project access/title/logo from the graph - what do we need search for anymore?

**Comment by olemp** [comment]
We need to think of all the consequences. We shouldn't move completely to CAML queries directly to the lists since search gives us the possibility to search cross portfolios.

Add CAML query as an option would be nice!

**Comment by olemp** [comment]
@tarjeieo We need to think of all the consequences. We shouldn't move completely to CAML queries directly to the lists since search gives us the possibility to search cross portfolios.

Add CAML query as an option would be nice!

**Comment by olemp** [comment]
Keep as is for now
