### ISSUE TITLE
Add Log list as an element on the configuration page

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#897]
**Is your feature request related to a problem? Please describe.**
Add Log list as an element on the configuration page.

**Describe the solution you'd like**
Add to configuration page:

![image](https://user-images.githubusercontent.com/7606007/202467163-6738042d-2f5b-4829-af5e-451fc067a155.png)
Add Log list as an element on the configuration page.

**Related issues**
#842

**Comment by olemp** [comment]
@Remi749 Something like this for description?

![image](https://user-images.githubusercontent.com/7606007/203322070-04c95397-08bc-4310-8bfc-0fbfe834af74.png)

**Comment by Remi749** [comment]
> @Remi749 Something like this for description?
> 
> ![image](https://user-images.githubusercontent.com/7606007/203322070-04c95397-08bc-4310-8bfc-0fbfe834af74.png)

perfect <3

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/commit/2b6b83f7da0ada43a14d4c9b6c20775a98b770b8
