### ISSUE TITLE
Error messages when installing/upgrading to 1.7.2

### ISSUE THREAD

**Issue by Petterandre** [Puzzlepart/prosjektportalen365#900]
**Describe the bug**
Install log attached, but will point out the issues.

Tested when upgrading from 1.6.0 and 1.6.1 -> 1.7.2

Receive the following error:
`File Objects/SiteFields/ProjectLog/GtProjectLogType.xml not found in directory . Exception = Unable to find the specified file.`

This is fixed in #899 

`ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Finner ikke filen.`
This error happens 33 times after 
`Creating view Prosjektadministrasjonsroller koblet mot prosjektegenskaper
Creating view Prosjektadministrasjonsroller koblet mot SharePoint-gruppe
Creating view Alle elementer
Creating view Alle elementer`

We get the same File not found error together with the following error message 13 times later in the install.
`ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: serverRelativePath
Parameter name: Den angitte verdien støttes ikke for parameteren serverRelativePath.`

The errors are following:
`Processing data rows for {resource:Lists_DataSources_Title}
Creating list item 1	9113ms	0ae7f1f5-b964-4b3b-b2f6-7db047e39578`

There are additional File not found errors later on in the script, all readable in the install log.

The installation appears to be OK, but considering the amount of error messages, it is concerning.

**To Reproduce**
Upgrade a PP instance.

**About your setup**
- Posh 5.1.19041.1682
- Bundled PnP.PowerShell version
- From PP 1.6.0 and 1.6.1

**Additional context**
[Install_Log_638047889645464356.txt](https://github.com/Puzzlepart/prosjektportalen365/files/10074956/Install_Log_638047889645464356.txt)

**Comment by olemp** [comment]
Hopefully will be solved by #899. CI is running now.

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen365/actions/runs/3531730964

**Comment by olemp** [comment]
Fixed by @Petterandre in #899
