### ISSUE TITLE
Phase web part not properly ordered

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#901]
**Describe the bug**
Phase webpart elements showing up in front of left menu, when the menu is opened in slide-in mode.

**To Reproduce**
Make the browser window narrow to switch navigation menu to "slide-in mode"
Open the menu

**Expected behavior**
Web part elements of the phase webpart to be kept behind the menu

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/203544541-f5c94967-9d63-4018-a013-24d0f9ec779a.png)

**About your setup**

- Browser [Chrome]
- Installed version [v1.7.2]

**Additional context**

**Comment by olemp** [comment]
Fixed in #921 by reducing `z-index` to **9**.
