### ISSUE TITLE
"? Hjelp" and hub menu clashes

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#902]
**Describe the bug**
Menuitem "?Hjelp" positioned in upper right corner (on the hub menu level) clash with the hub menu items when the window is reduced in with.

**To Reproduce**
Reduce window with until "? Hjelp" item is moved over the rightmost hub menu item and observe the behavior.

**Expected behavior**
 "?Hjelp" in upper right corner to interact seamless with the hub menu

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/203545019-734f3a17-33fa-4f3c-a49a-7aaa0108ca18.png)

**About your setup**

- Browser [Chrome]
- Installed version [v1.7.2]

**Additional context**

**Comment by tarjeieo** [comment]
Hard to avoid issues with this as long as we're stuffing it into the hub menu. I suggest creating a PP-specific footer instead. Might be other use cases for this as well down the line (e.g. "PP365 on GitHub", "Report an issue", "Suggest xyz")

**Comment by pzljanb** [comment]
> Hard to avoid issues with this as long as we're stuffing it into the hub menu. I suggest creating a PP-specific footer instead. Might be other use cases for this as well down the line (e.g. "PP365 on GitHub", "Report an issue", "Suggest xyz")

I like your approach with a footer :-)
