### ISSUE TITLE
Restrictive guest user access causes "Prosjektutlisting" (PP365 front page) to fail

### ISSUE THREAD

**Issue by okms** [Puzzlepart/prosjektportalen365#908]
**Describe the bug**
Guest users cannot see the projects they are members of on tenants using the Azure External collaboration setting 
> Guest user access is restricted to properties and memberships of their own directory objects (most restrictive)

**To Reproduce**
1. Make sure "External collaboration setting"  is configured to be "Guest user access is restricted to properties and memberships of their own directory objects (most restrictive)". This may take a couple of hours to go into effect.
![CleanShot 2022-11-29 at 15 28 30](https://user-images.githubusercontent.com/170147/204556008-419420d3-8a52-4229-a67b-88d0a2f0224a.png)
2. Invite an external user to the project portal hub site (portfolio site) and give them access to a project. Make sure they are invited as group members, not just a member of the sharepoint site. It may take 1-2 hours before the guest user is able to log in.
3. Log in with the guest account to the PP365 portfolio site
4. Observe that the "Prosjektutlisting" webpart is not loading

![CleanShot 2022-11-29 at 14 59 40](https://user-images.githubusercontent.com/170147/204557217-1f0d232b-8b63-4ef3-b358-449465de34a9.png)

**Expected behavior**
The webpart loads with rudementary information, e.g. the site title and its possible to navigate to the projects I as a guest user can access

**Comment by olemp** [comment]
@okms We would need to hide the "membership" tab and show the "has access" tab as default then, as we can't determine group membership if that request fails - obviously.

**Comment by olemp** [comment]
Should be solved in #909.
