### ISSUE TITLE
'Program' and 'Overordnet' SiteFields in 'Prosjekter' list in Portfolio are not synced from projects

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#912]
**Describe the bug**
'Program' and 'Overordnet' SiteFields in 'Prosjekter' list in Portfolio are not synced from projects

 A bug that was likely introduced in 1.7.X

**To Reproduce**
Create program og promote a project to parent, see that the Program/Overordnet field on portfolio is not set to 'yes'

**Expected behavior**
'Program' and 'Overordnet' SiteFields in 'Prosjekter' list in Portfolio should be synced from projects

**Comment by olemp** [comment]
So it's never synced to Portfolio @Remi749? 

A better solution would be to have a field "ProjectType" (with choices for Project, Program and Parent) or similiar, but I guess it will be too much work to re-do this now.

**Comment by olemp** [comment]
> So it's never synced to Portfolio @Remi749?
> 
> A better solution would be to have a field "ProjectType" (with choices for Project, Program and Parent) or similiar, but I guess it will be too much work to re-do this now.

Are these manually updated or was this pre 1.7, @Remi749?

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/7606007/208659169-27e1a69f-a43f-492e-b97a-67b8d6324f14.png">

**Comment by olemp** [comment]
Fixed in #927
