### ISSUE TITLE
GtProjectAdminRoles doesn't show up in existing project prior to 1.7.X

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#914]
**Describe the bug**
GtProjectAdminRoles doesn't show up in existing project prior to 1.7.X. Should be added to UpgradeAllSitesToLatest

**To Reproduce**
Check a project that was created prior to a 1.7.X upgrade, confirm that the field doesn't show up in edit form or exists on the 'Prosjektegenskaper' list.

**Expected behavior**
The field should show up in existing projects prior to 1.7.X

**Comment by olemp** [comment]
The field should show up after synchronisation of project properties. Have you tried that @Remi749?

**Comment by tarjeieo** [comment]
> The field should show up after synchronisation of project properties. Have you tried that @Remi749?

Confirming this is working in the project portal tenant. I think we can live with this workaround - kind of as expected for new project properties fields. Agree @Remi749, @pzljanb ?

**Comment by Remi749** [comment]
> > The field should show up after synchronisation of project properties. Have you tried that @Remi749?
> 
> Confirming this is working in the project portal tenant. I think we can live with this workaround - kind of as expected for new project properties fields. Agree @Remi749, @pzljanb ?

Agreed. Closing issue
