### ISSUE TITLE
Add project to parent search webpart includes channel sites in search

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#915]
**Describe the bug**
When searching for projects to add as child the search result includes "channel"-sites

**To Reproduce**

1. Go to '[...](https://prosjektportalen.sharepoint.com/sites/Program/SitePages/Admin.aspx)'
2. Click on 'Legg til prosjekter'
3. Search for 'rådg'
4. Observe search result to include "Anskaffelse av ny digital læringsplattform for studenter-Rådgivende"
5. Go to Teams and the Team observe that "Anskaffelse av ny digital læringsplattform for studenter" has a channel "Rådgivende"

**Expected behavior**
The search result should not include "Channel"-sites

**Screenshots**
![image](https://user-images.githubusercontent.com/58074707/205898667-e2d79dee-ceca-41b4-8e78-0672df6e40fb.png)
![image](https://user-images.githubusercontent.com/58074707/205898730-7c77ecf7-8fa9-4da2-b492-733c515ace10.png)

**About your setup**

- Browser [Chrome]
- Installed version [1.7.2]

**Additional context**

**Comment by tarjeieo** [comment]
Looks like we can solve this by using the WebTemplate managed property, e.g.

`DepartmentId:{b8899a70-4044-4aad-ab59-8401149cd53f} contentclass:STS_Site NOT WebTemplate:TEAMCHANNEL`

**Comment by tarjeieo** [comment]
Should be resolved by #922
