### ISSUE TITLE
Prosjekttidslinje on porteføljenivå not working when no projects are synced

### ISSUE THREAD

**Issue by golefstad** [Puzzlepart/prosjektportalen365#918]
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your needs, please complete the below template to ensure we have the details to help. Thanks!

#### Category

[ ] Enhancement

[x ] Bug

[ ] Question

#### Browser

[ ] Chrome

[ ] Internet Explorer

[x ] Edge

[ ] Safari

[ ] Other

#### Summary

I click the Prosjekttidslinje-tab on the top of the page. the page appears to be loading, but after a second the page is finished loading and is blank from below the Rediger-line. This problem showed up after upgrading to 1.7.2. I have installed this version in our test- and dev-tenant and the same issue appears in both.

#### Version

Please specify what version you are using: [1.7.2.9510d87]

You can find the version you are using in the bottom left corner of any page in the Project Portal site.

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question

_If you are reporting an issue, please describe the expected behavior. If you are suggesting an enhancement, please describe thoroughly the enhancement, how it can be achieved, and the expected benefit. If you are asking a question, ask away!_

#### Observed Behavior

_If you are reporting an issue, please describe the behavior you observed when performing the action. If you are making a suggestion or asking a question, delete this section._

#### Steps to Reproduce

_If you are reporting an issue, please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making a suggestion or asking a question, delete this section._

**Comment by olemp** [comment]
Can you attach some screenshots @golefstad?

**Comment by golefstad** [comment]
![Prosjektportalen tidslinje](https://user-images.githubusercontent.com/110966756/207561953-949d1502-05f9-4b01-aad2-f20868589952.png)
![Prosjektportalen tidslinje rediger](https://user-images.githubusercontent.com/110966756/207562705-a354d869-971b-44d3-bbe3-3284027a2f72.png)

**Comment by olemp** [comment]
Could you check if the console contains any errors/warnings/info @golefstad?

https://www.ibm.com/docs/en/rpa/21.0?topic=tools-opening-developer-in-microsoft-edge-browser

**Comment by golefstad** [comment]
![image](https://user-images.githubusercontent.com/110966756/208937250-998024bd-3ddc-42d2-bdcd-4ef8df9e9606.png)

**Comment by Remi749** [comment]
Turns out if no projects are synced to the hub without start/end date the timeline won't work.
