### ISSUE TITLE
Tilgang for å opprette porteføljeoversikt-visninger låst til områdeadministratorer

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#932]
**Describe the bug**
Permissions on the list Porteføljevisniger is lock to SiteAdmin.
This is resulting in regular members to be lifted as Owners on the Huib to be able to create new views.
And with this even other unwanted admin functions is given.

**To Reproduce**

**Expected behavior**
Give access to create new porteføljevsninger as a regular member by list permissions on the list instead of todays locking against Siteadmin.

**About your setup**

- Installed version [v1.7.2]

**Additional context**

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/pull/1028
