### ISSUE TITLE
Aggregert webdel bør lenke direkte til elementet som vises

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#947]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

I oversikten over leveranser, risiko, gevinster, erfaringer etc. så er det bare lenke til prosjektet. Om man skal se mer detaljer om et element så må man selv finne det ved å navigere.

### Beskriv løsningen du ønsker

Elementet bør være klikkbart og peke til skjemaet for elementet (i det minste listen). Enten ved at tittel er klikkbar eller et ikon ved siden av raden (kanskje best?)

**Comment by olemp** [comment]
> Enig, tenker vi gjør tittel klikkbar og finner ut om vi kan peke direkte til elementet eller bare listen.

Løst i PR https://github.com/Puzzlepart/prosjektportalen365/pull/1010
