### ISSUE TITLE
Medlem/eier-rettigheter caches mellom prosjekter

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#953]
**Describe the bug**
Dersom jeg er eier i prosjekt A og medlem i prosjekt B, får jeg ofte opp feil menyvalg under Prosjektinformasjon. Som medlem kan jeg se alle valg, og som eier kan jeg risikere å bare få opp "vis prosjektinformasjon".

**To Reproduce**

1. Gå til prosjekt A der du er eier
2. Naviger til hubens hjemmeområde og velg et prosjekt du er medlem i
3. Observer at du ser alle menyvalgene under Prosjektinformasjon
4. Ta en hard refresh så blir det riktig
5. Det samme andre veien - fra medlemsprosjekt til et eierprosjekt

**Expected behavior**
Visningen bør håndheve rettighetene dine.

**Screenshots**

![PPIssuePermissions](https://user-images.githubusercontent.com/1837390/215054027-4f7837be-7713-497a-9a36-308904d7f3d1.gif)

**About your setup**

- Browser [e.g. chrome, safari] Edge
- Installed version [found under {Prosjektportalen}/Lists/Installasjonslogg/AllItems.aspx] 1.7.2

**Comment by Remi749** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen365/commit/95359bc1244478cfcab1edc575764dddbd676d1c
