### ISSUE TITLE
Project status: Status colors all black

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#96]
e.g. https://pzlcloud.sharepoint.com/sites/NedleggelseavElisenbergpostkontor/SitePages/Prosjektstatus.aspx#selectedReport=30

**Comment by olemp** [comment]
@tarjeieo implemented in https://github.com/Puzzlepart/prosjektportalen365/commit/db157dd96604b328f0c9bd5a3e85d03a9400f57e. Using list `Prosjektkolonnekonfigurasjon` to find the color.
