### ISSUE TITLE
Prosjekter man ikke har tilgang til bør vises i oversikter på program/overordnet

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#961]
### Er forespørselen din relatert til et problem? Vennligst beskriv.

Prosjekter man ikke har tilgang til vises ikke i oversikter på program/overordnet. Dette bør vises på samme vis som Porteføljeoversikten (grået ut)

### Beskriv løsningen du ønsker

Prosjekter man ikke har tilgang til bør vises i oversikter på program/overordnet på lik linje som prosjekter man ikke har tilgang til vises i Porteføljeoversikten

- Dette kan kanskje styres med en egen rolle i Prosjektadministrasjonroller listen?

**Comment by olemp** [comment]
Du tenker da at man spør mot Prosjekter-listen istedenfor å utføre et søk, @Remi749?

![image](https://user-images.githubusercontent.com/7606007/217799432-737cb8b3-42d4-40af-9147-f0b104281ad3.png)

**Comment by olemp** [comment]
> Du tenker da at man spør mot Prosjekter-listen istedenfor å utføre et søk, @Remi749?
> 
> ![image](https://user-images.githubusercontent.com/7606007/217799432-737cb8b3-42d4-40af-9147-f0b104281ad3.png)

Det blir muligens en noe kompleks løsning da vi eventuelt må hente ut prosjekter på ulike måter med mindre vi ikke henter ut prosjektene fra Prosjekter-listen uansett - alltid.

**Comment by Remi749** [comment]
> > Du tenker da at man spør mot Prosjekter-listen istedenfor å utføre et søk, @Remi749?
> > ![image](https://user-images.githubusercontent.com/7606007/217799432-737cb8b3-42d4-40af-9147-f0b104281ad3.png)
> 
> Det blir muligens en noe kompleks løsning da vi eventuelt må hente ut prosjekter på ulike måter med mindre vi ikke henter ut prosjektene fra Prosjekter-listen uansett - alltid.

Se issue #972
