### ISSUE TITLE
Kommunikasjonsplaner under Programinnhold 

### ISSUE THREAD

**Issue by Hasse89** [Puzzlepart/prosjektportalen365#965]
### Beskriv løsningen du ønsker

I dag så har et Programområde (med underprosjekter) en aggregert oversikt over Gevinster, Leveranser og Usikkerheter fra alle underprosjektene.

Er det mulig og også legge til alle Kommunikasjonsplaner fra underprosjektene i den samme oversikten?
<img width="128" alt="Snippet" src="https://user-images.githubusercontent.com/120835919/217192584-7eb66574-ba40-4bce-b800-89d1677f7ff2.png">

**Comment by Remi749** [comment]
Hei @Hasse89,
vi har lagt fram plan for neste release ([etter 1.8](https://github.com/Puzzlepart/prosjektportalen365/milestone/26)). Dette vil da komme med som standard. Ellers så er dette noe som kan settes opp ut av boksen i mellomtiden. Dersom dere ønsker bistand til dette send oss gjerne en e-post til: prosjeportalen@puzzlepart.com og referer til denne saken.

**Comment by tarjeieo** [comment]
For å få til dette gjør vi følgende
- Legg på felt på datakilder for å skille mellom hvor datakilden kan brukes (Portefølje, Overordnet/Program, Prosjekt) - "Nivå"
- Oppdater alle oversiktssider til å respektere "Nivå", og la brukeren velge datakilde fra gitt Nivå
- Prepopuler alle aktuelle datakilder på relevante nivå, samt prosjektinnholdskolonner for aktuell data

**Comment by olemp** [comment]
> For å få til dette gjør vi følgende
> 
> * Legg på felt på datakilder for å skille mellom hvor datakilden kan brukes (Portefølje, Overordnet/Program, Prosjekt) - "Nivå"
> * Oppdater alle oversiktssider til å respektere "Nivå", og la brukeren velge datakilde fra gitt Nivå
> * Prepopuler alle aktuelle datakilder på relevante nivå, samt prosjektinnholdskolonner for aktuell data

Nivå legges til som en del av https://github.com/Puzzlepart/prosjektportalen365/issues/1097
