### ISSUE TITLE
Add project matrix to project status page and as a separate web part

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#97]

**Comment by olemp** [comment]
@remi749 Do you want to have a go at this? The code is in the PP 2 repo (https://github.com/Puzzlepart/prosjektportalen) and should be added as an SPFx webpart to the solution `SharePointFramework/ProjectWebParts`. Add a PR.

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen/tree/master/src/js/WebParts/RiskMatrix

**Comment by olemp** [comment]
Work started in https://github.com/Puzzlepart/prosjektportalen365/pull/171

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen365/issues/172
