### ISSUE TITLE
Feltet GtSearchQuery bør ha støtte for flere enn 255 tegn

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#970]
Feltet GtSearchQuery bør ha støtte for flere enn 255 tegn. Løsningen på dette må nok bli å konvertere feltet til `Note` og sette egenskapen `UnlimitedLengthInDocumentLibrary` til `TRUE`.

Oppdatering av felttype kan vel ikke skje automatisk kun med provisjonering av Portefølje-malen så mulig det må legges inn som et upgrade-steg (?).

<img width="625" alt="image" src="https://user-images.githubusercontent.com/7606007/217543482-3ccb3499-f93b-4d76-a8c2-a4f2312ba20b.png">

**Comment by tarjeieo** [comment]
Vi løser det ved å endre feltet til Note, og gjør ingenting med eksisterende installasjoner. Kan løses enkelt manuelt dersom det dukker opp.
