### ISSUE TITLE
Gjester og medlemmer mangler rettigheter

### ISSUE THREAD

**Issue by pzljanb** [Puzzlepart/prosjektportalen365#971]
### Beskriv feilen

Får ikke tilgang til sentrale prosjekter-data inne fra prosjektet som Medlem eller Gjest.

### Hvordan reprodusere feilen

Opprett et prosjekt i en ny installasjon av PP365 v1.8 og gi en bruker nr2 tilgang som medlem eller gjest
Gå inn på prosjektet som den nye medlemmen og se feilen

### Forventet oppførsel

Skulle hatt tilgang

### Skjermbilder

![image](https://user-images.githubusercontent.com/58074707/217562063-fcf361e9-c952-4835-8f4d-0d1fe18f2937.png)

### Ytterligere informasjon

Er mulig at feilen ikke skyldes prosjektet, men begrensinger på Hub

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by olemp** [comment]
@Remi749 Har disse brukerne tilgang til hubområdet?

**Comment by olemp** [comment]
@pzljanb Har disse brukerne tilgang til hubområdet?

**Comment by Remi749** [comment]
Ser at problemet du opplever, @pzljanb, har med at visning av statusrapport i Prosjektinformasjon webdelen er slått på. Dersom den slås av så vises webdelen som normalt. Så det er kanskje noe med tilgangene til brukeren her?
