### ISSUE TITLE
Listeutvidelse for Idebehandling blir trigget på andre lister

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#986]
### Beskriv feilen

Listeutvidelse for Idebehandling blir trigget på andre lister

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå hit: https://puzzlepart.sharepoint.com/sites/Prosjektutlistingen/Lists/Prosjektleveranser/AllItems.aspx
 2. Se i console at utvidelsen prøver å sjekke på 'Idebehandlere' gruppen

### Forventet oppførsel

Listeutvidelse for Idebehandling skal bare trigges på Idebehandling eller Ideregistrering listene på Porteføljenivå. Ingen andre steder.

### Skjermbilder

![image](https://user-images.githubusercontent.com/28678468/218744191-006fae0f-bf5e-46b4-b61a-acbe76bafb0c.png)

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.7.2

**Comment by olemp** [comment]
@Remi749 Er denne lagt som en custom action på hele siten, eller kun på listen? Om det førstnevnte er tilfellet, er det kanskje ingen sjekk på om han er på riktig liste (Idebehandling).

**Comment by Remi749** [comment]
> @Remi749 Er denne lagt som en custom action på hele siten, eller kun på listen? Om det førstnevnte er tilfellet, er det kanskje ingen sjekk på om han er på riktig liste (Idebehandling).

Det ligger som en utvidelse på hele siten ja, null sjekk på om man står i riktig liste. Det skal gjøres en stor revamp av hele idebehandlingsopplegget, så endringer på dette issuet kan forekomme.
