### ISSUE TITLE
Include active/inactive projects field to filter projects from portfolio

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#99]
See field GtProjectLifecycleStatus.

In v2 er started using the query 'ContentTypeId:0x010088578E7470CC4AA68D5663464831070211* GtProjectLifecycleStatus="Avsluttet"'

**Comment by olemp** [comment]
Must be 1.1.0

**Comment by tarjeieo** [comment]
Ja, egentlig .joy: Men da må vi håndtere upgrade-script som endrer queries på alle eksiterende porteføljer.

**Comment by olemp** [comment]
Will be included in `1.1.3`. Date TBA. CHANGELOG updated.
