### ISSUE TITLE
Lenke til sentral tidslinjeinnholdsliste fra Program/Overordnet tidslinje fungerer ikke, melding bør endres

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#995]
### Beskriv feilen

Lenke til sentral tidslinjeinnholdsliste fra Program/Overordnet tidslinje fungerer ikke. Forslag er å endre meldingen til følgende:

"Her listes alle prosjektene med start- og sluttdato som er tilknyttet området. For å zoome inn/ut i tidslinje: ALT+Musehjul"

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til Program/Overordnet tidslinje
 2. Klikk på lenken i informasjonsdialogen
 4. Se feil

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by pzljanb** [comment]
Jeg begynner å lure på om den sentrale listen ikke lenger skal henvises til noen steder.
Vil heller at vi leder brukeren til prosjektets(programmets) egen side for Prosjekttidslinje. Og det behøves ikke en lenke til da dette finnes i venstremenyen allerede

**Comment by Remi749** [comment]
> 

Den er god, da legger vi heller inn en sjekk og fjerner lenke.

**Comment by olemp** [comment]
> > Jeg begynner å lure på om den sentrale listen ikke lenger skal henvises til noen steder. Vil heller at vi leder brukeren til prosjektets(programmets) egen side for Prosjekttidslinje. Og det behøves ikke en lenke til da dette finnes i venstremenyen allerede
> 
> Den er god, da legger vi heller inn en sjekk og fjerner lenke.

Legger inn en sjekk for hva..?

**Comment by tarjeieo** [comment]
Om webdelen kjører i "programmodus" så skal ikke meldingen vises. Om webdelen kjører i "vanlig modus" i prosjektene så skal meldingen vises og lenken peke til hubens tidslinjeliste

**Comment by olemp** [comment]
> Om webdelen kjører i "programmodus" så skal ikke meldingen vises. Om webdelen kjører i "vanlig modus" i prosjektene så skal meldingen vises og lenken peke til hubens tidslinjeliste

Skjønner! 💯

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/pull/1009

![image](https://user-images.githubusercontent.com/7606007/220613521-c1def779-4bad-4769-b3a3-cdb7ac8316c0.png)

**Comment by olemp** [comment]
@Remi749 / @pzljanb kan ta seg av lukking når denne er verifisert.

**Comment by olemp** [comment]
Er det noe feil @Remi749?

![image](https://user-images.githubusercontent.com/7606007/220637290-aa8af901-da5a-437f-beaf-66f4e1f6df39.png)

**Comment by Remi749** [comment]
@olemp , tenker det er viktig at det vises en melding, ettersom meldingen inneholder innstrukser for hvordan man zoomer blandt annet.

Tenker følgende melding for Program/Overordnet: 

"Her listes alle prosjektene med start- og sluttdato som er tilknyttet området. For å zoome inn/ut i tidslinje: ALT+Musehjul"

**Comment by olemp** [comment]
> @olemp , tenker det er viktig at det vises en melding, ettersom meldingen inneholder innstrukser for hvordan man zoomer blandt annet.
> 
> Tenker følgende melding for Program/Overordnet:
> 
> "Her listes alle prosjektene med start- og sluttdato som er tilknyttet området. For å zoome inn/ut i tidslinje: ALT+Musehjul"

Stod at meldingen skulle fjernes i denne kommentaren:

![image](https://user-images.githubusercontent.com/7606007/220639180-21d83be3-851c-4efb-a902-05ac0c6e57e9.png)

Da får vi heller endre på meldingen for programmer.

**Comment by olemp** [comment]
@Remi749 Kan du oppdatere issue tittel og beskrivelse?
