### ISSUE TITLE
Fargekonfigurasjon for dynamisk matrise virker ikke som det skal

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#998]
### Beskriv feilen

- Dersom matrisen er satt opp 5x farger virker kun de 4 første farge parameterne.
- Dersom matrisen er satt opp 6x farger virker kun de 5 første farge parameterne.
Les: Påvrker ikke fargene

### Forventet oppførsel

Farge parameterne burde fungere uansatt hvilket oppsett.

### Hvilke nettleser(e) oppleves feilen på?

Chrome

### Versjon

1.8.0

**Comment by olemp** [comment]
@Remi749 Den bruker nyanser av fargene utifra hvor høy risikofaktor er. Ikke akkurat den fargen man spesifiserer.

![image](https://user-images.githubusercontent.com/7606007/233303227-388012cc-9851-494d-b02b-26b00a6b8f2f.png)

![image](https://user-images.githubusercontent.com/7606007/233303259-67553b7b-60f3-4bfa-a574-d7b621ae5726.png)

**Comment by Remi749** [comment]
Åpner denne på nytt:

0% bør være den fargen som er satt helt til venstre. 100% bør være den fargen som er satt til høyre uavhengig av størrelse.
![image](https://user-images.githubusercontent.com/28678468/233311247-5ab83090-33f0-45e8-b8dd-e173c4a124f5.png)

**Comment by tarjeieo** [comment]
Det er vel også en kjensgjerning at mange organisasjoner har en definert matrise med spesifiserte farger, og ikke sjatteringer mellom ulike. Er det fortsatt støttet med denne måten å gjøre det på?

**Comment by Remi749** [comment]
> Det er vel også en kjensgjerning at mange organisasjoner har en definert matrise med spesifiserte farger, og ikke sjatteringer mellom ulike. Er det fortsatt støttet med denne måten å gjøre det på?

Dette er det beste man kan få til for øyeblikket (3 farger):
![image](https://user-images.githubusercontent.com/28678468/233314353-80fd95fd-b6eb-4511-b2d6-11297098457c.png)

**Comment by olemp** [comment]
> Det er vel også en kjensgjerning at mange organisasjoner har en definert matrise med spesifiserte farger, og ikke sjatteringer mellom ulike. Er det fortsatt støttet med denne måten å gjøre det på?

Skal se hva jeg får til når jeg ser på denne. Bør være mulig.

**Comment by olemp** [comment]
@Remi749 @tarjeieo Skal vi bare skru av funksjonaliteten? Er vel kanskje ingen som bruker det?

**Comment by tarjeieo** [comment]
Fine by me - hva tenker @pzljanb?

**Comment by pzljanb** [comment]
Er det feil slik det er nå så bør den bare disables ja, enig

**Comment by olemp** [comment]
> Er det feil slik det er nå så bør den bare disables ja, enig

Da er denne disabled!
